### ISSUE TITLE
Property identifier does not refer to a managed property

### ISSUE THREAD

**Issue by daidai2016** [OmniLayer/omnicore#1029]
omnicore-cli "omni_sendfreeze" "3M9qvHKtgARhqcMtM5cRT9VaiDJ5PSfQGY" "3HTHRxu3aSDV4deakjC7VmsiUp7c6dfbvs" 2 1000

**Comment by dexX7** [comment]
Hello,

you can only freeze tokens, when you are the creator of that token. In this case, you tried to freeze Test Omni, which are not the creator of.

**Comment by daidai2016** [comment]
@dexX7 thanks
