### ISSUE TITLE
Omni_send broadcast transaction failed, error code 206, the original account address also has BTC and USDT

### ISSUE THREAD

**Issue by yikaixiong** [OmniLayer/omnicore#1032]
The reason is that my FROM account is not enough money? In fact, the amount of money in the FROM account is enough.Usually the reason is？

**Comment by Bushstar** [comment]
Can you please provide more details, what Omni version are you using?
What is the source address?
What is the exact call you are running?

**Comment by yikaixiong** [comment]
Thank you, it has been solved, because my account balance is not enough.
