### ISSUE TITLE
How to freeze usdt tokens

### ISSUE THREAD

**Issue by daidai2016** [OmniLayer/omnicore#1033]
How to freeze usdt tokens？

What actions are required？ Has it bothered me for a long time? Please help me! Thank you

**Comment by dexX7** [comment]
Hello,

since you are not the creator of USDT tokens, you can't freeze them.

**Comment by daidai2016** [comment]
@dexX7  I see.  thanks.

**Comment by knoxcard2** [comment]
close issue?
