### ISSUE TITLE
Omnicore synchronization block problem

### ISSUE THREAD

**Issue by mienv567** [OmniLayer/omnicore#1037]
From 2009 to 2017, the omnicore synchronization block was completed in half a day. How come after 18 years, the speed of the synchronization block slowed down, and it was only synchronized for 2 months overnight?

**Comment by mienv567** [comment]
![omni](https://user-images.githubusercontent.com/7724835/67650284-64424580-f977-11e9-94a5-703dd524a97c.png)

**Comment by dexX7** [comment]
Hello @mienv567,

which version are you using?

**Comment by mienv567** [comment]
Omni Core Daemon version v0.6.0

**Comment by mienv567** [comment]
And I use an American server And the speed is 10Gbps

**Comment by mienv567** [comment]
@dexX7
