### ISSUE TITLE
Where can find the sha256sum or public key of signatures for omnicore-0.6.0-x86_64-linux-gnu.tar.gz

### ISSUE THREAD

**Issue by aihua** [OmniLayer/omnicore#1039]
Where can find the sha256sum or public key of [https://github.com/OmniLayer/omnicore/releases/download/v0.6.0/omnicore-0.6.0-x86_64-linux-gnu.tar.gz.sig](signatures) for [https://github.com/OmniLayer/omnicore/releases/download/v0.6.0/omnicore-0.6.0-x86_64-linux-gnu.tar.gz](omnicore-0.6.0-x86_64-linux-gnu.tar.gz)? @dexX7 @msgilligan @dacoinminster @germanf @marvgmail

**Comment by dexX7** [comment]
Hello,

the files on GitHub are GPG signed with my key:

**Comment by aihua** [comment]
ok, thanks.
