### ISSUE TITLE
omniexplorer for testnet?

### ISSUE THREAD

**Issue by toknT** [OmniLayer/omnicore#1040]
where is omniexplorer for testnet?

I can only find mainnet here https://omniexplorer.info/ .

**Comment by liutao0532** [comment]
have not

**Comment by toknT** [comment]
Finally I still not find a testnet explorer.
But,there is a way to get the balance of address(your have it's private key)
- build a testnet node 
- use rpc method `importprivkey` (import your testnet wallet's private key)
- sync to the latest(mutch slower than btc testnet ,It cost me 3 day)
- use rpc method `omni_getbalance`
