### ISSUE TITLE
upgrade to 0.7.0 version，then walletpassphrase returns null

### ISSUE THREAD

**Issue by Judge0523** [OmniLayer/omnicore#1041]
![TIM截图20191107094752](https://user-images.githubusercontent.com/6762068/68353204-cbb08000-0143-11ea-9c7f-0da2042e6a4d.png)

**Comment by Bushstar** [comment]
That's the expected behaviour, on successful calls to walletpassphrase, Bitcoin 0.18.1 returns null. Omnicore 0.7.0 is based on Bitcoin 0.18.1.

**Comment by Judge0523** [comment]
> That's the expected behaviour, on successful calls to walletpassphrase, Bitcoin 0.18.1 returns null. Omnicore 0.7.0 is based on Bitcoin 0.18.1.

tanks
