### ISSUE TITLE
What is the deadline to upgrade to v0.7?

### ISSUE THREAD

**Issue by palimarrao** [OmniLayer/omnicore#1046]
I am running Omnicore v0.5. What is the deadline to upgrade to v0.7?

**Comment by palimarrao** [comment]
Ping. Any one when's the deadline?

**Comment by achamely** [comment]
No definitive date as of yet. 
Once the next feature activation is announced the deadline will be about 2 weeks after. 
So you will have at minimum 2 weeks from any announcement that is made

**Comment by palimarrao** [comment]
Thanks @achamely.  What channel will be used for notification? Is it best to just check Github periodically?

**Comment by achamely** [comment]
When the date has been determined we will make announcements to out dev email list, public blog post, twitter account and I will ask the devs if its possible to add something to github as well

**Comment by palimarrao** [comment]
Great, thanks for the information.
