### ISSUE TITLE
[daemon stopped] omni_funded_send

### ISSUE THREAD

**Issue by puffanddmx** [OmniLayer/omnicore#1057]
Using omni_funded_send function causes omni daemon to stop on rpc send. (In the test condition, there is no btc in the fee address.) If the fee address does not have btc, the daemon should not die. If you know this part, please let me know. There is no error in the log and the daemon stops immediately. The version is 0.7.0. Can you tell me what the problem is?

**Comment by 847807873** [comment]
这个怎么样了？我也遇到了！
{"jsonrpc":"1.0","id":"1","method":"omni_funded_send","params":["mtSp4Wkz5FsTLqeBuPskY1yuQmBWs52aNK","mriu2cm3tmL1yuvJeUENGxQgV9mUt2QdJP",1,"0.01","mtSp4Wkz5FsTLqeBuPskY1yuQmBWs52aNK"]}
http://127.0.0.1:18332/wallet/test2
每次打开都要回归区块！
![image](https://user-images.githubusercontent.com/10612067/71401785-d8425680-2665-11ea-83d2-78e477bfd699.png)

**Comment by lambda2003** [comment]
I got the same error. -> After it was stopped, I restarted it(omnicored). Then it started block scanning. It took a few mins or hours. I have the same question with "puffanddmx".  Is it normal? :(
