### ISSUE TITLE
Does omni support native segwit address?

### ISSUE THREAD

**Issue by brucexiu** [OmniLayer/omnicore#1061]
Bitcoin has been updated to 0.18.0, Then can I receive USDT using a native segwit address with prefix bc1?

**Comment by dexX7** [comment]
Not yet, but it's planned for the next release.

**Comment by brucexiu** [comment]
> Not yet, but it's planned for the next release.

Could you please kindly tell me the ETA?

**Comment by mrbianchi** [comment]
Now?

**Comment by Alex314Ru** [comment]
Looks like it isn't. I just upgraded our Omni Core node to v0.9.0, and when I specify "bc1" address with the `omni_createrawtx_reference` command the resulting transaction still has `referenceaddress` the same as the `sendingaddress`.

**Comment by supertestnet** [comment]
Now?

**Comment by alexpros87** [comment]
any news on omni support for bc1 adresses??
