### ISSUE TITLE
tx 30a0751b006cc8cb929e7b46491414c024391d8477892bbff8b8e7757d69db5e status is not same in different explorer

### ISSUE THREAD

**Issue by bitcodernull** [OmniLayer/omnicore#1072]
the transaction : 30a0751b006cc8cb929e7b46491414c024391d8477892bbff8b8e7757d69db5e 

the status is not valid in token viewer explorer : https://usdt.tokenview.com/cn/tx/615342/71
but it is valid in omni explorer (https://omniexplorer.info/search/30a0751b006cc8cb929e7b46491414c024391d8477892bbff8b8e7757d69db5e )

in my owner node ,  it is not valid 

so how to check the tx status,  and why?

**Comment by bitcodernull** [comment]
i rescan my node , the tx status is valid in my node

**Comment by bitcodernull** [comment]
maybe the code have bugs according to the problem
i found the omniexplorer/  tokenview / blockchain have the differrent balance to a address

**Comment by 1036225283** [comment]
> i reindex my node , the tx status is valid in my node

how to reindex. I have the same problem

**Comment by pranavburnwal** [comment]
> > i reindex my node , the tx status is valid in my node
> 
> how to reindex. I have the same problem

https://bitcoin.stackexchange.com/a/60711

**Comment by bitcodernull** [comment]
reindex is very slow ,about 3 days
and i reindex, i met the sam problem on the another tx 

i found the root cause maybe is  the error balance , the error banlance is the two times the origin balance

**Comment by pranavburnwal** [comment]
Yes, I have similar situation. Any solution you could figure out?

**Comment by dexX7** [comment]
Hey guys, please retest with the latest version:

https://github.com/OmniLayer/omnicore/releases

Or with the develop branch:

https://github.com/OmniLayer/omnicore/tree/develop
