### ISSUE TITLE
Is there any way to pay fee instead of sender?

### ISSUE THREAD

**Issue by sjlee1125** [OmniLayer/omnicore#1075]
I gonna make rawtransaction of simple send.
Is there any way to pay fee instead of sender?
any other address

**Comment by pranavburnwal** [comment]
Yup but you need have private key for the address from which you need to pay fees.

**Comment by Septian-Bhoechie** [comment]
> Yup but you need have private key for the address from which you need to pay fees.

@pranavburnwal @sjlee1125 how to do this?

**Comment by pranavburnwal** [comment]
> > Yup but you need have private key for the address from which you need to pay fees.
> 
> @pranavburnwal @sjlee1125 how to do this?

No easy way out of this one. 
Best I can refer to is go through this: https://www.righto.com/2014/02/bitcoins-hard-way-using-raw-bitcoin.html

**Comment by achamely** [comment]
@sjlee1125 It depends. 
All omni protocol txs MUST include at least one utxo (the  first) from the address that is sending the tokens. the remaining fee can be paid by other address in the wallet. Take a look at the funded send calls in the documentation https://github.com/OmniLayer/omnicore/blob/master/src/omnicore/doc/rpc-api.md#omni_funded_send
