### ISSUE TITLE
tx98cdcb33286b3185dfc993d9a9808003620bfdc4c88a429044c8d04ed0a1ddff status is not same in different explorer

### ISSUE THREAD

**Issue by 1036225283** [OmniLayer/omnicore#1076]
the transaction : 98cdcb33286b3185dfc993d9a9808003620bfdc4c88a429044c8d04ed0a1ddff

the status is not valid in token viewer explorer : https://blockchair.com/zh/bitcoin/transaction/98cdcb33286b3185dfc993d9a9808003620bfdc4c88a429044c8d04ed0a1ddff
but it is valid in omni explorer (https://omniexplorer.info/search/98cdcb33286b3185dfc993d9a9808003620bfdc4c88a429044c8d04ed0a1ddff )

in my owner node , it is not valid

so how to check the tx status, and why?

**Comment by bitcodernull** [comment]
i found the incorrect balance is two times the origin balance

**Comment by dexX7** [comment]
Hey guys, please retest with the latest version:

https://github.com/OmniLayer/omnicore/releases

Or with the develop branch:

https://github.com/OmniLayer/omnicore/tree/develop
