### ISSUE TITLE
Tx dabef406d7e357e22033fb84cb7f200e91dffe218f625f2da35f315958a58d0d has different 'valid' status from different nodes

### ISSUE THREAD

**Issue by nining** [OmniLayer/omnicore#1078]
I'm developer from [Bitpie Wallet](https://bitpie.com) team.  We're running omnicore nodes to support USDT-OMNI transactions in our wallet app.  Today a user reported an issue and we identified that the TX "**valid**" status returned from one of the omnicore nodes was wrong. 

I never expected there would exist different "**valid**" statuses for the same transaction on different nodes.

TX dabef406d7e357e22033fb84cb7f200e91dffe218f625f2da35f315958a58d0d has different 'valid' status from different nodes. We cross checked with public explorers, and their status is also different.  On Blockchair, the TX is valid:
https://blockchair.com/bitcoin/transaction/dabef406d7e357e22033fb84cb7f200e91dffe218f625f2da35f315958a58d0d
On OmniExplorer, the TX is INVALID:
https://omniexplorer.info/search/dabef406d7e357e22033fb84cb7f200e91dffe218f625f2da35f315958a58d0d
The omni_gettransaction result from our node 1:
```
$ omnicore-cli omni_gettransaction dabef406d7e357e22033fb84cb7f200e91dffe218f625f2da35f315958a58d0d
{
  "txid": "dabef406d7e357e22033fb84cb7f200e91dffe218f625f2da35f315958a58d0d",
  "fee": "0.00007277",
  "sendingaddress": "17r3rHrgA6VGGAf28zuaqHdTuBzHu68Bdb",
  "referenceaddress": "12jMdk4waPg48mYNJ8k5UEFLUGYFnKoKHJ",
  "ismine": false,
  "version": 0,
  "type_int": 0,
  "type": "Simple Send",
  "propertyid": 31,
  "divisible": true,
  "amount": "7002.00000000",
  "valid": true,
  "blockhash": "000000000000000000068e1bc49568d1f278ddf60b1a29c879bf4e32b62f98d8",
  "blocktime": 1582700658,
  "positioninblock": 2620,
  "block": 619040,
  "confirmations": 148
}
```
The omni_gettransaction result from our node 2:
```
$ omnicore-cli omni_gettransaction dabef406d7e357e22033fb84cb7f200e91dffe218f625f2da35f315958a58d0d
{
  "txid": "dabef406d7e357e22033fb84cb7f200e91dffe218f625f2da35f315958a58d0d",
  "fee": "0.00007277",
  "sendingaddress": "17r3rHrgA6VGGAf28zuaqHdTuBzHu68Bdb",
  "referenceaddress": "12jMdk4waPg48mYNJ8k5UEFLUGYFnKoKHJ",
  "ismine": false,
  "version": 0,
  "type_int": 0,
  "type": "Simple Send",
  "propertyid": 31,
  "divisible": true,
  "amount": "7002.00000000",
  "valid": false,
  "invalidreason": "Sender has insufficient balance",
  "blockhash": "000000000000000000068e1bc49568d1f278ddf60b1a29c879bf4e32b62f98d8",
  "blocktime": 1582700658,
  "positioninblock": 2620,
  "block": 619040,
  "confirmations": 148
}
```

I noticed there were 2 other issues (#1076 and #1072 ) and no developer has responded.  I'm sure this is a very serious bug and can recur very often.
 

We updated both nodes to latest version 0.7.1 downloaded from github release pages on Jan 24.

Here is the OS environment on node 1:
```
$ uname -a
Linux node1 5.3.0-40-generic #32~18.04.1-Ubuntu SMP Mon Feb 3 14:05:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
$ cat /etc/issue
Ubuntu 18.04.4 LTS \n \l
$ lscpu
Model name:          Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
$ mount|grep omni
/dev/nvme5n1p1 on /home/omnicore type btrfs (rw,noatime,nodatasum,nodatacow,ssd,space_cache,subvolid=1298,subvol=/@omnicore)
```
Here is the OS environment on node 2:
```
$ uname -a
Linux node2 5.3.0-28-generic #30~18.04.1-Ubuntu SMP Fri Jan 17 06:14:09 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
$ cat /etc/issue
Ubuntu 18.04.4 LTS \n \l
$ lscpu
Model name:          Intel(R) Core(TM) i9-7900X CPU @ 3.30GHz
$ mount|grep omni
/dev/nvme3n1p1 on /home/omnicore type btrfs (rw,noatime,nodiratime,nodatasum,nodatacow,ssd,space_cache,subvolid=597,subvol=/@omnicore)
```

This issue may also affect the balance value.  We have another node returned wrong balance value and we removed that node from our production environment 2 days ago.
 
A very high volume of USDT-OMNI transactions (high percentage of the total) are being conducted by [Bitpie Wallet](https://bitpie.com) every day. We hope to identify and solve this issue ASAP to avoid any risk of loss to user's assets.

**Comment by pranavburnwal** [comment]
+1

**Comment by bitcodernull** [comment]
I think the root cause is the wrong amount, twice the correct amount

**Comment by dexX7** [comment]
Hey guys, please retest with the latest version:

https://github.com/OmniLayer/omnicore/releases

Or with the develop branch:

https://github.com/OmniLayer/omnicore/tree/develop
