### ISSUE TITLE
We do not appear to fully agree with our peers

### ISSUE THREAD

**Issue by crow123** [OmniLayer/omnicore#1081]
RPC Query Failed (method: listtransactions, params: [*, 50, 0, true], response header: 500 Internal Server Error, response: {"result":null,"error":{"code":-2,"message":"Safe mode: Warning: We do not appear to fully agree with our peers! You may need to upgrade, or other nodes may need to upgrade."},"id":"1"}

**Comment by dexX7** [comment]
Please use the latest version v0.8.0.

https://github.com/OmniLayer/omnicore/releases
