### ISSUE TITLE
RPC can‘t use

### ISSUE THREAD

**Issue by baillluu123** [OmniLayer/omnicore#1088]
Hello, I have set up an omnicore wallet on the server, and the data is currently being synchronized.
I am currently experiencing some problems. When I use java to call the wallet's RPC api, it cannot be called. The error message is Connection refused: connect.
The server uses Alibaba Cloud. I have enabled all IP access permissions for the security group and the firewall is turned off. I don't know what’s wrong.

Here is my configuration bitcoin.conf file information

testnet = 1
server = 1
rpcuser = admin
rpcpassword = 1qaz @ WSX
rpcallowip = :: / 0
rpcport = 8080
rpcbind = 0.0.0.0
txindex = 1
datacarriersize = 80
omnidebug = tally
omnidebug = packets
omnidebug = pending

I checked the port listening on the server, and there is no port 8080. Is my RPC not working?
I guessed that maybe my configuration file didn't work.But my current wallet is a test network, the testnet configuration parameter of the configuration file, must be read,
otherwise it should be the mainnet by default.
Please help me to see if there is something wrong with my configuration file, or what configuration parameters missed?

**Comment by achamely** [comment]
@baillluu123 try setting the rpcbind= the actual ip address of your interface and not 0.0.0.0
The newer bitcoin core code the server is based on changed how rpc interface responds and you need to specific each ip address it is allowed to listen/respond on
