### ISSUE TITLE
json-rpc doc of omnicore-0.8.0??????

### ISSUE THREAD

**Issue by lijianl** [OmniLayer/omnicore#1092]
where could I find json-rpc api doc of omnicore-0.8.0? 
could you give any official link of json-rpc api doc?
it is hard to use jsonrpc after update omnicore to 0.8.0 version, json-rpc command ambiguous???

**Comment by fuckgm** [comment]
omnicore-cli help

**Comment by lijianl** [comment]
thanks you very much

**Comment by lijianl** [comment]
@fuckgm   are there any public node so that I can use to build a wallet service

**Comment by dexX7** [comment]
The latest RPC documentation can be found here:

https://github.com/OmniLayer/omnicore/blob/master/src/omnicore/doc/rpc-api.md
