### ISSUE TITLE
Slow sync on v0.8

### ISSUE THREAD

**Issue by pranavburnwal** [OmniLayer/omnicore#1094]
Extremely slow sync on v0.8

Older version usd to sync within a day on the same hardware. v0.8 is running from 2+ days.

omnicore V0.8
Self compiled

Ubuntu 16
4 cores
16Gb RAM
4GB Swap
SSD

**Comment by dexX7** [comment]
Hello,

just now I merged some very significant performance improvements for the initial synchronization and rescanning.

Are you able to build from source?

https://github.com/OmniLayer/omnicore/tree/develop

**Comment by pranavburnwal** [comment]
Thanks @dexX7 
Will try and update.
When can I expect these to go in new release?

**Comment by dexX7** [comment]
So far we haven't decided yet, if we wait for further improvements or release a minor version inbetween, but I will bring it to the meeting today.

**Comment by pranavburnwal** [comment]
Sure please update here. Thanks!

**Comment by chaoyebugao** [comment]
Version v0.8.0 release. I got the same problem. It got stuck when sync into 0.08%.

**Comment by pranavburnwal** [comment]
After testing the slow sync in fixed in current develop.

@dexX7  Can share when v0.8.1 is going to release

**Comment by dexX7** [comment]
Hi @pranavburnwal,

0.8.1 was released:

https://github.com/OmniLayer/omnicore/releases

**Comment by pranavburnwal** [comment]
@dexX7  Thanks!  Worked as a charm. So closed ticket.
