### ISSUE TITLE
Errors during RegTest: ERROR: CheckProofOfWork() : hash doesn't match nBits

### ISSUE THREAD

**Issue by msgilligan** [OmniLayer/omnicore#115]
I was running the Gradle `:omnij-rpc:regTest` task directly from IntelliJ (via the Gradle projects window) on Mac OS X 10.10.4 with commit ad189d67b6c2af10820066600cd2dab4f182a351 and my system slowed down and I noticed the `ERROR: CheckProofOfWork() : hash doesn't match nBits` being repeated rapidly and apparently endlessly.

This may have been the problem I saw while running RegTest last week. Because the problem seemed to be about to crash my machine, I immediately hit Command-Q in IntelliJ which was running the tests. When IntelliJ and therefore the test client exited, the message stopped repeating.

    Omni Core handler: new confirmed transaction [height: 2015, idx: 0]
    Omni Core handler: block connect end [new height: 2015, found: 0 txs]
    2015-07-06 06:47:26 update_tally_map(mpexoDuSkGGqvqrkrjiFng38QPkJQVFyqv, 1=0x1, +0, ttype=0) ERROR: amount to credit or debit is zero
      - Connect postprocess: 100.69ms [238.44s]
    - Connect block: 100.86ms [239.04s]
    keypool keep 3669
    ThreadRPCServer method=getblockcount
    ThreadRPCServer method=getblockhash
    ThreadRPCServer method=getblock
    ThreadRPCServer method=gettxout
    ThreadRPCServer method=setgenerate
    keypool added key 3770, size=101
    keypool reserve 3670
    CreateNewBlock(): total size 1000
      nActualTimespan = 139476644  before bounds
    GetNextWorkRequired RETARGET
    Params().TargetTimespan() = 1209600    nActualTimespan = 4838400
    Before: 207fffff  7fffff0000000000000000000000000000000000000000000000000000000000
    After:  1e09debb  000009debbc99a778556334111eefccdaab889667445223000ddebbc99a77855
      nActualTimespan = 139476644  before bounds
    GetNextWorkRequired RETARGET
    Params().TargetTimespan() = 1209600    nActualTimespan = 4838400
    Before: 207fffff  7fffff0000000000000000000000000000000000000000000000000000000000
    After:  1e09debb  000009debbc99a778556334111eefccdaab889667445223000ddebbc99a77855
      nActualTimespan = 139476644  before bounds
    GetNextWorkRequired RETARGET
    Params().TargetTimespan() = 1209600    nActualTimespan = 4838400
    Before: 207fffff  7fffff0000000000000000000000000000000000000000000000000000000000
    After:  1e09debb  000009debbc99a778556334111eefccdaab889667445223000ddebbc99a77855
          - Connect 1 transactions: 0.01ms (0.007ms/tx, 0.000ms/txin) [0.11s]
        - Verify 0 txins: 0.02ms (0.000ms/txin) [0.41s]
    ERROR: CheckProofOfWork() : hash doesn't match nBits
    ERROR: CheckProofOfWork() : hash doesn't match nBits
    ERROR: CheckProofOfWork() : hash doesn't match nBits
    ERROR: CheckProofOfWork() : hash doesn't match nBits
    ERROR: CheckProofOfWork() : hash doesn't match nBits
    ERROR: CheckProofOfWork() : hash doesn't match nBits
    ERROR: CheckProofOfWork() : hash doesn't match nBits
    ERROR: CheckProofOfWork() : hash doesn't match nBits
    ERROR: CheckProofOfWork() : hash doesn't match nBits

... snip ... (1000's of occurrences of the CheckProofOfWork() error message)

    ERROR: CheckProofOfWork() : hash doesn't match nBits
    ERROR: CheckProofOfWork() : hash doesn't match nBits
    ERROR: CheckProofOfWork() : hash doesn't match nBits
    ERROR: CheckProofOfWork() : hash doesn't match nBits
    ERROR: CheckProofOfWork() : hash doesn't match nBits
    ERROR: CheckProofOfWork() : hash doesn't match nBits
    Checking mempool with 0 transactions and 0 inputs
      - Load block from disk: 0.00ms [0.00s]
          - Connect 1 transactions: 0.01ms (0.006ms/tx, 0.000ms/txin) [0.11s]
        - Verify 0 txins: 0.02ms (0.000ms/txin) [0.41s]
        - Index writing: 0.08ms [0.25s]
        - Callbacks: 0.03ms [0.04s]
      - Connect total: 0.18ms [0.58s]
      - Flush: 0.03ms [0.02s]
      - Writing chainstate: 0.01ms [0.01s]
    Omni Core handler: block connect begin [height: 2045]
    estimates: for confirming within 0 blocks based on 100/3 samples, fee=0.00039525 BTC/kB, prio=-1
    Checking mempool with 0 transactions and 0 inputs
    UpdateTip: new best=00000064baa55013e7c99116bb365f74f0f99164a70c3ed3b3af7e676fc53b56  height=2046  log2_work=25.65125  tx=4854  date=2015-07-06 06:50:22 progress=1.000000  cache=554
    Flushed wallet.dat 110ms
    AddToWallet f225ffc14c3ce698de3fc3cc2a29e9a1739b74ea9cc968e1c2bf7c99d901e239  new
    Omni Core handler: new confirmed transaction [height: 2046, idx: 0]
    Omni Core handler: block connect end [new height: 2046, found: 0 txs]
      - Connect postprocess: 166.35ms [243.72s]
    - Connect block: 166.57ms [244.33s]
    keypool keep 3772
    Flushing wallet.dat
    Flushed wallet.dat 65ms

**Comment by msgilligan** [comment]
This seems to be reproducible on the 2nd time I run the tests after starting Omni Core. (Note that I use a shell script that removes the Omni state files to start omnicored)

**Comment by zathras-crypto** [comment]
Interesting...

Is this new?
Do you see the same CheckProofOfWork() regularly or is this something
you've only started seeing recently?


FYI, our Omni Code doesn't usually touch underlying Bitcoin stuff (eg such
as block generation and validation) so my first guess is this is something
we've inherited from upstream.

**Comment by dexX7** [comment]
In regtest mode the mined blocks must satify a certain level of difficulty, which is low, but still given. In `setgenerate` it loops until sufficient difficulty is reached:

https://github.com/OmniLayer/omnicore/blob/omnicore-0.0.10/src/rpcmining.cpp#L181-L184:

```c++
while (!CheckProofOfWork(pblock->GetHash(), pblock->nBits)) {
    // Yes, there is a chance every nonce could fail to satisfy the -regtest
    // target -- 1 in 2^(2^32). That ain't gonna happen.
    ++pblock->nNonce;
}
```

Each time it's not sufficient, a log entry is written:

https://github.com/OmniLayer/omnicore/blob/omnicore-0.0.10/src/pow.cpp#L93-L95:

```c++
// Check proof of work matches claimed amount
if (hash > bnTarget)
    return error("CheckProofOfWork() : hash doesn't match nBits");
```

If it becomes too much, and the regtests slow down, it helps to clear the whole regtest dir. The block reward decreases over time, also in regtest mode, so more mining is required, the more tests you run. :)

Feel free to reopen, if there is something else.
