### ISSUE TITLE
Start File not created on SRC directory

### ISSUE THREAD

**Issue by Daniel600** [OmniLayer/omnicore#1171]
HI All - we are currently running Omni 0.8.2 looking to be able to query the UTXO set via address - we came across this pull request which seems ready - https://github.com/OmniLayer/omnicore/pull/1165 - however when we try and run the version - https://github.com/Bushstar/omnicore/tree/omni-add-bitcore-indexing  - the src directory does not create omnicored start file

**Comment by Bushstar** [comment]
Please note that the address indexing feature should be regarded as experimental, we are still testing it ourselves.

Can you share your ./configure options?

I'd like to try and recreate the problem you are experiencing.

**Comment by Daniel600** [comment]
./configure --disable-wallet

**Comment by Daniel600** [comment]
Result after command -

```
Options used to compile and link:
with wallet = no
with gui / qt = yes
with bip70 = yes
with qr = yes
with zmq = yes
with test = yes
with fuzz = no
with bench = yes
with upnp = yes
use asm = yes
sanitizers =
debug enabled = no
gprof enabled = no
werror = no

target os = linux
build os =

CC = gcc
CFLAGS = -g -O2 -fPIC
CPPFLAGS = -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS -fPIC
CXX = g++ -std=c++11
CXXFLAGS = -fstack-reuse=none -Wstack-protector -fstack-protector-all -Wall -Wextra -Wformat -Wvla -Wformat-security -Wredundant-decls -Wno-unused-parameter -Wno-implicit-fallthrough -g -O2 -fPIC
LDFLAGS = -pthread -Wl,-z,relro -Wl,-z,now -pie
ARFLAGS = cr
```

**Comment by Bushstar** [comment]
I think that you are on the wrong branch. I use that repo for all Bitcoin GitHub forked projects, see if you have a bitcoind binary in the src directory. The output should have with `bitcore  = yes` at the top. Try running the following to checkout the Bitcore indexing branch.

`git checkout omni-add-bitcore-indexing`

You need to run configure as follows to enable the indexing.

`./configure --disable-wallet --enable-bitcore-rpc`

The output should show the following at the top.

```
Options used to compile and link:
  with wallet   = no
  with bitcore  = yes
```

**Comment by chakhalyan1** [comment]
Hi @Bushstar thanks for answer  i have tested it again  same problem.
~/omnicore:# git checkout omni-add-bitcore-indexing
error: pathspec 'omni-add-bitcore-indexing' did not match any file(s) known to git.
~/omnicore:# ./configure --disable-wallet --enable-bitcore-rpc
`Options used to compile and link:
  with wallet   = no
  with gui / qt = yes
    with bip70  = yes
    with qr     = yes
  with zmq      = yes
  with test     = yes
    with fuzz   = no
  with bench    = yes
  with upnp     = yes
  use asm       = yes
  sanitizers    =
  debug enabled = no
  gprof enabled = no
  werror        = no

  target os     = linux
  build os      =

  CC            = gcc
  CFLAGS        = -g -O2 -fPIC
  CPPFLAGS      =   -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2  -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS -fPIC
  CXX           = g++ -std=c++11
  CXXFLAGS      =   -fstack-reuse=none -Wstack-protector -fstack-protector-all  -Wall -Wextra -Wformat -Wvla -Wformat-security -Wredundant-decls  -Wno-unused-parameter -Wno-implicit-fallthrough   -g -O2 -fPIC
  LDFLAGS       = -pthread  -Wl,-z,relro -Wl,-z,now -pie
  ARFLAGS       = cr`

**Comment by Bushstar** [comment]
It could not find the branch for some reason. Try cloning the repo again using the following which specifies the branch at the outset.

`git clone https://github.com/Bushstar/omnicore.git -b omni-add-bitcore-indexing`

Otherwise you can clone from OmniLayer and then checkout PR https://github.com/OmniLayer/omnicore/pull/1165.

```
git clone https://github.com/OmniLayer/omnicore
git pull origin pull/1165/head
```

When you run `git log` in the repo you should see the following as the last commit.

```
Author: Peter Bushnell <bushsolo@gmail.com>
Date:   Mon Aug 24 13:05:44 2020 +0100

    Add Bitcore indexing to Omnicore
```

**Comment by chakhalyan1** [comment]
result is 
`Options used to compile and link:
  with wallet   = no
  with bitcore  = yes
  ...
  ...
`

**Comment by Bushstar** [comment]
You should now be building with the indexing built in. Note that the following needs to be present in bitcoin.conf for the indexing to be enabled.

`addressindex=1`

**Comment by chakhalyan1** [comment]
its  correct in our config file,  this version will continue sync process Omni 0.8.2  version blockchain or will start from zero ?

**Comment by Bushstar** [comment]
It will have to reindex the entire chain to build up the address index. In my experience the reindexing is slower than running a new sync.

**Comment by chakhalyan1** [comment]
our bitcoin.config file like that
```
excessiveblocksize=2000000000
maxstackmemoryusageconsensus=2000000000
debug=1
printtoconsole=0
daemon=1
txindex=1
addressindex=1
timestampindex=1
spentindex=1
deprecatedrpc=accounts
deprecatedrpc=addwitnessaddress
deprecatedrpc=signrawtransaction
rpcuser=******
rpcpassword=******
rpcport=8332
rpcthreads=1024
rpcworkqueue=6144
rpcservertimeout=30
server=1
rest=1
```

**Comment by chakhalyan1** [comment]
> It will have to reindex the entire chain to build up the address index. In my experience the reindexing is slower than running a new sync.

it was done before  now

**Comment by chakhalyan1** [comment]
all steps done successfully, but when start ./omnicored it stoped again, in the loge show following row 
`2020-09-15T14:03:35Z : You need to rebuild the database using -reindex-chainstate to change -addressindex.`
it will take long ?

**Comment by Bushstar** [comment]
If you have a fully synced node then it will take a long time to reindex to build up the address index, in my experience it is quicker to sync a new data directory than to reindex.

**Comment by chakhalyan1** [comment]
ok thanks

**Comment by chakhalyan1** [comment]
Hi @Bushstar, Our sync process very slow, 2 day it was synced yet 35% is it ok?

**Comment by Bushstar** [comment]
@chakhalyan1 sorry, missed your last message, reindex is a very slow process, your time does seem typical.

Closing as ow resolved.
