### ISSUE TITLE
V0.11.0 release is mandatory but provides no estimation or date for activiation

### ISSUE THREAD

**Issue by jblanchette-circle** [OmniLayer/omnicore#1236]
Please correct or point in the right direction and close is this is incorrect!

---

In the latest release here: https://github.com/OmniLayer/omnicore/releases/tag/v0.11.0

It claims to be mandatory and says "after the activation" but does not state when that will be or how to know when to expect it

> This release is mandatory and after the activation of the new features

Please advise for node maintainers and providers.  

When possible request this information is always provided for mandatory updates in the release tags 🙏

**Comment by du2zy** [comment]
There is also no updated link and hash on the download page of the official website: https://www.omnilayer.org/download.html

Fix it, please!

**Comment by dexX7** [comment]
Hey guys,

thanks a lot for the feedback! I'm currently updating the download links on omnilayer.org and they will be live later.

As for the update timing: when we activate the new features, there is a two weeks period within the version must be updated. There will be a note within Omni Core, as well as on our Twitter (https://twitter.com/omni_layer) and other channels.

**Comment by dexX7** [comment]
Should be updated now!

https://www.omnilayer.org/download.html
