### ISSUE TITLE
Transaction refund

### ISSUE THREAD

**Issue by Kennyalph** [OmniLayer/omnicore#1239]
Hello Omni team!! I need assistance in the reversal of an $800 usdt I sent from my binance usdt wallet to another binance btc wallet.. I have attached a screenshot of the transaction details to this email.. I will be glad if the team can refund because this money is all my life saving.. thanks for the anticipated assistance #
![Screenshot_2021-09-21-12-38-56-595_com android chrome](https://user-images.githubusercontent.com/91131260/134168249-0b385171-d73c-4eb5-91d0-651e15ca0698.jpg)

**Comment by achamely** [comment]
@Kennyalph We do not have the ability to reverse/return anything. 
All funds are owned and controlled by the address they are currently on. 
As you have mentioned that is a Binance BTC wallet you need to contact the Binance support team, explain what you transferred an unsupported token to your BTC address and request their assistance in recovering the funds.
