### ISSUE TITLE
cannot upgrade

### ISSUE THREAD

**Issue by tydiamo** [OmniLayer/omnicore#1240]
hello
directory ./omnicore/src
i have replace "omnicore-cli" with the lastest file
but i cannot put the lastest "omnicored" with PSFTP

the i delete the old "omnicored" on my server
and put the lastest "omnicored" with PSFTP

after these operation ,i  restart omnicore via
`cd 
./start_omni.sh
`

it comes out "failed to run command './omnicore/src/omnicored': Permission denied"

could u pls help me ?

**Comment by achamely** [comment]
@tydiamo it sounds like permission on your omnicored file are too limited. 
try changing the permissions on omnicored to make it readable/executable by everyone on your system
`chmod 755 omnicored`
