### ISSUE TITLE
Taproot support

### ISSUE THREAD

**Issue by markya0616** [OmniLayer/omnicore#1243]
https://decrypt.co/80904/new-bitcoin-core-release-adds-taproot-what-you-need-know

Bitcoin Core version 22.0 supports the upcoming Taproot protocol upgrade.
For Omni, we should release a new version of omni node based on Bitcoin Core v22.0 to support Taproot?

**Comment by dexX7** [comment]
Hey,

we are going to rebase Omni Core on top of a newer Bitcoin Core version, but there is currently no ETA yet.

**Comment by markya0616** [comment]
@dexX7 Taproot activation will happen on 11/16. What happen if we keep using the omni version which doesn't not support Taproot?

**Comment by dexX7** [comment]
It won't change, you can still Omni Core and regular Bitcoin transactions.
