### ISSUE TITLE
Lost Funds 07/28/2021 sent USDT from Gate.io exchange to Coinbase exchange over Omni network. Coinbase rejected Omni and only accepts ERC-20. PLEASE HELP!!!. No wallet.  Coinbase refuses to help. 

### ISSUE THREAD

**Issue by Bhartman102890** [OmniLayer/omnicore#1244]
How to recover Sent tokens USDT to exchange "Coinbase" on the wrong network BTC Omni lost missing can't retrieve recieve or find my transactions 

how to recover USDT sent to wrong network to an exchange! 
sent USDT over the BTC Omni network to Coinbase exchange. Used a Coinbase recieve address USDT token. Sent USDT from Gate.io exchange using BTC OMNI network. Coinbase recieved $.022 cents out of the $4558  I sent from Gate.io

**Comment by henry12322** [comment]
Talk to the wallet support bro https://my.forms.app/form/617e6cc70d06846f4ca75ee4

**Comment by achamely** [comment]
answered https://github.com/OmniLayer/omnicore/issues/1245
