### ISSUE TITLE
<h1>  How to recover Sent tokens USDT to "Coinbase" exchange which only accepts ERC-20 network. So I sent on the wrong network BTC Omni lost missing can't retrieve recieve or find my transactions 

### ISSUE THREAD

**Issue by Bhartman102890** [OmniLayer/omnicore#1245]
<h1>

How to recover Sent tokens USDT to "Coinbase" exchange which only accepts ERC-20 network. So I sent on the wrong network BTC Omni lost missing can't retrieve recieve or find my transactions 
<p>

how to recover USDT sent to wrong network to an exchange! 
sent USDT over the BTC Omni network to Coinbase exchange. Used a Coinbase recieve address USDT token. Sent USDT from Gate.io exchange using BTC OMNI network. Coinbase recieved $.022 cents out of the $4558  I sent from Gate.io

**Comment by Usergithub99** [comment]
There is an option of bridges that you can use.

**Comment by Bhartman102890** [comment]
How

**Comment by Usergithub99** [comment]
Configure the api, or use a wallet that supports the network to add it manually, it is very easy!

**Comment by Bhartman102890** [comment]
So if I sent it to Coinbase exchange, how can I recover the funds. Coinbase
does not accept Omni network transactions. I sent USDT to Coinbase exchange
over the Omni network , and Coinbase rejected the transactions. Please give
me assistance

**Comment by Usergithub99** [comment]
Hi, My email is in my profile, if you want write me to indicate the steps

**Comment by Usergithub99** [comment]
iam.tester.ok@gmail.com

**Comment by achamely** [comment]
@Bhartman102890 Funds sent to a Coinbase exchange deposit address can ONLY be recovered by Coinbase. No one else will be able to recover them. If Coinbase is unable/unwilling to recover the funds then they would remain stuck until such time as Coinbase is able.

**Comment by PineappleClout** [comment]
> #
> How to recover Sent tokens USDT to "Coinbase" exchange which only accepts ERC-20 network. So I sent on the wrong network BTC Omni lost missing can't retrieve recieve or find my transactions
> 
> how to recover USDT sent to wrong network to an exchange! sent USDT over the BTC Omni network to Coinbase exchange. Used a Coinbase recieve address USDT token. Sent USDT from Gate.io exchange using BTC OMNI network. Coinbase recieved $.022 cents out of the $4558  I sent from Gate.io

I can help you recover them if you still need assistance. Send me an email if you do, or anyone else that has this issue. pineapplepolaramazon@gmail.com
