### ISSUE TITLE
What happens to tokens sent to a M address non generated by an Omnilite Core wallet?

### ISSUE THREAD

**Issue by imajinnmind** [OmniLayer/omnicore#1249]
HRU all?
First post here.
Not a dev or a coder.

I got my way around creating a token on the omnilite wallet.
To test the send/receive feature, i asked someone to provide me with an M address. Unfortunately is wasnt generated by omnilite wallet but a Litecoin wallet.
Checked the TXID on the block explorer; It was confirmed but the receiver did not receive the tokens.
I m curious to know what happened to these tokens and is there a way to retrieve them?

Tx in advance

**Comment by achamely** [comment]
@imajinnmind tokens still get transferred however because recipient does not use a wallet that supports the omni protocol they won't be able to see the tokens. 
They will need to import their address into a compatible wallet to see the tokens / regain access to them

**Comment by imajinnmind** [comment]
Thank you
