### ISSUE TITLE
Lost 11B on trading platform 

### ISSUE THREAD

**Issue by DerionFaleneva** [OmniLayer/omnicore#1295]
General bitcoin questions and/or support requests are best directed to the Bitcoin StackExchange at https://bitcoin.stackexchange.com.

For reporting security issues, please read instructions at https://bitcoincore.org/en/contact/.

If the node is "stuck" during sync or giving "block checksum mismatch" errors, please ensure your hardware is stable by running memtest and observe CPU temperature with a load-test tool such as linpack before creating an issue! -->

**Expected behavior**

**Actual behavior**

**To reproduce**

**System information**

**Comment by GarettBill** [comment]
Same thing happened to me but thanks to Blackhathacker111 who helped me message him on telegram his telegram username is https://t.me/Blackhathacker111

**Comment by DrrDino** [comment]
Do you know you can recover everything you lost on trading platforms?? Yes 100% legit message Blackhathacker111 on telegram he helped me recover all I lost
