### ISSUE TITLE
32 bit versions crash, when dumping crowdsale information

### ISSUE THREAD

**Issue by dexX7** [OmniLayer/omnicore#130]
On Windows, and Ubuntu, the 32 bit versions crash, when [dumping crowdsale information](https://github.com/OmniLayer/omnicore/blob/3c902a24530ec6a6421d5cd78891938f81865ba2/src/omnicore/sp.cpp#L579), which is used by [mastercore::eraseExpiredCrowdsale()](https://github.com/OmniLayer/omnicore/blob/3c902a24530ec6a6421d5cd78891938f81865ba2/src/omnicore/sp.cpp#L773).

I tested it via regtests, and the last line I see in my log:
```
eraseMaxedCrowdsale() FOUND MAXED OUT CROWDSALE from address= 'n3RMLuGrJv7sfKMsw1raKjmfekBgi8BHQG', erasing...
```
The `mastercore_crowdsales.log` was created, but is empty.

Since this feature is pretty much unused, and should be removed anyway, this is probably a good time.

**Comment by zathras-crypto** [comment]
Interesting...  If you ```--printtoconsole``` do you still see a crash?  I'm assuming so (assuming the problem is in ```crowd.print```).

> Since this feature is pretty much unused

I always thought of it as a debugging tool hehe rather than a feature (basically dump the SP database for the crowdsale to a log file).

**Comment by dexX7** [comment]
> If you --printtoconsole do you still see a crash?

Yes. Since the file is created, but empty, and there is no error message in the log, it looks like it's caused by:
```c++
fprintf(fp, "\n%s\n", DateTimeStrFormat("%Y-%m-%d %H:%M:%S", GetTime()).c_str());
```
Currently I have no good way to test this, and only the binaries from the Gitian builds, so this is a bit like a black box, hehe.

> I always thought of it as a debugging tool

Hm.. in my opinion this is very similar to the STO file writing, which we also removed some time ago. What exactly would you miss? And couldn't this data also be retrieved via RPC, for example with `mscrpc 2`?

**Comment by zathras-crypto** [comment]
> Hm.. in my opinion this is very similar to the STO file writing, which we also removed some time ago. 

Fair point... The STO file writing I saw as just duplication (since data for an STO is already written to omnicore.log) and thus of no value...

> What exactly would you miss? And couldn't this data also be retrieved via RPC, for example with mscrpc 2?

```mscrpc 2``` does not provide historical crowdsale data (does it even provide active crowdsale data?) - I get that we can retrieve the data via RPC with say ```omni_getcrowdsale``` but my thoughts were simply that of debugging/verification - ie if we are investigating a bug with crowdsale processing - personally I always like to look to a log to compare with RPC output but perhaps that's just me hehe

**Comment by dexX7** [comment]
Ahh, now I see your point.

I like your idea of using `msc_debug_sp`.

What do you think about removing it, as done for the Travis tests, but with [fa7fd5e742](https://github.com/dexX7/bitcoin/commit/fa7fd5e742b32ff61e074d08b3c97916081d2fa7) to get the same information nevertheless?

**Comment by zathras-crypto** [comment]
> What do you think about removing it, as done for the Travis tests, but with fa7fd5e742 to get the same information nevertheless?

Perfect :)
