### ISSUE TITLE
Consensus mismatch (omni-mainnet-consensus #82) 

### ISSUE THREAD

**Issue by msgilligan** [OmniLayer/omnicore#134]
See https://ci.omni.foundation/job/omni-mainnet-consensus/82/

Note that #82 was triggered by a change to OmniJ and #81 completed successfully. So the mismatch is likely a result of new transactions rather than a recent change to Omni Core.

It also seems possible that the mismatch could be the result of a bug fix -- I haven't inspected the relevant transactions.

**Comment by msgilligan** [comment]
So, it looks like this was the first DEX Phase 2 transaction in the TEST OMNI (TMSC) Ecosystem on the Bitcoin MAIN NET. Given that the 3 remote servers are using Omni Core 0.0.9 for consensus these mismatches are expected.

I've disabled the TMSC comparison for now with a Spock `@Ignore` tag: https://github.com/OmniLayer/OmniJ/commit/541a111151aa22efcacd514fa9069a208346a170

I'm going to close this issue, too.

**Comment by msgilligan** [comment]
`omni-mainnet-consensus` is passing now:
https://ci.omni.foundation/job/omni-mainnet-consensus/86/

With TMSC comparison disabled we're down to *17,889* tests from *24,804* tests in the previous build.

**Comment by dexX7** [comment]
The test ecosystem is the wild west, without rules. :)

Thanks for the report nevertheless!
