### ISSUE TITLE
High resolution program icons

### ISSUE THREAD

**Issue by dexX7** [OmniLayer/omnicore#138]
Currently the icons used for Omni Core have a rather low resolution. This is especially notable on OS X.

We should try to replace them.

![preview](https://cloud.githubusercontent.com/assets/5836089/8746066/fb9c0b6e-2c85-11e5-87db-fce319041e19.png)

CC: @achamely: maybe there are some for OW?

**Comment by zathras-crypto** [comment]
@dexX7 I'll ping you and email with some images that might be useful...

**Comment by dexX7** [comment]
Yup, I'm currently looking into it. Thanks!

**Comment by dexX7** [comment]
We have:

- OS X: src/qt/res/icons/bitcoin.icns
- Windows: share/pixmaps/bitcoin.ico

Correct?

**Comment by dexX7** [comment]
Alright, this is much sharper:

![os_x](https://cloud.githubusercontent.com/assets/5836089/8749638/2589baf8-2ca3-11e5-84a8-e4b05201f6ce.png)

But I believe there should be a background image, similar to the following:

![bitcoin_core_osx-10 2](https://cloud.githubusercontent.com/assets/5836089/8749716/b34a758a-2ca3-11e5-9b2e-eb0b6080d01e.png)

![bitcoin_core_osx-11 0](https://cloud.githubusercontent.com/assets/5836089/8749719/b5d4b77a-2ca3-11e5-905b-38b7b4cdfd14.png)

We already replaced the image via https://github.com/OmniLayer/omnicore/pull/114/files, so I'm not sure, why it's missing. Maybe due to the file permissions?
