### ISSUE TITLE
Exodus crowdsale purchases do not update UI

### ISSUE THREAD

**Issue by zathras-crypto** [OmniLayer/omnicore#143]
Whilst not an issue for mainnet (there will never be any more Exodus purchases on mainnet), on testnet when sending funds to the moneyman address, when the transaction confirms there is no update to the UI thus the client must be closed and reopened to refresh the testnet MSC balance.

The cause is due to an optimization that ensures a cache check on balances is only performed in the event that there are Omni transactions within the block that could have changed the state.  Since an Exodus purchase is not currently considered an Omni transaction, the cache check is skipped and thus no balance changes to the wallet are detected by the cache code, meaning the UI is not notified of an update.

The offending code is in omnicore.cpp:
```
    // transactions were found in the block, signal the UI accordingly
    if (countMP > 0) CheckWalletUpdate();
```

The ideal resolution to the issue is to consider Exodus purchases as Omni transactions and thus update the count within the block handlers.

Further investigation required.

Note, this may also affect DEx v1 payments?  They need an Exodus output but carry no payload so I'm unsure if they're affected at this stage, more testing required to determine.

**Comment by dexX7** [comment]
I recall that I mentioned this some time ago, then it was fixed, if I'm not mistaken, but I can see, how this currently results in this issue.

Yes, DEx payments are affected, too.
