### ISSUE TITLE
send_all_MP method - send all owned omni assets in 1 transaction

### ISSUE THREAD

**Issue by nixoid** [OmniLayer/omnicore#153]
Hi there.

This is a high priority protocol feature request.

Some users have more than one omni-based asset on their address. Specifically users of Tether(http://wallet.tether.to/) already got 3 currencies + bitcoin and there are much more in plans.

We often have a need to transfer all assets from one account to another. Specifically:
1) when recovering multisig account with lost key
2) when merging 2 cold storage accounts
3) user wants to send all his money to his new account

It is inconvenient and expensive from technical and financial standpoint to broadcast separate transaction for each asset, especially given that wallet may support hundreds of them (holytransaction.com)

So, speaking on behalf of Tether, Holytransaction and other companies i can tell that we'd like to see this feature soon :) 

Important: it has to be a protocol method(as opposed to wallet rpc command) since we build transactions with own code.

Thank you.

**Comment by CraigSellars** [comment]
I have asked @nixoid to do a pull request against the spec so that it can be added

**Comment by dexX7** [comment]
Interesting idea.

The core implementation and RPC call should be easy.

ACK from my side.

**Comment by nixoid** [comment]
Protocol spec pull request created:
https://github.com/OmniLayer/spec/pull/313

**Comment by zathras-crypto** [comment]
ACK.  As per @dexX7 should be straight forward.

@dexX7 to avoid duplication of work, I'm happy to take this on as it should be a quick job but didn't want to double up if you were already on it.

**Comment by zathras-crypto** [comment]
> @dexX7 to avoid duplication of work

Scratch that, just saw your PR :)

**Comment by dexX7** [comment]
@zathras-crypto: I'm going offline for now, but I pushed #155 as starting point. There are two items I'm not really sure about, so input/contribution would be welcomed. :)

**Comment by zathras-crypto** [comment]
What should the behaviour be for reserved balances?  Eg:

* I list some of my tokens for property id n on the MetaDEx or DEx
* I broadcast a send all

Should my trades & sell offers be automatically cancelled and the reserved tokens returned to my balance, followed by sending to the recipient, or should a send all only apply to "available" balances?

**Comment by nixoid** [comment]
For menit's ok to simply reject send all transaction if some tokens are
locked

**Comment by zathras-crypto** [comment]
@nixoid I tend to look at rejecting a transaction as a last resort, so would prefer to define the behaviour and then allow a transaction to proceed in the case of reserved balances.  It's not too much trouble either way, we can either leave reserved balances in place at the original address or auto-cancel trades and then transfer reserved tokens along with the rest.  Input welcomed of course :)

Also FYI the implementation is taking place in https://github.com/OmniLayer/omnicore/pull/155, feel free to add any commentary/feedback.

**Comment by dexX7** [comment]
- "Send All" should only touch the available balance. This is the behavior we have everywhere else, too.

- While thinking about it, I noticed: with "send all" (and others) we must enforce that the first payload of a transaction is processed. Consider a "simple send" transaction, which Alice creates, where Bob appends a reference output (e.g. in the atomic swap scheme in #11). What we don't want is to give Bob the opportunity to sweep all tokens Alice has (or do something other than the initial "simple send"). This isn't new behavior, and already done, so it's more like a side note in this context.
