### ISSUE TITLE
Plan overall Omni Documentation Strategy.

### ISSUE THREAD

**Issue by msgilligan** [OmniLayer/omnicore#191]
@dexX7 and I have been talking about and working on documentation tools.

We'd like to discuss and agree upon an overall project documentation strategy for _all_ Omni projects.

I'd like to use the Github Pages site as the main location for technical (and white paper) documentation, but that is open for discussion.

Some of this discussion has happened around Issue #185, but I think we need a "parent" issue for the overall documentation strategy. I'll write a summary proposal in a future comment. (... before Monday)

**Comment by dexX7** [comment]
At the very beginning all files were mixed with the Bitcoin Core files, but we started to move into [src/omnicore](https://github.com/OmniLayer/omnicore/tree/omnicore-0.0.10/src/omnicore). In terms of code, this move isn't finished, and the QT/UI related files are still in the base QT dir. At least my current strategy regarding code is to split and untangle, and later group, merge and stuff everything in packages/subdirs.

We also moved the documentation, which introduced the issue that we now have two `README.md`, which I don't consider as optimal, but I currently also see no really good alternative.

Our documentation is unfortunally very limited, but let me quickly list all documents we have, or currently plan to have:

- [README.md](https://github.com/OmniLayer/omnicore/blob/omnicore-0.0.10/README.md) (duplicate)
- [src/omnicore/README.md](https://github.com/OmniLayer/omnicore/blob/052297b7ca80fbe220948465cd0836473fa8fb73/src/omnicore/README.md)
- [src/omnicore/COPYING] (https://github.com/OmniLayer/omnicore/blob/052297b7ca80fbe220948465cd0836473fa8fb73/src/omnicore/COPYING)
- [src/omnicore/doc/configuration.md](https://github.com/OmniLayer/omnicore/blob/052297b7ca80fbe220948465cd0836473fa8fb73/src/omnicore/doc/configuration.md)
- [src/omnicore/doc/rpc-api.md](https://github.com/OmniLayer/omnicore/blob/dd7efd7162f6dddaa04ea269c27c9dbb8b229cc4/src/omnicore/doc/rpc-api.md)
- [src/omnicore/doc/release-notes.md](https://github.com/OmniLayer/omnicore/blob/052297b7ca80fbe220948465cd0836473fa8fb73/src/omnicore/doc/release-notes.md)
- [src/omnicore/doc/release-notes/](https://github.com/OmniLayer/omnicore/tree/052297b7ca80fbe220948465cd0836473fa8fb73/src/omnicore/doc/release-notes)

There is also the Bitcoin Core documentation in [doc/](https://github.com/OmniLayer/omnicore/tree/omnicore-0.0.10/doc) with some useful stuff in it, which we partially use, such as the build instructions or Gitian guide.

The following documentation related issues and tasks are not yet completed:

- #71: Documentation for Omni Core specific options
- #96: Changelog and release notes for 0.0.10
- #185: Create a CONTRIBUTING.md and define project related best practises
- #193: Documentation for Omni Core debug categories

**Comment by msgilligan** [comment]
I updated the [README](https://github.com/OmniLayer/omnilayer.github.io/blob/source/README.adoc) of the Github Pages site with more *How To* information about working on the site.

I also moved the`content`, `templates`, and `assets` directories [up 2 levels](https://github.com/OmniLayer/omnilayer.github.io/issues/6) to make them easier to find.

**Comment by dexX7** [comment]
Thanks @msgilligan!

Besides converting the available documentation, we also need to finalize the "docs in progress", which are currently scattered in keywords and small descriptions in the open issues.

As note and todo, mostly for myself:

- the documentation files need to be included in the [Makefile.am#L20-L28](https://github.com/OmniLayer/omnicore/blob/omnicore-0.0.10/Makefile.am#L20-L28)
- the Windows installer is generated via [NSIS](http://nsis.sourceforge.net/Main_Page), and the following lines touch the documentation: [src/omnicore/res/omnicore-setup-win.nsi.in#L78-L85](https://github.com/OmniLayer/omnicore/blob/30fdde4833ac20c130d62e9d560b3b0d70ee8744/src/omnicore/res/omnicore-setup-win.nsi.in#L78-L85)
- the deinstallation instructions for Windows are also handled via NSIS, and these parts are relevant: [src/omnicore/res/omnicore-setup-win.nsi.in#L133-L137](https://github.com/OmniLayer/omnicore/blob/30fdde4833ac20c130d62e9d560b3b0d70ee8744/src/omnicore/res/omnicore-setup-win.nsi.in#L133-L137)

**Comment by dexX7** [comment]
To quote @msgilligan:

---

I think the documentation needs of this project are significant enough that we should create a separate documentation site. That is, we shouldn't try to *present* all the documentation on the Github site.

The reasons for this are:

1. The quantity of documentation is large and needs to be organized, indexed, etc.
1. There is a need for documentation of multiple releases of the software to be available simultaneously (e.g. 0.0.9/stable and 0.0.10/beta)
1. The repository is a clone of the Bitcoin repository which we do not control, yet we need to keep things in sync.
1. We want to minimize the amount of software involved in the build process for security reasons.

Which brings us back to Issue #191.

As far as the README files go, I think we should really only have one -- the one that is the project homepage on Github. It should provide a summary of the project, explain that it is a fork of Bitcoin, and provide links to other documents. The README in `src/omnicore` should be really short and explain what the purpose of that directory is and where to go for more information. It won't be a web landing page like the main README, though people looking at downloads/checkouts of the source might want to open it to understand what the `src/omnicore` directory is.

---

I understand your reasoning. The idea behind having the primary readme in `src/omnicore` was basically to have everything together, and in regards to the project structure, Omni Core is currently like a plugin to Bitcoin Core, similar to LevelDB.

I tend to agree nevertheless: the readme in the project root is the "first impression" and where users start to look first, so it makes sense to introduce the project there, too.

**Comment by msgilligan** [comment]
Closing this issue was we have made progress on documentation in recent years and there are other places to continue this discussion.
