### ISSUE TITLE
Provide an on-chain hint to signal 0.0.10 compliance

### ISSUE THREAD

**Issue by dexX7** [OmniLayer/omnicore#192]
While we solved one problem of handling consensus breaking changes with the feature activation mechanism, namely that a hardcoded activation might be completely mis-timed, it's still not forseeable, if or when users update their software.

We currently don't have a way to determine whether users really updated, and it may be useful, if there were an identifiable characteristic that seperates 0.0.10 from 0.0.9 clients, even before we activate Class C, so I've been thinking about a few options, where we may sneak in a hint, ordered by reliability and absence of potentially negative side effects:

1. The sequence number byte of class B transactions is unchecked, and may be abused and replaced with a magic byte.

2. Due the fixed size of public keys, but variable size of actual payloads, there is usually unused payload space at the end of class B packets, which may be used. However, the availability of free space isn't guaranteed, but very likely.

3. Appending an extra data output with OP_RETURN is arguably cheap (in terms of transaction size), and until the switch over, it could be used as extra indicator. This isn't subtle, and if sending data outputs is deactivated (e.g. `-datacarrier=0`, `-datacarriersize=0`), then it won't work.

4. We could change the default `-minrelaytxfee` by one or two satoshi and thus affect the resulting output values of transactions (e.g. 546 satoshi as per default). This doesn't seem reliable though, given that there are currently still a lot of transactions with non-minimal output values in the wild, and I explicitly recommended to change the value manually during the recent "spam attack".

What we can not identify or tackle with any approach like this are custom implemenations aka. non-Omni Core clients, and this includes send scripts. As result, it can skew the impression.

We can also not necessarily assume that the ratio of hinting to non-hinting transactions reflects the ratio of updated and non-updated clients. Consider for example: if the last 90 of 100 transactions indicate an updated client, then it may as well just be the case that one single entity sent out many more transactions than others at that time.

Further it should be noted that not all network participants must update, and if we observe transactions without hint, then this doesn't imply the sender "may be left behind". A practical example: the faucet uses a custom transaction generation, but has no (and doesn't need any) understanding of what's going on, which is fine for the particular use-case, but again, something like this can skew the impression.

Last but not least, it may have an exposing effect in all cases. Most notably, if we assume evil intentions, then we could send out tainted/revealing release candidates to targeted users or integrators and then observe the chain to pin down and map tainted transactions (and therefore sources) to such targeted entities. Likewise, if the distribution of the release is staged in multiple steps (e.g. integrators first, then public release), then we would expose certain parties to some degree.

I'm playing devil's advocat here, given that identifying certain parties isn't all that difficult to begin with, but nevertheless, it makes the situation worse, so this may be weighted into a decision.

What do you think?

It would especially useful to get some feedback regarding Omni Wallet and other important participants. CC: @achamely, @nixoid: do you use Omni Core, or a custom implementation, to send transactions, and do you have an insight regarding other parties?

**Comment by dexX7** [comment]
The train has left the station. /close

**Comment by zathras-crypto** [comment]
Oh wow </redface> sorry dude for missing this :(

To be honest, I think that this wouldn't be reliable enough data (for the reasons you already noted) to be actionable without the possibility of funkiness from some outside entity.  

I'd love to know what kind of user base we have, how many and on what version but I think this is a project where we won't have that info - I'm hoping the activations system will do a good enough job at notifying old clients, but we'll still have to throw out an alert on the old methodology to ping 0.0.9 clients about the upgrade.  I was thinking:
* Send old-type alert when 0.0.10 final is released
* Send another old-type alert with new tx/ver to force shutdown at activation block when first new feature is activated
