### ISSUE TITLE
List all requirements, and tag issues with milestone for 0.0.10

### ISSUE THREAD

**Issue by dexX7** [OmniLayer/omnicore#194]
Using one issue to track the progress and requirements for the next release seems to have limited value, so I'd like to try to use the milestone feature of GitHub, which is probably a much cleaner solution.

I would like to gather *all* requirements necessary for the release, and I created a [milestone](https://github.com/OmniLayer/omnicore/milestones/0.0.10) for this purpose.

Here are four simple guidelines:

1. once there is *no* open issue tagged with [0.0.10](https://github.com/OmniLayer/omnicore/milestones/0.0.10) tag left, it means [0.0.10](https://github.com/OmniLayer/omnicore/milestones/0.0.10) is *ready* and we can publish a release candidate

2. if there is an unresolved bug, or feature that *must* be resolved or included in the release, and there is no related issue for it, a [new issue](https://github.com/OmniLayer/omnicore/issues/new) should be created

3. if there is an open issue, which is *necessary* for the release, but *without* the [0.0.10](https://github.com/OmniLayer/omnicore/milestones/0.0.10) milestone tag, the tag should be added

4. if there is an open issue, which is tagged with [0.0.10](https://github.com/OmniLayer/omnicore/milestones/0.0.10), but *not* considered as necessary for the release, the milestone tag should be removed

This means as consequence that as long as there are open issues with milestone tag, there won't be a release (or the process failed). This should help us to prioritize tasks and to get a better understanding of what still needs to be done.

Personally I'm going to be rather conservative, and I won't start to tag issues, which may, or may not be required for the release, and I would really welcome, if someone from the "planning committee" takes a moment to tackle it. I'm especially thinking about items such as the "send all" transaction type, or whether documentation is considered as a requirement, which I can't evaluate from my point of view, because I have no insight of the business side.

Maintainers can add and remove milestone tags similar to issue labels:

![set_milestone](https://cloud.githubusercontent.com/assets/5836089/9428478/5b58e09a-49af-11e5-8e79-b0da4158db2a.png)

Other contributors are welcome, and can leave a note in this thread, so a maintainer may tag the related issue.

The process itself may also be discussed here of course.

**Comment by zathras-crypto** [comment]
I think this is a great idea and will help to manage scope creep and maintain focus.

**Comment by dexX7** [comment]
I'm wondering, whether we should tag pull requests as well? Would be nice in retrospective to select milestone 0.0.10, to show all changes. Sort of like a build-in change log.

@zathras-crypto: do you think this is a good idea, or can you think of any complications here?

**Comment by dexX7** [comment]
Well, I guess that's it! :)

It would really be great to have release notes and a change log, but this is probably going to be aweful. :(

Other than that, what's next?

I suggest to:

1. finalize the docs
2. merge #162 last (ideally this -> the tag)
3. then do a test build
4. tag the release candidate
5. publish

The rc1 should be published to a somewhat larger audience, but not necessarily be considered as release:

- If no issues occure after some exposure, then the status is upgraded from rc1 -> release
- If there are issues, then the issues should be fixed, and rc2 scheduled, and the cycle repeats

**Comment by dexX7** [comment]
Release candidate 1 has been tagged, so there isn't much need for this issue anymore.

However, we should continue to use milestones: either for 0.0.10.1 or 0.0.11. The process should also be properly documted (where?).

**Comment by dexX7** [comment]
Just as quick note: I created the milestone [0.0.10.1](https://github.com/OmniLayer/omnicore/milestones/0.0.10.1) and tagged a few issues, which seem doable, but please please feel free to remove tags or add tags to other issues. :)
