### ISSUE TITLE
Prepare 0.0.10 developer preview 3 binaries

### ISSUE THREAD

**Issue by dexX7** [OmniLayer/omnicore#198]
This issue is mosty @zathras-crypto:

If we are going to create new binaries, then `rm -rf ~/omnicore ~/gitian.sigs` and `git clone` a fresh versions of [omnicore](https://github.com/OmniLayer/omnicore) and [gitian.sigs](https://github.com/OmniLayer/gitian.sigs). This is probably not be needed, since Gitian fetches from GitHub, but it doesn't hurt either.

The following commands refer to the [current tip](https://github.com/OmniLayer/omnicore/commit/d62b0a964924b3804fb5c6805b37e401dd20052c):
```bash
export SIGNER=dexX7
export COMMIT=d62b0a964924b3804fb5c6805b37e401dd20052c
export RELEASE=0.0.9.99-d62b0a9649
```
```bash
./bin/gbuild --commit omnicore=${COMMIT} ../omnicore/contrib/gitian-descriptors/gitian-win.yml
./bin/gsign --signer $SIGNER --release ${RELEASE}-win --destination ../gitian.sigs/ ../omnicore/contrib/gitian-descriptors/gitian-win.yml
mv build/out/omnicore-*.zip build/out/omnicore-*.exe ../
```
```bash
./bin/gbuild --commit omnicore=${COMMIT} ../omnicore/contrib/gitian-descriptors/gitian-linux.yml
./bin/gsign --signer $SIGNER --release ${RELEASE}-linux --destination ../gitian.sigs/ ../omnicore/contrib/gitian-descriptors/gitian-linux.yml
mv build/out/omnicore-*.tar.gz build/out/src/omnicore-*.tar.gz ../
```
```bash
./bin/gbuild --commit omnicore=${COMMIT} ../omnicore/contrib/gitian-descriptors/gitian-osx.yml
./bin/gsign --signer $SIGNER --release ${RELEASE}-osx-unsigned --destination ../gitian.sigs/ ../omnicore/contrib/gitian-descriptors/gitian-osx.yml
mv build/out/omnicore-*.tar.gz build/out/omnicore-*.dmg ../
```

As done before, we should sign the results: https://gist.github.com/dexX7/eb993493fb3b20f3b34f

**edit:** updated commit hash, see https://github.com/OmniLayer/omnicore/issues/198#issuecomment-138397396.

**Comment by dexX7** [comment]
Build results of https://github.com/OmniLayer/gitian.sigs/pull/9:

- [https://s3.amazonaws.com/.../0.0.9.99-01d49a6845/omnicore-0.0.9.99-dev-linux32.tar.gz](https://s3.amazonaws.com/ci.omnicore.private/builds/0.0.9.99-01d49a6845/omnicore-0.0.9.99-dev-linux32.tar.gz)
- [https://s3.amazonaws.com/.../0.0.9.99-01d49a6845/omnicore-0.0.9.99-dev-linux64.tar.gz](https://s3.amazonaws.com/ci.omnicore.private/builds/0.0.9.99-01d49a6845/omnicore-0.0.9.99-dev-linux64.tar.gz)
- [https://s3.amazonaws.com/.../0.0.9.99-01d49a6845/omnicore-0.0.9.99-dev-osx-unsigned.dmg](https://s3.amazonaws.com/ci.omnicore.private/builds/0.0.9.99-01d49a6845/omnicore-0.0.9.99-dev-osx-unsigned.dmg)
- [https://s3.amazonaws.com/.../0.0.9.99-01d49a6845/omnicore-0.0.9.99-dev-osx-unsigned.tar.gz](https://s3.amazonaws.com/ci.omnicore.private/builds/0.0.9.99-01d49a6845/omnicore-0.0.9.99-dev-osx-unsigned.tar.gz)
- [https://s3.amazonaws.com/.../0.0.9.99-01d49a6845/omnicore-0.0.9.99-dev-osx64.tar.gz](https://s3.amazonaws.com/ci.omnicore.private/builds/0.0.9.99-01d49a6845/omnicore-0.0.9.99-dev-osx64.tar.gz)
- [https://s3.amazonaws.com/.../0.0.9.99-01d49a6845/omnicore-0.0.9.99-dev-win32-setup.exe](https://s3.amazonaws.com/ci.omnicore.private/builds/0.0.9.99-01d49a6845/omnicore-0.0.9.99-dev-win32-setup.exe)
- [https://s3.amazonaws.com/.../0.0.9.99-01d49a6845/omnicore-0.0.9.99-dev-win32.zip](https://s3.amazonaws.com/ci.omnicore.private/builds/0.0.9.99-01d49a6845/omnicore-0.0.9.99-dev-win32.zip)
- [https://s3.amazonaws.com/.../0.0.9.99-01d49a6845/omnicore-0.0.9.99-dev-win64-setup.exe](https://s3.amazonaws.com/ci.omnicore.private/builds/0.0.9.99-01d49a6845/omnicore-0.0.9.99-dev-win64-setup.exe)
- [https://s3.amazonaws.com/.../0.0.9.99-01d49a6845/omnicore-0.0.9.99-dev-win64.zip](https://s3.amazonaws.com/ci.omnicore.private/builds/0.0.9.99-01d49a6845/omnicore-0.0.9.99-dev-win64.zip)
- [https://s3.amazonaws.com/.../0.0.9.99-01d49a6845/omnicore-0.0.9.99-dev.tar.gz](https://s3.amazonaws.com/ci.omnicore.private/builds/0.0.9.99-01d49a6845/omnicore-0.0.9.99-dev.tar.gz)

**Comment by zathras-crypto** [comment]
I was running through the process, but I have a hash mismatch on win64-setup.exe (but the hashes match for zip)...

You:
```
b0baae4b1666f45d39c9c20f0ba77db94c0d602f867419622cb6f0607d8d92df  omnicore-0.0.9.99-dev-win32-setup.exe
0d4d9900ebf5352b67b4e07f7da6a00c1e7795bfdf4f3d02060b96db8ddfee43  omnicore-0.0.9.99-dev-win32.zip
8147c7860edb44cc63f95ed50f92fa566cfd1cc5f04a519281fb31e148347b3e  omnicore-0.0.9.99-dev-win64-setup.exe
5d23ba79194d6e886c76e161f7dee76b0757335c205a2db64ad111d03cc67e36  omnicore-0.0.9.99-dev-win64.zip
e223b6cf10511583a413d7abed893e58f7bceb208f4af0cb3de17183a3e95b46  src/omnicore-0.0.9.99-dev.tar.gz
```

Me:
```
b0baae4b1666f45d39c9c20f0ba77db94c0d602f867419622cb6f0607d8d92df  omnicore-0.0.9.99-dev-win32-setup.exe
0d4d9900ebf5352b67b4e07f7da6a00c1e7795bfdf4f3d02060b96db8ddfee43  omnicore-0.0.9.99-dev-win32.zip
c8f8c98d5963eaebff9ff9cc0b6750173ca6d671274bc25a8c049b1b773f4944  omnicore-0.0.9.99-dev-win64-setup.exe
5d23ba79194d6e886c76e161f7dee76b0757335c205a2db64ad111d03cc67e36  omnicore-0.0.9.99-dev-win64.zip
e223b6cf10511583a413d7abed893e58f7bceb208f4af0cb3de17183a3e95b46  src/omnicore-0.0.9.99-dev.tar.gz
```

**Comment by dexX7** [comment]
> hash mismatch on win64-setup.exe

Argh, that's strange. Since the zips match, it might be similar to the last time: the setup/installer somehow messed up, except that we didn't touch the installer icons since then. :/

I'm away for now, but I re-run the Windows build to see, if it's yet another hash, or 8147c.. also the second time.

**Comment by zathras-crypto** [comment]
Our linux builds match FYI.  OSX is running now.  Once that is done I'll rerun the Windows build too and see if I get a hash that matches my last run.

**Comment by zathras-crypto** [comment]
OSX matches too.  So just win64-setup.exe.  Rerunning windows now.

**Comment by dexX7** [comment]
Just real quick: I've got another hash for win64-setup this time:
```
7539d458e69d4bcbdefeea157adc7da0a81e968777599c2991ace0777fd1d0ab
```
So there is a non-deterministic element during the setup file generation, like an icon that is recreated or  so, but I'm still surprised, because I don't recall we changed anything in that direction recently.

**Comment by zathras-crypto** [comment]
> So there is a non-deterministic element during the setup file generation

I got the same hash a second time round :/

**Comment by zathras-crypto** [comment]
>> So there is a non-deterministic element during the setup file generation

> I got the same hash a second time round :/

And same hash a third time:
```
c8f8c98d5963eaebff9ff9cc0b6750173ca6d671274bc25a8c049b1b773f4944  omnicore-0.0.9.99-dev-win64-setup.exe
```

**Comment by dexX7** [comment]
Interesting. What would you suggest to do next? I could setup a new VM, or try it on another machine, but that doesn't seem to help to pin down the issue. I could use an older commit as reference, to check, if I have mismatches only in this case, or generally.

Can you upload your build signatures? I compared mine, and it looks like the only difference is the hash, not the dependencies:

https://gist.github.com/dexX7/c66670ad289a071761e3/revisions

**Comment by zathras-crypto** [comment]
> What would you suggest to do next?

I'm not really sure - is there anything Gitian could be caching that is resulting me getting the same hash when you are not?  I didn't wipe ~/gitian-builder before starting (but did wipe ~/omnicore and cloned again).

> Can you upload your build signatures? 

Sure, https://github.com/OmniLayer/gitian.sigs/pull/10/files

**Comment by dexX7** [comment]
Thanks. We use different Gitian versions, which have slightly different output, but I removed the empty lines and compared it to my results:

https://gist.github.com/dexX7/c66670ad289a071761e3/revisions

While the last revision shows some changes, all of them are due to reordered lines, but not due to other hashes, so our setup and environment is definitely similar. After testing the current tip on mainnet, I'm going to restart the Gitian build process with the last commit, where our results matched. If it then also matches, I'm going to step through the commits and build each one twice, until I find the one where it starts to differ. Peew.. this is going to take time, hehe.

I didn't remove `~/gitian-builder` either, but in any case, even with a slightly different setup etc., it *should* match.

I see currently three options:

- there is a non-deterministic element (why only for me, not for you?)
- my build environment is compromised (why only the win64-setup build?)
- gitian-builder has an issue

Given that we had an issue with the installer before, I'd consider this as cause as most likely.

This is the diff since the last matching build:

- https://github.com/OmniLayer/omnicore/compare/b50c70e08a93cf8f49eaa56b8944c28755e97a38...OmniLayer:01d49a6845a05dc5a356e09f9878f6c3e8dd3c7a

And now I see we also updated the code base to the tip of bitcoin:0.10, but still.. I'm not really seeing anything unexpected, at least at the moment.

**Comment by dexX7** [comment]
Wow, that's really interesting and odd. I rebuild b50c70e08a93cf8f49eaa56b8944c28755e97a38, which previously matched [gitian.sigs/.../0.0.9.99-b50c70e08a-win](https://github.com/OmniLayer/gitian.sigs/tree/master/0.0.9.99-b50c70e08a-win).

And I actually have a different hash for win64-setup, while the others are the same!

If I recall correctly, then I published my results for this build when I was away with my notebook, so it was a different build machine.

I'm now going to wipe and setup a new Debian VM and start with the tip from scratch now.

**Comment by dexX7** [comment]
Haha, I can't believe it. With the presitine setup:
```
b3c9858febccb4dab0a313f10b77facd549db523b0b60ddb1d5d12c4bb1b496c  omnicore-0.0.9.99-dev-win32-setup.exe
0d4d9900ebf5352b67b4e07f7da6a00c1e7795bfdf4f3d02060b96db8ddfee43  omnicore-0.0.9.99-dev-win32.zip
c8f8c98d5963eaebff9ff9cc0b6750173ca6d671274bc25a8c049b1b773f4944  omnicore-0.0.9.99-dev-win64-setup.exe
5d23ba79194d6e886c76e161f7dee76b0757335c205a2db64ad111d03cc67e36  omnicore-0.0.9.99-dev-win64.zip
e223b6cf10511583a413d7abed893e58f7bceb208f4af0cb3de17183a3e95b46  src/omnicore-0.0.9.99-dev.tar.gz
4160b92fb594d01538be3dd527b7df2dc260fd65cb6dbda89aee621720ebf9c9  omnicore-win-0.10-res.yml
```

Now the win32-setup doesn't match. ;(

**Comment by dexX7** [comment]
On another machine I also see mismatches of winXX-setup.exe.

**Comment by dexX7** [comment]
Let's try something new: what Debian version did you use? What was the last commit of gitian-builder? (navigate to `~/gitian-builder` and type `git log`)

**Comment by zathras-crypto** [comment]
> Now the win32-setup doesn't match. ;(

:(

> On another machine I also see mismatches of winXX-setup.exe.

Double :(

> there is a non-deterministic element (why only for me, not for you?)

What can I do to help test here?  Would it help for me to spin up a completely fresh build environment and run the builds again?

> my build environment is compromised (why only the win64-setup build?)

Unlikely if you're getting mismatches with a pristine build environment...

> gitian-builder has an issue

Potentially, though I'm not sure how to troubleshoot that...

> If I recall correctly, then I published my results for this build when I was away with my notebook, so it was a different build machine.

Have you tried building on your notebook that you used for the last builds?

**Comment by zathras-crypto** [comment]
> Let's try something new: what Debian version did you use?

```
debian@debian:~$ cat /etc/issue
Debian GNU/Linux 7 \n \l
debian@debian:~$ cat /etc/debian_version 
7.8
```

> What was the last commit of gitian-builder?

```
debian@debian:~/gitian-builder$ git log -1
commit b48730064a54a01d926d60062e9feb303ede2396
Author: Miron <m@tradehill.com>
Date:   Tue Jun 30 15:17:41 2015 -0700

    handle no lxc installed
```

**Comment by dexX7** [comment]
> Have you tried building on your notebook that you used for the last builds?

Yep, though unfortunally not the same exactly same environment, but one I setup yesterday from scratch. Had mismatches for the setup files.

> What can I do to help test here?

I'm out of ideas mostly. I assume you can't publish your VM? Hehe. (even if, I'm not really sure, if this brings us closer to a solution)

> last commit

Thanks! I'm going to setup a similar environment, though since that commit, there were not many changes, as it looks like:

- https://github.com/devrandom/gitian-builder/compare/b48730064a54a01d926d60062e9feb303ede2396...master

**Comment by dexX7** [comment]
And again.. mismatch:
```
b0baae4b1666f45d39c9c20f0ba77db94c0d602f867419622cb6f0607d8d92df  omnicore-0.0.9.99-dev-win32-setup.exe
0d4d9900ebf5352b67b4e07f7da6a00c1e7795bfdf4f3d02060b96db8ddfee43  omnicore-0.0.9.99-dev-win32.zip
037e4dbe7b3f7332547f09618c7d3034acdcdb3cc720ac69a710d84270a5b26d  omnicore-0.0.9.99-dev-win64-setup.exe
5d23ba79194d6e886c76e161f7dee76b0757335c205a2db64ad111d03cc67e36  omnicore-0.0.9.99-dev-win64.zip
e223b6cf10511583a413d7abed893e58f7bceb208f4af0cb3de17183a3e95b46  src/omnicore-0.0.9.99-dev.tar.gz
```
This was with the gitian-build commit you mentioned, and Debian 7.8.

Now I could try to use Debian 8.1, given that this was the latest point where our hashes matched (the last dev preview, build via the notebook).

**Comment by zathras-crypto** [comment]
> This was with the gitian-build commit you mentioned, and Debian 7.8.

So if you re-run the build within the *same* environment, do you still get different hashes?

> Now I could try to use Debian 8.1, given that this was the latest point where our hashes matched (the last dev preview, build via the notebook)

There must be something else non-deterministic in the process, and my build VM must have it cached or something - that is the only thing I can think of :(

I can spin up and setup a new VM and try, but suspect I'll start getting different hashes same as you...

**Comment by dexX7** [comment]
Earlier I setup an EC2 instance, and guess what: the Win64 setup hash was different each build (tested it three times).

@zathras-crypto: so regarding the third preview: should we start with d62b0a964924b3804fb5c6805b37e401dd20052c?

**Comment by zathras-crypto** [comment]
> @zathras-crypto: so regarding the third preview: should we start with d62b0a9?

Yep that sounds good.  I'll let you know my results :)

**Comment by dexX7** [comment]
Okay, great. It probably takes a moment until I'm finished, but I'll post my results, too. I expect that the installers don't match, but if the others match, it would be great, if you could swap the files hosted via Chest (which are currently linked via the MetaDEx guide).

**Comment by dexX7** [comment]
I got the following results:
```
aedea1b3a12c1a95d2436b8c6ca15489590a2fbd58935daff49433a450a9786b  omnicore-0.0.9.99-dev-win32-setup.exe
612258637afe1cba6ef2288029a9f39ffb6660ae2bbdac32e5884c87718772fe  omnicore-0.0.9.99-dev-win32.zip
e125012e87ed6e6751fce5b051b3c8adb5079dd311899dca62df71d7b07aff24  omnicore-0.0.9.99-dev-win64-setup.exe
cdc0b8495f947d6b35ca749f22afb0781866c21e02158b49dcbe82b6e9113a90  omnicore-0.0.9.99-dev-win64.zip
27ed060db0c1bd20c51525710737a7bb3e5cf3b05dbb8b6a261a6c5a8b8f1beb  src/omnicore-0.0.9.99-dev.tar.gz
```
```
327388c3616c25f957b4b8ef4ac28a7da3ea025a039a143011b9626b1e2c4e11  omnicore-0.0.9.99-dev-linux32.tar.gz
0734a3dd8b970820beff3f27ff4b23662371eec2c73cdbc3e195c87d6c72d428  omnicore-0.0.9.99-dev-linux64.tar.gz
27ed060db0c1bd20c51525710737a7bb3e5cf3b05dbb8b6a261a6c5a8b8f1beb  src/omnicore-0.0.9.99-dev.tar.gz
```
```
359eb6d6364b84aca11b18c9796c6d475475fc98c972a0a2f6e66e055110d4b9  omnicore-0.0.9.99-dev-osx-unsigned.dmg
0d0d8e714e3d436cfd4c0eb5de381d57a063b5efb593076d7bb35eda966e6891  omnicore-0.0.9.99-dev-osx-unsigned.tar.gz
3182258edbe4ad7d21d6de6277382a4f07089d2a4aebdd6557f83183de4e9126  omnicore-0.0.9.99-dev-osx64.tar.gz
27ed060db0c1bd20c51525710737a7bb3e5cf3b05dbb8b6a261a6c5a8b8f1beb  src/omnicore-0.0.9.99-dev.tar.gz
```

**Comment by zathras-crypto** [comment]
I ran into some connectivity issues so still building, but so far I have:

```
aedea1b3a12c1a95d2436b8c6ca15489590a2fbd58935daff49433a450a9786b  omnicore-0.0.9.99-dev-win32-setup.exe
612258637afe1cba6ef2288029a9f39ffb6660ae2bbdac32e5884c87718772fe  omnicore-0.0.9.99-dev-win32.zip
3c3968baea4f9d4719732e07a0f362199aa21574085cfad3364e510e772032cc  omnicore-0.0.9.99-dev-win64-setup.exe
cdc0b8495f947d6b35ca749f22afb0781866c21e02158b49dcbe82b6e9113a90  omnicore-0.0.9.99-dev-win64.zip
27ed060db0c1bd20c51525710737a7bb3e5cf3b05dbb8b6a261a6c5a8b8f1beb  src/omnicore-0.0.9.99-dev.tar.gz
```

```
327388c3616c25f957b4b8ef4ac28a7da3ea025a039a143011b9626b1e2c4e11  omnicore-0.0.9.99-dev-linux32.tar.gz
0734a3dd8b970820beff3f27ff4b23662371eec2c73cdbc3e195c87d6c72d428  omnicore-0.0.9.99-dev-linux64.tar.gz
27ed060db0c1bd20c51525710737a7bb3e5cf3b05dbb8b6a261a6c5a8b8f1beb  src/omnicore-0.0.9.99-dev.tar.gz
```

Will update with OSX soon :)

**Comment by zathras-crypto** [comment]
And the OSX results:
```
359eb6d6364b84aca11b18c9796c6d475475fc98c972a0a2f6e66e055110d4b9  omnicore-0.0.9.99-dev-osx-unsigned.dmg
0d0d8e714e3d436cfd4c0eb5de381d57a063b5efb593076d7bb35eda966e6891  omnicore-0.0.9.99-dev-osx-unsigned.tar.gz
3182258edbe4ad7d21d6de6277382a4f07089d2a4aebdd6557f83183de4e9126  omnicore-0.0.9.99-dev-osx64.tar.gz
27ed060db0c1bd20c51525710737a7bb3e5cf3b05dbb8b6a261a6c5a8b8f1beb  src/omnicore-0.0.9.99-dev.tar.gz
```

So looks like we're a match for everything but the x64 windows installer.

I'll push up the sigs now.

**Comment by zathras-crypto** [comment]
Sigs pushed https://github.com/OmniLayer/gitian.sigs/pull/11

**Comment by dexX7** [comment]
Okay great, that's at least something! :)

> Sigs pushed OmniLayer/gitian.sigs#11

So the Win results won't match. What do you suggest? I think we should merge it nevertheless. I'm going to push mine in a few minutes.

**Comment by dexX7** [comment]
I found out that it's possible to remove entries from the Gitian results, and I pushed an update via https://github.com/OmniLayer/gitian.sigs/pull/14.

@zathras-crypto: can you publish an updated version without the Win64 installer, too?

To do so, remove:
```diff
diff --git a/0.0.9.99-d62b0a9649-win/zathras/omnicore-win-0.10-build.assert b/0.0.9.99-d62b0a9649-win/zathras/omnicore-win-0.10-build.assert
index c330aec..cbc2747 100644
--- a/0.0.9.99-d62b0a9649-win/zathras/omnicore-win-0.10-build.assert
+++ b/0.0.9.99-d62b0a9649-win/zathras/omnicore-win-0.10-build.assert
@@ -3,8 +3,6 @@
 
     612258637afe1cba6ef2288029a9f39ffb6660ae2bbdac32e5884c87718772fe  omnicore-0.0.9.99-dev-win32.zip
 
-    3c3968baea4f9d4719732e07a0f362199aa21574085cfad3364e510e772032cc  omnicore-0.0.9.99-dev-win64-setup.exe
-
     cdc0b8495f947d6b35ca749f22afb0781866c21e02158b49dcbe82b6e9113a90  omnicore-0.0.9.99-dev-win64.zip
 
     27ed060db0c1bd20c51525710737a7bb3e5cf3b05dbb8b6a261a6c5a8b8f1beb  src/omnicore-0.0.9.99-dev.tar.gz
```

Then delete the old signature:
```bash
~/gitian.sigs$ rm 0.0.9.99-d62b0a9649-win/zathras/omnicore-win-0.10-build.assert.sig
```

And create a new one (GPG has to be configured as usual):
```bash
~/gitian.sigs$ gpg --detach-sign 0.0.9.99-d62b0a9649-win/zathras/omnicore-win-0.10-build.assert
```

Finally publish the results:
```
~/gitian.sigs$ git checkout -b 0.0.9.99-d62b0a9649-update
~/gitian.sigs$ git add 0.0.9.99-d62b0a9649-win/zathras/omnicore-win-0.10-build.assert
~/gitian.sigs$ git add 0.0.9.99-d62b0a9649-win/zathras/omnicore-win-0.10-build.assert.sig
~/gitian.sigs$ git commit -m "0.0.9.99-d62b0a9649 build signature update of zathras
~/gitian.sigs$ git push origin 0.0.9.99-d62b0a9649-update
```

And create a pull request. :)

Once done our results match perfectly and we don't have "wrong" data in the repo.

Let me know, if you need help.

**Comment by zathras-crypto** [comment]
> can you publish an updated version without the Win64 installer, too?

Sure, I'll do it later this morning...

Re the win64 installer, what do you think I should do about uploading to Omnichest?  I don't want to leave the old x64 win installer but the guide links to it.  Should I just upload the non deterministic x64 installer from this new build?

**Comment by dexX7** [comment]
Yeah, it's a bit unfortunate that the version number is the same.

Options:
- update the guide, remove the installers
- upload installer nevertheless (your call)
- have a dead link (no!.. :)

**Comment by zathras-crypto** [comment]
> can you publish an updated version without the Win64 installer, too?

Done.

> update the guide, remove the installers

I went with this option :)

> if you could swap the files hosted via Chest (which are currently linked via the MetaDEx guide).

Done.

**Comment by dexX7** [comment]
Well, damn. :(

I have no idea how this happened, but I verified all previous results once again, and now that:
```bash
$ ~/gitian-builder/bin/gverify --destination ~/gitian.sigs --release 0.0.9.99-b50c70e08a-win ~/omnicore/contrib/gitian-descriptors/gitian-win.yml
```
```diff
  MISMATCH
- 942f62294d827418c8cce0bc25c66350b4609831a3cd3e3fb7b525dae016f6eb  omnicore-0.0.9.99-dev-win64-setup.exe
+ b95097ed4cb7b9082b49e1195a0873bb69ca2c537533da8fd8490f0afd406a00  omnicore-0.0.9.99-dev-win64-setup.exe
```

See:
- https://github.com/OmniLayer/gitian.sigs/blob/master/0.0.9.99-b50c70e08a-win/zathras/omnicore-win-0.10-build.assert#L6
- https://github.com/OmniLayer/gitian.sigs/blob/master/0.0.9.99-b50c70e08a-win/dexX7/omnicore-win-0.10-build.assert#L5

**Comment by dexX7** [comment]
@zathras-crypto: sorry for the trouble.. could you please mirror the steps from above, but also for the other mismatch?

```diff
diff --git a/0.0.9.99-b50c70e08a-win/zathras/omnicore-win-0.10-build.assert b/0.0.9.99-b50c70e08a-win/zathras/omnicore-win-0.10-build.assert
index 8ec51a1..3e72f68 100644
--- a/0.0.9.99-b50c70e08a-win/zathras/omnicore-win-0.10-build.assert
+++ b/0.0.9.99-b50c70e08a-win/zathras/omnicore-win-0.10-build.assert
@@ -3,8 +3,6 @@
 
     632106cbc51cb1d0c7e9e4118dc53cb1c9e9c2cb7a987626b71102e86d5cfe8c  omnicore-0.0.9.99-dev-win32.zip
 
-    b95097ed4cb7b9082b49e1195a0873bb69ca2c537533da8fd8490f0afd406a00  omnicore-0.0.9.99-dev-win64-setup.exe
-
     68d6bd2b8e515ba58969120258098c80a1673f1aa99991f56098d7e1b67de9a0  omnicore-0.0.9.99-dev-win64.zip
 
     fcd1dc5e3bc70e1217aed28aee6ac94bcad3c3ec6f035e8208ed122999367210  src/omnicore-0.0.9.99-dev.tar.gz

```
```bash
rm 0.0.9.99-b50c70e08a-win/zathras/omnicore-win-0.10-build.assert.sig
gpg --detach-sign 0.0.9.99-b50c70e08a-win/zathras/omnicore-win-0.10-build.assert
git checkout -b 0.0.9.99-b50c70e08a-update
git add 0.0.9.99-b50c70e08a-win/zathras/omnicore-win-0.10-build.assert
git add 0.0.9.99-b50c70e08a-win/zathras/omnicore-win-0.10-build.assert.sig
git commit -m "0.0.9.99-b50c70e08a build signature update of zathras"
git push origin 0.0.9.99-b50c70e08a-update
```

**Comment by zathras-crypto** [comment]
> sorry for the trouble.

No trouble at all mate :)  https://github.com/OmniLayer/gitian.sigs/pull/18

**Comment by dexX7** [comment]
Nice! :)

I'm going to close this issue, because the third preview is out.
