### ISSUE TITLE
Omnicore ping/socket timeout  |  frozen ?

### ISSUE THREAD

**Issue by achamely** [OmniLayer/omnicore#199]
Running into some weird ones with omnicore.  updated to (0b6ff8818983a06146bc75d620755ba831ee04d3)   and recompiled/rebuilt  with a make clean restarted with - -startclean  and it appears omnicore is freezing/timing out after a certain point:    this is the last lines i’m seeing in console 

2015-08-27 00:17:02 parseTransaction(block=371317, 2015-08-24 13:58:50 idx= 551); txid: 009867|
3141a07a444c2956f346594d5793206291139c1fb1c695aa62ce7ade16                                    |
2015-08-27 00:17:02     ------------------------------                                        |
2015-08-27 00:17:02              version: 0, class B                                          |
2015-08-27 00:17:02                 type: 22 (DEx Accept Offer)                               |
2015-08-27 00:17:02             property: 1 (MSC)                                             |
2015-08-27 00:17:02                value: 5.00000000                                          |
2015-08-27 00:17:02 DEx_acceptCreate: found a matching sell offer [seller: 1GZukjGe682vhi9N6rD|
WqqGVKmZ6mKha1i, buyer: 1QKeexfVVSVoiDvsPxtpv8Y3rVS7rFztLc, property: 1)                      |
2015-08-27 00:17:02 update_tally_map(1GZukjGe682vhi9N6rDWqqGVKmZ6mKha1i, 1=0x1, -500000000, tt|
ype=1): before=500000000, after=0                                                             |
2015-08-27 00:17:02 update_tally_map(1GZukjGe682vhi9N6rDWqqGVKmZ6mKha1i, 1=0x1, +500000000, tt|
ype=2): before=0, after=500000000                                                             |
2015-08-27 00:17:02 CMPAccept(500000000): d77c14d62451a46d7f7c82f34a26f4bc238c8607c14443a3828a|
3d11e7c5a7aa                                                                                  |
2015-08-27 00:17:02 recordTX(0098673141a07a444c2956f346594d5793206291139c1fb1c695aa62ce7ade16,|
 valid=YES, block= 371317, type= 22, value= 500000000)                                        |
socket receive timeout: 1201s                                                                 |
socket receive timeout: 1201s                                                                 |
ping timeout: 1200.037091s                                                                    |
socket receive timeout: 1201s                                                                 |
ping timeout: 1200.037845s                                                                    |
ping timeout: 1200.015288s                                                                    |
socket receive timeout: 1201s                                                                 |
ping timeout: 1200.038484s

restarting (with or without start clean) seems to generate the same result (with both appearing to restart parsing mp tx’s from scratch) any insights into what to do next would be appreciated

**Comment by dexX7** [comment]
Hi @achamely,

I'm going to try to reproduce this issue. Can you please post your `bitcoin.conf`, and the last lines of `debug.log`, as well as `omnicore.log`? Please remove all sensitive information (like RPC connection!). Which OS do you use?

**Comment by dexX7** [comment]
So far I was not able to reproduce the issue and I successfully parsed all transactions with the a build based on the current tip.

Does it always stop with the transaction you referred to, or just during the parsing in general?

**Comment by achamely** [comment]
@dexX7 i think the issue appears to be related to the rpc calls when its loading.  I disabled all remote query programs and restart omnicore again and it was able to finish parsing and no longer displays the timeout messages and responds to rpc commands as expected.   Not sure entirely but for now it seems the issue has disappeared so i'm going to close this

**Comment by dexX7** [comment]
Ah, thanks for the quick update and keeping me in the loop. Great to hear the issue is resolved for you.

It's a bit disturbing though. During the initialization phase, including the initial parsing, all RPC requests are responded to with JSON exceptions (error code -28), and this is pretty shielded from the rest. Please let me know, if you uncover something new. :)

**Comment by achamely** [comment]
yea, it may have just been a coincidence that disabling those other things first allowed it to work or it could have been a network thing that just worked itself out. either way i'll keep an eye on it
