### ISSUE TITLE
Add timeout to automated RPC tests

### ISSUE THREAD

**Issue by dexX7** [OmniLayer/omnicore#228]
Currently [the script used to run the OmniJ RPC tests](https://github.com/OmniLayer/omnicore/blob/omnicore-0.0.10/qa/pull-tester/omnicore-rpc-tests.sh) via Travis CI dumps the last 200 lines of `omnicore.log` in case of a failure. This is intended to identify issues.

However, if the tests stall for some reason, and no output is produced for more than 10 minutes, the job is cancelled and considered as failure without showing the log.

We should add a mechanism to cover this case, so the logs are also dumped, if no output was produced after 9:xx minutes or so.

Ping @msgilligan: could you assist here? :)

**Comment by msgilligan** [comment]
> the job is cancelled and considered as failure without showing the log.

Cancelled by Travis?

Can you use a shell `cleanup` function like [this one](https://github.com/OmniLayer/OmniJ/blob/master/test-omni-integ-regtest.sh#L4-L7)? I suppose it depends upon how Travis cancels the job.

**Comment by dexX7** [comment]
Ah, sorry to be unclear. Travis CI cancells stalled jobs, although the effort is probably moot, because all timeouts I have seen so far were not caused by OmniJ or Omni Core, but rather caused Travis (that's my guess, and they are very rare though).

Thanks for the cleanup trap hint, I assume it would then look like this?

```diff
  #!/bin/bash
  
+ function cleanup {
+     if [ $STATUS -ne 0 ]; then tail -n 200 $DATADIR/regtest/omnicore.log; fi
+ }
+ trap cleanup EXIT
+ 
  # Get BUILDDIR and REAL_BITCOIND
  CURDIR=$(cd $(dirname "$0"); pwd)
  . "${CURDIR}/tests-config.sh"
  
  TESTDIR="$BUILDDIR/qa/tmp/omnicore-rpc-tests"
  DATADIR="$TESTDIR/.bitcoin"
  
  # Start clean
  rm -rf "$TESTDIR"
  
  git clone https://github.com/OmniLayer/OmniJ.git $TESTDIR
  mkdir -p "$DATADIR/regtest"
  touch "$DATADIR/regtest/omnicore.log"
  cd $TESTDIR
  echo "Omni Core RPC test dir: "$TESTDIR
  echo "Last OmniJ commit: "$(git log -n 1 --format="%H Author: %cn <%ce>")
  $REAL_BITCOIND -regtest -txindex -server -daemon -rpcuser=bitcoinrpc -rpcpassword=pass -debug=1 -omnidebug=all -omnialertallowsender=any -discover=0 -listen=0 -datadir="$DATADIR" &
  $REAL_BITCOINCLI -regtest -rpcuser=bitcoinrpc -rpcpassword=pass -rpcwait getinfo
  $REAL_BITCOINCLI -regtest -rpcuser=bitcoinrpc -rpcpassword=pass -rpcwait getinfo_MP
  ./gradlew --console plain :omnij-rpc:regTest
  STATUS=$?
  $REAL_BITCOINCLI -regtest -rpcuser=bitcoinrpc -rpcpassword=pass -rpcwait stop
  
- # If $STATUS is not 0, the test failed.
- if [ $STATUS -ne 0 ]; then tail -n 200 $DATADIR/regtest/omnicore.log; fi
- 
- 
  exit $STATUS
```

**Comment by msgilligan** [comment]
That looks right. I'm not sure which signal (if any) you'll get when Travis cancels the job.

**Comment by dexX7** [comment]
Just to clarify: Travis cancells the job, if no output was received for more than 10 minutes, e.g. in case of a hung.

My initial idea was some kind of a watchdog with timer that gets active after 9:59 minutes of no output.

A cleanup trap could work, and I'm going to test it, if we experience the issue once more.

I'm going to close the issue for now, given that it was basically a one time event in the past, and currenty I don't see the need to take action.

Thanks neverthess for pushing me in the right direction!
