### ISSUE TITLE
Win64 installer via Gitian is not deterministic

### ISSUE THREAD

**Issue by dexX7** [OmniLayer/omnicore#230]
Since the second developer preview, as it looks like, we were unable to produce a deterministic Win64 installer. The cause is still unknown.

So far I've tested Debian 7.8, Debian 8.1, a Windows 8.1 host, a Windows 10 host, and using a Debian 8.1 instance via EC2.

As next step I'm going to build the tip of bitcoin:0.10 (https://github.com/bitcoin/bitcoin/commit/ae52a7ffd1b3743e76220812c7f581c5c08f975b), to see, whether this produces similar results. I'm also going to test to build the 0.10 tag, for which a bunch of [results](https://github.com/bitcoin/gitian.sigs/tree/master/0.10.0-win) are available upstream, if the tip is not deterministic.

This is a rather crude approach to pin down the issue, but I'm out of ideas. If the 0.10 tip is deterministic, then I'm going to replace our [omnicore-0.0.10/src/omnicore/res/omnicore-setup-win.nsi.in](https://github.com/OmniLayer/omnicore/blob/omnicore-0.0.10/src/omnicore/res/omnicore-setup-win.nsi.in) with the original [share/setup.nsi.in](https://github.com/OmniLayer/omnicore/blob/omnicore-0.0.10/share/setup.nsi.in).

The alternative I can currently think of is to manually go through all steps, i.e. mirror the behavior of Gitian.

**Comment by dexX7** [comment]
Okay... I tested https://github.com/bitcoin/bitcoin/commit/ae52a7ffd1b3743e76220812c7f581c5c08f975b, and the tip of bitcoin:10 is deterministic:

![010tip](https://cloud.githubusercontent.com/assets/5836089/9787160/781e0498-57c0-11e5-87f0-f9e4508fd77c.png)

**Comment by dexX7** [comment]
I confirmed that the first developer preview (https://github.com/OmniLayer/omnicore/commit/374779dbb677da3f3e62e59143f828364115f16b) is deterministic, and my results [match the original results](https://github.com/OmniLayer/gitian.sigs/tree/master/0.0.9.99-374779dbb6-win):

![dp1](https://cloud.githubusercontent.com/assets/5836089/9791118/cbe15a9e-57d9-11e5-8d9d-d1d719e1155d.png)

**Comment by dexX7** [comment]
The second developer preview (https://github.com/OmniLayer/omnicore/commit/b50c70e08a93cf8f49eaa56b8944c28755e97a38) is **not** deterministic:

![dp2](https://cloud.githubusercontent.com/assets/5836089/9792247/7e1815a4-57df-11e5-9601-1a9dacc77695.png)

This is good news, because there was only a handful of PRs inbetween. The full diff:

- https://github.com/OmniLayer/omnicore/compare/374779dbb677da3f3e62e59143f828364115f16b...OmniLayer:b50c70e08a93cf8f49eaa56b8944c28755e97a38

My guess right now is that it's caused by:

- #140 Use higher resolution program icons

**Comment by dexX7** [comment]
(forgot to send the last comment..)

The icon change was indeed the cause! After reverting 947a6cede385b5d5c8c2703525c3863e75aaf2c6, the results match!

![dp2revert](https://cloud.githubusercontent.com/assets/5836089/9794692/dba6bdb2-57ec-11e5-818d-bc83c2d4e92a.png)

Up next: create a new icon, but only with the sizes of the old icon, then apply it on top of the main branch and test again.

**Comment by dexX7** [comment]
It worked. :)

**Comment by zathras-crypto** [comment]
Mate you are a star!  :)
