### ISSUE TITLE
Keep rpc output as consistent as possible from 0.0.9 to 0.0.10 for integrators

### ISSUE THREAD

**Issue by achamely** [OmniLayer/omnicore#241]
Integrations and integrators generally rely on consistency with expected output, formatting and field names/indexes.

In mastercore 0.0.9  the Dex v1 output field was called 'subaction'
in omnicore 0.0.10 the field has been changed to just action. 

@zathras-crypto @dexX7 Can we revert the field name to subaction?

Ex:
gettransaction_MP 353a086c9f5dfe455d35e734ee31694722c861abbee46ec306be028f10b09c75
{
  "result": { ...
    "subaction": "Cancel",

vs

gettransaction_MP 353a086c9f5dfe455d35e734ee31694722c861abbee46ec306be028f10b09c75
{
  "result": {
    "action": "cancel",

**Comment by dexX7** [comment]
While I agree that we should try to maintain compatibility whenever possible, I also believe the API should be improved. The field `"action"` is available for DEx and MetaDEx transactions, and we don't use capitalized results anywhere else, which ultimately motivated the update.

What do you suggest do handle API changes in general? We had a bit of discussion about this, and basically came to the conclusion that changes should be kept minimal, and only included in major versions. This is a bit fuzzy, and some input would be helpful.

**Comment by msgilligan** [comment]
My suggestion is that there always be a 1 release "grace period" (deprecation warning) for any breaking changes. That means for 1 release both the new and previous version of the API will work. That way users can upgrade to the new version (especially if necessary for consensus) and then begin migrating to the new APIs.

If that's too difficult to do for 0.0.10 the so be it, but we should establish this policy for releases after 0.0.10.

For the above method would it be possible to have `gettransaction_MP` return the old JSON and `omni_ get transaction` return the updated JSON?

**Comment by achamely** [comment]
The hiccup was the subaction renamed to action but I've already updated omni_engine to handle both versions of the output and the capitalization isn't really an issue as everything is normalized before checking. In the long run it does makes sense to standardize the output to 'action'.  Part of the issue of alpha/beta testing is some of these changes are being discovered as we go ;)  

I do like @msgilligan's suggestion of a grace period for breaking changes but since omnicore is such a major rewrite/update i think it will be ok but we should make sure we document all change like this in release notes for integrators so they are well aware of the implications. 
Given this, I'll close out this issue for now.

**Comment by dexX7** [comment]
> Part of the issue of alpha/beta testing is some of these changes are being discovered as we go ;)

Yes, and that's very useful! This might have slipped through without this remainder. I added a note to the [changelog thread]. :)

I like your suggestions. As alternative I could also think about returning both fields:
```js
{
  // ...
  "subaction": "New",
  "action": "new",
  // ...
}
```

... but that's a bit aweful in my opinion.

> For the above method would it be possible to have gettransaction_MP return the old JSON and omni_ get transaction return the updated JSON?

`gettransaction_MP` is forwarded to `omni_get transaction`, and the whole RPC result construction is basically build around transaction types, and not calls.

**Comment by dexX7** [comment]
Side note regarding the labels: I'm really not sure, how to use "improvement". Almost all things we discuss are improvements, so this is kind of a wildcard. As rule of thumb the closest description I can think of is: "improvements are no features, i.e. it adds no new functionality, and there is no other fitting category". Ideally we should probably get rid of it, and use more explicit labels, to remove the uncertainty.

In the past days I changed and updated quite a few labels, and it's certainly not perfect, so please don't mind the back and forth! :) And please feel free to add new labels or change existing ones, whenever you think it's reasonable. In case it goes out of hand, we may create a thread to plan the use of labels.

**Comment by zathras-crypto** [comment]
> In mastercore 0.0.9 the Dex v1 output field was called 'subaction'
> in omnicore 0.0.10 the field has been changed to just action. 
> capitalization

I think it's probably not hugely likely that many integrators are matching capitalization on JSON attributes and the vast majority of integrators don't offer DEx interaction (so only use balance and send calls) thus we'll probably get away with the change.  Standardizing on lower case helps avoid potential pitfalls in the future on the off-chance someone does enforce matching capitalization :)

> Integrations and integrators generally rely on consistency with expected output, formatting and field names/indexes.

@achamely sorry for any problems caused by the change, and it's great to get this kind of feedback from your integration work on OmniWallet :)  Generally we try to keep things backwards compatible but occasionally on a change it isn't straight forward to do so.

> As alternative I could also think about returning both fields ... ... but that's a bit aweful in my opinion.

Agreed, I'm not too keen on this one, it could lead to confusion.

>> ...would it be possible to have gettransaction_MP return the old JSON and omni_ get transaction return the updated JSON?
 
> gettransaction_MP is forwarded to omni_get transaction

While the RPC layer has undergone far too much work in 0.0.10 to make it feasible to implement all the 0.0.9 code under the old names, it is possible to decouple the forward and duplicate ```omni_gettransaction``` into ```gettransaction_MP``` with a modified attribute name (```subaction``` instead of ```action```).  It's ugly, but doable.

> I added a note to the changelog thread. :)

Thanks :)  Perhaps in the release notes we can have a "Upgrading from 0.0.9 to 0.0.10" section, and there-in add a sub-section "RPC changes" where we advise about the attribute change and also advise about the ```omni_*``` calls & that the original ```*_MP``` calls are deprecated and will be removed in a future release.

**Comment by dexX7** [comment]
> I think it's probably not hugely likely that many integrators are matching capitalization on JSON attributes

If I'd process the data and need to learn more about the actual value, then there would be something like: `if result['action'] == "new"`, and string comparisons are usually case sensitive.

NACK on an RPC extension for `gettransaction_MP` for this release; it seems like an overkill. I support 100 % backwards compatibility for 0.0.10+ though.

**Comment by achamely** [comment]
@zathras-crypto  i fully support the "Upgrading from 0.0.9 to 0.0.10" section  that would be very good to have for any integrator when seeing explicitly what's changed with rpc calls. 

As to the string checks i already normalize everything to lowercase so capitalization didn't really matter, it was just the field name.  But i've already added additional logic to handle both so at this point omniEngine/wallet is ok and can handle either return (Yay for integrators letting me use them as a test bed for new software).   I agree that trying to split up the calls omni_* and *_MP is probably more hassle than its worth at this point in time and putting stipulations/announcements that they will be deprecated/moved over to the knew calls in the next release or two should be enough for any integrators to handle a graceful transition/update to the new call.
