### ISSUE TITLE
Enable "protected branch" feature of GitHub

### ISSUE THREAD

**Issue by dexX7** [OmniLayer/omnicore#245]
There is a really interesting improvement, which can be used to block pushes, which don't pass tests, and to prevent forced pushes (i.e. rewriting the git history):

https://github.com/blog/2051-protected-branches-and-required-status-checks

It works as expected:

```bash
/tmp/protected-branch-test$ git push origin master -f
Counting objects: 1, done.
Writing objects: 100% (1/1), 205 bytes | 0 bytes/s, done.
Total 1 (delta 0), reused 0 (delta 0)
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: Cannot force-push to a protected branch
To https://github.com/dexX7/protected-branch-test.git
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'https://github.com/dexX7/protected-branch-test.git'
```

@achamely, @CraigSellars: could you please enable this feature for the main branch here, including the CI tests?

To do so, please go to the repository `Settings`, then select `Branches`, and enable:

- [x] Protect this branch
- [x] Require status checks to pass before merging
- [x] Include administrators
- [x] continuous-integration/travis-ci

It should look like this:

![protected_branches](https://cloud.githubusercontent.com/assets/5836089/9975382/f4c6a706-5eba-11e5-9456-c033d81d7c24.png)

The guard can be disabled at any time.

**Comment by achamely** [comment]
Done and done

**Comment by herbeymoreno** [comment]
First merge, POST method api
