### ISSUE TITLE
Transactions Not Appearing in Omni Layer Tab

### ISSUE THREAD

**Issue by cc5alive** [OmniLayer/omnicore#265]
Sent 0.5 BTC on Omni Core Testnet TXID 40a5a43ddf9b3363cb300a3b949d33bc221c389e61ddb1fd67ce08f627a1401e-000 and received 50 OMNI and 50 Test OMNI.  These appear in the Balances tab but not in the Transaction tab under the Omni Layer sub-tab.

Testing with Mac OSX 10.10.5 with Omni Core version v0.10.2.0-d62b0a9 (64-bit).

**Comment by dexX7** [comment]
Exodus purchases are currently only processed on a low level. Thanks for pointing it out, this is definitely something to tackle!
