### ISSUE TITLE
Remove "Omni Wallet" branding in splash

### ISSUE THREAD

**Issue by zathras-crypto** [OmniLayer/omnicore#277]
As discussed during this mornings all hands, we're going to remove the "Omni Wallet" branding from the Omni Core splash screen to avoid user confusion.

I've knocked up some updated splashes (design unchanged, only the wording). 

Please let me know which one is preferred and I will put in a quick PR.  Note I shrunk and put the images on a background to make it easier to see them (as I couldn't figure a way to get GitHub to size & put a border around them).

Originals:
![compareorig](https://cloud.githubusercontent.com/assets/5633351/10927654/b9f609be-82f5-11e5-9249-dfbadc9acc3d.png)

Options:
![compare1](https://cloud.githubusercontent.com/assets/5633351/10927657/bd8f2006-82f5-11e5-9dd6-ef3acf580167.png)
![compare2](https://cloud.githubusercontent.com/assets/5633351/10927660/c0bcf9a6-82f5-11e5-9d82-1efad992f68f.png)
![compare3](https://cloud.githubusercontent.com/assets/5633351/10927663/c40da204-82f5-11e5-8c08-18a4816d021b.png)

Thanks
Z

**Comment by dexX7** [comment]
All of them look great!

I think I'd go with "Desktop" or "Qt".

**Comment by dexX7** [comment]
Resolved via #278.
