### ISSUE TITLE
Looking For Binaries

### ISSUE THREAD

**Issue by hamiltino** [OmniLayer/omnicore#280]
Looking for 64bit linux binaries, are there any available?

**Comment by zathras-crypto** [comment]
Hi,

We have a release candidate build (0.0.10-rc1) available for testing our upcoming 0.0.10 release.  We're just finalizing the hosting for the downloads, but I've popped it up on Omnichest.info for you in the mean time.

http://omnichest.info/omnicore/omnicore-0.0.10.0-rc1-linux64.tar.gz

Thanks
Z

**Comment by hamiltino** [comment]
Thank You!
