### ISSUE TITLE
UI broken when selling divisible for divisible

### ISSUE THREAD

**Issue by zathras-crypto** [OmniLayer/omnicore#294]
When attempting to trade divisible properties for divisible properties via the UI, the calculation for the amount desired can easily overflow ```int64_t``` and give unexpected results.  To maintain precision, the amount and price are first converted to their native ```int64_t``` representations before being multiplied and then subsequently divided by ```COIN``` if it's a divisible/divisible trade.  

Goes without saying that multiplying two ```int64_t```'s can overflow, for example if we take the below, we've got an amount of 250012345678 and a price of 100000000 - which overflows to an incorrect total price of 65544904940.  The recalculation function detects the overflow and presents "N/A" as the total amount, but the send function still allows the trade to go through with the incorrect amount desired:
![before](https://cloud.githubusercontent.com/assets/5633351/11490857/b6d0e7b8-9830-11e5-8a65-bd36608e2381.png)

**Comment by zathras-crypto** [comment]
See https://github.com/OmniLayer/omnicore/pull/295 for fix.

![after](https://cloud.githubusercontent.com/assets/5633351/11490996/cf574768-9831-11e5-8b35-a62a0be1814d.png)

**Comment by dexX7** [comment]
Tagged as target for 0.0.10.

**Comment by dexX7** [comment]
Resolved via #295.
