### ISSUE TITLE
When main Qt window is resized 'Balances' and 'Recent Transactions' don't grow to fill it.

### ISSUE THREAD

**Issue by msgilligan** [OmniLayer/omnicore#296]
For users with more than a handful of currencies, they can't be displayed in the 'Balances' area without scrolling. It would also be nice to be able to see more than a handful of 'Recent Transactions'

The two panels displaying this information should be sized/resized to fill the containing window, but they are not. See attached screenshot.

![screen shot 2015-12-01 at 7 04 02 pm](https://cloud.githubusercontent.com/assets/61612/11521938/a3271094-9866-11e5-95cb-54006e606161.png)

**Comment by dexX7** [comment]
I tried to tackle this and at least the balances field grows with the following patch:
```diff
diff --git a/src/qt/forms/overviewpage.ui b/src/qt/forms/overviewpage.ui
index 1d78759..b74ac50 100644
--- a/src/qt/forms/overviewpage.ui
+++ b/src/qt/forms/overviewpage.ui
@@ -238,10 +238,13 @@
      <property name="orientation">
       <enum>Qt::Vertical</enum>
      </property>
+     <property name="sizeType">
+      <enum>QSizePolicy::Preferred</enum>
+     </property>
      <property name="sizeHint" stdset="0">
       <size>
        <width>1</width>
-       <height>1</height>
+       <height>28</height>
       </size>
      </property>
     </spacer>
```

However, the number of recent transactions is hardcoded, so this is a bit more tricky.

**Minimum size:**

![small](https://cloud.githubusercontent.com/assets/5836089/12064881/f0c6c442-afcd-11e5-80b0-e04477c0eecf.png)

**Resized:**

![big](https://cloud.githubusercontent.com/assets/5836089/12064888/005ea73a-afce-11e5-8932-debe757e6d7d.png)

**Comment by zathras-crypto** [comment]
Nice :)

Recent transactions as you say is going to be more complex because of the hardcoded nature of the approach.  Since recent transactions is a big hack anyway (in order to display recent Omni transactions) perhaps it'll be better all round to just rip out the old Bitcoin panel for recent transactions and do our own.

**Comment by zathras-crypto** [comment]
As a side note, I'd like to see us move into our own forms entirely at some point, as that'll greatly reduce the impact of changes made upstream.

**Comment by dexX7** [comment]
> As a side note, I'd like to see us move into our own forms entirely at some point, as that'll greatly reduce the impact of changes made upstream.

I agree, this would be awesome.
