### ISSUE TITLE
Mac OS notification icons and labels are still 'Bitcoin-Qt' and orange 'B' image.

### ISSUE THREAD

**Issue by msgilligan** [OmniLayer/omnicore#297]
In one case both the icon and the application name are incorrect:

![screen shot 2015-12-01 at 6 58 04 pm](https://cloud.githubusercontent.com/assets/61612/11521993/4b1dac86-9867-11e5-8410-b264afbbc3a1.png)

In another case, the app name is 'Omni Core' but the icon is still the orange Bitcion logo:

![screen shot 2015-12-01 at 6 52 11 pm](https://cloud.githubusercontent.com/assets/61612/11522003/59866696-9867-11e5-917f-b12199f57af3.png)

**Comment by dexX7** [comment]
@msgilligan: is this still an issue with v0.2?

**Comment by dexX7** [comment]
After moving on top of Bitcoin Core 0.13, this may no longer be an issue.
