### ISSUE TITLE
Seed blocks need updating for 380000 to 390000

### ISSUE THREAD

**Issue by zathras-crypto** [OmniLayer/omnicore#319]
Block 390000 has passed, seed blocks should be updated.

**Comment by zathras-crypto** [comment]
Note to avoid duplication of effort - I'm part way through this and will submit in the morning.

**Comment by dexX7** [comment]
Haha, awesome. I'm very very glad you're on this! I probably would have started from scratch, or digged through the old threads to find the bits of last time. :)
