### ISSUE TITLE
Seed blocks from 370000 to 380000 are not used

### ISSUE THREAD

**Issue by zathras-crypto** [OmniLayer/omnicore#322]
```const int MAX_SEED_BLOCK = 369999;``` in ```seedblocks.cpp``` causes seed blocks 370000 to 380000 to be ignored and every block in the range to be checked.

A verification should be performed that the seed blocks are accurate for this range.

**Comment by dexX7** [comment]
Ouch, good catch!

I guess the last time we updated the seedblocks we just added the blocks, but missed to update the boundary. Could be tackled in combination with #319.

**Comment by zathras-crypto** [comment]
Exactly, yep I'm doing those now, and will run verification by doing a full parse with the seed block filter disabled and comparing the consensus hashes :)

**Comment by zathras-crypto** [comment]
Hmm...

```
Error: Shutting down due to failed checkpoint for block 380000 (hash 00000000000000000b06cee3cee10d2617e2024a996f5c613f7d786b15a571ff)
```

Investigating further now...

**Comment by dexX7** [comment]
Hmm... we both tested #267 (adding the seedblocks), so there was a flaw with the way how we tested them?

**Comment by zathras-crypto** [comment]
#267 is the API connector PR bud...

I'm not sure - I just ran through a full parse with seed block filtering disabled to double check the consensus hashes and they're fine, so the issue must be in the seed blocks for 370K to 380K.  Since we both tested with ```MAX_SEED_BLOCK``` incorrectly set to 370K instead of 380K I would assume that's why we didn't pick up the fault.

I've already done the seed blocks for 380K to 390K, but I won't publish them just yet until I figure out where the problem is with the blocks 370K to 380K (I have some scripts running to determine that now) so I can publish a single PR :)

**Comment by dexX7** [comment]
Yeah sorry, I flipped the numbers. Should have been #276.

**Comment by zathras-crypto** [comment]
Re testing approach, I think it's valid (comparing consensus hashes with & without the seed block filter) I just think in this case we were actually comparing without seed block filtering in both cases.

**Comment by zathras-crypto** [comment]
FYI, so far pinned it down to somewhere between 370K & 372K.  Narrowing further now...

**Comment by zathras-crypto** [comment]
Narrowed it further down to a 200 block range and did a quick compare with 'Chest's DB.  370002 is missing (the first seed block in that range) so it's possible it was a mistake when I was formatting.  Running testing now to see if that's the only one.

Side note, kind of lucky I used 'Chest for this, I had to login to AWS to change the firewall rules to access it from where I'm staying and I found I had accidentally left several big (C3.XLarge) instances running from some testing a couple of weeks back - d'oh!  If I hadn't seen that it could have got *very* expensive!

**Comment by zathras-crypto** [comment]
OK, sadly testing failed again so there are multiple missing seed blocks.  Not sure what happened with my generation last time (I use the same approach each time), I'm going to run through the generation process again and see if that corrects the results.

**Comment by zathras-crypto** [comment]
Cross post from Skype:
```
[3:00:17 AM] zathrasc: Interesting tidbit I noticed while doing the latest seed block and consensus hash lists - in the last few months more than 21% of Bitcoin blocks have contained at least one Omni transaction
```

**Comment by zathras-crypto** [comment]
OK, I've finally managed to eek out the problems and update the seed block list for 370,000 to 390,000 such that it passes the checkpoints (which are generated with the seed block filter disabled).  I'm going to reformat to clean it up and upload tomorrow (time for a New Years drink or two now hehe)...

One thing that became clear is that I'd like to revisit and get https://github.com/OmniLayer/omnicore/pull/226 in to the code, as it'll make debugging things like this much easier (FYI the problem was a change issuer transaction was missed earlier in the block list and it wasn't until a grant was attempted from the new issuer address that consensus hashing picked up the difference which obviously threw off my troubleshooting as the problem wasn't actually at the block where the consensus hashes differed).

Happy new year dude!

**Comment by dexX7** [comment]
Hey Z, hope you had some fun last night too! :) Happy new year!

Thanks for pinning this one down!

**Comment by zathras-crypto** [comment]
> Hey Z, hope you had some fun last night too! :) Happy new year!

Hehe thanks bud, yeah it was great to spend New Year with the family - a little too much to drink haha but that's half the fun :)  Happy New Year to you too mate, and hope you enjoyed yourself too :)
