### ISSUE TITLE
Remove unneeded seed blocks with structurally invalid transactions

### ISSUE THREAD

**Issue by dexX7** [OmniLayer/omnicore#329]
Via https://github.com/OmniLayer/omnicore/pull/325#issuecomment-168745414:

There are around 50 blocks that can be safely removed from the current seed block list, which are related to structurally invalid transactions.

**Comment by zathras-crypto** [comment]
Just noting the blocks to be removed here, I'll remove them from the seed block list and reformat to clean it up shortly.

```
259439
259446
259453
260118
260126
260754
260763
262051
262329
262353
262355
262358
262371
262700
263222
263781
263797
265589
265970
268283
269792
269832
269833
269834
270020
272877
280374
280465
285642
288704
289842
293016
296365
296383
304952
306853
306868
306870
306878
306894
314416
```
