### ISSUE TITLE
Add documentation for getseedblocks, getcurrentconsensushash, setautocommit

### ISSUE THREAD

**Issue by dexX7** [OmniLayer/omnicore#331]
Currently there is no RPC API documentation for the following calls:

- omni_getseedblocks
- omni_getcurrentconsensushash
- omni_setautocommit

Even though these are not really end-user calls, we should eventually document them.

**Comment by zathras-crypto** [comment]
Ack, will do :)

**Comment by dexX7** [comment]
This is roughly what I had in mind. The help texts should be adjusted (e.g. `blockhash` is missing for `omni_getcurrentconsensushash`). I'll push a PR later. :)

...

---

### omni_getseedblocks

Returns a list of blocks containing Omni transactions for use in seed block filtering.

WARNING: The Exodus crowdsale is not stored in LevelDB, thus this is currently only safe to use to generate seed blocks after block 255365.

**Arguments:**

| Name                | Type    | Presence | Description                                                                                  |
|---------------------|---------|----------|----------------------------------------------------------------------------------------------|
| `startblock`        | number  | required | the first block to look for Omni transactions (inclusive)                                    |
| `endblock`          | number  | required | the last block to look for Omni transactions (inclusive)                                     |

**Result:**
```js
[         // (array of numbers) a list of seed blocks
  nnnnnnn,  // the block height of the seed block
  ...
]
```

**Example:**

```bash
$ omnicore-cli "omni_getseedblocks" 290000 300000
```

---

### omni_getcurrentconsensushash

Returns the consensus hash covering the state of the current block.

**Arguments:**

*None*

**Result:**
```js
{
  "block" : nnnnnn,         // (number) the index of the block this consensus hash applies to
  "blockhash" : "hash",     // (string) the hash of the corresponding block
  "consensushash" : "hash"  // (string) the consensus hash for the block
}
```

**Example:**

```bash
$ omnicore-cli "omni_getcurrentconsensushash"
```

---


## Configuration

The RPCs for the configuration can be used to alter Omni Core settings.

### omni_setautocommit

Sets the global flag that determines whether transactions are automatically committed and broadcasted.

**Arguments:**

| Name                | Type    | Presence | Description                                                                                  |
|---------------------|---------|----------|----------------------------------------------------------------------------------------------|
| `flag`              | boolean | required | the flag                                                                                     |

**Result:**
```js
true|false  // (boolean) the updated flag status
```

**Example:**

```bash
$ omnicore-cli "omni_setautocommit" false
```

---

**Comment by zathras-crypto** [comment]
Ahh perfect, thanks dude - saved me a job hehe :)
