### ISSUE TITLE
Remove legacy code and hardcode activations

### ISSUE THREAD

**Issue by dexX7** [OmniLayer/omnicore#339]
This is up for discussion:

I'd like to hardcode the activation blocks and remove the legacy code, where possible.

After block 395000 we should check, whether this is safe to do.

There are two upsides:

- no need for a synchronized client, e.g. when decoding transactions and providing a height > class C activation
- less code (in particular I'm thinking about the old parsing code)

What's not yet clear to me is how to deal with the activated activation transactions: I tend to just ignore them. In the greater picture Omni features are activated by height, and not based on some transactions. Activation transactions are just a handy tool for Omni Core, but other implementations should just be fine with hardcoded values, instead of parsing activation transactions.

**Comment by CraigSellars** [comment]
By removing the legacy code, will there still be a method to allow for a “full parse” to confirm validity of the state prior to the code removal?

**Comment by dexX7** [comment]
Yes. Let me quickly explain what legacy code is about:

With 0.0.10 we touched a lot of consensus critical code, e.g. when adding Class C. While we assumed the new code has the same behavior as the old code, it was a risk we didn't want to take, so we decided to leave the old code completely untouched and only switch to the overhauled code via activation. Now that the activation is through, we can confirm that the overhauled code really had the same behavior as the old code, and the old code can safely be removed.

The other part of the issue tackles the activations. Now that we know the activation height, we could hardcode them (instead of relying on the activation transactions), but I'm not sure where you guys stand on this point.

**Comment by zathras-crypto** [comment]
...scrubbing comment left in draft...

@dexX7 must have missed this one, sorry dude - yep fully support removing legacy code that's unused, though what result are you trying to achieve by hardcoding activation heights?  I completely agree fundamentally speaking Omni features are activated by height, but that height is defined by an on-chain transaction.  I agree once a transaction has been committed to the blockchain we can essentially hard code its results, but we don't do that for anything else, so wondering what we gain from doing so with activations.

**Comment by dexX7** [comment]
I guess it comes down to the question, whether we change consensus rules backwards.

For example, if there is not a single mainnet transaction where the granting tokens side effect is triggered, we may as well remove the consensus switch and that feature completely, without changing history.

I'm currently running tests for granting tokens side effects and crowdsale crossovers, which probably have a chance to be removed (if we decide to). Then I'm going to check the DEx math overhaul, but if I'm not mistaken, we can't do it in this case (have tested it earlier).

**Comment by dexX7** [comment]
We could remove:

- FEATURE_GRANTEFFECTS
- FEATURE_SPCROWDCROSSOVER

We can not remove:

- FEATURE_DEXMATH

**Comment by zathras-crypto** [comment]
I support removing code where the change doesn't impact history.  Understand since DEx transactions are already on the books that we can't change those so FEATURE_DEXMATH needs to stay.

**Comment by dexX7** [comment]
> I support removing code where the change doesn't impact history.

I kind of feel like I'm nitpicking, so sorry for that. :)

But something else came to my mind, which has probably no practical relevance: if someone "doesn't like" a new feature, such as no more granting side effects, then he or she may just ignore an alert sender. If we hardcode new rules (i.e. remove the consensus activation switch), then this isn't possible anymore. If we consider this as fine, and basically detach rule changes from historical activations, then we may as well hardcode the activation blocks?
