### ISSUE TITLE
Activation warnings aren't visible in the UI until client restart

### ISSUE THREAD

**Issue by zathras-crypto** [OmniLayer/omnicore#342]
@msgilligan was chatting to me on Skype this morning and raised that the MetaDEx activation wasn't displaying in the client.  A restart of the client correctly displays the activation warning.

@dexX7 I'm sure we've discussed this one before, just opening an issue to make sure we keep track of it.  At first guess I'm thinking I probably should have added ``` uiInterface.OmniStateChanged();``` to ```AddPendingActivation()``` but I'll confirm and push up a fix.

**Comment by msgilligan** [comment]
I'm pretty sure @achamely saw the same issue on his (Win or Linux) machine.
