### ISSUE TITLE
v11 - Fees

### ISSUE THREAD

**Issue by patrickdugan** [OmniLayer/omnicore#345]
We want to toll the trading of non-OMNI pairs in v11 and distribute those fees to OMNI holders. 

Quoting Zathras:

"The idea of fees is clear - the implementation has not been done though in Omni Core and the path is less than clear on that front - stripping .05% (rounded to nearest token) fee is a non-issue.  Using existing STO (send to owners) logic is also pretty straight forward to distribute between existing Omni owners.  What's not straight forward is storing fractions of a token for accumulation - our tally systems in Omni Core don't have that level of precision, so we'd be looking at a secondary layer for fractions which must be persisted etc.  Bear in mind we're looking at a secondary layer for unique tokens too and I'm sure you can see where complexity might get out of hand quite quickly, so we should be considering the best approaches."

So I would suggest we do away with a secondary layer and focus on meeting min. requirements rather than absolute precision.

First off, the min. threshold to receive fees could be 1 OMNI, the eliminates the insanity of having 1 Willet receiving sub-willet fractions of other tokens.

Secondly, the allocation of fees should be N blocks, depending on how long it takes for the sum of fees in a particular currency (eg. USDT) to be at least ~606,500 Willets. Since the fee rate is 5 basis points, 1 USDT trades to create 1/20th a penny in fee revenue, or .00050000 USDT (50,000 Willets of Tether Dollars). That means only when about 12.02 USDT has traded will the sum hit the threshold and everyone who has at least 1 OMNI will receive at least 1 Willet on the following block. This logic can be applied continously. There is only 1 tally kept in the protocol that passes or fails check and then distributes when it passes. 

Am I missing anything?

**Comment by dexX7** [comment]
Hey guys,

just to clarify:

- the specification states a liquidity bonus for owners of sell orders
- a [blog post from J.R.](http://blog.omni.foundation/2014/06/11/mastercoin-is-for-burning/) mentions a fee, which is taken for non-Omni pairs, which is then "burned on the exchange"
- you are talking about redistribution (similar to https://github.com/OmniLayer/spec/issues/296?)

It's not clear to me which path we're going.

**Comment by zathras-crypto** [comment]
Just to avoid duplication of work dude I've made a start here, am currently adding helpers so we can work with fees, then I'll take a stab at the 0.05% math and pushing the fees into this new cache.

https://github.com/zathras-crypto/omnicore/tree/0.0.10-Z-MetaDExFees

**Comment by dexX7** [comment]
Resolved via #359.
