### ISSUE TITLE
v11 - Modify field for Reserve Properties

### ISSUE THREAD

**Issue by patrickdugan** [OmniLayer/omnicore#347]
In tx 56 and possibly the more vanilla generation of smart property, add a new parameter where the smart property can, by virtue of being on and address, put into reserve balance some proportional quantity of some other smart property. So:

Units to reserve per units of this smart property: int (e.g. 1, 5, ect.) and Smart Properties to reserve: property id or [propertyid1, id2...]

Additionally, to make these reserving properties meaningful at a protocol level, people shouldn't be able to just simple send them, otherwise the reservation powers are meaningless. 

So either these properties must be signed integers with a -1, +1 correlation between all units, or their movement may be invalidated by default and only subject to movement by some other app's trigger. The latter is very messy, the prior means these contract token types must be traded for on the Dex to net them out to 0 and thereby free balances. 

So 3 modifications: reserve params, signed integer values, de facto invalidation of simple sends to create enforced scarcity. First two are simple, latter is less problematic than the above paragraph's idea but still needs sandboxing.

**Comment by dexX7** [comment]
@patrickdugan: could you please post an example for this new transaction type, too?

The part I'm unable to grasp is:

> add a new parameter where the smart property can, by virtue of being on and address, put into reserve balance *some proportional quantity of some other smart property*

Initially I thought you want a plain and simple transaction type to "move tokens from the available balance into a reserved state [and potentially back]", but I guess there is more behind it?

**Comment by dexX7** [comment]
I think it's better to keep track of the specification or feature proposals in the spec repository:

https://github.com/OmniLayer/spec

Please feel free to open a new issue over there.
