### ISSUE TITLE
Fields for MetaDEx

### ISSUE THREAD

**Issue by zathras-crypto** [OmniLayer/omnicore#348]
```
[10:36:11 AM] Adam Chamely: oh one other thing
[10:36:32 AM] Adam Chamely: is it intentional that ['amountremaining']  is missing/removed when the status=filled
[10:36:41 AM] Adam Chamely: instead of just = 0
[10:37:06 AM] Adam Chamely: just want to confirm thats intentional and not a bug
[10:37:35 AM] Adam Chamely: (from the omni_gettrade output)
[10:37:52 AM] zathrasc: hmm, vaguely remember a discussion with @dexx on that one
```

@dexX7 I'm sure we talked about this before...  Can you remember our reasoning for removing the field? 

I'm pretty sure we opted to not state an amount was remaining if the trade was no longer open (eg a trade cancelled half way through may still have X amountremaining even though the trade is closed).

I can't recall properly though - what are your thoughts?

Options:
- amountremaining is not included in RPC output for non-open trades (current)
- amountremaining is included in RPC output always, is always zero for non-open trades
- amountremaining is included in RPC output always, is whatever the remaining value was before the trade was closed/cancelled

I'm trying to knock up a couple patches for @achamely to help with the OmniEngine integration, and this is one of the issues I'd like to lock in one way or the other.

Thanks
Z

**Comment by dexX7** [comment]
If I'm not mistaken, we discussed it in #200. A quote from you:

> Perhaps semantics but technically there is nothing available (remaining) if the trade is closed (filled or cancelled).

In terms of easier integration not omitting fields is easier.

**Comment by zathras-crypto** [comment]
Ahh perfect, thanks for that (how did you locate the old issue by the way?)

I see your point about omitting fields causing issues for integration, and now @achamely raised the same issue it adds more weight to the viewpoint.

Essentially my biggest concern was that:

1) I offer 10 X for sale
2) I sell 5 of them
3) I cancel the trade

The options available to us are:
1) Omit the ```amountremaining``` and ```amounttofill``` fields (the current code)
2) Provide these fields and set them to zero (may give incorrect impression that all tokens were sold)
3) Provide these fields and set them to whatever was left at time of cancellation (may give incorrect impression that tokens are still available)

I'm starting to think I may be worrying too much about giving an incorrect impression, after all this is an RPC layer that mainly integrators will be working with.

Given recent feedback I'd be inclined to go with option 2, since this doesn't require persisting extra data somewhere like levelDB (option 3 does).

Thoughts?

**Comment by dexX7** [comment]
I see up and downsides for each choice, so I'll leave the decision to you or @achamely.

**Comment by achamely** [comment]
For what it's worth, i'm basically taking the information you present now and incorporating the logic of option 2 into it within omniEngine and letting the rest of omniEngine's interpreter handle it from there.  So either option 1 or 2 works well for me. Option 3 is a little confusing with fields labeled amountremaining/amounttofill.  so my preference would be one of the first 2

**Comment by zathras-crypto** [comment]
I'd mostly like to do things in a standard way, I'm just not sure what that way should be haha :)

We currently omit fields in other places when they're not considered relevant (eg if a transaction is unconfirmed we omit the fields about the block - hash, height etc) but again I'm really not sure of the right way if integrators may rely on fields we omit in certain cases.  On the flip side, it may become troublesome to say we always want to include all fields in all cases as finding a suitable "empty" value for various things may not always be straightforward.

**Comment by dexX7** [comment]
> On the flip side, it may become troublesome to say we always want to include all fields in all cases as finding a suitable "empty" value for various things may not always be straightforward.

If only a part of an object can be representend correctly, it may make sense to split it into smaller parts, but this is probably even more inconvenient in this case (I'm mostly thinking about the discussion we started earlier re: stateful/stateless properties, etc.).

**Comment by dexX7** [comment]
MetaDEx was integrated some time ago.
