### ISSUE TITLE
MetaDEx fees distribution threshold

### ISSUE THREAD

**Issue by zathras-crypto** [OmniLayer/omnicore#351]
The requested distribution threshold is a floating target requiring the distribution to give each holder of at least 1 OMNI at least 1 willet of whatever property is being fee-distributed.

Unfortunately, I don't believe this is compatible with a dividend based on percentage of ownership.

The math has to cater for all eventualities, so let's look at the following hypothetical:

* Omni has let's say 500,000 tokens
* Alice owns 400,000 tokens 
* The other 100,000 tokens are split across 100,000 addresses, each address holding 1 Omni

So straight away Alice has 80% of the fee dividend.  Thus the remaining 20% must be stretched across 100,000 addresses, meaning said 20% must be at least 100,000 willets of the fee property to enable all addresses (>=1 OMNI) to get a share.  This in turn means 100% (ie the distribution threshold) must be at least 500,000 (if 20% must be at least 100,000).  For divisible tokens this is less of an issue, but for indivisible tokens having a fee distribution threshold of half a million tokens means it might never be reached.  There might not even be half a million tokens of that property in existence.

What about if we have 200,000 OMNI in 200,000 addresses, or 300,000 OMNI in 300,000 addresses and so on?

Basically in a nutshell the idea to use a floating threshold where we wait until there are enough fees to ensure every holder of at least 1 OMNI "gets something" is potentially flawed from a scalability PoV because the two factors involved are decoupled ("how many addresses hold at least 1 OMNI" and "how many tokens have been traded of property X" are not related).  It'd work in the current climate because OMNI tokens are only split across a few thousand addresses, but essentially the more addresses hold >=1 OMNI, the more difficult it's going to be to make sure "everyone gets something" leading to fee caches that get stuck.

TL:DR; there is a weakness in the requested model where simply increasing the number of addresses holding 1 OMNI serves to increase the fee threshold required for distribution, potentially to the point where the fee threshold for a given property is higher than the amount of tokens that property has in existence.

Instead I'd like to propose that the threshold for distribution is done as a percentage of the total tokens of the property being distributed.  So if there are N tokens in existence for the fee property, we'd trigger distribution when the cache reached m% of N.  This way we can never have a threshold that is higher than the amount of tokens in existence for a given property, and the threshold for fee distribution has a direct correlation to trading activity (trading volume as a subset of total tokens) on the property concerned.  

Hope that makes some kind of sense!  I'm open to alternatives, but I just think after looking at the math that it's going to be very difficult to apply a "distribute to make sure everyone gets something" when the distribution model is based on percentage owned.

Thanks
Z

**Comment by patrickdugan** [comment]
Sounds reasonable but then what is the criteria for handling sub-Willet fractions? 

I was thinking indivisible properties have the fee come out of the divisible part of the pair. We could invalidate indiv/indiv pairs as the math is insane for calculating fees on those.

If we then are always dealing in Willet minimums then this issue is generally not a problem.

**Comment by zathras-crypto** [comment]
> I was thinking indivisible properties have the fee come out of the divisible part of the pair. 

Fees are being applied to non-Omni pairs, and there is no guarantee that one side of the property would be divisible (it could be an indiv/indiv trade).  This also means we couldn't define that it is the liquidity taker whom pays the fee (since they could be trading indivisible or divisible tokens).

> We could invalidate indiv/indiv pairs as the math is insane for calculating fees on those.

There is no need to exclude any types of pairs :)  There is no need for fee handling to differ based on divisibility.

It's important to note that from an Omni Core perspective, internally that divisible = indivisible, we don't store them any differently.  Divisibility can simply be thought of as a display attribute (divisible properties are simply displayed divided by 100,000,000).

For example:
* 1 indivisible token = 0.00000001 indivisible tokens - stored in the tally as int64 value of 1
* 1 divisible token = 100000000 indivisible tokens - stored in the tally as int64 value of 100000000

So you can see how eg a value in the tally of 5000 can represent either 5000 indivisible tokens, or 0.00005000 divisible tokens simply by how we display it.

Regarding fees, I'm making a lot of progress with the prototype.  I've currently implemented that we simply don't subtract a fee for trades under 2000 (since 2000 is the lowest integer that can give a value of at least 1 when applying 0.05% subtraction, taking a fee from values under 2000 represents >0.05% fee).  

In practice this means:
* Trades under 0.00002000 divisible tokens are fee-free
* Trades under 2000 indivisible tokens are fee-free

Hope that helps clear things up a bit!

**Comment by zathras-crypto** [comment]
> Sounds reasonable but then what is the criteria for handling sub-Willet fractions?

We're not handling sub-willet fractions near-term I believe?  As previously discussed that would require a whole new way to handle tokens (additional layer) with more precision than is currently built into OmniCore.  I was under the impression we'd agreed to take a less fragile approach and only take whole willets as fees (rounded down ensures we don't tax >0.05%).

**Comment by dexX7** [comment]
Given that the fee distribution system was added, this issue seems to be resolved.
