### ISSUE TITLE
Omnicore-cli "Error -32601: Method not found"

### ISSUE THREAD

**Issue by got3nks** [OmniLayer/omnicore#352]
I'm running Omnicored

```
omni@server:~$ omnicore/omnicored --version
Omni Core daemon version v0.10.4.0-fe66360
```
Omni-related RPC commands aren't working with the cli tool:

```
omni@server:~$ omnicore/omnicore-cli "omni_getbalance", "address" 4
error: {"code":-32601,"message":"Method not found"}
```

**Comment by got3nks** [comment]
My bad, since I was running Bitcoin core on port 8332, I have to specify the different port when using the CLI tool:

`omnicore-cli -rpcport=8032 -rpcuser=user rpcpassword=pass "omni_getbalance", "address" 4`

**Comment by chaoyebugao** [comment]
Your command has extra comma after `omni_getbalance`
