### ISSUE TITLE
walletnotify

### ISSUE THREAD

**Issue by bumbar1** [OmniLayer/omnicore#354]
If using `walletnotify` option, sending Omnilayer transactions appear to be broadcasted twice.

**Comment by zathras-crypto** [comment]
Sorry for the delay in responding, I saw this in the issues list and must have missed the github notification.

Could you clarify the issue you are seeing and if possible provide steps to replicate? 

Thanks
Z

**Comment by bumbar1** [comment]
In config file, add `walletnotify` option to call some script (`walletnotify=/path/to/script %s`), then create an Omni transaction (eg `omni_send`) then the script will be called twice.

Speculation: this could be because first call (to script) is broadcasting transaction to everyone, and second call is everyone getting that broadcast.

**Comment by zathras-crypto** [comment]
Great, thanks for the info I'll see if I can replicate.

Couple of Q's if you don't mind; 

* Does the trigger (walletnotify) happen twice in succession or is there a delay in between?  What I'm trying to establish is whether the trigger fires once on broadcast and a second time when the transaction is mined in a block and actually processed into the state by Omni Core, or whether it fires twice immediately on broadcast.
* Does the same (double trigger of walletnotify) happen when doing a non-Omni transaction (eg ```sendtoaddress```)?

Thanks
Z

**Comment by bumbar1** [comment]
Trigger happens twice in succession (no delay), and then once more when the transaction is confirmed (when block is mined). Latter is part of `walletnotify`. Same also happens when doing non-Omni transaction.

**Comment by zathras-crypto** [comment]
Replicated and confirmed.

On testnet I see two triggers when sending the transaction and one when it confirms.

Doing this in regtest I see a total of 4 walletnotify triggers, once on sending the transaction and three on confirmation.

> Same also happens when doing non-Omni transaction.

Since Bitcoin Core codebase is left intact, if non-Omni calls exhibit the same behaviour it's likely we've inherited from upstream (can be confirmed by testing if Bitcoin Core 0.10.4 exhibits same behaviour).

Will start adding some debugging and work on a patch.

**Comment by dexX7** [comment]
> Will start adding some debugging and work on a patch.

If this behavior is inherited from Bitcoin Core, it should be patched upstream, if needed.

**Comment by nowa** [comment]
Has this problem been solved? 
Or can I distinguish between Omni transactions and non-Omni transactions?

**Comment by dexX7** [comment]
> Or can I distinguish between Omni transactions and non-Omni transactions?

You could by using [omni_gettransaction](https://github.com/OmniLayer/omnicore/blob/master/src/omnicore/doc/rpc-api.md#omni_gettransaction), which returns an error, if it's not an Omni transaction.

**Comment by antechdemo** [comment]
hey,when we get the testnet coin on the omni address from the btc faucet .its given response like Not a Master Protocol transaction. 
where to get TestOmni from? and whose address is that?How notify back?

**Comment by dexX7** [comment]
Hi @antechdemo, check this out:

https://github.com/OmniLayer/omnicore#testnet

On testnet or regtestnet, you can send some BTC to moneyqMan7uh8FqdCA2BV5yZ8qVrc9ikLP and once a block was mined, you get credited Test Omni.
