### ISSUE TITLE
What is next for the UI?

### ISSUE THREAD

**Issue by zathras-crypto** [OmniLayer/omnicore#362]
As we look at activating trading for all pairs, it highlights the problem that we have with the UI:

_Do we devote further resources into something we know we're not going to continue with?_

I think it's time we decided on a direction for the Omni Core UI and started moving towards it.  To note, without changes Omni Core QT won't be able to trade all pairs and will still act like all markets are OMNI/SPT markets.

I see our options as:

1) Continue with QT and attempt to do what we can for the Omni side, and just keep porting it along through Bitcoin Core changes
2) Drop QT and instead embed a browser based wallet in the daemon
3) Separate UI and daemon completely

I'm mostly in favour of 3) but only if we actually focus and deliver a separate UI.  Choosing option 3 and then leaving Omni Core users without a UI is not an option imo.  I least favour 1) as it's the most restrictive in terms of what we can achieve and requires a lot of work porting our UI between Bitcoin Core releases.

Thanks
Z

Pinging @dexX7 @marv-engine @CraigSellars @achamely @msgilligan @patrickdugan for feedback.

**Comment by dexX7** [comment]
@zathras-crypto: could you go into detail about the difference of 2 and 3?

Let me say it this way: I do not like to port the UI to a new code base, because this would eat a huge amount of time. In the long run our code emerges and becomes more independent, but even though, given that we currently mix the Bitcoin and Omni interface completely, it's pretty messy nevertheless.

If we can come up with a self-sustaining QT interface, e.g. in form of a seperate window, dedicated for Omni, I'd be more inclined to give it another thought, because it would be really nice to have a standalone desktop client without any other dependencies or attack vectors such as a browser.

But on the other hand it probably comes down to priorities: I'd rather improve the core and focus on the server side, as exchanges and alike are currently our primary users. To address end users, I believe a thin client, or a web wallet, is more appealing.

**Comment by zathras-crypto** [comment]
> @zathras-crypto: could you go into detail about the difference of 2 and 3?

Option 2 would have Omni Core include a browser based wallet within the daemon.
Option 3 would have Omni Core as a daemon only, and we'd spin up a new product to serve as a UI (which may or may not use Omni Core as a source of data).

> If we can come up with a self-sustaining QT interface ... it would be really nice to have a standalone desktop client without any other dependencies or attack vectors such as a browser

Hmm, that's a really good point - I didn't consider extra security considerations.  Also to note is that the SSL code was recently pulled from Bitcoin Core's HTTP interface which would be an absolute requirement for a local web wallet.

I definitely agree with you on priorities, the daemon is our primary and I'd like to see trading in OmniWallet as a next UI step - I understand Adam & Tomas are already working towards this.  

All that said I worry about losing perspective - OmniWallet & OmniChest & exchanges we're listed on etc are all very cool, but they're all "centralized" - a decent UI client that our users can (and want to) use that's local to the user and doesn't require trusting anything other than the blockchain is still something I believe we should strive for - it's just the direction is a little unclear.

**Comment by msgilligan** [comment]
Long-term I support Option 3, but if there is a way to get one more release with Omni QT UI that adds Dexx Phase 1 (BTC<->OMNI) and all-pair trading it might be nice to have for one more release cycle. I really like the idea of a complete standalone, P2P client/wallet. It drives home the point about our exchange being decentralized. That said, I'm not the one facing the UI coding effort and I'm sympathetic to what Dexx and Z are saying.

I'm hoping that OmniPortfolio (which could grow in to Omniwallet Desktop/Mobile) will be a viable candidate for Option 3 in a few months. It is currently working with *either* Omniwallet REST API or Omni Core RPC API for consensus info, but will be P2P for transaction signing & broadcasting.

**Comment by zathras-crypto** [comment]
> which could grow in to Omniwallet Desktop/Mobile

That's something I'd be really supportive of...

> It is currently working with either Omniwallet REST API or Omni Core RPC API for consensus info, but will be P2P for transaction signing & broadcasting.

What would be involved to go fully P2P (the 'endgame' for a desktop/mobile wallet)?

I wonder if lite clients would be able to use some form of "state snapshot" download for our consensus checkpoints - it wouldn't matter how/where the data came from because if it was tampered with in any way it'd fail the corresponding checkpoint (which would be hardcoded).  This would provide a head start to a state engine to avoid needing to process all history.  

We could potentially then use bloom filters (BIP37) to filter on the Exodus public key for Class B and OP_RETURN outputs for Class C to get just the transactions relevant to Omni, and then use the SPV idea of "I haven't verified this transaction but since it's N blocks deep in the longest chain I can assume the rest of the network has" to trust transactions and allow a state to be built up by the client locally.

I can't say I know too much about this stuff as I haven''t worked with SPV before, but perhaps there are some options here?

**Comment by msgilligan** [comment]
Yeah, a fully-decentralized version would be awesome. I Don't have any idea what, if anything would work. Your ideas are interesting. There're also an SPV algorithm for Onename's name service meta-layer weshould look at.

**Comment by CraigSellars** [comment]
I’m wondering if we can go down the route that OpenBazaar did - where there is a small daemon running, a basic web server and a wrapper app that acts as the app to access functionality.  If we go down this route, I think it’s something that we should consider making as a pull request against Bitcoin Core, to pull the entire industry in the same direction - make daemon-like, but more flexibility on how to shape the UI.

In the short term, I agree with Sean - having DEx in the UI is important, even if the experience isn’t the best.  I’m thinking simple drop-downs for each SP in some pair, which makes the left side whatever pair you select, and the right side the other pair you want (you could even put the number of open trades in parentheses).  This obviously doesn’t scale well if we have hundreds/thousands of currencies, but it does work in the short term.  By the time we have hundreds or thousands of currencies on the platform, we will have migrated to a more elegant UI solution.

I am also in favor of asset creation in the QT UI.  While we may be currently limited with QT’s flexibility (ease of development), we should at least strive to provide minimal UI support for the currently activated features.

**Comment by msgilligan** [comment]
One of the things I've done in OmniPortfolio is create a checkbox titled *Popular Properties Only* and it will filter out all properties except OMNI, USDT, AGRS, MAID, SEC. Since that's the vast majority of use cases it should make the dropdowns smaller. You could also automatically add any SPTs that you have created or hold the private key for.

**Comment by dexX7** [comment]
> I can't say I know too much about this stuff as I haven''t worked with SPV before, but perhaps there are some options here?

You're on the right path: ideally only Omni transactions would be fetched from peers (one way or another.. whether that's with bloom filters or just getting the whole block and discarding the rest, or there is some server pointing to specific transacftions) and the state constructed locally. This state could then be compared against multiple consensus servers. A thin client could require that all servers must match, and if so, then only one honest server is needed to avoid bad data.

**Comment by dexX7** [comment]
We're going to reevaluate this, when we move to the next version.
