### ISSUE TITLE
Roadmap Sorting

### ISSUE THREAD

**Issue by patrickdugan** [OmniLayer/omnicore#369]
1. Needs to be spec'd

Futures:
- Publish Contract Series tx type
- Trade Futures tx type
- Publish Data
- Settlement Logic
- Fees Logic

2. Needs to be implemented in protocol & reference client

   Futures

   Split Address tx

   Coloring/attributing colored coins to balance for SPV

   Remove BTC restriction for crowdsale

3. Needs to be implemented for user accessibility (eg UI)

   SPV functionality around colored coins.

   Automatic BTC input/smart property payment thereof for new users, from the above.

   Trezor'ed transactions

**Comment by dexX7** [comment]
@patrickdugan: What is "split address tx"?

**Comment by zathras-crypto** [comment]
@dexx7 I'm assuming send-to-many mate.

Re 'colored coins' I'm all for SPV but my suggestion was using bloom filters ala BIP37 not moving to output based balances (which is only possible for a small subset of our features and needs a suggested 'how' we would achieve this.

**Comment by zathras-crypto** [comment]
@patrickdugan @dexX7 please see https://github.com/OmniLayer/omnicore/issues/370 for a draft on Send-To-Many.

Also @dexX7 Send-To-Many introduces the possibility that we see many more transactions with large payloads (the only other 'large' transactions are issuances and they're fairly rare).  Do you think it's time to revisit the discussion on payload compression?

**Comment by dexX7** [comment]
Probably outdated. Please update/reopen, if there is new content.
