### ISSUE TITLE
Meta DEx logic and trade sequence discussion: "both partially filled"

### ISSUE THREAD

**Issue by dexX7** [OmniLayer/omnicore#37]
Please confirm, whether the behavior is expected and matches the specification.

---

The following trade sequence is based on https://github.com/OmniLayer/omnicore/issues/21#issuecomment-100124483, and shows, whether a trade is executed in favor of the buyer, and confirms that it's possible to end up with two partially filled orders.

**Trade sequence:**

| Trade | For Sale        | Desired        | Unit Price          | Inverse Unit Price  |
|:-----:| ---------------:| --------------:| -------------------:| -------------------:|
|   A   | 25 SPX          | 2.50000000 MSC |  0.10000000 MSC/SPX | 10.00000000 SPX/MSC |
|   B   |  0.55000000 MSC | 5 SPX          | ~9.09090909 SPX/MSC |  0.11000000 MSC/SPX |

**Outcome:**

Both orders are partially filled, and 5 SPX trade for 0.50000000 MSC.

After the trade A still has 20 SPX left for sale, and B still has 0.05000000 MSC left for sale.

**Comment by dexX7** [comment]
It's been some time, so for the sake of clearing the backlog. /close

**Comment by zathras-crypto** [comment]
I was really hoping @marv-engine would cast his eye over this one...

**Comment by dexX7** [comment]
Yeah, I agree. Some additional ACKs would be nice. On the other hand, given the time (and related issues, and the email to the group), I consider the absence of objections as silent agreement.
