### ISSUE TITLE
Futures - Settlement Logic

### ISSUE THREAD

**Issue by patrickdugan** [OmniLayer/omnicore#379]
Settlement comes in two forms: Merkle Branch or Oracle Address

In both cases the final price will be put through an algorithm that indexes all the trade prices of every single contract transaction over the life of a particular contract. 

The parameters for a Merkle Branch contract include:

[SPT#1, SPT#2], Blocks to Average

Example: [1, 31], 8

This would make a contract that settles based on the volume-weighted average of the last 8 blocks prior to settlement of OMNI/USDT trading. So each Dex trade in those blocks has a price derived from that ratio between the properties, used to calculate VWAP as such: (Asset1Traded x PriceInAsset2) / TotalAsset1 Volume

The parameters for an Oracle contract include:

<Bitcoin Address>, Lookback Period, Grace Period

E.g. 1braV3NUwco123412!6#$!s2ye!g, 8, 3

This contract could take OMNI as collateral but settle based on the BTC/USD index that Brave New Coin publishes. They try to publish every block but cannot guarantee that consistency, so if there is no price published on the settlement block, then a 3 block grace period follows, and if there is no settlement price published on that third block, then an average of all prices published in the 8 blocks prior to settlement is used. If the price is published in the grace period then that is the price used for settlement, which would commence on the same block as the confirmed block publishing the clearing price. 

In either case the following logic is presumed in the settlement algorithm:

1) Every trade involving a given contract is indexed with its own settlement price included in the trade's Op_Return data, each trade is its own atomic link in the chain, rather than being thought of as unique tokens. 

2) Even if someone is closing a position and effectively lowering the current open interest (supply of contracts), the trade they are doing is considered effectively a new contract. The only case where this is not true is the rare situation where the exact same parties who opened contracts together are closing them at the same time; theoretically special logic would allow for instant settlement between the parties, but we're going to keep it simple and consistent. 

3) On the settlement block, all Dex trades including the SPT# for the particular contract since its predecessor expired and it began to exist are listed and the trade amounts and prices are tallied. The gross settlement between the two addresses is deduced: shorts pay settlement price - trade price and longs pay trade price - settlement price; in this case a negative number implies a transfer of wealth to the contract holder in the amount of the difference times the contracts involved. 

4) Since people can un-reserve collateral when they reduce positions, except for course for any mounts they have lost trading the contract, there will be plenty of situations where linearly applying gross settlement would be impossible because there would be no reserve to claim. So having figured out the gross settlements, now the net settlements are calculated by looking at the last trade before settlement and going backwards to keep a complete chain of collateral movement back to the first trade of the contract. All of the trades that closed positions, applied retroactively, should allow just enough reserve collateral to pay other losses backwards in the chain. This involves determining where payouts should be split so everything can be moved to the right addresses in a single assignment by the protocol (in a manner similar to how fees works, i.e. not having to break these down into discrete Bitcoin protocol transactions). 

5) Having figured the net settlement amounts between everything, the changes in balance happen simultaneously with the disappearance of all contract balances.

**Comment by dexX7** [comment]
I think it's better to keep track of the specification or feature proposals in the spec repository:

https://github.com/OmniLayer/spec

Please feel free to open a new issue over there.
