### ISSUE TITLE
Meta DEx logic and trade sequence discussion: "best fill"

### ISSUE THREAD

**Issue by dexX7** [OmniLayer/omnicore#38]
Please confirm, whether the behavior is expected and matches the specification.

---

The trade sequence is based on https://github.com/mastercoin-MSC/spec/issues/170#issuecomment-44070201, and shows, whether the maximum possible amount of tokens, at the best price, is traded.

**Trade sequence:**

| Trade | For Sale       | Desired        | Unit Price          | Inverse Unit Price  |
|:-----:| --------------:| --------------:| -------------------:| -------------------:|
|   A   | 0.00000020 MSC | 0.00000010 SPX |  0.50000000 SPX/MSC |  2.00000000 MSC/SPX |
|   B   | 0.00000012 SPX | 0.00000017 MSC | ~1.41666667 MSC/SPX | ~0.70588235 SPX/MSC |

From the other thread, and sort of applicable, green are accepted combinations by both:

![8c82ee40-e380-11e3-8d7c-83365710d2f6](https://cloud.githubusercontent.com/assets/5836089/7615068/338a8a5a-f99b-11e4-9809-bb7f761bdf56.png)

**Outcome:**

A is completely filled by B, and 0.00000020 MSC are traded for 0.00000010 SPX.

After the trade B still has 0.00000002 SPX left for sale.

**Comment by patrickdugan** [comment]
Seems to check out, love the elegance of the math in that filled prices fan between the inverse price of each order.

**Comment by dexX7** [comment]
Given that there were no objections, the logic appears to be solid.
