### ISSUE TITLE
Futures - Fees Logic

### ISSUE THREAD

**Issue by patrickdugan** [OmniLayer/omnicore#380]
Fees work like they do on the normal Dex, except the currency in which fees are paid is always the settlement currency. This implies that the minimum amount of collateral needed to trade one contract is the requirement for that contract plus a fractional fee. 

Trading contracts collateralized by OMNI is free. 

The fee logic splits based on which settlement logic applies to the given contract. 

For Oracle-based contracts, the maker fee in free, the taker fee is two basis points (0.0002); half of the fee goes to OMNI holders and half goes to the address publishing the data feed that the contract settles on. 

For Merkle-based contracts, the maker fee is -1 basis point (0.0001, i.e. liquidity providers receive a small rebate) and the taker fee is 2 basis points, with half going to OMNI holders as above. 

Since contracts are indivisible units, and if the minimum amount of collateral required for a contract be 1 unit of some smart property, then the smallest amounts transferred between market takers and makers would be .0001 of some currency.

The same logic used for Dex fees in spot trading applies here, where they are tallied to an eventual threshold of distribution to OMNI holders.

**Comment by dexX7** [comment]
I think it's better to keep track of the specification or feature proposals in the spec repository:

https://github.com/OmniLayer/spec

Please feel free to open a new issue over there.
