### ISSUE TITLE
get transaction history

### ISSUE THREAD

**Issue by tallesdantas** [OmniLayer/omnicore#382]
Hello guys , i would like to know if is this possible to get all the transacation history of a determined address as seen here for example:

http://omnichest.info/lookupadd.aspx?address=1Po1oWkD2LmodfkBYiAktwh76vkF93LKnh&prop=31

in a json format, so i can track the transactions status of a determined address, thanks alot guys

**Comment by dexX7** [comment]
Hey @tallesdantas,

there is a RPC to list wallet transactions: [omni_listtransactions](https://github.com/OmniLayer/omnicore/blob/v0.0.10/src/omnicore/doc/rpc-api.md#omni_listtransactions), as well as a call to list all Omni transactions in a specific block: [omni_listblocktransactions](https://github.com/OmniLayer/omnicore/blob/v0.0.10/src/omnicore/doc/rpc-api.md#omni_listblocktransactions).

**Comment by tallesdantas** [comment]
How can i get it trought the url?,  I'm using nodejs,  do you have an example?   Thanks alot

**Comment by tallesdantas** [comment]
i'm using the rest api of omnichest, i really need this =/ is there an easy way to do this on nodejs?

**Comment by dexX7** [comment]
My bad, you were referring to omnichest.info and not Omni Core.

I pinged @zathras-crypto, who might help.

**Comment by tallesdantas** [comment]
thanks @dexX7 , i appreciate the help.

**Comment by zathras-crypto** [comment]
Hey guys,

Sorry - been a crazy few days personally (few problems with our new place).

@dexX7 thanks

@tallesdantas it's possible to:
* request all the txids for transactions an address has sent:  http://omnichest.info/ask.aspx?api=getsenderhistory&address=1Po1oWkD2LmodfkBYiAktwh76vkF93LKnh

and/or

* request all the txids for transactions an address has received: http://omnichest.info/ask.aspx?api=getrecipienthistory&address=1Po1oWkD2LmodfkBYiAktwh76vkF93LKnh

You can then look at transactions you're interested in with http://omnichest.info/ask.aspx?api=gettx&txid=35b192c3262e9ac862d2440c81dbca4fda06812e06334a3d4e559e7360a2a5e1

Substitute addresses/txids as needed.

That's how to get at the data with these generic calls currently in the API, however is a quite inefficient way to monitor an address, as we're asking OmniChest's database to lookup *all* transactions in its history each time we make the API request.

I often do custom APIs for folks and if you can tell me a bit more about what you want to do perhaps I can prepare a more suitable API call :)

Thanks
Z

**Comment by tallesdantas** [comment]
@zathras-crypto  thanks sathras , this call "http://omnichest.info/ask.aspx?api=getrecipienthistory&address=" was the one i was needing, i really appreciate the help =D

**Comment by dexX7** [comment]
Aweome, thanks @zathras-crypto.

I think this resolves the issue. @tallesdantas: please feel free to raise a new ticket, if you need anything. :)
