### ISSUE TITLE
Meta DEx logic and trade sequence discussion: "effective prices"

### ISSUE THREAD

**Issue by dexX7** [OmniLayer/omnicore#39]
Please confirm, whether the behavior is expected and matches the specification.

---

The sequence is based on https://github.com/OmniLayer/omnicore/issues/21#issuecomment-98020753, and shows that the effective price must be within the accepted price range, and otherwise a trade isn't executed.

**Trade sequence:**

| Trade | For Sale       | Desired        | Unit Price          | Inverse Unit Price  | Match? |
|:-----:| --------------:| --------------:| -------------------:| -------------------:|:------:|
|   A   | 0.00000006 MSC | 0.00000006 SPX |  1.00000000 SPX/MSC |  1.00000000 MSC/SPX |     No |
|   B   | 0.00000010 SPX | 0.00000001 MSC |  0.10000000 MSC/SPX | 10.00000000 SPX/MSC |    Yes |
|   C   | 0.00000001 MSC | 0.00000010 SPX | 10.00000000 SPX/MSC |  0.10000000 MSC/SPX |     No |
|   D   | 0.00000001 MSC | 0.00000004 SPX |  4.00000000 SPX/MSC |  0.25000000 MSC/SPX |    Yes |

**Outcome:**

1) When A is added, then there is no other order to match against, and this results in a new offering.

2) When B is added, then B is matched against A, and A is filled completely by B, but there is an amount left for sale of 0.00000004 SPX @ 0.1 MSC/SPX.

3) When C is added, then C and B are not matched, due to the minimal tradable amount of 0.00000001 MSC, which implies an *effective* unit price of at least 0.25 MSC/SPX to make the trade happen.

4) When D is added, then D and B are matched, and both orders are filled completely.

After this trading sequence, order A, B and D were filled, but C is still unmatched, and should be listed in the orderbook.

**Comment by patrickdugan** [comment]
Yes, this is an implementation of what seems to be the right answer to the question of minimum sizes.

**Comment by dexX7** [comment]
Given that there were no objections, the logic appears to be solid.
