### ISSUE TITLE
Sending tx: wallet may be locked or fees may not be sufficient

### ISSUE THREAD

**Issue by got3nks** [OmniLayer/omnicore#392]
I've sent 0.0005 BTC to the address which I'm sending the tx from, but I'm still getting the error: **wallet may be locked or fees may not be sufficient**

Is there any way to know how much in fees will be required to send a tx?

**Comment by zathras-crypto** [comment]
Sorry for the late reply :(

That should be a suitable amount using defaults.  What response do you get from the call ```estimatefee 6```?

**Comment by dexX7** [comment]
Hey @got3nks, could you please post the address you're trying to send from?

**Comment by got3nks** [comment]
`estimatefee 6` returned 0.00149700, which is more BTC than is currently sitting on the address. But it's quite expensive!

**Comment by got3nks** [comment]
1AFcEEDqDSCr8JNhPibwWMrRbAG49sotsn has 0.0065 BTC yet failing to send assets.

Request:
```
    [fromaddress] => 1AFcEEDqDSCr8JNhPibwWMrRbAG49sotsn
    [toaddress] => 12GpUEMshoBD5sGagRgzKyFA9h2ohcYefF
    [propertyid] => 31
    [amount] => 99.5
```
Error -211
 **Error creating transaction (wallet may be locked or fees may not be sufficient)**

**Comment by dexX7** [comment]
> estimatefee 6 returned 0.00149700, which is more BTC than is currently sitting on the address. But it's quite expensive!

You could try to restart Omni Core with the command line option `-txconfirmtarget=n`, where `n` equals the estimated number of blocks a transaction should take to confirm. As per default Omni Core uses 6 confirmations, which appearingly results in an estimated fee of 0.00149700 BTC/kB at the very moment. You could try a number like `10´ or `15`, so it becomes cheaper.

> 1AFcEEDqDSCr8JNhPibwWMrRbAG49sotsn has 0.0065 BTC yet failing to send assets.

To me it looks like the address actually only has 0.00**0**65 BTC.

Please try either to use a lower `-txconfirmtarget`, or send some additional BTC to that address.

**Comment by got3nks** [comment]
I restarted the wallet with -txconfirmtarget=12

root@cryptos:/# ps aux | grep omni
omni  15602 31.2  4.4 2687140 542344 ?      SLl  15:51   1:02 /home/omni/omnicore/omnicored -datadir=/home/omni/.omnicore -listen=0 -txconfirmtarget=12

But the transaction still didn't get through: **Error creating transaction (wallet may be locked or fees may not be sufficient)**

Is there any way to know how many kB the transaction size will be, to make sure the balance will be enough to process it?

**Comment by dexX7** [comment]
Awesome, glad it worked out!

> Is there any way to know how many kB the transaction size will be, to make sure the balance is enough to process it?

You can use the RPC `estimatefee n` to get an idea about the fee/kB going to be used, but there is no handy way to determine the size of the transaction. If you have many small value inputs, then it's going to be larger, but a very rough estimate is 300-600 byte for a regular Omni transaction.

**Comment by got3nks** [comment]
Thanks a lot for the help. Why does Omnilayer's **estimatefee** differ so much from Bitcoin Core's?

Core 120100
`estimatefee 6` 0.00043786
`estimatefee 15` 0.00024177

Omnilayer 100400
`estimatefee 6` 0.00149700
`estimatefee 15` 0.00059880

Considering current Bitcoin price level, this can make a huge difference.

**Comment by dexX7** [comment]
This is indeed a huge difference! What Core version was this?

**Comment by got3nks** [comment]
Bitcoin version v0.12.1 (2016-04-11 13:01:43 +0200)

**Comment by dexX7** [comment]
Thanks for the information!

The fee estimation has indeed changed a bit, and I wasn't aware it makes such a big difference.

In this case I recommend to use a slightly lower number for `txconfirmtarget` to get a similar behavior.

As a side note, after this release we are going to rebase Omni Core on top of Bitcoin Core 0.12, or potentially 0.13.

**Comment by got3nks** [comment]
Did you mean an higher number for `txconfirmtarget`?

**Comment by dexX7** [comment]
My bad, sorry! Yes, a higher number for `txconfirmtarget`.

**Comment by dexX7** [comment]
We updated the default confirm target to 15, which should result in cheaper transactions.

Thanks again for providing numbers on this. :)

**Comment by rio-coffe** [comment]
Just send to node 0.00001 BTC

**Comment by dexX7** [comment]
Yes, that should work @rio-coffe, thanks!
