### ISSUE TITLE
Work around bytespersigop limit

### ISSUE THREAD

**Issue by dexX7** [OmniLayer/omnicore#394]
Our bare-multisig transactions have a hard time, because they are now basically non-standard due to a new "bytes per sigop" limit.

We should find a workaround for 0.0.11.

**Comment by dexX7** [comment]
As far as I can see the only workaround is is to bloat Class B transactions.

In the worst case, and only looking at the ratio based on each output, to counter a 1-of-3 bare-multisig output with compressed public key, the transaction needs either 13 additional P2PKH outputs, 6 additional P2SH outputs or roughly one additional transaction input.

Bloating transactions by adding new outputs seems like an expensive method, so we should try bloating with additional inputs first, and then use additional outputs as last resort.

**Comment by dexX7** [comment]
A solution could look like this:

- After creating a transaction with Omni Core, [count the sigops](https://github.com/luke-jr/bitcoin/blob/fdc202f4b02802bfb0ec162d71a115eb86f1bde9/src/main.cpp#L933-L934)
- If we [hit the limit](https://github.com/luke-jr/bitcoin/blob/fdc202f4b02802bfb0ec162d71a115eb86f1bde9/src/main.cpp#L965), then go back and try to add additional inputs
- If there are not inputs available, try to bloat the transaction with additional outputs-to-self

**Comment by zathras-crypto** [comment]
Awesome thanks for the info bud :)

> A solution could look like this

I think you're close there - and I support adding an additional input to work around the sigops limit if one is available, but I'm not sure I agree with bloating the transaction by splitting the change into a bunch of outputs (I understand we'd need quite a lot) as this contributes to UTXO bloat (though I realize our hand is being forced here).

Given the only remaining requirement for Class B is issuance, I see a few options:

1) Require the user to have multiple inputs available to send an issuance.
2) Code the automatic sending of a transaction to split a UTXO into two UTXOs, and then use those (now unconfirmed) UTXOs for the inputs.
3) Modify issuance to slim down the transaction enough for class C and pull metadata (like category etc) from elsewhere.
4) Split change into multiple UTXOs (ie add enough P2PKH outputs to bloat the transaction).

Option 1 is simple, 2/3 are complex & not immediately deployable, but perhaps better approaches, 4 is again simple but I'm a bit concerned about bloat.

**Comment by dexX7** [comment]
> I understand we'd need quite a lot

Yeah, unfortunally. A P2PKH output also costs one sigop, which makes it difficult to use to counter.

> as this contributes to UTXO bloat 

Only temporarily though. The outputs are spendable, and if it's an user who creates many transactions, then they will be used as inputs at some point.

> 1) Require the user to have multiple inputs available to send an issuance.

Yup, let's do it.

> 2) Code the automatic sending of a transaction to split a UTXO into two UTXOs

Note that we'd need one or two additional inputs per multisig output. When there is an issuance with long descriptions, then splitting into two won't be enough.

> 3) Modify issuance to slim down the transaction enough for class C and pull metadata (like category etc) from elsewhere

How? I like the direction (i.e. getting rid of non-consensus data on-chain), but it's probably a broader topic and not suitable as quick-fix for this context.

> 4) Split change into multiple UTXOs (ie add enough P2PKH outputs to bloat the transaction)

We can summarize that adding inputs is reasonable, but it's an open question, whether bloating transactions with additional outputs is preferred over a failure.

In this case, and in the case the user has not enough BTC to fund the extra outputs, or pay enough fee to cover additional inputs, is there an alternative? I currently don't see one, but I'm wondering how we could present this situation to the user.

**Comment by dexX7** [comment]
Partially resolved by #396.
