### ISSUE TITLE
Meta DEx logic and trade sequence discussion: "clean results"

### ISSUE THREAD

**Issue by dexX7** [OmniLayer/omnicore#40]
Please confirm, whether the behavior is expected and matches the specification.

---

The following sequence is based on testnet trades, which initially caused trouble, because the resulting amounts were calculated based on truncated or rounded intermediate results.

**Trade sequence:**

| Trade | For Sale        | Desired          | Unit Price          | Inverse Unit Price  |
|:-----:| ---------------:| ----------------:| -------------------:| -------------------:|
|   A   | 23.00000000 MSC | 100.00000000 SPX | ~4.34782609 SPX/MSC |  0.23000000 MSC/SPX |
|   B   | 50.00000000 SPX |  10.00000000 MSC |  0.20000000 MSC/SPX |  5.00000000 SPX/MSC |

**Outcome:**

B is completely filled by A, and 50.00000000 SPX trade for 11.50000000 MSC.

After the trade A still has 11.50000000 MSC left for sale.

**Comment by patrickdugan** [comment]
Checks out.

**Comment by dexX7** [comment]
Given that there were no objections, the logic appears to be solid.
