### ISSUE TITLE
Omni Core v0.0.11-rc2 Takes too long to initialize

### ISSUE THREAD

**Issue by jjmr007** [OmniLayer/omnicore#407]
My system is Windows 7

I was using the Bitcoin Core 0.12.1 for win64, when I decided to switch to Omni.
But it didn't was running on my pc. I was told that likely my chain data were corrupted.
So I had to run the Omni Core wallet from the command prompt as 
"omnicore-qt.exe -reindex" 
in order to fix the blocks in my database. It took several days.

Now Omni is running well on my PC, but each time I initialize the wallet, it takes too long 
"verifying blocks"... 1%... 2%... 3%... (an eternity), some times over an hour!.

Is there something I need to do to have run Omni Core in a "normal way"?
How can I fix this (If it can be fixed at all)?

**Comment by zathras-crypto** [comment]
Hi @jjmr007 welcome & thanks for the report!

Your experience is expected - the blockchain for Bitcoin Core 0.12 is not backwards compatible with Bitcoin Core 0.10 (which Omni Core 0.0.11 is based on).  This is why your local copy of the blockchain needed to be reindexed.

That sounds like an awfully long time to verify blocks - you can start with the parameter ```--checkblocks=1``` to change the amount of latest blocks that'll be verified on startup from the default of 288 to 1.

Is this a relatively fast computer?  

Thanks
Z

**Comment by jjmr007** [comment]
Hi @zathras-crypto ... thank you very much it worked perfectly, almost inmediately!
[https://www.dropbox.com/s/n1rpps1eijkak8r/Omni%20Initialized.PNG?dl=0](url)
