### ISSUE TITLE
Meta DEx logic and trade sequence discussion: "rational numbers"

### ISSUE THREAD

**Issue by dexX7** [OmniLayer/omnicore#41]
Please confirm, whether the behavior is expected and matches the specification.

---

The following sequence is straight forward, but yields unexpected results, if floating point numbers, instead of rational numbers, are used for the calculations.

**Trade sequence:**

| Trade | For Sale       | Desired        | Unit Price         | Inverse Unit Price |
|:-----:| --------------:| --------------:| ------------------:| ------------------:|
|   A   | 1.00000000 SPX | 2.00000000 MSC | 2.00000000 MSC/SPX | 0.50000000 SPX/MSC |
|   B   | 1.66666666 MSC | 0.83333333 SPX | 0.50000000 SPX/MSC | 2.00000000 MSC/SPX |

**Outcome:**

B is completely filled by A, and 1.66666666 MSC trade for 0.83333333 SPX.

After the trade A still has 0.16666667 SPX left for sale.

**Comment by patrickdugan** [comment]
We should be using only integers where 1 = 1 willet and 100,000,000 = 1 Omni or SP. 

I'd say as a rule, always round down when a price doesn't leave two whole numbered 100 millionths as the result. So the result may be every so minutely less of a position than what the user ordered, and that's ok because we're talking about the same fractions of a penny.

**Comment by dexX7** [comment]
Hey @patrickdugan,

the smallest tradable amount is indeed 1 willet, and if it doesn't resolve nicely, then it's rounded.

The amounts to trade are based on the price of the order, which was already in the book, and the amount to pay is rounded up in such a case, because otherwise it would be too expensive for the other order.

The trade is only executed, if the new price is still within the accepted range of the new order, which is shown in greater detail in #39.

**Comment by dexX7** [comment]
Given that there were no objections, the logic appears to be solid.

**Comment by zathras-crypto** [comment]
FYI I requested in the meeting this morning that @marv-engine @msgilligan and any other testing resources look at these issues and comment on the math

**Comment by dexX7** [comment]
Ah, thanks. @marv-engine, @msgilligan: please feel free to reopen then. :)
