### ISSUE TITLE
Should "Publish Value" transactions carry a description?

### ISSUE THREAD

**Issue by zathras-crypto** [OmniLayer/omnicore#413]
As title.

The original intention was for transactions to allow a 'memo' or 'note' to be attached (sneds, grants etc) but this is rarely used currently.

In the "Publish Value" model I'm currently prototyping there is no need to "setup" a feed, you just publish a value (and feed ref) from an address, and the latest value published is the 'current' value of the feed.  

This means descriptions would be per transaction - this provides the flexibility that new information can be provided in the description with each new published value (such as metadata) but also provides the mechanism to add non-consensus data to the blockchain.

Should we include a description field in the Publish Value transaction?

**Comment by dexX7** [comment]
Could you provide an explicit use case this would be used for?

**Comment by zathras-crypto** [comment]
> Could you provide an explicit use case this would be used for?

This is tough because I'm not fully understanding of the entire futures process that we'll be implementing.  I put the field in so that publishers of the feed could include a string value but as to whether that's required I don't know.

One example that was in my mind when prototyping was prior discussions about where a contract would be settled once a certain secret was published - that could be one use case, another would be metadata (eg this value applies to X range or Y date or whatever).

More than happy to remove it if it's not needed :)

**Comment by dexX7** [comment]
> More than happy to remove it if it's not needed :)

Well, there might be some use for it, but until then I'd rather go the route of adding it, if it's really needed, not the other way around. :)

**Comment by dexX7** [comment]
I think it's better to keep track of the specification or feature proposals in the spec repository:

https://github.com/OmniLayer/spec

Please feel free to open a new issue over there.
