### ISSUE TITLE
Equivalent to listsinceblock?

### ISSUE THREAD

**Issue by bitcoincoltd** [OmniLayer/omnicore#415]
Is there some way to pull up all omni transactions since a certain block?

In the same way that `listsinceblock` on bitcoin-cli will pull up a list of all transactions affecting your wallet after a certain block?

**Comment by zathras-crypto** [comment]
Hi & welcome,

Please take a look at https://github.com/OmniLayer/omnicore/blob/omnicore-0.0.10/src/omnicore/doc/rpc-api.md#omni_listtransactions

You're probably looking for:

``omnicore-cli omni_listtransactions "*" 999 0 startblock```

This will retrieve up to 999 transactions, skipping the first 0, that occurred on or after startblock.

Thanks
Z

**Comment by bitcoincoltd** [comment]
Yup perfect, thanks.
