### ISSUE TITLE
Decoding transactions may not work due to missing activations

### ISSUE THREAD

**Issue by dexX7** [OmniLayer/omnicore#416]
Not all features which already activated are hardcoded, such as the use of OP_RETURN scripts to embed data.

With an unsychronized client this can result in inaccurate data when decoding transactions with `omni_decodetransaction`. See related discussion here: https://github.com/OmniLayer/omniwallet/issues/1314#issuecomment-240390536

I tackled this topic before in #339, and we decided that activation transactions should be used to activate features, even if they are already activated, instead of simply hardcoding the activation block to our set of rules.

I'd like to restart the discussion and would prefer to hardcode previous activations.

**Comment by zathras-crypto** [comment]
I think this is absolutely vital functionality (the ability for anybody to download Omni Core and use it to verify a transaction).  

I think it's a pretty big obstacle to that functionality to require a synced chain.

So yep I'm supportive of hardcoding activation heights, and happy to do so starting from the release after each activation.

**Comment by dexX7** [comment]
The activations were hardcoded via #470. :)
