### ISSUE TITLE
Shwoing wrong balance(increase on each send) on omnicore wallet

### ISSUE THREAD

**Issue by ghost** [OmniLayer/omnicore#425]
Hi All,

I am using omnicore in testnet mode. It returns wrong balance on getbalance command and this wrong balance increase on each bitcoin send occurs. It seems strange that when i check my address on bitcoin explorer showing the actual (which is very less ) balance (http://tbtc.blockr.io/address/info/n2NeuwiAf6Py2MimzfginW8KuCuCs6u64i)
Acutal balance is: 3.43740427 TBTC
getbalance returns: 10.31238974 BTC

I have only one address in account

Thanks,
Mufeed

**Comment by dexX7** [comment]
Hi @ghost, this looks like an upstream issue, because we don't touch die Bitcoin calls like `getbalance`. However, please notice, due to the account system, this call may not show the actual balance.
