### ISSUE TITLE
Activate new features for testnet

### ISSUE THREAD

**Issue by dexX7** [OmniLayer/omnicore#428]
We currently have a few features, which are not activated on testnet, and we should update the rules, so people can test it on testnet.

**Comment by zathras-crypto** [comment]
Agreed, so just to confirm - we should keep things disabled in regtest so that activation can be tested, but as far as testnet is concerned, we can just set the activation block for all new features to 0?

**Comment by dexX7** [comment]
Yes, this is what I'm suggesting. Might be combined with #416.

Leaving the regtest stuff disabled allows testing of the activations. :)
