### ISSUE TITLE
0.0.11.1 how to remove Omni (#1) from wallet?

### ISSUE THREAD

**Issue by CaptainSkywave** [OmniLayer/omnicore#434]
I am pleased with the Omni Core 0.0.11.1 (WIN 64 bit) wallet - thank you guys :) - looking forward to 0.0.11.2
When opening the wallet first time - before I import my various SPT #'s I see that the wallet opened with a default (?) SPT already there:
Omni (#1) - with a 0 balance.
How can I remove that one from the wallet?
I have googled but not able to find anywhere a description/tutorial on how to do this.

edit later:
It's mainly an aestethic issue - I like things to be clean and minimalistic - so I feel it a bit annoying to have an "account" displayed, that I don't use.
If it has to be integrated with the wallet in order for it to work - could it then be hidden from the Overview somehow?

**Comment by dexX7** [comment]
Hi @CaptainSkywave,

I actually haven't thought about this, but you are right. Currently there is no way to hide the primary tokens, even if there is no balance, but we should consider this for the next version.

Thanks for pointing out!

**Comment by CaptainSkywave** [comment]
Thanks dexX7.
And also thx for 0.0.11.2 - awesome work! 
Running on WIN server 2012 R2 STD 64 bit here - smooth sailing :)

**Comment by CaptainSkywave** [comment]
@dexX7 I'm curious as to why you removed this from Next release, which is now 0.0.12.0 ?
I still find it a nuisance to have it (Omni (#1)) featured in the overview for no use (AFAIK?).

**Comment by dexX7** [comment]
Hi @CaptainSkywave,

initially there was some discussion about removing the Qt interface and focus on providing a rock solid daemon/server only version, so I removed the milestone.

However, we're keeping the GUI and @zathras-crypto picked up your idea in #471. :)

**Comment by dexX7** [comment]
Resolved via #471.
