### ISSUE TITLE
Fix and update icons and splash screen

### ISSUE THREAD

**Issue by dexX7** [OmniLayer/omnicore#437]
The icons and splash screen may not be correct in the 0.13 based version.

At some point we should do test builds via Gitian and see, which parts are still missing, e.g. Windows installer backgrounds, OS X background, program/tray icons or splash screen.

**Comment by dexX7** [comment]
We probably need to do some testing with Gitian anyway, because, as far as I recall, the build process has changes a bit:

https://github.com/OmniLayer/omnicore/blob/develop/doc/gitian-building.md

**Comment by dexX7** [comment]
The build process was straight forward, but I'm currently running into an issue, which I haven't resolved yet:

![noinc](https://cloud.githubusercontent.com/assets/5836089/22071307/03d60160-dd9f-11e6-938c-57e624ceb58c.png)

**Comment by dexX7** [comment]
Next issue to resolve:

![exe](https://cloud.githubusercontent.com/assets/5836089/22113779/bf14c51a-de67-11e6-896e-911ec117d954.png)

**Comment by dexX7** [comment]
The icons look fine. :)

Setup files:

![setup-package](https://cloud.githubusercontent.com/assets/5836089/22181978/4f1bd21a-e099-11e6-94f2-fac8e241513e.png)

Extracted files:

![files](https://cloud.githubusercontent.com/assets/5836089/22181979/52f2380c-e099-11e6-99a1-cbeb3bb7547c.png)

Setup dialog:

![setup](https://cloud.githubusercontent.com/assets/5836089/22181980/577b1e5c-e099-11e6-925c-954801e8eceb.png)

![setup-2](https://cloud.githubusercontent.com/assets/5836089/22181981/59cec96a-e099-11e6-8500-05e2a6b19c09.png)

However, I think the splash screen could benefit from some improvements:

![splash](https://cloud.githubusercontent.com/assets/5836089/22181984/69c3c686-e099-11e6-8ec4-136990928b21.png)

@zathras-crypto: what do you think?

**Comment by dexX7** [comment]
@zathras-crypto: do you think it's feasible to port the old image to the new splash screen?

**Comment by zathras-crypto** [comment]
Awesome great work thanks dude :)

The Bitcoin devs changed the way the splash is done - I didn't spend much time on the new one so I'm sure I could improve it/make it look like the old one - I'll try some changes and send you some screenshots.

**Comment by zathras-crypto** [comment]
@dexX7 could you give https://github.com/OmniLayer/omnicore/pull/453 a try for the splash when you have a spare moment?  Thanks :)

**Comment by dexX7** [comment]
All good!

I think we can consider this issue to be resolved, by #451, #452 and #453. :)
