### ISSUE TITLE
Omnicore backup wallet not showing 2nd layer coins

### ISSUE THREAD

**Issue by thesolarminer** [OmniLayer/omnicore#445]
I tried to load a backup wallet in a new machine with the latest omnicore 11.2 wallet win 64 version.  I copied the blocks and index data from a linux machine also running omnicore 11.2 so I didn't sync from scratch.  After it synced I copied the wallet into the data directly.  After it loaded only the bitcoin fees are seen.  The maidsafe tokens are not populating correctly.  Only the first maidsafe transaction populated.  Multiple maidsafe deposits were maid to the same address.

I have tried to import a private key and rescan.  Same result.
Tried zapwallettx and same result.
Tried deleting the OMNI and MP directories and same result.

Does the new wallet only catch the first maidsafe transaction for a bitcoin address?   Is there something else I need to do to get the rest of the maidsafe to show up?

Thanks for any help.

**Comment by dexX7** [comment]
Hey @thesolarminer,

can you confirm you backed up all private keys from your old machine?

Please head over to `Help` -> `Debug` -> `Console`, then enter:

```
dumpprivkey <address>
```

Where `<address>` is an address you control with Maid from your old wallet.

If there is an error, then the backup was not successful.

If a private key was dumped, then please enter:

```
omni_getbalance <address> 3
```

Where `address` is the previous address. Does the result show the balance you expect?

**Comment by thesolarminer** [comment]
Yeah, the private key was dumped without error and added without error.  It is getting the right key and trying to import the transactions.  The bitcoin fees for each transaction show up on the right dates, but only the first maidsafe amount shows.  omni_getbalance address 3 still only shows that first transaction amount.

The block explorer verifies the full amount under that address is still there.  I also copied the old wallet file over and loaded omni with that and it does the same thing.  The wallet is just not catching the 2nd, 3rd, 4th maidsafe deposits to the same address.

**Comment by dexX7** [comment]
@thesolarminer: thanks for the information.

Would you mind posting that address you are referring to?

**Comment by thesolarminer** [comment]
I did some more digging.  I was able to send out a transaction from the old computer to a new wallet.  It confirmed just fine.  I tried to load that wallet on the new computer.  The new wallet sees the transaction but it shows up as invalid.  So I looks like the blockchain on the new machine is bad - maybe missed something when copying from the linux machine to windows.  I'll do a 2 day CPU test(I mean reindex) and see if that fixes it.

**Comment by zathras-crypto** [comment]
Sorry for the delayed response...

Does the transaction show up as valid on [omniexplorer.info](http://omniexplorer.info)?

Since you've tried to load the wallet in question on more than one node and seen the same behaviour, the first recommendation would be to rescan the wallet.  Start Omni Core with the `--zapwallettxes` parameter to do so.

We can confirm if it's your local node reporting bad data which seems unlikely but always good to check.  Please run the RPC `omni_getcurrentconsensushash` and provide the data returned.  This is a hash of the entire state at a particular blockheight and can be used to verify your node data without you needing to provide us with your address(es).

It's also possible to wipe the state from Omni Core and start fresh.  A reindex is not necessary.  Simply pass the `--startclean` parameter at startup.  This will take several hours unless you happen to be running the 0.2 develop branch with the perf improvements, but that's not released yet so not recommended.

**Comment by thesolarminer** [comment]
Good advice.  Appreciate all the help.

Yeah, the new transaction shows up on the explorer.   I already tried zapwallettxes and deleted the Omni directories, which is probably the same as your --startclean command.  On day 2 of the new blockchain download.

**Comment by thesolarminer** [comment]
The new blockchain download did the trick.  It really seemed odd that a bitcoin block issue would show bitcoin parts of transactions but not the maidsafe coins.  I guess it was just something wrong with a block a few months ago that only affected the omnilayer.  

The solution to anyone else with a similar transaction problem is to try in order of least time(either use debug window or for a command line start add -- before the option): 
zapwallettxes
omni_getcurrentconsensushash and verify your blockchain is correct.  
- If the blockchain is good run startclean this to redownload omnilayer data(Plan on 3hrs).
- If not, delete everything in the omnicore data directory(save your wallet.dat first) and start your wallet and it will redownload the blockchain(plan on 3 days).

**Comment by dexX7** [comment]
Glad your issue was resolved, and thanks for posting additional information! @thesolarminer

**Comment by trybye** [comment]
what's the difference between 'dumpwallet' and 'backupwallet',under what situations should i run 'backupwallet'
