### ISSUE TITLE
paymentrequestplus.h:8:31: fatal error: paymentrequest.pb.h: No such file or directory

### ISSUE THREAD

**Issue by dragon28** [OmniLayer/omnicore#446]
Hello People,

found some error during make:

In file included from qt/test/../paymentserver.h:35:0,
                 from qt/test/paymentservertests.h:8,
                 from qt/test/test_main.cpp:13:
qt/test/../paymentrequestplus.h:8:31: fatal error: paymentrequest.pb.h: No such file or directory
compilation terminated.
Makefile:6938: recipe for target 'qt/test/qt_test_test_omnicore_qt-test_main.o' failed
make[2]: *** [qt/test/qt_test_test_omnicore_qt-test_main.o] Error 1
make[2]: Leaving directory '/home/dragon/omnicore/src'
Makefile:8138: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/dragon/omnicore/src'
Makefile:587: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by dexX7** [comment]
Hi @dragon28, did you run the following before?

```
./autogen.sh
./configure
```

**Comment by dragon28** [comment]
Hello @dexX7 ,

I apologize, I made a mistake that I forgot to install libprotobuf-dev protobuf-compiler packages on my Ubuntu 64bits 16.04.1 before compile an make the software.

Please kindly ignore or close this issue.

Thank you responding to this issue and again I apologize for any inconvenient.

**Comment by dexX7** [comment]
Hey @dragon28, 

I'm glad your issue was resolved. You're welcome; we are here to help. :)
