### ISSUE TITLE
2 API questions

### ISSUE THREAD

**Issue by Crypto2** [OmniLayer/omnicore#475]
1. Does  omni_getallbalancesforid return all of the balances of the token for the entire network or just balances in the wallet?

2. Can omni_sendsto be used to distribute Bitcoin to each holder of a token based on how much of the token they hold? I've seen in some places Bitcoin can be specified as propertyid = 0?

ie. omni_sendsto "fromaddress" 0 "amount" "fromaddress" ourtokenid

**Comment by zathras-crypto** [comment]
Hey :)

1) It returns all balances for the entire state, not just for addresses in the wallet.

2} STO cannot be used for Bitcoin, as that would require creating a UTXO for every recipient which could mean a very large transaction (and get very expensive fee wise).  We're about to activate cross property STO, such that you could distribute say n Tether between all holders of Omni (or MAID or whatever) for example, but Bitcoin sadly we don't support.

Hope that helps & please feel free to shout if you need further info.

Thanks
Z

**Comment by Crypto2** [comment]
Ok, thanks for your help :)

**Comment by dexX7** [comment]
@Crypto2: would it be useful for you, if you had a Bitcoin nominated STO call?

Back then I created one for testing, which hasn't been integrated, but it should be straight forward to add such a call.

**Comment by Crypto2** [comment]
It would be convenient for sure but not essential, other wise I just have to calculate shares manually and use sendmany to do the same thing manually.

**Comment by dexX7** [comment]
Given the inital issue was resolved, I'm going to close this. Please feel free to reopen or create a new one, if you still have any questions. :)
