### ISSUE TITLE
OmniCore breaks on start on Windows 10 64 bits

### ISSUE THREAD

**Issue by QcMrHyde** [OmniLayer/omnicore#476]
I get that error while trying to open OmniCore v0.0.12rel...

![image](https://user-images.githubusercontent.com/6273472/26907100-cf5e15ce-4bbe-11e7-8e0e-ea192eccd0f0.png)

**Comment by dexX7** [comment]
Hi @QcMrHyde,

thanks for reporting this!

Unfortunally this error is most likely the result of using an incompatible blockchain format from Bitcoin Core 0.11 or higher. Omni Core, in it's current form, is based on Bitcoin Core 0.10.4. We are going to release a new port very very soon, which will be compatible with the new database format.

In the meantime, you could reindex the database by starting Omni Core with the flag `-reindex`:

`./omnicored -reindex` (or `./omnicore-qt -reindex`, ...)

Please note, reindexing the database can take several hours.
