### ISSUE TITLE
Seperate RPC commands for DEx actions

### ISSUE THREAD

**Issue by dexX7** [OmniLayer/omnicore#48]
As discussed in https://github.com/OmniLayer/omnicore/issues/47#issuecomment-103733520.

Instead of:
```
sendtrade_OMNI "fromaddress" propertyidforsale "amountforsale" propertiddesired "amountdesired" action
```
There should be seperate commands for each action, for example:
```
sendtrade_OMNI "fromaddress" propertyidforsale "amountforsale" propertiddesired "amountdesired"
sendcanceltradebyprice_OMNI "fromaddress" propertyidforsale "amountforsale" propertiddesired "amountdesired"
sendcanceltradebypair_OMNI "fromaddress" propertyidforsale propertiddesired
sendcancelalltrades_OMNI ecosystem
```

The traditional DEx commands could be seperated in a similar fashion, too.

Edit: bonus points for finding an alternative to the `_OMNI` suffix. ;)

**Comment by zathras-crypto** [comment]
Supported.

Though commands should be eg ```sendtrade_OMNI``` rather than ```sendtrade``` to match existing naming convention (which I know there is a lack of consensus on _OMNI suffix, but that's probably a different discussion)
