### ISSUE TITLE
Loading persistent state: NONE

### ISSUE THREAD

**Issue by jinglics** [OmniLayer/omnicore#484]
I replace bitcoind by omnicored, using existed data block. After scanning for more than an hour, I restart. It shows "Loading persistent state: NONE" and scans agiain?

**Comment by dexX7** [comment]
Hey @jinglics, if you abort the initial Omni transaction scanning, the process starts from the beginning.

Are you already using Omni Core v0.2? The inital scan should be faster with that version.

**Comment by jinglics** [comment]
Yes. I use omnicore-0.2.0 now. But how to continue the scanning transactions after I restart omnicored, not start from beginning?
Thanks.

**Comment by dexX7** [comment]
When you finish the process once, it won't happen again. Is your blockchain already fully synchronized?

**Comment by jinglics** [comment]
I think mine one has already finished all the transaction scanning (100%) and also can detect new blocks. But after Ctrl+C to stop, It begins to scan again after restart.

**Comment by jinglics** [comment]
But after finishing scanning, there's a warning
Jul 05 06:50:55 btc-sfo omnicored[13683]: 2017-07-05 06:50:55 Exodus balance: 28880.52208659 OMNI
Jul 05 06:50:55 btc-sfo omnicored[13683]: 2017-07-05 06:50:55 Omni Core initialization completed
Jul 05 06:51:09 btc-sfo omnicored[13683]: Warning: Please check that your computer's date and time are correct! If your clock is wrong, Omni Core will not work properly.

**Comment by zathras-crypto** [comment]
Hi Jinglics,

To avoid rescanning on startup Omni Core needs to be cleanly stopped.   Are you stopping Omni Core with the `stop` RPC call?  CTRL+C will likely terminate rather than shutdown.  You should see "Omni Core shutdown completed" if shutting down cleanly.

The warning about the clock is related to the client knowing when the blockchain is synchronised - is your clock accurate?

Thanks
Z

**Comment by miran456852** [comment]
Hi Jinglics，do you solve this problem？

**Comment by miran456852** [comment]
I see the same problem

**Comment by dexX7** [comment]
Hi @miran456852, can you please check your system's clock? Which OS are you running?

**Comment by miran456852** [comment]
CentOS Linux release 7.4.1708 (Core)，and how to set up system clock？my time zone is as/shanghai

**Comment by dexX7** [comment]
Hi, can you please try:

```
yum install ntp
chkconfig ntpd on
ntpdate pool.ntp.org
```
