### ISSUE TITLE
Maidsafe Coin Stuck

### ISSUE THREAD

**Issue by jpiece** [OmniLayer/omnicore#488]
hi,

There's my mistake to withdraw from wrong blockchain to get BTC. now my btc address stuck with the madisafe coin inside, anyone can help me to retrieve it back? many thanks, any conditions can be deal.

![image](https://user-images.githubusercontent.com/31202242/29507229-cda2a256-8681-11e7-86a0-70ca0a8187c0.png)

Thanks

**Comment by dexX7** [comment]
Hi @jpiece, do you have the private key for that address? If so, you can import it into http://omniwallet.org/.

**Comment by dexX7** [comment]
I'm going to close this issue for now, but please feel free to reopen, if you have any other question.
