### ISSUE TITLE
[Question] How to send tokens if they are distributed on different addresses

### ISSUE THREAD

**Issue by gituser** [OmniLayer/omnicore#489]
Hi.

I'm a total newbie on omnicore.

So here is what I'm doing: I'm accepting Tether-token small payments on different addresses (for each deposit I do generate a new address). (e.g. addr1 got 0.5 tether, addr2 got 2 tether, addr3 got 4 tether, addr4 got 2 tether).

Now how do I transfer total for example 5 tether to some address?

Thank you.

EDIT:

it seems even simple send isn't working for me for some reason:

```
omnicore@omnicore-testnet-dev:~$ ./omnicore-cli omni_getbalance mocVk5GAuNuvMCyvEtAeA1adxocd7B3xfv 2
{
  "balance": "100.00000000",
  "reserved": "0.00000000"
}

omnicore@omnicore-testnet-dev:~$ ./omnicore-cli omni_send "mocVk5GAuNuvMCyvEtAeA1adxocd7B3xfv" "miFtNACdAxUD45CJ8QEgJSV2VX9i94wF8A" 2 "1"
error code: -206
error message:
Error with selected inputs for the send transaction
```

Any idea why it might be not working?

**Comment by dexX7** [comment]
Hi @gituser,

there are probably two points to mention:

1. Unfortunately you can't bundle those amounts, and you need to send a transaction from each new address.

2. To send tokens you also need some smaller amount of bitcoins, because Omni messages are embedded in Bitcoin transactions.

**Comment by gituser** [comment]
@dexX7 thank you for the quick answer.

I do have some testnet bitcoins on the balance - 
```
omnicore@omnicore-testnet-dev:~$ ./omnicore-cli getbalance
0.99986440
```
the question is how much do I need to have in order to send tokens and how much will be spent there from each token send?

regarding 1) is there any function to do some sort of account sweep to my main account? (like e.g. in monero or ethereum) or do I need to create a lot of transactions in order to get all my tokens in 1 place in order to send them to someone?

thank you.

**Comment by jaty** [comment]
Having same issues, created new address via your client, sent 5USDT to it and now I'm trying to test omni_send/omni_sendsto sending from this generated address to tether account/another generated address in wallet, but it fails everytime. In your RPC-API docs for omni_send it says that all you need is just provide fromAddress toAddress propertyId and amount, but it doesn't work at all. I always get this error "Error with selected inputs for the send transaction" on omni_send, omni_sendsto etc. What am I doing wrong?

**Comment by deniszadorozny** [comment]
Same Question, I have my omni coins on some address(derived using getnewaddress) and now I need have them in one place, sending from the generated address to the default account address gives: "Error with selected inputs for the send transaction"

**Comment by dexX7** [comment]
@jaty @deniszadorozny:

The address you are trying to send from needs to have some bitcoin. See also:

https://github.com/OmniLayer/omnicore/wiki/Why-do-I-need-bitcoin-to-create-Omni-transactions%3F

**Comment by slumber1122** [comment]
@dexX7 I accepted some btc testcoin from[testnet3 faucet](https://live.blockcypher.com/btc-testnet/address/mg4CSKco5WPLtsWg6wASgzJ7339Y9Kbtv7/), but the command
```
./omnicore-cli getbalance
0.00000000
```
so , How can I get testcoin?

**Comment by gituser** [comment]
With huge fees right now in bitcoin - tether seems to be pointless to use it as a distributed system.

**Comment by dexX7** [comment]
Please feel free to reopen this issue or create a new one, if you have another question.

**Comment by dexX7** [comment]
Hi @mcb345,

this is a common issue integrators face. We added two new RPCs, which allow to create raw transactions, which are funded from other sources, which may help in this context:

- https://github.com/OmniLayer/omnicore/blob/develop/src/omnicore/doc/rpc-api.md#omni_createfunded_send
- https://github.com/OmniLayer/omnicore/blob/develop/src/omnicore/doc/rpc-api.md#omni_createfunded_sweep

These RPCs are available in the develop branch and going to be part of the v0.3.1 release, which is expected in two weeks.

**Comment by wh1291104857** [comment]
那目前只能给每个分地址转BTC手续费，然后转到主账户地址
