### ISSUE TITLE
[Question] Commission when using omni_send

### ISSUE THREAD

**Issue by avelrl** [OmniLayer/omnicore#490]
How to make the commission in the BTC be taken from a different address, and not from the sending address when you call omni_send?
I try and get an error
```bash
root@omnicore:/data/omnicore/bin# ./omnicore-cli "omni_send" "15krpcsgvPgsL1R94YXTmuSDiZ7t4bpPXG" "3JKQ1PjmJV7LbwuPkV28jUDFrhqnNqfPLh" 31 "10.0" "1CCExLz6YbdT7h3i6BHrQgbkU1vKvwp5v1" 0.00000001
error code: -206
error message:
Error with selected inputs for the send transaction
```
Thanks

**Comment by dexX7** [comment]
Unfortunaly using a different address for funding the transaction doesn't work. The sender needs sufficient BTC to pay for the transaction

**Comment by dexX7** [comment]
I'm going to close this issue for now, but please feel free to reopen, if you have any additional question. :)

**Comment by qianlifeng** [comment]
I have the same question, if I have a lot of USDT addresses, do I need to send BTC to all of them and then send the USDT out? Is there any convenient way?

**Comment by dexX7** [comment]
Hi @qianlifeng,

currently you need to send BTC to each of them, however, with #658 things become much easier, which is going to be integrated into the next release. If you can build from source, you could give it a try already.
