### ISSUE TITLE
How to transfer funds.

### ISSUE THREAD

**Issue by NormanPageTheSecond** [OmniLayer/omnicore#491]
And thats it. How do I transfer from omni to another wallet?

**Comment by dexX7** [comment]
HI @NormanPageTheSecond: are you using Omni Core UI or the RPC client?

**Comment by dexX7** [comment]
Hi @NormanPageTheSecond, please reopen this issue, when you provide the missing information. Thanks!

**Comment by NormanPageTheSecond** [comment]
Not sure to be honest. I can veiw my balance but can't open my wallet. I'm using 2FA. Got details etc. Otherwise flummoxed.

**Comment by dexX7** [comment]
Ah, it looks like you're using Omni Wallet. Please open a ticket here:

https://github.com/OmniLayer/omniwallet/issues

**Comment by NormanPageTheSecond** [comment]
I am using Omniwallet with 2fa but it wont open. I've followed the faqs to no avail. So I can't 'provide the missing information' .

**Comment by dexX7** [comment]
@NormanPageTheSecond: please use https://www.omniwallet.org/about/contact to contact the Omni Wallet support.
