### ISSUE TITLE
ERROR MESSAGE -206 "The send transaction has failed. Error with selected inputs."

### ISSUE THREAD

**Issue by dyang100** [OmniLayer/omnicore#492]
![error message -206](https://user-images.githubusercontent.com/32077646/30563083-b01a10d4-9c8e-11e7-93ed-2557a085fc4b.PNG)

I double checked both sending and receiving addresses to ensure they were correct, and also made sure there was enough BTC to send as this was not my first time moving maidcoins out of my wallet, its just the only time I seem to be having an issue....... any help would be greatly appreciated. Not sure exactly why I'm getting this error message. (To clarify: I have .00013672 BTC in my wallet AVAILABLE and the average maidsafe transaction only cost .00003 BTC to send so I am mind-boggled. PLEASE HELP!)

**Comment by dyang100** [comment]
Apparently, the BTC that says its available in my omnicore wallet, might be in a different address than the one I'm trying to send coins out of. If that's the case, is there an easy way to move BTC between addresses on my computer of my coins? Or do I just have to send BTC to these addresses individually the traditional way? Thank you in advance for any help, and appreciate anyone's swift reply.

**Comment by zathras-crypto** [comment]
Hi,

You will need to send BTC to your Omni address in order to send a transaction.  

Unfortunately you can't move BTC between addresses in your wallet just on your computer, it has to be done on the blockchain using a regular BTC send.

Thanks
Z

**Comment by dyang100** [comment]
@zathras-crypto Thank you for the reply!
