### ISSUE TITLE
What is the plan to deal with the segwit2x support?

### ISSUE THREAD

**Issue by phuongnd08** [OmniLayer/omnicore#496]
We are using omnicore to sign usdt transaction. How does it affected by segwit2x?

**Comment by dexX7** [comment]
Hi @phuongnd08, we are going to publish a statement about this shortly.

**Comment by phuongnd08** [comment]
Would you give some estimation on this? Where should be subscribe to hear about this statement?

**Comment by dexX7** [comment]
We're probably going to publish a statement on https://blog.omni.foundation/ in the next week or so, but in short:

While the Omni protocol is blockchain agnostic, Omni Core uses Bitcoin Core as underlying base and we're going to continue to do so.

**Comment by dexX7** [comment]
Please feel free to reopen this issue or leave any additional comments. :)
