### ISSUE TITLE
how to listen new block arrived event instead of get new block info in a loop

### ISSUE THREAD

**Issue by kylejan** [OmniLayer/omnicore#498]
how to listen new block arrived event instead of get new block info in a loop.

for example, after an api 'subscribeaddress' we can get new transaction corresponding to this address once the new transaction is detected

**Comment by dexX7** [comment]
Hey @kylejan,

there is a [ZMQ](https://github.com/OmniLayer/omnicore/blob/master/doc/zmq.md) interface as well as the `-blocknotify=<cmd>` option, which executes a command when the best block changes (`%s` in `cmd` is replaced by block hash).

You could for example put the following in your `bitcoin.conf`:

```
blocknotify=/home/bitcoin/printblock.sh %s
```

And in `printblock.sh`:

```sh
#!/bin/sh
echo "New block found: $@"
```

Whenever a new block is found, it is passed to `printblock.sh` and printed in place of `$@`.

In the context of Omni Layer transactions, you could use a script, which is triggered by new blocks, that then fetches all Omni transactions of that block with [omni_listblocktransactions](https://github.com/OmniLayer/omnicore/blob/master/src/omnicore/doc/rpc-api.md#omni_listblocktransactions) and [omni_gettransaction](https://github.com/OmniLayer/omnicore/blob/master/src/omnicore/doc/rpc-api.md#omni_gettransaction).

To list unconfirmed Omni transactions, you can use [omni_listpendingtransactions](https://github.com/OmniLayer/omnicore/blob/master/src/omnicore/doc/rpc-api.md#omni_listpendingtransactions).

**Comment by kylejan** [comment]
got it. thanks so much!
