### ISSUE TITLE
why the omnicored's block data is different against the bitcoind's block data?

### ISSUE THREAD

**Issue by kylejan** [OmniLayer/omnicore#499]
I have an existed testnet bitcoin blockchain data downloaded by bitcoind.

when I use omnicored on this existed data, the latest block number change from 1200000+ to 800000+.

is that correct? i think there may be something wrong.

**Comment by dexX7** [comment]
That's very odd and I don't really follow.

Which version did you previously use?

**Comment by kylejan** [comment]
I am using bitcore-node before. the corresponding bitcoind's version is v0.12.1

**Comment by zathras-crypto** [comment]
Omni Core should be on the testnet3 chain which has 1200000+ blocks.

Could you please paste the output of `omni_getinfo`? 

Thanks
Z

**Comment by kylejan** [comment]
{
  "omnicoreversion_int": 20000000,
  "omnicoreversion": "0.2.0",
  "mastercoreversion": "0.2.0",
  "bitcoincoreversion": "0.13.2",
  "block": 1109772,
  "blocktime": 1490755358,
  "blocktransactions": 0,
  "totaltrades": 16299,
  "totaltransactions": 21751,
  "alerts": [
  ]
}

 i think it will be latest in the end. but the download speed is very slow. I have started the download procedure of blockchain for 3 days
