### ISSUE TITLE
omnicore-cli "getinfo" method gives error "Warning: unknown new rules activated (versionbit 28)"

### ISSUE THREAD

**Issue by kylejan** [OmniLayer/omnicore#500]
omnicore version 0.2.0

when i use rpc method "getinfo", i get error Warning: unknown new rules activated (versionbit 28)

how to solve this?

**Comment by zathras-crypto** [comment]
Hi,
This will be resolved in the next version of Omni Core (the warning is related to miner signalling and can be safely ignored).
Thanks
Z

**Comment by kylejan** [comment]
got it! thanks

**Comment by gggin** [comment]
Problem is still here
# ./omnicore-cli -datadir=data getinfo
{
  "version": 130200,
  "protocolversion": 70015,
  "walletversion": 130000,
  "balance": 1.01685611,
  "blocks": 1413228,
  "timeoffset": 0,
  "connections": 12,
  "proxy": "",
  "difficulty": 56234572.68927951,
  "testnet": true,
  "keypoololdest": 1536576702,
  "keypoolsize": 100,
  "paytxfee": 0.00000000,
  "relayfee": 0.00001000,
  "errors": "Warning: unknown new rules activated (versionbit 28)"
}
