### ISSUE TITLE
Error with selected inputs for the send transaction

### ISSUE THREAD

**Issue by kylejan** [OmniLayer/omnicore#501]
when call omni_send, there is an error "Error with selected inputs for the send transaction".
is that because there is no enough btc for the transaction?
if yes, how can i know that how much btc needed to complete this transaction?

**Comment by dexX7** [comment]
> is that because there is no enough btc for the transaction?

Yes.

> if yes, how can i know that how much btc needed to complete this transaction?

There is no handy way to check this at the moment, because the actual fees depend on the network status.

**Comment by kylejan** [comment]
got it, thanks

**Comment by dexX7** [comment]
Hi @macrotea, please post a new issue here: https://github.com/OmniLayer/omniwallet/issues

**Comment by LaoBan-ywcm** [comment]
@macrotea Have you salevd this problem?I have the same problem now
