### ISSUE TITLE
is that possible to use an address's bitcoin to make a omni transaction sent from another address ?

### ISSUE THREAD

**Issue by kylejan** [OmniLayer/omnicore#503]
for example,
i have bitcoin in address A, tether in address B while address B does not have enough bitcoin to do an omni transaction.
is that possible to i make a transaction sent from address A to address C and put the payload tether transaction sent from address B in it?

**Comment by dexX7** [comment]
Unfortunately there is no easy way at the moment.

Right now you could use the raw transaction interface to create transactions by hand. The first input must be from the token holder, other inputs can be added as you wish, which could be used to pay for fees.

There is a tutorial about raw transaction creation:

https://github.com/OmniLayer/omnicore/wiki/Use-the-raw-transaction-API-to-create-a-Simple-Send-transaction

And more discussion about this topic can be found in this issue: https://github.com/OmniLayer/omnicore/issues/383

**Comment by kylejan** [comment]
I think this method will have another problem.

for example,

if both address A and address B have tokens, and I will concat uxtos of these two address to make a raw transaction. In my purpose, I want send tokens from B to C. but because I put both B's utxos and A's utxos into the input of raw transaction, how can I know the tokens is sent from B instead of A?

**Comment by kylejan** [comment]
oh i see, is that the token will be subtracted from the first input address?

**Comment by zathras-crypto** [comment]
That's right, the sender is simply the first vin *for class C (nulldata)* transactions.

Class C is our current transaction format, but I wanted to mention if by some chance you are using one of our older formats (eg bare multisig) that the sender is actually worked out via a different method.

**Comment by kylejan** [comment]
got it, thanks
