### ISSUE TITLE
I a withdrawal, display is invalid.Who can tell me how to solve?THX.

### ISSUE THREAD

**Issue by 495880776** [OmniLayer/omnicore#504]
I withdraw from the Liqui.
After 24 hours, the query Txid is invalid.
There is no order, no back to my original account.
Who knows how to solve this kind of "invalid" situation?

**Comment by dexX7** [comment]
Hey @495880776, can you please post a transaction id?

**Comment by dexX7** [comment]
Please feel free to reopen this issue or create a new one, if you have new input.
