### ISSUE TITLE
Multiple Simple Send in one bitcoin transaction?

### ISSUE THREAD

**Issue by phuongnd08** [OmniLayer/omnicore#506]
Can we craft a transaction that perform multiple simple send in 1 bitcoin transaction?
for example, we have 3 address A, B, C

Our btc transation inputs have vins from A, B, C
And outputs goes to D, E, F and [Simple Send A-> D], [Simple Send B -> E], [Simple Send C -> F]?

Will omni node accepts such transaction as valid?

**Comment by dexX7** [comment]
Currently it doesn't consider such a transaction as valid. We started the discussion about it some time ago in #370.
