### ISSUE TITLE
Where is my money?

### ISSUE THREAD

**Issue by fernand0neves** [OmniLayer/omnicore#509]
I transfer money U$ 573,33 for my account into HITBTC.com to my account into RIVALO.com, but the support of RIVALO.com tell me receive only U$ 0,04!
where is my money?
There is the link:
http://omnichest.info/lookuptx.aspx?txid=d11d9179179d8783235c76dd901fbd60a55d5791d9a7cd7ae4c241276caa5f6d

**Comment by Philx0** [comment]
This isn't the right place for help. Anyway, it seems you sent tether to an address that only accepts bitcoin. I can't imagine any company (or payment providers) putting costly dev hours into recovering those funds.

**Comment by dexX7** [comment]
@Philx0 seems to be right. You need an Omni aware wallet to receive and send USDT.

If you can export your private key, you could import it on www.omniwallet.org. Otherwise I suggest you get in contact with the Tether support.
