### ISSUE TITLE
Omnicore bad sync

### ISSUE THREAD

**Issue by zekylaf** [OmniLayer/omnicore#510]
Hi, I am new at Omni. I started the omnicored with the -testnet flag. 
Currently, the testnet blockchain synchronization is 100%. Now, I am using rpc commands to get some info. I sent some bitcoin tesnet coins to address mgsMwzzRTbxh5ghxomKwpvoXNLygJYhEZX. The txid is 9a7f030bf45c27c3f08504810a99073f4e3f196be160f6d7c0920833a9a7c323.

When I use:
$ ./omnicore-cli omni_listblocktransactions 1250425 
The answer is:
[ ]

When I use:
$ ./omnicore-cli omni_listpendingtransactions mgsMwzzRTbxh5ghxomKwpvoXNLygJYhEZX
The answer is:
[ ]

When I use:
$ ./omnicore-cli omni_listtransactions mgsMwzzRTbxh5ghxomKwpvoXNLygJYhEZX
The answer is:
[ ]

When I use:
$ ./omnicore-cli gettransaction 9a7f030bf45c27c3f08504810a99073f4e3f196be160f6d7c0920833a9a7c323
The answer is:
error code: -5
error message:
Invalid or non-wallet transaction id

What am I doing wrong? I can't get the balance of the address. It looks like Omnicore is not synchronizing the transactions from the blockchain.
Thanks

**Comment by dexX7** [comment]
How did you resolve this?

**Comment by zekylaf** [comment]
All omni commands were answering [] because it only looks for transactions that includes an omni propertyId. 

The command _gettransaction_ started to answer the transaction data a few hours later. I don't know what happened.
