### ISSUE TITLE
unsupported feature 14 ('Unknown feature')

### ISSUE THREAD

**Issue by alor** [OmniLayer/omnicore#518]
When I issue omni_getinfo I get this warning:

```
{"omnicoreversion_int"=>20000000,
 "omnicoreversion"=>"0.2.0",
 "mastercoreversion"=>"0.2.0",
 "bitcoincoreversion"=>"0.13.2",
 "block"=>498711,
 "blocktime"=>1512980904,
 "blocktransactions"=>8,
 "totaltrades"=>1511,
 "totaltransactions"=>687603,
 "alerts"=>
  [{"alerttypeint"=>1,
    "alerttype"=>"alertexpiringbyblock",
    "alertexpiry"=>"499200",
    "alertmessage"=>
     "Your client must be updated and will shutdown at block 499200 (unsupported feature 14 ('Unknown feature') activated)\n"}]}
```

I've tried to figure out myself what's this unsupported feature but failed to find the cause. What will it happen? do I need a new omnicore version?

**Comment by dexX7** [comment]
Hi @alor, we're currently in the process of releasing a new Omni Core version. The warning will then be removed. Stay tuned. :)

**Comment by dexX7** [comment]
Omni Core v0.3 was released. This should resolve the issue.
