### ISSUE TITLE
Wallet Issue -  Wallet icon appears on bottom row of win 64 loads but then

### ISSUE THREAD

**Issue by WendyCoin** [OmniLayer/omnicore#522]
My wallet will not display on the desktop.....  It is listeed
![1omn](https://user-images.githubusercontent.com/29295933/34184408-6c9a2ac2-e4d4-11e7-89bc-b6ef753b6cf0.png)

Please help.  Anyone else  having this issue?

**Comment by dexX7** [comment]
Hi @WendyCoin,

is your chain completely synchronized or did you start Omni Core for the first time?

**Comment by dexX7** [comment]
Please feel free to reopen this issue or create a new one, if you have another question.
