### ISSUE TITLE
I withdrawal "AMP", 48 hour later unconfirmed?

### ISSUE THREAD

**Issue by sexxxxxxy** [OmniLayer/omnicore#523]
please help me, i send AMP to my account but 48h later say UNCONFIRMED

http://omniexplorer.info/lookuptx.aspx?txid=2e1f2d4587d958c0fe729393a8ddbeb6466ae07f515a1bc39bd579edfb3d7937?
![1](https://user-images.githubusercontent.com/34732583/34241755-52160c48-e5dd-11e7-8751-b1f5d19b3fb5.png)

**Comment by huuthinhhcmit** [comment]
Me too ! :(

**Comment by dexX7** [comment]
Hey guys,

currently the Bitcoin protocol is very loaded and there is not much we can do. :(

**Comment by laznjak** [comment]
did u got your AMP?
