### ISSUE TITLE
USDT transaction

### ISSUE THREAD

**Issue by Boshwithyou** [OmniLayer/omnicore#524]
Hello. Can someone help me? 
I sent my USDT on 19.12.17 and the operation is still unconfirmed. Moreover, the operations that occurred before / after me have long been confirmed.
Do not tell me what might be a problem? How it can be fixed? and how long to wait?
Sorry for my English!
tixd - ed8b673f260cc6680536433c73fe0715de7dedc5c79ecbc18cd3493f4499d291

**Comment by kingmaxbd** [comment]
I have the same problem...
txid 295d4eff5b996b452b1295c335fea4182ba595548de5603af675fd3ad37319fc
txid 3be39f6b46dee67b501efa88dcc315f0d10baf93720be4f696ae3f53ae627a69
txid 809a31b4a89c0395c194f3980ba54cade1cd9f5051411f80db927ecaad419cd6

**Comment by dexX7** [comment]
Hey guys,

the Bitcoin network is currently under heavy load. Please make sure to pay a sufficient fee.
