### ISSUE TITLE
Where is my USDT?

### ISSUE THREAD

**Issue by d3mero** [OmniLayer/omnicore#525]
Hello, i have two unconfirmed transactions and w8 3 days!!!!!
Pls help me, i need my money!!!!
f60d1dca8f04e4ac20f54235d6e259029f61ccbf93a4607bb503b582da152a4f

3d6d4df6d9277e0ddbc4428f62ef1d1d2e334cb58a0fcc0c328be17306f2acae

How lond i`m w8?

**Comment by dexX7** [comment]
Hey there,

the Bitcoin network is currently under heavy load. Please make sure to pay a sufficient fee.

There is unfortunately nothing I can do about this. :(
