### ISSUE TITLE
I have not received USDT

### ISSUE THREAD

**Issue by ngoduyson0302** [OmniLayer/omnicore#527]
Please check my help transfer transaction USDT from 06/12/2017 I have not received coin.
Here is the link on the web omni:
https://omniexplorer.info/lookuptx.aspx?txid=b0da356ee8a9ff55fce17efdc54772299b3437bc091fcd088adc599dcb59e275

My address wallet on Poloniex: 1NU5jr67XzqCY6Eq1sX4waHmFzsfTWKusD

Transaction was confirmed or I have not received coin.
Please check help me.
Thank you!

**Comment by kekkyojin** [comment]
Someone moved your 995 USDT to another address. Maybe Poloniex did it. Ask Poloniex.
