### ISSUE TITLE
I dont know where my MAID is. Would appreacite some help.. ty

### ISSUE THREAD

**Issue by laznjak** [OmniLayer/omnicore#528]
I sent 208 MAID from hitbtc to Poloniex 19.12.2017 and it got stucked because transacion had no hash. [http://prntscr.com/huj5k5](url)

And now it looks like my MAID got stucked again.. so if someone can help me how to finally get it i would be so appreacite.. ty in advance 

http://omniexplorer.info/lookupadd.aspx?address=14wEbGzM7CHZY1XKY34TVwqPybfh95vsUf

**Comment by dexX7** [comment]
Hi @laznjak,

happy new year! It looks like you sent 208 Maid to 14wEbGzM7CHZY1XKY34TVwqPybfh95vsUf, which is probably a Poloniex wallet? This transaction confirmed a few days ago on the 26th of December.

Is this correct?

**Comment by laznjak** [comment]
Happy new year..
Yea Poloniex wallet.. I was on holidays with my family and when i got home(27,12) it was same as it is atm,before that i waited 6 days for support to fix my transaction hash

On poloniex there is nothing on history site..

![sewxvpkyrrmb1e46bdz-8g](https://user-images.githubusercontent.com/34984360/34466726-cbb0590a-eede-11e7-940f-dfc399eae2b0.png)

**Comment by dexX7** [comment]
Did you hear back from Poloniex?

**Comment by laznjak** [comment]
Still no answer neither from poloniex neither from hitbtc.. And still no MAID tho..

**Comment by dexX7** [comment]
I hope it finally worked out well!

Please feel free to reopen this issue or create a new one, if there is any progress.
