### ISSUE TITLE
tether faucet on omni testnet?

### ISSUE THREAD

**Issue by kiahmed** [OmniLayer/omnicore#529]
Hi, 
I am playing with omni api and wanted to integrate with an app for tether support but before that wanted to do some test transaction. Where can I find a faucet for tetehr to send to my latest omni wallet (0.3.0) while it is running on test mode or it considers btc test coins only? Please help..

thanks

**Comment by dexX7** [comment]
Hi @kiahmed,

on testnet you can get TestOmni by sending Bitcoin to moneyqMan7uh8FqdCA2BV5yZ8qVrc9ikLP.

**Comment by kiahmed** [comment]
where to get TestOmni from? and whose address is that? My onmi core desktop wallet generated this address on testnet mykJ9Mp68adZB7knteS3T9FWHjaNXAoePo

**Comment by kiahmed** [comment]
how do i sent TestOmni or other test coins here? 
![capture](https://user-images.githubusercontent.com/28849607/34578898-b382d18c-f154-11e7-9bf2-8e7680e02980.PNG)

**Comment by dexX7** [comment]
@kiahmed:

when you send Bitcoin to moneyqMan7uh8FqdCA2BV5yZ8qVrc9ikLP on testnet, you receive TestOmni. The address is the protocol built in faucet, so to speak.

**Comment by kiahmed** [comment]
isee, then how do I map it to my address to test against my node?

**Comment by dexX7** [comment]
Can you please clarify?

The steps for testing are roughly like this:

1. Create new addresss via receive tab or with `getnewaddress`
2. Get Bitcoin from a faucet and send them to the address from the first step
3. Send Bitcoin via coin control in the GUI or `sendtoaddress` from the address generated in step one to `moneyqMan7uh8FqdCA2BV5yZ8qVrc9ikLP`
4. Then wait for confirmation and see that the address from the first step received TestOmni, either via the GUI or with the `omni_getbalance` RPC.

**Comment by kiahmed** [comment]
ok..thanks. but I wanst able to complete step 2. As I keep saying the address the onni core wallet generates all btc faucets and other omni protocol faucets says wrong btc address..how come?

**Comment by dexX7** [comment]
@kiahmed: you need to look for a testnet BTC faucet.

**Comment by kiahmed** [comment]
i tried this one https://testnet.manu.backend.hamburg/faucet

if you know any other that works, let me know please

**Comment by kiahmed** [comment]
testnet=1 in config file

**Comment by kiahmed** [comment]
finally got my tomni ..thanks guys

**Comment by dexX7** [comment]
Awesome!

**Comment by Govind13100** [comment]
@kiahmed " testnet=1 in config file " where is this file ??????

**Comment by lianhongHou** [comment]
@Govind13100 
the file is <datadir>/bitcoin.conf

**Comment by Govind13100** [comment]
@lianhongHou ya i got that and now able to run testnet. 

I want to confirm some thing if you're able to suggest me then please do suggest

I want to do tether (USDT) transfer i.e create usdt wallet and create transaction.

Does this wallet work for tether ???? if not then did you know any other API or any other thing that could help to implement USDT????

**Comment by dexX7** [comment]
> Does this wallet work for tether ?

Tether uses the Omni Layer main net, yes. But as far as I know, they don't have a token on test net.

**Comment by Govind13100** [comment]
@dexX7 Thank you for your reply , but then how could one test for tether ???

**Comment by qld-cf** [comment]
@dexX7  i got the return balance by "omni_getbalance", like
```
 {
  "balance": "65.40000000",
  "reserved": "0.00000000"
}
```
but i can't get the transactions of omni

**Comment by qld-cf** [comment]
so why would be like that

**Comment by dexX7** [comment]
HI @qld-cf, I think money generation transactions on testnet don't show up as Omni transaction.

**Comment by qld-cf** [comment]
@dexX7  
1. thx for your answer.
2. i used the command "omni_getbalance" to get the return balance(the propertyid is 2)，this is not  correct id for me，i want the test usdt(propertyid:31).. see 

> https://omniexplorer.info/sp.aspx

> https://omniexplorer.info/sp.aspx?mode=test
and what should i do to get the test usdt? looking forward your reply

**Comment by qld-cf** [comment]
now i follow omni website api doc,

> http://omnichest.info/apidocumentation.aspx

i use my address that recharged usdt，

> http://omniexplorer.info/ask.aspx?api=gethistory&address=1Q5Nv7ZTwTTvYnkSSbzbTkpF4pd8GB7MEu
but the error follows like "missing parameters"

> https://omniexplorer.info/ask.aspx?api=gettx&txid=539aceb2e0cd8435fa3b6a5935d3cbbdd4ab722a540959b1fa64471caef430d3
Is there any problem here?

**Comment by dexX7** [comment]
Ahh, just to clarify: there are two "ecosystems": main and test. These are not related to mainnet or testnet.

While you can get Omni and Test Omni on testnet by sending coins to `moneyqMan7uh8FqdCA2BV5yZ8qVrc9ikLP`, there is no USDT on testnet.

**Comment by kiahmed** [comment]
right..so assuming test omni works on testnet, when the wallet switched to mainnet it should just work for USDT correct?

**Comment by dexX7** [comment]
Well no, there is actually a "Test Omni" token on the Bitcoin mainnet. ;)

**Comment by vanhung17101** [comment]
@dexX7 i got the return balance by "omni_getbalance" but i can't get the transactions of omni:(
 What should I do?
I made the transaction, the return is Sender has insufficient balance:((( help me....

**Comment by vanhung17101** [comment]
Looking forward to the early reply from you
@dexX7

**Comment by wupeaking** [comment]
@qld-cf @lianhongHou  Hi 各位， 你们同步omnilayer有遇到问题吗？ 我现在同步特别慢，而且现在同步到115W左右的区块高度时不同步了。 请问大家有遇到吗？

**Comment by dexX7** [comment]
@vanhung17101: can you please clarify what you mean by "you can't get the transaction"?

You should be able to retrieve any transaction that was mined or sent with `omni_gettransaction`, however, there is one exception: this doesn't work for sends to `moneyqMan7uh8FqdCA2BV5yZ8qVrc9ikLP`.

**Comment by kensama7** [comment]
@dexX7 
```
Ahh, just to clarify: there are two "ecosystems": main and test. These are not related to mainnet or testnet.

While you can get Omni and Test Omni on testnet by sending coins to moneyqMan7uh8FqdCA2BV5yZ8qVrc9ikLP, there is no USDT on testnet.
```

If so, How can I change to "test ecosystems".

**Comment by dexX7** [comment]
When creating tokens, there is a field for this called "ecosystem":

https://github.com/OmniLayer/omnicore/blob/master/src/omnicore/doc/rpc-api.md#omni_sendissuancefixed

**Comment by yuerski** [comment]
Hi @Govind13100  , finally have you found any method to get usdt on testnet ?  i hv same question , haha

**Comment by dexX7** [comment]
@yuerski: you can only get Omni on testnet, but you may as well create your own token with the RPC interface:

https://github.com/OmniLayer/omnicore/blob/master/src/omnicore/doc/rpc-api.md#omni_sendissuancefixed

**Comment by yuerski** [comment]
@dexX7  THANK YOU  ,let me try , haha  , wait for minutes

**Comment by yuerski** [comment]
can not . in windows 8 , start up omni core , programe alerts "error loading wallet.dat : Wallet require newer version of omni Core" , although i get lastest version on official site   .  -_-

**Comment by yuerski** [comment]
and  ,  i m not able to use gradle project ,   faint . prefer to maven ..........

**Comment by dexX7** [comment]
@yuerski: hm. You probably used a Bitcoin Core version, which isn't fully compatible.

You could export your private keys and backup your wallet.dat file, then remove it and start Omni Core, and import the keys.

**Comment by antechdemo** [comment]
Hi,
The address the omni core wallet generates all btc faucets and other omni protocol faucets says wrong btc address..how come?

**Comment by dexX7** [comment]
@antechdemo: can you please post an example?

**Comment by antechdemo** [comment]
I wasnt able to complete step 2. As I keep saying the address the omni core wallet generates all btc faucets and other omni protocol faucets says wrong btc address..

**Comment by dexX7** [comment]
Ah, right, you're running Omni Core on mainnet. You need to start the client with `-testnet` to start in testnet mode.

**Comment by antechdemo** [comment]
Hi, thanx for the reply,But i already set the testnet= 1 mode in the bitcoin.conf file.But the issue is occured when we deposit some btc on the address of the omni.The btc coin is not reflected back on that address. 
If using walletnotify option,example   walletnotify=/usr/local/sbin/rabbitmqadmin publish routing_key=peatio.deposit.coin payload='{"txid":"%s", "channel_key":"tether"}'

**Comment by jayphbee** [comment]
Does omniexplorer public api available now?

**Comment by dexX7** [comment]
Hi @jayphbee, check out https://api.omniexplorer.info/.

**Comment by jayphbee** [comment]
@dexX7  amazing work! By the way, is it open source for the backend ?

**Comment by kazaff** [comment]
@dexX7 how can i use `sendtoaddress` method and control the sender address?  this method only set up toAddress.... so, i don't know  which address the `TOMNI` coin send to...

**Comment by dexX7** [comment]
Can you please clarify the question @kazaff?

**Comment by Sambusik** [comment]
So to my understanding, USDT does not have a testnet. 
In other words, we cannot test sending test coins of USDT to an address, this must be done on the mainnet, with real USDT.

I've reached a point where I have some OMNI (#1) & Test OMNI (#2), but no USDT (#31) to send out, so technically, there is no proper way to test if USDT is working for us, unless we test it with real USDTs.

**Comment by dexX7** [comment]
@Sambusik, this is correct, but you could create your own token in regtest mode or testnet, or use Omni or Test Omni to test with.

**Comment by sonpython** [comment]
@dexX7 the `sendtoaddress` will auto unspent address to send testnet btc to `moneyqMan7uh8FqdCA2BV5yZ8qVrc9ikLP` no I can not specify the `<from address>` so we can not force the faucet from `moneyqMan7uh8FqdCA2BV5yZ8qVrc9ikLP` to tranfer TOMNI to correct address.

**Comment by 2003liuyi2006** [comment]
sendtoaddress "money2NAZex8aCqUZixnLanGRktzZZmp3S2KfUx5" 0.1

**Comment by n10s16s22** [comment]
can anyone help me to finding the faucets for tether

**Comment by n10s16s22** [comment]
can anyone help me find out the faucets for tether

**Comment by kiahmed** [comment]
@antechdemo you still having the problem, sounds to me your config isn't recognized by the wallet , its creating its own default config and still running on mainnet probably
