### ISSUE TITLE
Grant @dexx7 alert rights

### ISSUE THREAD

**Issue by zathras-crypto** [OmniLayer/omnicore#53]
This should be a no-brainer really.  @dexX7 is doing great work for us and in my opinion should be given alert broadcast rights.

Opinions aside though, he has merge access so in theory could simply add his own alert address if he wanted to anyway.  Thus I propose we request @dexX7 supply us with a mainnet address that can be added to ```CMPTransaction::step2_Alert``` along with existing approved senders.

@dexX7 - this is not mandatory mate - if you don't want to that's fine - but I thought given how much you have contributed for us and how involved you are in the project it was only right to at least extend the option.

**Comment by dexX7** [comment]
Thanks @zathras-crypto.

I tagged it as `release`, as task to do until the release. :)

**Comment by dexX7** [comment]
Speaking of, I was always wondering how we could properly test the alert system via automated tests, without hardcoding keys, which are used in the tests.

The answer is actually simple: (note to self) make it configurable.

There could be a startup option `--alertsender=address`, and while doing so, it would probably also make sense to have `--ignorealert=address`, just to be on the safe side.

**Comment by zathras-crypto** [comment]
I can see the value in something like ```--alertallowsender=address``` for testing but can you fill me in on what purpose you see for ```--alertignoresender=address```? (in the context that ```--overrideforcedshutdown``` is already available?

**Comment by dexX7** [comment]
Shutdown, and likewise overwriting the shutdown are nuclear options, but there are more aspects.

In the best case a compromised alert key might be used to broadcast messages, which are then shown in Omni Core. Pushing a new version without that key is certainly the way to go, but as temporary solution the key could be ignored.

I'm playing devil's advocat here though. :)
