### ISSUE TITLE
USDT transaction

### ISSUE THREAD

**Issue by Waldeinsamkeit422** [OmniLayer/omnicore#531]
Hello. Can someone help me? 
I sent my USDT on 1.03 and the operation is still unconfirmed. Moreover, the operations that occurred before / after me have long been confirmed. 
Do not tell me what might be a problem? How it can be fixed? and how long to wait? 
Sorry for my English! 
Sender | 1DcKsGnjpD38bfj6RMxz945YwohZUTVLby 
Recipient | 1Bc7KCnrW4WEYGzGgX8RfBrv4D4pkME8Eb 
tixd - 3b1688ef0ef9b01c905e5b7a3a622b91be06c8cc4a0b11492a800ae017474126

**Comment by achamely** [comment]
That transaction appears to be part of a chain of transactions which will never confirm because one of the parent transactions was double spent and the is no longer available. 
You will need to contact the sender and ask them to reprocess/send a new transaction for you
