### ISSUE TITLE
[coding question]how to solve "* `private_key_path` file must exist:"

### ISSUE THREAD

**Issue by vincentwang0736** [OmniLayer/omnicore#532]
I followed this guide to build omni dev envirionment
Everything is ok until I run this command:

> vagrant up mastercore --provider=aws

I got this error:

> There are errors in the configuration of this machine. Please fix
> the following errors and try again:
> 
> SSH:
> * `private_key_path` file must exist:

Here is my Vagrantfile about private_key_path:

> Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
>   config.ssh.username = "ubuntu"
>   config.ssh.host = "xx.xx.xx.xx"
>   config.ssh.private_key_path = "/root/.ssh/id_rsa"

the private key file is really exist in the path:"/root/.ssh/id_rsa",and setup in Vagrant.But I still can't finish that command.

My System is:ubuntu 16.04,Vagrant 1.9.8
I am searching for a long time on net. But no use. Please help or try to give some ideas how to achieve this.

thank a lot!

**Comment by dexX7** [comment]
@msgilligan: can you help?

**Comment by dexX7** [comment]
The project you mentioned is no longer maintained.

Please feel free to reopen this issue or create a new one, if you have another question.
