### ISSUE TITLE
Missing transaction from omniexplorer.info

### ISSUE THREAD

**Issue by ddabek** [OmniLayer/omnicore#533]
When I lookup this address 1KjG75GmXNaj3jtHdXZpFVuh95S9yaoNR6 on omniexplorer.info it does not show; in the omniwallet.org address lookup it shows the balance.

Can anyone explain what happened here?

**Comment by achamely** [comment]
Omniexplorers search function seems to be having some issues. But the address does show up: http://omniexplorer.info/lookupadd.aspx?address=1KjG75GmXNaj3jtHdXZpFVuh95S9yaoNR6
