### ISSUE TITLE
 if I want to run omniwallet locally,must I install omnicore and synchronize  all the 177g data?

### ISSUE THREAD

**Issue by vincentwang0736** [OmniLayer/omnicore#534]
if I want to run omniwallet locally,must I install omnicore and synchronize  all the 177g data?

**Comment by dexX7** [comment]
Hey, can you please define what you mean with "locally"?

If you want to be connected to mainnet and transact with external users, then you need to synchronize all data, but if you want to create a local test network, then you could use regtestnet.

**Comment by vincentwang0736** [comment]
transaction is just broadcast,why i have to synchronize all data?

**Comment by dexX7** [comment]
Well, this is just how Bitcoin works:

https://bitcoin.org/en/full-node
