### ISSUE TITLE
something wrong when calling the apis of omniwallet

### ISSUE THREAD

**Issue by vincentwang0736** [OmniLayer/omnicore#535]
After installing omniwallet in ubuntu16.04, I tried on calling a getting api on my browser:

> http://xx.xx.xx.xx/v1/system/stats.json

But I got "502 Bad Gateway"

/var/log/nginx/error.log putput:

> *198 upstream prematurely closed connection while reading response header from upstream, client: 118.198.116.180, server: localhost, request: "GET /v1/system/stats.json HTTP/1.1", upstream: "uwsgi://127.0.0.1:1088", host: "xx.xx.xx.xx

And I didn't found uwsgi's log file ,So I want to ask where is uwsgi's log file by the way.
And what's the matter about 502 Bad Gateway？
thanks a lot!

**Comment by achamely** [comment]
Please do not spam your questions over the entire project. Keep them relevant to the specific repos: https://github.com/OmniLayer/omniwallet/issues/1578
