### ISSUE TITLE
How to enable Prune

### ISSUE THREAD

**Issue by khaitranvan96kt** [OmniLayer/omnicore#536]
I try the Prune function but not can be!
>>./omnicore/src/omnicored -reindex -prune=550
: Disabled transaction index detected.

Omni Core requires an enabled transaction index. To enable transaction indexing, please use the "-txindex" option as command line argument or add "txindex=1" to your client configuration file within your data directory.

Configuration file: /home/robot/.bitcoin/bitcoin.conf

Would you like Omni Core to attempt to update your configuration file accordingly?
Error: Please add txindex=1 to your configuration file manually.

Anhd

>> ./omnicore/src/omnicored -reindex -prune=550 -txindex=1
Error: Prune mode is incompatible with -txindex.
2018-01-15 04:49:31 Omni Core shutdown completed

**Comment by dexX7** [comment]
Hi @khaitranvan96kt, pruning is currently not supported.

**Comment by kiahmed** [comment]
well, to piggyback on this then whats the work around to save the entire chain which is pretty large the bigger problem is ongoing massive increase of data. If btc, bch wallets enable prune? Which omni disabled it?

**Comment by dexX7** [comment]
From an architectural perspective: when scanning and decoding Omni transactions, we are going through the whole transaction history. This process is detached from the transaction processing process of Bitcoin Core, to allow scanning and finding Omni transactions even after chain was already synchronized.
