### ISSUE TITLE
specification for Class C transactions

### ISSUE THREAD

**Issue by yushizhao** [OmniLayer/omnicore#537]
In the Appendix A of https://github.com/OmniLayer/spec#appendix-a-storing-omni-protocol-data-in-the-blockchain, we have specification for Class A and B. Do we have one for C?

**Comment by dexX7** [comment]
Currently not.

But in short: any number of OP_RETURN scripts is accepted, with any length and any number of push operations. Outputs with OP_RETURN 0x6f6d6e69 are considered, the prefix stripped, and the rest of the payload or payloads, in case there are multiple such outputs, merged.

**Comment by dexX7** [comment]
Please feel free to reopen this issue or create a new one, if you have another question.

**Comment by qqil** [comment]
> Currently not.
> 
> But in short: any number of OP_RETURN scripts is accepted, with any length and any number of push operations. Outputs with OP_RETURN 0x6f6d6e69 are considered, the prefix stripped, and the rest of the payload or payloads, in case there are multiple such outputs, merged.

What you can say about this statement for BTC network?

> A standard transaction (one that conforms to the isStandard() checks) can have only one OP_RETURN output. However, a single OP_RETURN output can be combined in a transaction with outputs of any other type.
