### ISSUE TITLE
Unconfirmed Tether transaction

### ISSUE THREAD

**Issue by macaskill7** [OmniLayer/omnicore#539]
Hello,

I sent a transaction from Kucoin exchange to Binance exchange about an hour ago, it is still unconfirmed.

Is this just normal congestion or is there some other issue? The transaction id is 329a1267ca73e057bb06cc6f82a85a0ce1ab0586438840aad46d4f41b193078

**Comment by dexX7** [comment]
Hi there,

I'm unable to find 329a1267ca73e057bb06cc6f82a85a0ce1ab0586438840aad46d4f41b193078.

**Comment by dexX7** [comment]
Please feel free to reopen this issue or create a new one, if you have another question.

**Comment by Matuvi95** [comment]
Buenas macaskill17, tuve exactamente el mismo problema, se llego a solucionar?
