### ISSUE TITLE
Lost Funds on 01/07/2018

### ISSUE THREAD

**Issue by obouhouj** [OmniLayer/omnicore#540]
Hello ,
I lost money between USDT (Tether ) and BTC (Bitcoin) , here s the transactions Ref below :
Completed
2018-01-07 02:09:44
USDT 999.73803638
Address: 15hXVABkA2Jv5mWqAWDieBs4QW3bDqmwVe
Txid: d7e2ed7996cd51cbdb59a53c1ab730136c82488d18cfc013c559fb21c1661e5d Check , this transaction
is lost , it s not showing on Bitcoin .
Completed
2018-01-07 03:59:52
BTC 0.00000546
Address: 15hXVABkA2Jv5mWqAWDieBs4QW3bDqmwVe
Txid: d7e2ed7996cd51cbdb59a53c1ab730136c82488d18cfc013c559fb21c1661e5d Check ,
When i calculate USDT (TetherUS) $999.73803638 into BTC (Bitcoin) 0.00000546 , Not even a Dollar .
I hope you can help me get back my money  .
    Thank you .

**Comment by waleedbukhari** [comment]
I have same problem

**Comment by dexX7** [comment]
Hi there,

you need an Omni aware wallet to show USDT. Which wallet are you using?

**Comment by waleedbukhari** [comment]
I sold usdt tether coin from binance I thought will go to my bitcoin but it’s went Omni layer I create wallet on Omni but it’s shows 0 balance please if u can help me on this thanks for your time. I put the bid coin address still went somewhere

[image1.png]

Sent from my iPhone

On Jan 20, 2018, at 10:33 AM, dexX7 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi there,

you need an Omni aware wallet to show USDT. Which wallet are you using?

**Comment by waleedbukhari** [comment]
I have coin base wallet also I create wallet on Omni . Thank u for replying fast

**Comment by waleedbukhari** [comment]
Can u plz tell me how do I get my money to binance or coinbase or to my account which ever one is faster 
I don’t see my money in Omni do you know where is my money

**Comment by dexX7** [comment]
Please clarify: you traded something for USDT on Binance and then what? Did you withdrawal the tokens? If so, to which wallet?

**Comment by waleedbukhari** [comment]
I accidentally pasted the bitcoin address on the usdt withdrawal instead of the wallet address. You can call me (209)751-7797. I can probably explain it better over the phone.

On Jan 20, 2018, at 12:34 PM, dexX7 <notifications@github.com<mailto:notifications@github.com>> wrote:


Please clarify: you traded something for USDT on Binance and then what? Did you withdrawal the tokens? If so, to which wallet?

**Comment by martyer1949** [comment]
I also suffered a similar loss for the same reason. I SUGGEST A CLASS ACTION LAW SUIT! They obviously know how to get the USDT into your Bitcoin wallet because they sent you a tiny bit of what they should have sent you. THIS IS CRIMINAL!

**Comment by martyer1949** [comment]
I also suffered a similar loss for the same reason. I SUGGEST A CLASS ACTION LAW SUIT! They obviously know how to get the USDT into your Bitcoin wallet because they sent you a tiny bit of what they should have sent you. THIS IS CRIMINAL!

**Comment by dexX7** [comment]
@waleedbukhari: I understand. Can you also state which wallet you sent the tokens to, i.e. from which wallet did you use the bitcoin address? Was this Coinbase or Binance? Binance helped it's users in the past to retrieve tokens! :)

@martyer1949: Unfortunately it's not as simple as this. Omni transactions are no regular transactions, but specially crafted transactions with payloads that instruct Omni aware software. While Coinbase sends regular Bitcoin transactions frequently, they are not willing to sign anything else.

**Comment by martyer1949** [comment]
Then return it to Binance! The Bitcoin receiving address was a Coins.ph address to which you sent the equivalent of $11 to instead of the total of $1483!!!

**Comment by dexX7** [comment]
@martyer1949: there is nothing we can do here. Please reach out to Coins.ph, because they are the ones having your tokens right now.

**Comment by martyer1949** [comment]
How can they have my tokens when you sent them just .0000054BTC?

**Comment by dexX7** [comment]
It's not *us* who sent the Bitcoin or USDT, but Binance.

Tokens transfer transactions are special Bitcoin transactions with a payload attached. To "see" the tokens you need an Omni aware wallet. You/Binance sent them to a wallet, which is not Omni aware. Please reach out to the support of that corresponding wallet to retrieve the tokens.

**Comment by dexX7** [comment]
@martyer1949: the tokens are held by Coins.ph, but they need an Omni aware wallet to show up.

**Comment by martyer1949** [comment]
This is the blockchain record. Does it not mean that Coins.ph received just .0000054 from you?


0eb01ff81d7427560bd8aa4351bef49a24cb108e13f863963abc7e83b48d8ce4
--
1FoWyxwPXuj4C6abqwhjDWdz6D4PZgYRjA |   | 1FoWyxwPXuj4C6abqwhjDWdz6D4PZgYRjA 0.22223218 BTCUnable to decode output address 0 BTC3QXVFR15D3raFn29cCGuiBKHhJKoigT3bb 0.0000054 BTC

**Comment by dexX7** [comment]
No. There are three things going on:

1. a Bitcoin transfer of 0.22223218 BTC to FoWyxwPXuj4C6abqwhjDWdz6D4PZgYRjA
2. a TetherUS transfer of 1483.17383578 USDT to 3QXVFR15D3raFn29cCGuiBKHhJKoigT3bb
3. a Bitcoin transfer of 0.0000054 BTC to 3QXVFR15D3raFn29cCGuiBKHhJKoigT3bb

Omni Layer transactions are an extension to the Bitcoin protocol and only show up when using Omni aware software. The transfer shows up, when using an Omni aware transaction explorer such as OmniExplorer. See here:

http://omniexplorer.info/lookuptx.aspx?txid=0eb01ff81d7427560bd8aa4351bef49a24cb108e13f863963abc7e83b48d8ce4

These tokens are now held in 3QXVFR15D3raFn29cCGuiBKHhJKoigT3bb and there is nothing I or the rest of the Omni team can do to help, as you instructed Binance to send the tokens to Coins.ph. Please reach out to their support, because they have the private key to this address and may be willing to help you to retrieve the USDT.

**Comment by martyer1949** [comment]
Your saying that Binance can retrieve them if they choose to, but Coins.ph cannot because they cannot see them?

**Comment by dexX7** [comment]
No, Binance can not retrieve them. Coins.ph can, if they install and use an Omni aware wallet.

**Comment by martyer1949** [comment]
Ok I do appreciate your help. Thanks!

**Comment by waleedbukhari** [comment]
I was trying to send it to my gdax wallet but I accidentally pasted my binance bitcoin address. Now on my transaction history i see my balance as ustd thetherUS.



Sent from my iPhone

On Jan 21, 2018, at 12:10 AM, martyer1949 <notifications@github.com<mailto:notifications@github.com>> wrote:


Ok I do appreciate your help. Thanks!

**Comment by dexX7** [comment]
@waleedbukhari: lucky you, I guess. GDAX doesn't support USDT and they won't help you to retrieve any, if you send them there.

**Comment by waleedbukhari** [comment]
No i didnt send there i paste the biance bid coin address i want it to send it on my binance bidcoin but went some where else . I talk to binance they send we send the money to usdt so u have to talk to them . Can u plz tell me where will be my is ??
I paste the binoance bidcoin address

Sent from my iPhone

On Jan 23, 2018, at 1:52 PM, dexX7 <notifications@github.com<mailto:notifications@github.com>> wrote:


@waleedbukhari<https://github.com/waleedbukhari>: lucky you, I guess. GDAX doesn't support USDT and they won't help you to retrieve any, if you send them there.

**Comment by dexX7** [comment]
So you're saying the tokens ended up in your Binance Bitcoin wallet?

**Comment by waleedbukhari** [comment]
No i dont know where it went

Sent from my iPhone

On Jan 23, 2018, at 2:03 PM, dexX7 <notifications@github.com<mailto:notifications@github.com>> wrote:


So you're saying the tokens ended up in your Binance Bitcoin wallet?

**Comment by dexX7** [comment]
Can you please check all the services you were using and check out the deposit addresses? From Binance, Coinbase, GDAX? When we figure out where the tokens went, we may be able to get in contact with the support and retrieve the tokens, if they are willing to help.

**Comment by waleedbukhari** [comment]
[image1.jpeg]

Sent from my iPhone

On Jan 23, 2018, at 11:33 PM, dexX7 <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you please check all the services you were using and check out the deposit addresses? From Binance, Coinbase, GDAX? When we figure out where the tokens went, we may be able to get in contact with the support and retrieve the tokens, if they are willing to help.

**Comment by waleedbukhari** [comment]
1ME6YddVq27nRqCgrbyMrayCBPxeyGUGuT

This is the address i sent n thats my binance bidcoin address

Sent from my iPhone

On Jan 23, 2018, at 11:33 PM, dexX7 <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you please check all the services you were using and check out the deposit addresses? From Binance, Coinbase, GDAX? When we figure out where the tokens went, we may be able to get in contact with the support and retrieve the tokens, if they are willing to help.

**Comment by dexX7** [comment]
So it *is* a Binance deposit address? In this case please reach out to the Binance support.

**Comment by waleedbukhari** [comment]
Yeah its a binance address

Sent from my iPhone

On Jan 24, 2018, at 2:45 AM, dexX7 <notifications@github.com<mailto:notifications@github.com>> wrote:


So it is a Binance deposit address? In this case please reach out to the Binance support.

**Comment by dexX7** [comment]
Awesome. As far as I know they helped other users in the past. Let us know how it went when you contact their support.

**Comment by DRMFR** [comment]
Can somebody please help. I sent btc from gdax to my Binance USDT address and is showing completed on my Coinbase account but is no where to be found on Binance and is not showing in history. I logged on to Omni explorer and it shows an available balance but have no idea where it is and why it didn’t get to Binance

**Comment by dexX7** [comment]
Hey @DRMFR, please reach out to the Binance support. Given that this was just a BTC send, it should be possible for them to account it properly for you.

**Comment by martyer1949** [comment]
Binance can account for it, but coins.ph says that their wallet cannot recognize BTC. When it was sent to coins.ph it was lost in the wilderness of their wallet! What to do??? Marty 

    On ‎Tuesday‎, ‎May‎ ‎15‎, ‎2018‎ ‎06‎:‎05‎:‎05‎ ‎AM‎ ‎CDT, dexX7 <notifications@github.com> wrote:  
 
 
Hey @DRMFR, please reach out to the Binance support. Given that this was just a BTC send, it should be possible for them to account it properly for you.

**Comment by dexX7** [comment]
@martyer1949: unfortunately it's really up to them and whether they can help you. :(

**Comment by jappktrunks** [comment]
@martyer narefund na po ba pera nyu? Parehas kc tau problema nag send din aq ng usdt sa coinsph
