### ISSUE TITLE
USDT withdrawal has not shown up in my bitcoin wallet

### ISSUE THREAD

**Issue by lgblogin** [OmniLayer/omnicore#542]
Good morning.
I have a problem with my transaction, I sent USDT (Tether) 3 days ago to my bitcoin address but it still hasnt shown up.
![screenshot 4](https://user-images.githubusercontent.com/35622890/35181515-11a9a504-fd91-11e7-839d-3152c6671e1e.png)

![screenshot 2](https://user-images.githubusercontent.com/35622890/35181517-251a297e-fd91-11e7-9a33-358bd6a105e6.png)

I hope you can help me with my problem.

Thank you.

**Comment by dexX7** [comment]
Hi there, you need an Omni aware wallet and USDT won't show up, if you send them to a Bitcoin wallet.

Please contact the Binance support, so they can help to retrieve the tokens.
