### ISSUE TITLE
Lost Funds on 01/10/2018

### ISSUE THREAD

**Issue by sh57jbi** [OmniLayer/omnicore#543]
Hello ,

I lost money between USDT (Tether ) and BTC (Bitcoin) , here s the transactions Ref below :

Completed
2018-01-10 08:23:57
USDT 9161.29997761
Address: 33D7ZrBExKyqUPzfGByqQLnJr56efeSD1G
Txid: 072eaabd98db8efd059be4cbc728edf9de2f96f0e63f626a3323d12d58c1c711 Check , this transaction
is lost , it s not showing on Bitcoin .

Completed
2018-01-10 08:34:26
BTC 0.00000546
Address: 1FoWyxwPXuj4C6abqwhjDWdz6D4PZgYRjA
Txid: 072eaabd98db8efd059be4cbc728edf9de2f96f0e63f626a3323d12d58c1c711 Check ,

When i calculate USDT (TetherUS) $9161.29997761 into BTC (Bitcoin) 0.00000546 ,

Completed
2018-01-10 08:49:44
USDT 1470.1
Address: 33D7ZrBExKyqUPzfGByqQLnJr56efeSD1G
Txid: 441d45d65bcade2a3efa385c1a53da03e8cf48fc3826ef848b9e213ff616434e Check , this transaction
is lost , it s not showing on Bitcoin .

Completed
2018-01-10 09:08:11
BTC 0.00000546
Address: 1FoWyxwPXuj4C6abqwhjDWdz6D4PZgYRjA
Txid: 441d45d65bcade2a3efa385c1a53da03e8cf48fc3826ef848b9e213ff616434e Check ,

When i calculate USDT (TetherUS) $1470.1 into BTC (Bitcoin) 0.00000546 ,

Not even a Dollar .
I hope you can help me get back my money .
Thank you .

**Comment by dexX7** [comment]
Hi there,

which wallet did you send the tokens to? The recipient needs an Omni aware wallet to "see" the TetherUS.

It's a valid Omni Layer transaction though and the tokens are in 33D7ZrBExKyqUPzfGByqQLnJr56efeSD1G:

http://omniexplorer.info/lookuptx.aspx?txid=441d45d65bcade2a3efa385c1a53da03e8cf48fc3826ef848b9e213ff616434e

**Comment by sh57jbi** [comment]
Hello ,
I want you to understand that I am a Korean so I can not speak English well.
I accidentally send the tokens to BTC (Bitcoin). You can also redo the procedure to the original position.
thank you!

**Comment by dexX7** [comment]
Unfortunately Bitcoin and Omni transactions can't be reversed.

Please contact the upbit.com support for help. They might be able to retrieve the tokens.

**Comment by sh57jbi** [comment]
Is not it supposed to return it to my original binnance account 1FkVU72tvWg1GPjkWxGmCLxrbT6JneAQjb ?

업비트 나의 계좌에서 받지 못하다면  원래 위치인 바이낸스 나의 계좌로 되돌려 놓아야 하는것이 정상적인 거래가 아닌가요?

**Comment by dexX7** [comment]
No, generally transactions can't be reversed, whether it's an Omni transaction or a Bitcoin transaction.

Did you talk to upbit.com already?

**Comment by sh57jbi** [comment]
I have already sent mail to upbit.com, but I do not have an answer yet 
But upbit.com says it does not trade USDT .
Can I get another COIN to my account at upbit.com or binance.com? Or can you send me my BTC Wallet (btc.com) account, 3CVYuqZ8A793xPKmeZZQo3Ba6eDbkH1mYK?

help me

**Comment by dexX7** [comment]
If they don't help to retrieve your tokens, there is nothing we can do. :(

**Comment by sh57jbi** [comment]
" your tokens" I do not know what it means. Please give detailed explanation

**Comment by sh57jbi** [comment]
I hope that the money(coin) that I can not find is like my life line as my whole life.
내가 찾지 못하고 있는 돈은 나의 전재산으로 우리집 생명줄과 같은 것으로 제발 찾아주길 바랍니다.

Thank you!

**Comment by dexX7** [comment]
Hi there, what I mean: we can not help you. You need to convince upbit.com to help. :(

**Comment by sh57jbi** [comment]
I do not understand. How can I help me on upbit.com if my money is on your
company https://omniexplorer.info? Can I return my money at your company
https://omniexplorer.info to my original location https://www.binance.com/
my account 1FkVU72tvWg1GPjkWxGmCLxrbT6JneAQjb?

2018-02-14 1:34 GMT+09:00 dexX7 <notifications@github.com>:

**Comment by sh57jbi** [comment]
If you can help me at upbit.com, please let me know specifically how you
can help me

2018-02-14 9:44 GMT+09:00 byoung ig Jung <sh57jbi@gmail.com>:

**Comment by dexX7** [comment]
The money is not in our company! It's in upbit.com.

**Comment by sh57jbi** [comment]
I do not understand.
Deposit 0.00000540 BTC
129 KRW

Payment completed
Transaction ID
441d45d65bcade2a3efa385c1a53da03e8cf48fc3826ef848b9e213ff616434e 2018.01.10
08:51
Deposit 0.00000540 BTC
128 KRW

Payment completed
Transaction ID
072eaabd98db8efd059be4cbc728edf9de2f96f0e63f626a3323d12d58c1c711 2018.01.10
08:26
I do not understand why you are on upbit.com for some reason though I did
not make a deposit

2018-02-14 15:47 GMT+09:00 dexX7 <notifications@github.com>:

**Comment by dexX7** [comment]
@sh57jbi: the Omni Layer protocol embeds payloads into regular Bitcoin transactions. The transactions can not be reversed. Omni Layer transactions are only visible with omniexplorer.info and regular Bitcoin explorers do not show token movements. You sent tokens to upbit.com. We can not help you. upbit.com now has the tokens. We can not redo the transaction.

**Comment by sh57jbi** [comment]
Is it impossible to recover if USDT is misplaced as the upbit.com bit coin
address and is in urgent need?

2018-02-14 23:00 GMT+09:00 dexX7 <notifications@github.com>:

**Comment by dexX7** [comment]
The only ones that can help you are upbit.com.

**Comment by sh57jbi** [comment]
I can not recover from upbit.com. Please tell me how to recover it.

2018-02-28 0:28 GMT+09:00 dexX7 <notifications@github.com>:

**Comment by dexX7** [comment]
If they don't help: you can't. :(

**Comment by dexX7** [comment]
I added a wiki page about this topic. Please let me know, if there is still anything unclear:

- [FAQ: I sent tokens to an incompatible wallet such as Coinbase or GDAX. Can you reverse the transaction?](https://github.com/OmniLayer/omnicore/wiki/I-sent-tokens-to-an-incompatible-wallet-such-as-Coinbase-or-GDAX.-Can-you-reverse-the-transaction%3F)

Please also feel free to reopen this issue, if there is any progress. We'd also love to hear, if you were able to retrieve the tokens!
