### ISSUE TITLE
Missing USDT, Status: Invalid

### ISSUE THREAD

**Issue by nthung2002** [OmniLayer/omnicore#546]
Dear all, 

I stranfered 1000 USDT from 
Sender | 15Vxzho3ww1tF8MGk2XDCTxGfNRQSVr1Uh
to 
Recipient | 1Po1oWkD2LmodfkBYiAktwh76vkF93LKnh

Token | TetherUS (#31)

Here is my Transaction ID
https://omniexplorer.info/lookuptx.aspx?txid=2abddad5cf83f2a8d57a1f1f452b5c4e84315322cd7ba4edcaf725f06d9e34ea

Now the Status | INVALID, I didn't recived 1000 USDT in my wallet, 
Checking detail at: Raw Omni Data is Missing parameters.

Can you check and approve to transfer 1000 USDT to my recieve wallet and you refund to my Sneder wallet please.

Thank you so much
nthung2002

**Comment by dexX7** [comment]
Hi there,

the transaction failed, because 15Vxzho3ww1tF8MGk2XDCTxGfNRQSVr1Uh doesn't have enough balance. To me it looks like this was an internal transfer of Poloniex. Are you a Poloniex team member?

**Comment by dexX7** [comment]
I just noticed: there was another valid transaction transferring 1000 USDT right before the invalid one:

https://omniexplorer.info/lookuptx.aspx?txid=dbff8cf7e495a129c6821c2c7e1ef25ee9b4ece9ede6bf9deb462ab82872f9ea

**Comment by nthung2002** [comment]
Dear Github support,

I am not from Poloniex, I am the user of Poloniex and Bittrex.

On December 12th 2017, I had 3 transactions as below:

Bittrex USDT Wallet: 1K29EovsXD5fEKsi8nzpBT6QJTQ67KCgHU
Amount 16,422.9900 USDT - Request date 12/12/2017 14:54:39
Detail: : 452738452c11e29bcb16ee6ef2c37ea6e3827746b36a2c64175f2312d95ef78c
..................................................
Bittrex USDT Wallet 1K29EovsXD5fEKsi8nzpBT6QJTQ67KCgHU
Amount:  1,000.0000 USDT - Request date 12/12/2017 13:31:42
Detail:  1d3e21a91b5870022edfea1ca7ec832fe40218cd92541cd3a14f4c9ea07154e3
.....................................................
Poloniex USDT Wallet: 15Vxzho3ww1tF8MGk2XDCTxGfNRQSVr1Uh
Amount 1,000.0000 USDT - Request date: 12/12/2017 07:28:56
Detail: 5c269b203ef5b8ad7a89103a1761e0dd6c92a1610451bc6b0016e857597b5c7e

I transfered to Poloniex first, but it was unsuccessful, so I tried to send 1000 USDT to Bittrex first, then it was successful, so I continued to transfer the rest of my USDT 16,422,99 USDT to Bitrex for trading.

I sent an email to Poloniex support on Dec 12th 2017, but till now they didn't answer.

Please check it carefully and proceed my transaction.

Thank you
Nguyen Thanh Hung

**Comment by nthung2002** [comment]
Dear Github support,

I am not from Poloniex, I am the user of Poloniex and Bittrex. I reorder the transaction base on the time: 07:28:56, 13:31:42 and  14:54:39

On December 12th 2017, I had 3 transactions as below:

Poloniex USDT Wallet: 15Vxzho3ww1tF8MGk2XDCTxGfNRQSVr1Uh
Amount 1,000.0000 USDT - Request date: 12/12/2017 07:28:56
Detail: 5c269b203ef5b8ad7a89103a1761e0dd6c92a1610451bc6b0016e857597b5c7e
..................................................
Bittrex USDT Wallet 1K29EovsXD5fEKsi8nzpBT6QJTQ67KCgHU
Amount: 1,000.0000 USDT - Request date 12/12/2017 13:31:42
Detail: 1d3e21a91b5870022edfea1ca7ec832fe40218cd92541cd3a14f4c9ea07154e3
.....................................................
Bittrex USDT Wallet: 1K29EovsXD5fEKsi8nzpBT6QJTQ67KCgHU
Amount 16,422.9900 USDT - Request date 12/12/2017 14:54:39
Detail: : 452738452c11e29bcb16ee6ef2c37ea6e3827746b36a2c64175f2312d95ef78c
..................................................
I transfered to Poloniex first, but it was unsuccessful, so I tried to send 1000 USDT to Bittrex first, then it was successful, so I continued to transfer the rest of my USDT 16,422,99 USDT to Bitrex for trading.

I sent an email to Poloniex support on Dec 12th 2017, but till now they didn't answer.

Please check it carefully and proceed my transaction.

Thank you
Nguyen Thanh Hung

**Comment by dexX7** [comment]
Hi @nthung2002, unfortunately there is nothing we can do as developers. :( However, given that Bittrex and Poloniex list Omni Layer tokens, they can help you to retrieve the tokens, if/when the right person sees your ticket. I wish you best luck!

**Comment by dexX7** [comment]
I added a wiki page, which may be relevant to this topic. Please let me know, if there is still anything unclear:

- [FAQ: I sent tokens to an incompatible wallet such as Coinbase or GDAX. Can you reverse the transaction?](https://github.com/OmniLayer/omnicore/wiki/I-sent-tokens-to-an-incompatible-wallet-such-as-Coinbase-or-GDAX.-Can-you-reverse-the-transaction%3F)

Please also feel free to reopen this issue, if there is any progress. We'd also love to hear, if you were able to retrieve the tokens!

**Comment by fernandoyo** [comment]
Hi, I'm experimenting with omnicore-cli.

First I sent 120 USDT to my local wallet.
Then, from my local I sent 2.1 USDT to another wallet "1KAsHQ2..."

https://omniexplorer.info/tx/21c3354ab4422faca43761826884bb4398871a2c404a2fff71be91c9502d3ba0


It worked without any flaw, the problem happened when I sent 2.1 USDT from this new wallet to Bittrex again. First I did not pay attention and my first mistake happened, while doing the omni_createrawtx_change  command I entered bittrex address as change address instead of mine. Ok, that's is my mistake, but I did not understood why the transaction is invalid.
https://omniexplorer.info/tx/7c9a358a100af28c6cdd50bb66899a0c2eb4299dcdd419829fef1680c0b69710
https://blockchain.info/tx/7c9a358a100af28c6cdd50bb66899a0c2eb4299dcdd419829fef1680c0b69710

I knew that the balance on my USDT wallet was low, so I used inputs from another address 1EdRgYUgbfjMbnQtfeFaRRVooi8fSwpCwu

I think it is invalid transaction because the omnilayer considered that "1EdRgY-address" sent the USDT without balance. It should have been sent from the "1KAsHQ2..." wallet...

My question is, did the problem happened because while doing "createrawtransaction" I first entered the txid inputs from the wallet that had no USDT?

./omnicore-cli "createrawtransaction" '[{"txid":"e57e8693be37deded83a2228374cfb1206258d57e7bca718ce0d41dad292956f","vout":0},{"txid":"21c3354ab4422faca43761826884bb4398871a2c404a2fff71be91c9502d3ba0","vout":1}]' '{}'

This inputs were used:
[
  {
    "txid": "e57e8693be37deded83a2228374cfb1206258d57e7bca718ce0d41dad292956f",
    "vout": 0,
    "address": "1EdRgYUgbfjMbnQtfeFaRRVooi8fSwpCwu",
    "account": "btcteste",
    "scriptPubKey": "76a914957d368eeb963742d4b53c7248b3a5f59dcd5c3488ac",
    "amount": 0.00010000,
    "confirmations": 320,
    "spendable": true,
    "solvable": true
  }, 
  {
    "txid": "21c3354ab4422faca43761826884bb4398871a2c404a2fff71be91c9502d3ba0",
    "vout": 1,
    "address": "1KAsHQ2z9HLq6BY1CUiCuKv1CFbQakobGf",
    "account": "",
    "scriptPubKey": "76a914c74ffb4dcfe95fb591e0800b8709a327988a148c88ac",
    "amount": 0.00000546,
    "confirmations": 148,
    "spendable": true,
    "solvable": true
  }
]

**Comment by dexX7** [comment]
Hi @fernandoyo,

thanks for asking. So just to clarify:

The "sender" of an Omni Layer transaction is determined based on the first transaction input. The other ones can be from different sources. E.g.:

```
vin[0] = 1EdRgYUgbfjMbnQtfeFaRRVooi8fSwpCwu << sender
vin[1] = 1KAsHQ2z9HLq6BY1CUiCuKv1CFbQakobGf
```

The recipient is based on the last output. If the last output then is from the sender, it's skipped once. If the next potential output is also from the sender, the recipient is also the sender. Some examples:

Normal case where the recipient simply has the last output:
```
sender = 1KAsHQ2z9HLq6BY1CUiCuKv1CFbQakobGf

vout[0] = payload
vout[1] = 1KAsHQ2z9HLq6BY1CUiCuKv1CFbQakobGf
vout[2] = 17ozxkNUuJxP9rh5AN8Zmm867LG8oYRWoH
vout[3] = 1EdRgYUgbfjMbnQtfeFaRRVooi8fSwpCwu < recipient
```

Case where the change is at the last position, but the recipient is still 1EdR:
```
sender = 1KAsHQ2z9HLq6BY1CUiCuKv1CFbQakobGf

vout[0] = payload
vout[1] = 17ozxkNUuJxP9rh5AN8Zmm867LG8oYRWoH
vout[2] = 1EdRgYUgbfjMbnQtfeFaRRVooi8fSwpCwu < recipient
vout[3] = 1KAsHQ2z9HLq6BY1CUiCuKv1CFbQakobGf < skipped once, because sender
```

Case where the recipient is also the sender:
```
sender = 1KAsHQ2z9HLq6BY1CUiCuKv1CFbQakobGf

vout[0] = payload
vout[1] = 17ozxkNUuJxP9rh5AN8Zmm867LG8oYRWoH
vout[2] = 1EdRgYUgbfjMbnQtfeFaRRVooi8fSwpCwu < recipient
vout[3] = 1KAsHQ2z9HLq6BY1CUiCuKv1CFbQakobGf < skipped once, because sender
```
