### ISSUE TITLE
How can I show balance in each currency (propertyid)?

### ISSUE THREAD

**Issue by khaitranvan96kt** [OmniLayer/omnicore#547]

**Comment by dexX7** [comment]
Check out the [omni_getbalanceforid](https://github.com/OmniLayer/omnicore/blob/master/src/omnicore/doc/rpc-api.md#omni_getallbalancesforid) RPC.

**Comment by khaitranvan96kt** [comment]
![selection_010](https://user-images.githubusercontent.com/26017496/35399273-76c53af4-0226-11e8-88fb-8ea068ad31f3.png)
Why? I have tried but it's failed?

**Comment by dexX7** [comment]
Does this address have any balance?

**Comment by khaitranvan96kt** [comment]
I'm using regtest=1.

**Comment by dexX7** [comment]
Alright. In this case do the following to get started:

1. Create a new address with `getnewaddress` (or via GUI)
2. Send some Bitcoin to the new address
3. Use the coin selection to select coins of that address and send some to `moneyqMan7uh8FqdCA2BV5yZ8qVrc9ikLP`

After mining a block `omni_getbalanceforid 1` should show some Omni balance.

You might skip this, and after moving some Bitcoin to a new address, you could create new tokens with [omni_sendissuancefixed](https://github.com/OmniLayer/omnicore/blob/master/src/omnicore/doc/rpc-api.md#omni_sendissuancefixed) or [omni_sendissuancemanaged](https://github.com/OmniLayer/omnicore/blob/master/src/omnicore/doc/rpc-api.md#omni_sendissuancemanaged).

If it doesn't work as expected, check out the `omnicore.log`, but of course, feel free to get back to me. :)

**Comment by khaitranvan96kt** [comment]
I did it! Thank you for your enthusiastic help.

**Comment by nitsx2** [comment]
Hey dex, I have some queries regarding omnicore and tether.   How can i differentiate the currencies in my omnicore cli ??

**Comment by dexX7** [comment]
Hi @nitsx2, can you please elaborate the question?
