### ISSUE TITLE
Set fees in Omnicore?

### ISSUE THREAD

**Issue by khaitranvan96kt** [OmniLayer/omnicore#548]
I want to use omnicore to also provide wallet services for my clients. How do I set up my system for free and mining fee a buyer for each transaction?

**Comment by dexX7** [comment]
Hi there,

you can set a fixed fee with the configuration option `-paytxfee=n.nnnnnnnn` or you could use `-txconfirmtarget=n` to use a dynamic fee.

**Comment by dexX7** [comment]
Please feel free to reopen this issue or create a new one, if you have another question.

**Comment by trusblock** [comment]
Now can use the `estimatefee` RPC get dynamical fee.

**Comment by dmitryrn** [comment]
@dexX7 so to calculate fee we need to use `estimatefee` or `estimatesmartfee`? In this [guide](https://github.com/OmniLayer/omnicore/wiki/Use-the-raw-transaction-API-to-create-a-Simple-Send-transaction) you set your own fee, not calculate them.
