### ISSUE TITLE
maxconnections works?

### ISSUE THREAD

**Issue by kiahmed** [OmniLayer/omnicore#550]
I was wondering if maxconnections feature works in linux build? I mentioned -maxconnections=20 in the conf file, but looks like the dameon ignores it and created 621 connections which is insane causing much more unnecessary load and server slow.

**Comment by dexX7** [comment]
Wow this is really a lot.

Are all of these 621 connections active? You could check this by using the RPC `getconnectioncount` or `getpeerinfo`.

**Comment by kiahmed** [comment]
ya ..but why it did despite the fact i tried to keep it under 20?

**Comment by congnghiakhiem** [comment]
How can you have many peers ? I can not find out to make more than 8 peers.

**Comment by kiahmed** [comment]
gotta have firewall open

**Comment by congnghiakhiem** [comment]
Can you explain more ? I need to open port 8333 or anything else ?

**Comment by dexX7** [comment]
Hi @kiahmed, were you able to resolve this issue?

If not, you may open an issue upstream: https://github.com/bitcoin/bitcoin/issues
