### ISSUE TITLE
President Coin Withdrawal Issue

### ISSUE THREAD

**Issue by sarnergis1** [OmniLayer/omnicore#551]
Hi,

I sent president trump coin from my c-cex account to livecoin account yesterday. but c-cex is warned me and it said ''we did not create a wallet we create a manually dont worry abt it, we are gonna send ur coins but just wait for it. If we wouldnt send ur coins u gonna take back''

after that i decided to wait for my coin but i couldnt see anything on my both balance. and im wondering abt my wallet. 

i guess u make the transactions so would you like to solve this problem or give me some informations abt it?

im looking forward to hearing from you..

thx a lot from now

have a nice day.

**Comment by dexX7** [comment]
Hey there,

you can check the balance of a wallet on www.omniexplorer.info.

**Comment by dexX7** [comment]
I added a wiki page, which may be relevant to this topic. Please let me know, if there is still anything unclear:

- [FAQ: I sent tokens to an incompatible wallet such as Coinbase or GDAX. Can you reverse the transaction?](https://github.com/OmniLayer/omnicore/wiki/I-sent-tokens-to-an-incompatible-wallet-such-as-Coinbase-or-GDAX.-Can-you-reverse-the-transaction%3F)

Please also feel free to reopen this issue, if there is any progress. We'd also love to hear, if you were able to retrieve the tokens!
