### ISSUE TITLE
Cant locate funds

### ISSUE THREAD

**Issue by JV** [OmniLayer/omnicore#552]
Hi,

I have apparently sent some funds to an address, but I cant locate the funds anywhere. What can I do to locate the funds?

Regards
JV

**Comment by JV** [comment]
I have managed to backtrace my steps and know what I tried doing and I did it all in the right way, the problem is the funds never came to the address.

So what do I do now?

**Comment by dexX7** [comment]
Hey there, can you post what you did?

**Comment by JV** [comment]
I tried sending the funds to my wallet/exchange wallet, I honestly cant remember which one at this moment.
________________________________

**Comment by JV** [comment]
0x9860a27c06fe56e379def134745b263ced0187f7e7871c365b96776eab47822c 

This is what I did but it never came to the wallet

And this is another one that is also not done even tho it clearly says failed.
0x936da899d8f81cf96f7e5f6eec8129fee08bbd7b772a4d895ddc73c2cdeb30c5

**Comment by dexX7** [comment]
@JV: looks like you're at the wrong project. These transactions are no Bitcoin or Omni Layer transactions, but look like ETH ones:

https://etherscan.io/tx/0x9860a27c06fe56e379def134745b263ced0187f7e7871c365b96776eab47822c
https://etherscan.io/tx/0x936da899d8f81cf96f7e5f6eec8129fee08bbd7b772a4d895ddc73c2cdeb30c5

**Comment by JV** [comment]
Ah, thank you for all your help and pointing me the right way.

Best regards,

JV

On Feb 15, 2018 10:46, dexX7 <notifications@github.com> wrote:

@JV<https://github.com/jv>: looks like you're at the wrong project. These transactions are no Bitcoin or Omni Layer transactions, but look like ETH ones:

https://etherscan.io/tx/0x9860a27c06fe56e379def134745b263ced0187f7e7871c365b96776eab47822c
https://etherscan.io/tx/0x936da899d8f81cf96f7e5f6eec8129fee08bbd7b772a4d895ddc73c2cdeb30c5

**Comment by dexX7** [comment]
You're welcome! Hope you resolve your issue.

Cheers
