### ISSUE TITLE
How to change rpc bind address?

### ISSUE THREAD

**Issue by zhag** [OmniLayer/omnicore#553]
Hello here!

I want to bind rpc on my em0 interface instead 127.0.0.1

When I try to use 'rpcconnect=' in config file bind address are 127.0.0.1

How can I change bind address to 0.0.0.0 or my public ipv4?

**Comment by dexX7** [comment]
Hey there,

does https://github.com/bitcoin/bitcoin/issues/8502#issuecomment-239621457 help you to resolve this issue?

**Comment by dexX7** [comment]
Please feel free to reopen this issue or create a new one, if you have another question.
