### ISSUE TITLE
OmniClientJS returns Error: connect ECONNREFUSED 127.0.0.1:18332

### ISSUE THREAD

**Issue by torpedko** [OmniLayer/omnicore#554]
I try to  OmniTests.js on my local machine but it returns an error: 
{ Error: connect ECONNREFUSED 127.0.0.1:18332
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 18332 }

How can I solve it?

**Comment by dexX7** [comment]
@msgilligan: any ideas?

**Comment by dexX7** [comment]
Please feel free to reopen this issue, if there is new input.
