### ISSUE TITLE
lost transaction during exchange

### ISSUE THREAD

**Issue by obioma76** [OmniLayer/omnicore#555]
please during the course of exchange from my USDT 16bUGjvunVp7LqygLHrTvHyvbvfeuRCWAh  wallet to BTC 18o14JEgZNoMFJovbjXy2a5PqpYaeJPK9u  it was stated that the $216 transaction failed but was reducted from my USDT wallet account. please kindly look forward to solving my problem as soon as possible it has been to 3 to 4 days now since this event.
                                            

Status: | Failed
-- | --
Date: | 15 Feb 2018 20:07
Recipient’s address: | 23mS43GhM8y7XW4dJpYKYA45cmburno8Cg4ure5og2ZXLLEwA84uXupKA32X5SrJuDPBgXTsSmQRoAbCzcDvM2d2Pa6GYSi
Amount: | 216 USDT
Fee: | 0.6 USDT
Arrival amount: | 0 BCN
Balance before: | 0.86085069 USDT
Balance after: | 0.86085069 USDT
Hash: | 1729f83a1c52e506991f85cb3a067feb8579c321049f801d3615a0bd25f0538e

**Comment by dexX7** [comment]
The transaction is valid and 216 USDT were sent to 18o14JEgZNoMFJovbjXy2a5PqpYaeJPK9u:

http://omniexplorer.info/lookuptx.aspx?txid=1729f83a1c52e506991f85cb3a067feb8579c321049f801d3615a0bd25f0538e

However, from there, there was an outgoing transaction sending USDT to 1Gc3biG5hsHAoj4ZNAtnT4sCBbtF9sKEEL:

http://omniexplorer.info/lookuptx.aspx?txid=a3dfb5ad80ea92f1d5d622f7089854ff19aa718e8a42ecdf9f0e196d06c5cdc6

Which wallet or service provider do you use? Did you reach out to their support?

There is nothing we can do besides guiding you or the other party.

**Comment by obioma76** [comment]
Yes sir I did but I was referred back to you.. According to them there was
when I get to you everything will be resolved. The said the problem was
from omniLayer. Is there any way out because right now I'm confused don't
know what to do. Please sir still try to  help me. Thank you very much. I
really do appreciate

On Feb 20, 2018 9:32 AM, "dexX7" <notifications@github.com> wrote:

The transaction is valid and 216 USDT were sent to
18o14JEgZNoMFJovbjXy2a5PqpYaeJPK9u:

http://omniexplorer.info/lookuptx.aspx?txid=1729f83a1c52e506991f85cb3a067f
eb8579c321049f801d3615a0bd25f0538e

However, from there, there was an outgoing transaction sending USDT to
1Gc3biG5hsHAoj4ZNAtnT4sCBbtF9sKEEL:

http://omniexplorer.info/lookuptx.aspx?txid=a3dfb5ad80ea92f1d5d622f7089854
ff19aa718e8a42ecdf9f0e196d06c5cdc6

Which wallet or service provider do you use? Did you reach out to their
support?

There is nothing we can do besides guiding you or the other party.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/OmniLayer/omnicore/issues/555#issuecomment-366919527>,
or mute the thread

**Comment by dexX7** [comment]
Can you get me a contact, where I could reach out to them? Please send this information with a reference to this issue to feedback@omni.foundation.

**Comment by dexX7** [comment]
I added a wiki page about this topic. Please let me know, if there is still anything unclear:

- [FAQ: I sent tokens to an incompatible wallet such as Coinbase or GDAX. Can you reverse the transaction?](https://github.com/OmniLayer/omnicore/wiki/I-sent-tokens-to-an-incompatible-wallet-such-as-Coinbase-or-GDAX.-Can-you-reverse-the-transaction%3F)

Please also feel free to reopen this issue, if there is any progress. We'd also love to hear, if you were able to retrieve the tokens!

**Comment by obioma761** [comment]
hello good day im the person you were chatting with regarding the lost of 216 usdt during exchange obioma76 sorry i was away quite some time i just returned to the site i noticed you closed our conversation, on the march 19  this was my transactions whivh were lost. please sir help me.




Status: Failed
 Date: 15 Feb 2018 20:07
 Recipient’s address: 23mS43GhM8y7XW4dJpYKYA45cmburno8Cg4ure5og2ZXLLEwA84uXupKA32X5SrJuDPBgXTsSmQRoAbCzcDvM2d2Pa6GYSi
 Amount: 216 USDT
 Fee: 0.6 USDT
 Arrival amount: 0 BCN
 Balance before: 0.86085069 USDT
 Balance after: 0.86085069 USDT
 Hash: 1729f83a1c52e506991f85cb3a067feb8579c321049f801d3615a0bd25f0538e

**Comment by obioma761** [comment]
i used free wallet for the transaction an i contacted there support team they said they can do nothing about it please can you help me

**Comment by obioma761** [comment]
Status: | Failed
-- | --
Date: | 15 Feb 2018 20:07
Recipient’s address: | 23mS43GhM8y7XW4dJpYKYA45cmburno8Cg4ure5og2ZXLLEwA84uXupKA32X5SrJuDPBgXTsSmQRoAbCzcDvM2d2Pa6GYSi
Amount: | 216 USDT
Fee: | 0.6 USDT
Arrival amount: | 0 BCN
Balance before: | 0.86085069 USDT
Balance after: | 0.86085069 USDT
Hash: | 1729f83a1c52e506991f85cb3a067feb8579c321049f801d3615a0bd25f0538e
Request id: | 48c35334-5f00-3fea-072f-15e0c473e67c

**Comment by dexX7** [comment]
> i used free wallet for the transaction an i contacted there support team they said they can do nothing about it please can you help me

Unfortunately we can't do anything here. Only the one who has the private keys can do something.

Please see this:

https://github.com/OmniLayer/omnicore/wiki/I-sent-tokens-to-an-incompatible-wallet-such-as-Coinbase-or-GDAX.-Can-you-reverse-the-transaction%3F
