### ISSUE TITLE
omni_getallbalancesforid return many values of addresses

### ISSUE THREAD

**Issue by congnghiakhiem** [OmniLayer/omnicore#556]
I try to use omni_getallbalancesforid to get balance of a property. But this command return many values of addresses which don't belong to my own wallet. Which command can do this for me ?

**Comment by dexX7** [comment]
You can use [omni_getbalance](https://github.com/OmniLayer/omnicore/blob/master/src/omnicore/doc/rpc-api.md#omni_getbalance) or [omni_getallbalancesforaddress](https://github.com/OmniLayer/omnicore/blob/master/src/omnicore/doc/rpc-api.md#omni_getallbalancesforaddress).

**Comment by congnghiakhiem** [comment]
omni_getbalance and omni_getallbalancesforaddress only show balance of a specified address. I want to get balance of all addresses in my wallet for each property.

**Comment by dexX7** [comment]
Ah, I see. I fear you'd have to use one of these calls and iterate over all wallet addresses.

**Comment by dexX7** [comment]
Please feel free to reopen this issue or create a new one, if you have another question.

**Comment by hrustbb2** [comment]
error code: -32601
error message:
Method not found

**Comment by dexX7** [comment]
Hi @hrustbb2, are you sure you are running Omni Core and not Bitcoin Core?

Can you please post the result of:

```
./omnicore-cli help
```
