### ISSUE TITLE
 I do not have access to my funds

### ISSUE THREAD

**Issue by 721121** [OmniLayer/omnicore#557]
how can I access my money that I send and arrive at your address by mistake
reference>8ee25b9c30d67279c77ece638732a39daa75980ee20c72408ddf21709b434bfc
Record
DepositsReturn Export the complete history of withdrawals
State CurrencyQuantity Date Information
Completed USDT258.16657335 2018-02-18 07:08:15
Address: 1uXSDsn7wLHcFxPgB9w434nzxDz2fi2Tb
Txid: 8ee25b9c30d67279c77ece638732a39daa75980ee20c72408ddf21709b434bfc
1uXSDsn7wLHcFxPgB9w434nzxDz2fi2Tb
This address was first seen 2/18/2018 3:50:32 PM
Balances
ID Name Reserved Balance Available Balance
- Bitcoin - 0.00000546
1 Omni 0 0
31 TetherUS 0.00 258.16657335

**Comment by dexX7** [comment]
Hi there,

do you know where you send the money to? Unfortunately there is nothing we can do, because Bitcoin and Omni Layer transactions are non-reversible. The receiver needs to use an Omni-aware wallet to interact with the tokens.

**Comment by dexX7** [comment]
I added a wiki page about this topic. Please let me know, if there is still anything unclear:

- [FAQ: I sent tokens to an incompatible wallet such as Coinbase or GDAX. Can you reverse the transaction?](https://github.com/OmniLayer/omnicore/wiki/I-sent-tokens-to-an-incompatible-wallet-such-as-Coinbase-or-GDAX.-Can-you-reverse-the-transaction%3F)

Please also feel free to reopen this issue, if there is any progress. We'd also love to hear, if you were able to retrieve the tokens!
