### ISSUE TITLE
Accidentally deposited USDT in BTC address in binance

### ISSUE THREAD

**Issue by rs12002** [OmniLayer/omnicore#559]
I accidentally deposited $1440.39845726 USDT in BTC address in binance due to which my money got lost in between and couldn't transfer it to BTC.Instead of selling BTC i chosen wrong option of depositing USDT balance to BTC address.My transaction id is 8b638c070a3dd14cdcaec0fdc3bb2a20c28baa696df77788ccb47da4d7112bc6.

Kindly refund my amount to USDT if it is blocked.

**Comment by 721121** [comment]
hello exactly the same happened to me and all binance Gdax coinbase our money is in terher US theproblemaes as we return it to our addresses Eduardo

**Comment by dexX7** [comment]
Hey guys,

you need an Omni aware wallet to interact with USDT.

Please contact the support of Binance and Coinbase, because these are the parties that are currently in control of the tokens. There is unfortunately no way to reverse the transactions.

**Comment by dexX7** [comment]
I added a wiki page about this topic. Please let me know, if there is still anything unclear:

- [FAQ: I sent tokens to an incompatible wallet such as Coinbase or GDAX. Can you reverse the transaction?](https://github.com/OmniLayer/omnicore/wiki/I-sent-tokens-to-an-incompatible-wallet-such-as-Coinbase-or-GDAX.-Can-you-reverse-the-transaction%3F)

Please also feel free to reopen this issue, if there is any progress. We'd also love to hear, if you were able to retrieve the tokens!

**Comment by mike1484** [comment]
Have you have been scammed of bitcoin?

Have you ever transfer to a wrong account?

Have you ever lost the drive to access your bitcoin account ?

Have you ever forgot the password to your bitcoin account?

Have you ever trade with fake mining site?

I have a Bitcoin Recovery Specialist, You can reach him on

TELEGRAM: @MiguelAntonio01 or https://t.me/MiguelAntonio01 +1 859 567 9005
