### ISSUE TITLE
Accidentally deposited USDT in BTC address in binance  

### ISSUE THREAD

**Issue by 721121** [OmniLayer/omnicore#560]
and now my money appears in tetherUS(#31)  I do not know how to recover my money, someone could please explain my steps to recover my money

**Comment by dexX7** [comment]
Hi there,

where did you send the USDT to?

**Comment by 721121** [comment]
My btc address

**Comment by dexX7** [comment]
If you control the private key to that destination, you can import it into omniwallet.org.

**Comment by dexX7** [comment]
I added a wiki page about this topic. Please let me know, if there is still anything unclear:

- [FAQ: I sent tokens to an incompatible wallet such as Coinbase or GDAX. Can you reverse the transaction?](https://github.com/OmniLayer/omnicore/wiki/I-sent-tokens-to-an-incompatible-wallet-such-as-Coinbase-or-GDAX.-Can-you-reverse-the-transaction%3F)

Please also feel free to reopen this issue, if there is any progress. We'd also love to hear, if you were able to retrieve the tokens!
