### ISSUE TITLE
10,000 Maid safe token lost due to sender have insufficient fund, the transaction stuck in the blockchain. What to do next?

### ISSUE THREAD

**Issue by JingDie** [OmniLayer/omnicore#561]
Dear community, please help as my 10,000 maidsafe token stuck in the blockchain. Attached the info for reference.
"txid":"890ed28aa71597a425446f4de217f80f66ab4ecd107470734515779b85f31d5f",
"fee":"0.00067500",
"sendingaddress":"1FPk7EdLc26mXYLnC7RiufnrkxSysRjhYr",
"referenceaddress":"1Nom3xADaomSQmVoNvJAnQy6yEEdZqbgRT",
"ismine":false,"version":0,"typeint":0,"type":"Simple Send","propertyid":3,"divisible":false,"amount":"10000","valid":false,"invalidreason":"Sender has insufficient balance","blockhash":"00000000000000000035fc6334630091c9b58acd624556cb4b4a5e94af908fd4","blocktime":1518799106,"positioninblock":154,"block":509475,"confirmations":3

thank you

**Comment by dexX7** [comment]
Hi there,

the transaction is invalid, because 1FPk7EdLc26mXYLnC7RiufnrkxSysRjhYr tried to send 10000 Maid, but currently only has a balance of 24 Maid.

**Comment by Adbastos** [comment]
how to recover
Address: | 1Miv9SMrssWNbJqkPC2TKxRk5Wq1zG2h3t
-- | --
5bfd19a19069c0dbe0705a42c77488b55d0cb4eaada9122b65da24464047fc11

**Comment by JingDie** [comment]
Hi there...
But my 10,000 maidsafe gone... Not returned to my address... Where to trace back? I use coin payments wallet

**Comment by JingDie** [comment]
I contacted coin payments.. They told me the transaction already broadcast to the blockchain... Need to wait for confirmation. But I found out the same thing too.. The transaction is invalid.

**Comment by dexX7** [comment]
I added a wiki page, which may be relevant to this topic. Please let me know, if there is still anything unclear:

- [FAQ: I sent tokens to an incompatible wallet such as Coinbase or GDAX. Can you reverse the transaction?](https://github.com/OmniLayer/omnicore/wiki/I-sent-tokens-to-an-incompatible-wallet-such-as-Coinbase-or-GDAX.-Can-you-reverse-the-transaction%3F)

Please also feel free to reopen this issue, if there is any progress. We'd also love to hear, if you were able to retrieve the tokens!

**Comment by Adbastos** [comment]
On 20 02 2018 I sent a deposit of 98 usd to the huobi brokerage company, only the value is stopped, blocked in ommi, as proof, would you like to know if it is possible to send to Binance?

**Comment by dexX7** [comment]
Hi @Adbastos, please reach out to the Huobi support. They may help!
