### ISSUE TITLE
how to recover usdt stuck in block

### ISSUE THREAD

**Issue by Adbastos** [OmniLayer/omnicore#562]
I'm 98 usdt stuck on the block 1 month and would like to know how to recover?

Address: | 1Miv9SMrssWNbJqkPC2TKxRk5Wq1zG2h3t
-- | --
5bfd19a19069c0dbe0705a42c77488b55d0cb4eaada9122b65da24464047fc11

**Comment by dexX7** [comment]
Hey there, the transaction has over 2000 confirmations and 1Miv9SMrssWNbJqkPC2TKxRk5Wq1zG2h3t now holds the tokens. Please note though, the receiver needs to use an Omni-aware wallet.

**Comment by dexX7** [comment]
I added a wiki page about this topic. Please let me know, if there is still anything unclear:

- [FAQ: I sent tokens to an incompatible wallet such as Coinbase or GDAX. Can you reverse the transaction?](https://github.com/OmniLayer/omnicore/wiki/I-sent-tokens-to-an-incompatible-wallet-such-as-Coinbase-or-GDAX.-Can-you-reverse-the-transaction%3F)

Please also feel free to reopen this issue, if there is any progress. We'd also love to hear, if you were able to retrieve the tokens!
