### ISSUE TITLE
Accidentally send USDT to BCH address

### ISSUE THREAD

**Issue by Ana8898ndi** [OmniLayer/omnicore#563]
Please recover my USDT 
Accidentally send USDT to BCH address
Txid: 6d359f570bcaa724dc75b311e90efa4cce13f70b777046489b9a93f246e09be8
Send to BCH address- 3HzcLfUjfRZyijVGJbEcpiVyzg5oUWDzXd

My USDT address- 1G1kyqeprmNRD1vjLNxCkTWx6v2VUQ8KF1
Please recover my USDT as soon as possible....help us..
Thanking you

**Comment by dexX7** [comment]
Hi there,
please note, there is no way for us to recover any tokens.

However, if you have the private key of the destination you sent the tokens to, you can import it into www.omniwallet.org. If this is a service, you need to contact their support, which may help you with sending the tokens somewhere else.

**Comment by dexX7** [comment]
I added a wiki page about this topic. Please let me know, if there is still anything unclear:

- [FAQ: I sent tokens to an incompatible wallet such as Coinbase or GDAX. Can you reverse the transaction?](https://github.com/OmniLayer/omnicore/wiki/I-sent-tokens-to-an-incompatible-wallet-such-as-Coinbase-or-GDAX.-Can-you-reverse-the-transaction%3F)

Please also feel free to reopen this issue, if there is any progress. We'd also love to hear, if you were able to retrieve the tokens!
