### ISSUE TITLE
Accidentally send USDT to OMNI address

### ISSUE THREAD

**Issue by Vasyaaaa** [OmniLayer/omnicore#564]
Please recover my USDT
Accidentally send USDT to OMNI address
Txid: a98ec988c6075d79bacfe2ec8b9dbe56b660de86f2d958645843392dd1e207f3
Send to OMNI address- 1HzTwXnKRZ4kFJPJuzereKyrCxhjQu3d8v
My USDT address- 1B7iy98nc3UvTesJgEYEteFWvDFAmn7Chn
Please recover my USDT as soon as possible....help us..
Thanking you

**Comment by dexX7** [comment]
Hey there,

there is nothing we can do about this.

Do you have access to the private key of `1HzTwXnKRZ4kFJPJuzereKyrCxhjQu3d8v`? If so, you can import it into www.omniwallet.org. If not, please contact the service associated with that destination, so they help you.

**Comment by Vasyaaaa** [comment]
And you can convert to OMNI?

**Comment by dexX7** [comment]
No.

**Comment by Vasyaaaa** [comment]
Вот гандоны вы!!!

**Comment by Vasyaaaa** [comment]
Гандоны!!!

**Comment by dexX7** [comment]
There is nothing we can do as developers, but you may be able to help yourself:

1. If you have the private key to the destination, import it into www.omniwallet.org.
2. If you know the service you sent the tokens to, please get in contact with them.

**Comment by Vasyaaaa** [comment]
How to use a private key? How to import?

**Comment by dexX7** [comment]
@Vasyaaaa: do you have the tokens in a wallet or service like Binance?

**Comment by Vasyaaaa** [comment]
No...Coinpaymants...

**Comment by dexX7** [comment]
Alright, please contact Coinpayments then and please note, there is nothing *we* can do as developers, as Coinpayments is now the holder of the tokens, because you sent them to them.

**Comment by dexX7** [comment]
I added a wiki page about this topic. Please let me know, if there is still anything unclear:

- [FAQ: I sent tokens to an incompatible wallet such as Coinbase or GDAX. Can you reverse the transaction?](https://github.com/OmniLayer/omnicore/wiki/I-sent-tokens-to-an-incompatible-wallet-such-as-Coinbase-or-GDAX.-Can-you-reverse-the-transaction%3F)

Please also feel free to reopen this issue, if there is any progress. We'd also love to hear, if you were able to retrieve the tokens!

**Comment by Vasyaaaa** [comment]
All close your question,for the problem solved.
--
Отправлено из Mail.Ru для Android понедельник, 19 марта 2018г., 13:02 +05:00 от dexX7  notifications@github.com :

**Comment by Vasyaaaa** [comment]
All close your question,for the problem solved.
--
Отправлено из Mail.Ru для Android понедельник, 19 марта 2018г., 13:02 +05:00 от dexX7  notifications@github.com :
