### ISSUE TITLE
Problems

### ISSUE THREAD

**Issue by Vasyaaaa** [OmniLayer/omnicore#565]
lease recover my USDT
Accidentally send USDT to OMNI address
Txid: a98ec988c6075d79bacfe2ec8b9dbe56b660de86f2d958645843392dd1e207f3
Send to OMNI address- 1HzTwXnKRZ4kFJPJuzereKyrCxhjQu3d8v
My USDT address- 1B7iy98nc3UvTesJgEYEteFWvDFAmn7Chn

And you can convert to OMNI?And you can convert to OMNI?And you can convert to OMNI?
Send to OMNI address- 1HzTwXnKRZ4kFJPJuzereKyrCxhjQu3d8v

**Comment by dexX7** [comment]
This is a duplicate of #564.
