### ISSUE TITLE
Backup USDT omnicore 

### ISSUE THREAD

**Issue by 97zgxgw** [OmniLayer/omnicore#566]
Hello.
How to backup omnicore when i use USDT?

**Comment by dexX7** [comment]
Hi there, you can backup your wallet.dat file in the Bitcoin datadir.

Which OS do you use?

**Comment by 97zgxgw** [comment]
Ubuntu.
Bitcoin core has special command for safe backup. How do that in Omnicore ?

**Comment by dexX7** [comment]
Omni Core is basically Bitcoin Core with extensions. You can backup Omni Core similar to Bitcoin Core.

**Comment by dexX7** [comment]
Please feel free to reopen this issue, if you have another question.
