### ISSUE TITLE
omni_getallbalancesforaddress failed to get balance of my testnet address

### ISSUE THREAD

**Issue by karokarolee** [OmniLayer/omnicore#573]
Hi dexX7, 
I got a testnet address through omnicore with parameter "-testnet", the address is "mrbyquSZpti7VzFgVwwc4p4trx3sq1geHJ", and get testnet bitcoin from the website "https://testnet.manu.backend.hamburg/faucet", in the GUI of omnicore, my balance is displayed correctly.

but when I use omnicore-cli to call method "omni_getallbalancesforaddress" to get balance of my address "mrbyquSZpti7VzFgVwwc4p4trx3sq1geHJ", console print "error code: -8, address not found".  Is my address invalid for rpc api?

**Comment by karokarolee** [comment]
Oh, I see, it seems that I need to have some omni layer coin in my address firstly.

**Comment by dexX7** [comment]
Correct, the `omni_` balance RPCs only show token balances. :)
