### ISSUE TITLE
Major withdrawal mistake

### ISSUE THREAD

**Issue by JSAG0705** [OmniLayer/omnicore#575]
I accidentally transferred funds from my Binance "Tether" account into my GDAX "Bitcoin" account.

Needless to say the funds are understandably not in my account. What needs to be done on my end or with your assistance to help me either carry over funds to GDAX or reverse transaction?

CoinBase says there is nothing they can do and if I’m correct, Binance will be of little help as well.

I have provide the transaction ID along with the GDAX address and Binace address used as well.

Date/Time: Sun Mar 18 2018 00:12:06 GMT-0500

Transaction ID:
6f75608468f70622c1f3e637fd28ab4f3dcbc5e7e4d877d116712dd0c0f1b841

GDAX Address:
3HbZRGZA1EscfDa52u1USwyphZ2C1kVi7J

Binance Address:
1FoWyxwPXuj4C6abqwhjDWdz6D4PZgYRjA

**Comment by dexX7** [comment]
Hi there,

unfortunately I have bad news: there is nothing we can do and unless Coinbase starts to cooperate, your funds are stuck.

The Omni Layer uses Bitcoin as transport layer and to "see" or interact with tokens, an Omni aware wallet must be used. Coinbase or GDAX don't support the Omni Layer.

There are thousands of USD worth stuck, but there is no case known to me, where they helped to retrieve the tokens. :(

Internally we keep a list with stuck tokens, for the case they ever come around. In this case we are going to contact you.

**Comment by dexX7** [comment]
I added a wiki page about this topic. Please let me know, if there is still anything unclear:

- [FAQ: I sent tokens to an incompatible wallet such as Coinbase or GDAX. Can you reverse the transaction?](https://github.com/OmniLayer/omnicore/wiki/I-sent-tokens-to-an-incompatible-wallet-such-as-Coinbase-or-GDAX.-Can-you-reverse-the-transaction%3F)

Please also feel free to reopen this issue, if there is any progress. We'd also love to hear, if you were able to retrieve the tokens!

**Comment by dexX7** [comment]
I added a wiki page about this topic. Please let me know, if there is still anything unclear:

- [FAQ: I sent tokens to an incompatible wallet such as Coinbase or GDAX. Can you reverse the transaction?](https://github.com/OmniLayer/omnicore/wiki/I-sent-tokens-to-an-incompatible-wallet-such-as-Coinbase-or-GDAX.-Can-you-reverse-the-transaction%3F)

Please also feel free to reopen this issue, if there is any progress. We'd also love to hear, if you were able to retrieve the tokens!
