### ISSUE TITLE
Bitcoind vs Omnicoind simultaneously

### ISSUE THREAD

**Issue by timka-zhm** [OmniLayer/omnicore#577]
Hi!
I have the Bitcoin daemon(`version v0.14.0`)  running on my machine(Debian 8). I use the Testnet with the following configuration parameters:
`testnet=1`
`mempoolexpirey=1`
`rpcthreads=2`
`rpcuser=<username>`
`rpcpassword=<userpassword`

Command line:
`/home/cryptodaemon/bin/bitcoind -datadir=/home/cryptodaemon/.bitcoin/ -testnet -printtoconsole`

Now I'm trying to run the Omni daemon(`Omni Core version v0.3.0`). But I get an error:
` Error: Unable to start HTTP server.` When I stop the Bitcoin daemon Omni daemon runs well. If I try to start Bitcoin daemon running - get the same issue.
Omni daemon configuration parameters:
`testnet=1`
`mempoolexpirey=1`
`rpcthreads=2`
`rpcuser=<username>`
`rpcpassword=<userpassword`
`txindex=1`
`server=1`

Command line:
`/home/cryptodaemon/omnicore/src/omnicored -datadir=/home/cryptodaemon/.omnicoin/ -testnet -printtoconsole`

Probably the problem is with the port(18333), but its changing didn't help. 
Please, help me to understand what am I doing wrong?

**Comment by dexX7** [comment]
Hi there,

is there anything in the logs in the datadir that may be relevant?

The options `-port`, `-rpcport` and `-datadir` should all be different for each client. Did you test with `-port` and `-rpcport` set for both clients?

**Comment by timka-zhm** [comment]
I print to the console with this flag `-printtoconsole`. The only one log is `Error: Unable to start HTTP server` that I wrote in the text of the issue.
I tested with `-port=19336` but got the same error. 
I didn't change `-rpcport` cause I don't know what it could be. In the repository here I have not found any information about alternative ports for the Omnicoin (https://github.com/OmniLayer/omnicore/blob/master/doc/build-unix.md)

**Comment by dexX7** [comment]
Please also try to use `-rpcport`. :)

**Comment by timka-zhm** [comment]
Could you tell me what port should I set for `-rpcport`?

**Comment by congnghiakhiem** [comment]
You can set port 18332 or 18334. Any ports that are not used by other processes, can be used for rpc server.

**Comment by timka-zhm** [comment]
Yeah, it works! 
Thanks :+1:

**Comment by dexX7** [comment]
Awesome! Thank for your help @congnghiakhiem.
