### ISSUE TITLE
What is exodus balance ?

### ISSUE THREAD

**Issue by congnghiakhiem** [OmniLayer/omnicore#578]
When start omnicored, I can see exodus balance: xxx OMNI.
But I can not find any OMNI in my addresses.
What is exodus balance ? Can I find and send them to another address ?

**Comment by dexX7** [comment]
Hi @congnghiakhiem,

actually this is a relict from the past. The ["Exodus address"](https://github.com/OmniLayer/spec#initial-token-distribution-via-the-exodus-address) is linked to the Omni foundation and printing the balance during startup served as indicator, whether the client loaded properly.

At this point it's probably only confusing and I'm going to remove the line. Thanks for pointing it out!
