### ISSUE TITLE
Omnicore Node with BTC node

### ISSUE THREAD

**Issue by Apollo-IT** [OmniLayer/omnicore#580]
I wanna deploy both OMNI and BTC node in a vps.
Can i do like that?
In this case, how's **bitcoin.conf** working?
**Walletnotify** option is working for both OMNIcore and BTC node?

**Comment by dexX7** [comment]
Hi there,

you certainly can: you need to use different `-port`, `-rpcport` and `-datadir` settings, if you want to run both at the same time.

Walletnotify works for both.

**Comment by Apollo-IT** [comment]
thanks

**Comment by timka-zhm** [comment]
Here is the answer-link
https://github.com/Omnicoin-Project/Omnicoin/wiki/Specifications-and-Technical-Information

**Comment by dexX7** [comment]
Hi @timka-zhm, actually the link you posted is about another project and unrelated to Omni Core, which is the reference client of the [Omni Layer](http://www.omnilayer.org/).
