### ISSUE TITLE
omni_listtransactions method returns empty array

### ISSUE THREAD

**Issue by timka-zhm** [OmniLayer/omnicore#582]
Hi!

1. I've installed the Omnicore daemon.
2. Started the testnet. Got synced blockchain.
3. Genereated new addresses using `getnewaddress` method. Got 10 addresses.
4. For one of them (`miYN8oirbN3QAUcpD3MkKuwDyJ78f6DRu5`) asked bitcoin test coins(here https://testnet.coinfaucet.eu/en/). Got coins:
`{
      "account": "",
      "address": "miYN8oirbN3QAUcpD3MkKuwDyJ78f6DRu5",
      "category": "receive",
      "amount": 0.92676139,
      "label": "",
      "vout": 0,
      "confirmations": 18,
      "blockhash": "00000000000eb69816dc17ec0952c88a6031d96afe6e13f8818332b873c90cba",
      "blockindex": 88,
      "blocktime": 1521713241,
      "txid": "1018a84dde70a757b3aab4a0b0ea7c294ddaa872310211f235386a3e45e10777",
      "walletconflicts": [],
      "time": 1521712775,
      "timereceived": 1521712775,
      "bip125-replaceable": "no"
    },`
    `{
      "account": "",
      "address": "miYN8oirbN3QAUcpD3MkKuwDyJ78f6DRu5",
      "category": "receive",
      "amount": 1.16903461,
      "label": "",
      "vout": 0,
      "confirmations": 16,
      "blockhash": "00000000000001db0860899e7e00a167a5734689b058f40cd85979691bdadc64",
      "blockindex": 104,
      "blocktime": 1521715292,
      "txid": "ed40097c75f5aedf7595c4cafddaaf4f4e1a0ce4aac62970f9fd442aa9962fb2",
      "walletconflicts": [],
      "time": 1521713550,
      "timereceived": 1521713550,
      "bip125-replaceable": "no"
    },`
5. According to the Documentation asked for OMNI and TOMNI (https://github.com/OmniLayer/omnicore#testnet)
`{
      "account": "",
      "address": "moneyqMan7uh8FqdCA2BV5yZ8qVrc9ikLP",
      "category": "send",
      "amount": -1.00000000,
      "vout": 1,
      "fee": -0.00114303,
      "confirmations": 14,
      "blockhash": "0000000025c1bf9c4fd2d384bf9d124df30cf39f8af16749e0ef1b0d6d4ed1d9",
      "blockindex": 51,
      "blocktime": 1521717090,
      "txid": "69f2e40e3490995b9ab1c7251904399336b05bbd54cc0c6e093e62e736a62266",
      "walletconflicts": [],
      "time": 1521715939,
      "timereceived": 1521715939,
      "bip125-replaceable": "no",
      "comment": "wanna get omni",
      "to": "omni owner",
      "abandoned": false
    }`
6. **Got 100 Test OMNI**:
    request:
` curl -H 'Content-Type: application/json' --user '<user>:<userpass>' -X POST --data-binary '{"jsonrpc": "2.0", "id":"omni_test", "method": "omni_getbalance", "params": ["miYN8oirbN3QAUcpD3MkKuwDyJ78f6DRu5", 2]}' http://127.0.0.1:18332`
    response:
`{"result":{"balance":"100.00000000","reserved":"0.00000000"},"error":null,"id":"omni_test"}`
**and 100 OMNI:**
    request: 
` curl -H 'Content-Type: application/json' --user '<user>:<userpass>' -X POST --data-binary '{"jsonrpc": "2.0", "id":"omni_test", "method": "omni_getbalance", "params": ["miYN8oirbN3QAUcpD3MkKuwDyJ78f6DRu5", 1]}' http://127.0.0.1:18332`
    response:
`{"result":{"balance":"100.00000000","reserved":"0.00000000"},"error":null,"id":"omni_test"}`

7. And now I cannot find these incoming transactions for OMNI and TOMNI using `omni_listtransactions`.
**Request:**
`curl -H 'Content-Type: application/json' --user '<user>:<userpass>' -X POST --data-binary '{"jsonrpc": "2.0", "id":"omni_test", "method": "omni_listtransactions", "params": []}' http://127.0.0.1:18332`
**Response:**
`{"result":[],"error":null,"id":"omni_test"}`

**Guys**, what am I doing wrong? 
Thanks a LOT!

P.S. Omnicoreversion: 0.3.0, Bitcoincoreversion: 0.13.2, OS: Debian 8

**Comment by congnghiakhiem** [comment]
curl --data-binary '{"jsonrpc":"1.0","id":"curltext","method":"omni_listtransactions","params":[]}' -H 'content-type:text/plain;' http://xxx:yyy@127.0.0.1:8332
This command works for me. Please try.

**Comment by dexX7** [comment]
Hi @timka-zhm,

the generation of Test Omni via this route doesn't show up when using `omni_gettransaction`, but all other transaction types are.

**Comment by timka-zhm** [comment]
congnghiakhiem, I'm using Testnet. You gave me the example with Mainnet port(8332)

**Comment by congnghiakhiem** [comment]
I'm sorry. You need change user, pass, ip, port to your own information.

**Comment by timka-zhm** [comment]
This is my request:
`curl --data-binary '{"jsonrpc":"1.0","id":"curltext","method":"omni_listtransactions","params":[]}' -H 'content-type:text/plain;' http://myrpcusername:rpcuserpassword@127.0.0.1:14873`

This is response:
`{"result":[],"error":null,"id":"curltext"}`

As you can see I got empty result.

dexX7, 
"doesn't show up when using `omni_gettransaction`" - using this method and transaction hash I got the answer. So, as I see it works for me.
Request:
`curl -H 'Content-Type: application/json' --user 'login:password' -X POST --data-binary '{"jsonrpc": "2.0", "id":"omni_test", "method": "omni_gettransaction", "params": ["cb4df6918cb911aa3f8a6fc7fde5801982c651c2c65c21eb6a4712b26a4e0064"] }' http://127.0.0.1:14873`

Response:
`{"result":{"txid":"cb4df6918cb911aa3f8a6fc7fde5801982c651c2c65c21eb6a4712b26a4e0064","fee":"0.00060000","sendingaddress":"mhf2ibPWMoeyibR2jS3jPLZQYTJsFSoG5r","referenceaddress":"mhf2ibPWMoeyibR2jS3jPLZQYTJsFSoG5r","ismine":false,"version":0,"type_int":0,"type":"Simple Send","propertyid":31,"divisible":false,"amount":"4","valid":false,"invalidreason":"Sender has insufficient balance","blockhash":"00000000004bd5d9292c87550fce80e30fe9dc1a1b0ae359fa7e38593fccdc8c","blocktime":1522049257,"positioninblock":134,"block":1289210,"confirmations":7},"error":null,"id":"omni_test"}
`

**Comment by skinderis** [comment]
@timka-zhm did you manage to solve this? Cause I have the same issue, omni_listtransactions method returns an empty array for me

**Comment by dexX7** [comment]
Hey guys, [omni_listtransactions](https://github.com/OmniLayer/omnicore/blob/master/src/omnicore/doc/rpc-api.md#omni_listtransactions) only works with wallet transactions, but not external ones. For external ones, you could use [omni_listblocktransactions](https://github.com/OmniLayer/omnicore/blob/master/src/omnicore/doc/rpc-api.md#omni_listblocktransactions).

**Comment by timka-zhm** [comment]
@skinderis try to use parameters those are mentioned as *optional*. It works for me
https://github.com/OmniLayer/omnicore/blob/master/src/omnicore/doc/rpc-api.md#omni_listtransactions
