### ISSUE TITLE
RPC method 'omni_listtransactions' skip parameter doesn't work

### ISSUE THREAD

**Issue by korimarik** [OmniLayer/omnicore#583]
Hi there!

After my previous issue, I've realized that 'omni_listtransactions' method works **with OPTIONAL** parameters those described here https://github.com/OmniLayer/omnicore/blob/master/src/omnicore/doc/rpc-api.md#omni_listtransactions.

Now, running a command
` curl -H 'Content-Type: application/json' --user 'user:passsord' -X POST --data-binary '{"jsonrpc": "2.0", "id":"omni_test", "method": "omni_listtransactions", "params": ["*", 10, 0, 0, 1289313]}' http://127.0.0.1:14873`
 
I have result:
`{"result":[{"txid":"629294792bafc31d74ac6f85361251892ed8fd23d7c710429deae5a9085a4676","fee":"0.00000271","sendingaddress":"miYN8oirbN3QAUcpD3MkKuwDyJ78f6DRu5","referenceaddress":"mg6xzhkUYLvReRuezdPcPmHydFsx2wKzGz","ismine":true,"version":0,"type_int":0,"type":"Simple Send","propertyid":1,"divisible":true,"amount":"5.00000000","valid":true,"blockhash":"00000000c1e5052a9f02c70c089388b3623f0cc9e6fdd0b03baa0a7b193f211e","blocktime":1522141663,"positioninblock":122,"block":1289297,"confirmations":20},{"txid":"b6266aef71c62f239a2e497e5ef9a2d63241b0962d987316beb988a43d68a067","fee":"0.00005146","sendingaddress":"miYN8oirbN3QAUcpD3MkKuwDyJ78f6DRu5","referenceaddress":"mg6xzhkUYLvReRuezdPcPmHydFsx2wKzGz","ismine":true,"version":0,"type_int":0,"type":"Simple Send","propertyid":2,"divisible":true,"amount":"80.00000000","valid":true,"blockhash":"0000000006a0b349a8c2ce92ce55370fe6eefc01ca2f90135a2069a480f06772","blocktime":1522075184,"positioninblock":54,"block":1289234,"confirmations":83},{"txid":"6620b047f61f11a5a3babc4adc8042016206567fafbdbb1d772d63af2e566cee","fee":"0.00004823","sendingaddress":"miYN8oirbN3QAUcpD3MkKuwDyJ78f6DRu5","referenceaddress":"mg6xzhkUYLvReRuezdPcPmHydFsx2wKzGz","ismine":true,"version":0,"type_int":0,"type":"Simple Send","propertyid":2,"divisible":true,"amount":"5.00000000","valid":true,"blockhash":"0000000051a9d604ae61f2168734d456e7e145f6f63a46e915a4118920688fa3","blocktime":1522073983,"positioninblock":387,"block":1289233,"confirmations":84},{"txid":"c1b84248dfc0ab1aab1e35072e51d35fd919b990f7c6677585fdff303ffbab9f","fee":"0.00010253","sendingaddress":"miYN8oirbN3QAUcpD3MkKuwDyJ78f6DRu5","referenceaddress":"mhY9hnCHdewUCftuREXDFWNeHAkE4THiSF","ismine":true,"version":0,"type_int":0,"type":"Simple Send","propertyid":2,"divisible":true,"amount":"13.00000000","valid":true,"blockhash":"000000007fd32cdd8b2de9fd2c12e4c6b8c9da33b3d42a438ce734d20f3ed227","blocktime":1522057809,"positioninblock":76,"block":1289218,"confirmations":99}],"error":null,"id":"omni_test"}`

There are 4 transactions here. 

**But**, when I want to **skip** some transactions(for example 2) I got the same **4** transactions. The command and result are below:
`curl -H 'Content-Type: application/json' --user 'user:password' -X POST --data-binary '{"jsonrpc": "2.0", "id":"omni_test", "method": "omni_listtransactions", "params": ["*", 10, 2, 0, 1289313]}' http://127.0.0.1:14873`

**Please, pay attention** to the third parameter **2**!!!

`{"result":[{"txid":"629294792bafc31d74ac6f85361251892ed8fd23d7c710429deae5a9085a4676","fee":"0.00000271","sendingaddress":"miYN8oirbN3QAUcpD3MkKuwDyJ78f6DRu5","referenceaddress":"mg6xzhkUYLvReRuezdPcPmHydFsx2wKzGz","ismine":true,"version":0,"type_int":0,"type":"Simple Send","propertyid":1,"divisible":true,"amount":"5.00000000","valid":true,"blockhash":"00000000c1e5052a9f02c70c089388b3623f0cc9e6fdd0b03baa0a7b193f211e","blocktime":1522141663,"positioninblock":122,"block":1289297,"confirmations":21},{"txid":"b6266aef71c62f239a2e497e5ef9a2d63241b0962d987316beb988a43d68a067","fee":"0.00005146","sendingaddress":"miYN8oirbN3QAUcpD3MkKuwDyJ78f6DRu5","referenceaddress":"mg6xzhkUYLvReRuezdPcPmHydFsx2wKzGz","ismine":true,"version":0,"type_int":0,"type":"Simple Send","propertyid":2,"divisible":true,"amount":"80.00000000","valid":true,"blockhash":"0000000006a0b349a8c2ce92ce55370fe6eefc01ca2f90135a2069a480f06772","blocktime":1522075184,"positioninblock":54,"block":1289234,"confirmations":84},{"txid":"6620b047f61f11a5a3babc4adc8042016206567fafbdbb1d772d63af2e566cee","fee":"0.00004823","sendingaddress":"miYN8oirbN3QAUcpD3MkKuwDyJ78f6DRu5","referenceaddress":"mg6xzhkUYLvReRuezdPcPmHydFsx2wKzGz","ismine":true,"version":0,"type_int":0,"type":"Simple Send","propertyid":2,"divisible":true,"amount":"5.00000000","valid":true,"blockhash":"0000000051a9d604ae61f2168734d456e7e145f6f63a46e915a4118920688fa3","blocktime":1522073983,"positioninblock":387,"block":1289233,"confirmations":85},{"txid":"c1b84248dfc0ab1aab1e35072e51d35fd919b990f7c6677585fdff303ffbab9f","fee":"0.00010253","sendingaddress":"miYN8oirbN3QAUcpD3MkKuwDyJ78f6DRu5","referenceaddress":"mhY9hnCHdewUCftuREXDFWNeHAkE4THiSF","ismine":true,"version":0,"type_int":0,"type":"Simple Send","propertyid":2,"divisible":true,"amount":"13.00000000","valid":true,"blockhash":"000000007fd32cdd8b2de9fd2c12e4c6b8c9da33b3d42a438ce734d20f3ed227","blocktime":1522057809,"positioninblock":76,"block":1289218,"confirmations":100}],"error":null,"id":"omni_test"}`

Guys, what am I doing wrong?
Thank a lot for any help!

**Comment by dexX7** [comment]
Thanks for this submission!

This is indeed not the behavior we want, because it doesn't cut the result and simply returns everything.

**Comment by timka-zhm** [comment]
Thank you for the response!

I see that it's done for 90%, but the date is not defined.
Could you tell me please, when approx are we waiting for the next Release?

**Comment by dexX7** [comment]
Currently there is no date set in stone. I'm tagging items on the go, but the list of open issues related to the next release is not complete.

Based on the question it sounds as you could need a solution for this issue rather sooner than later?

**Comment by timka-zhm** [comment]
Yes, you are right!)

**Comment by dexX7** [comment]
Hi @timka-zhm,

I submitted a fix for this via #592. Are you able to test it somehow?

**Comment by timka-zhm** [comment]
Hi, @dexX7 !
What will be the version of a release with this fix?
Should I reinstall Omnicore source code?

**Comment by dexX7** [comment]
We're not yet going to do a proper release, so you'd need to build Omni Core from source with this patch.

**Comment by timka-zhm** [comment]
I've started to build a new application using the current patch. I'll test it during this week. 
Thank you, guys!

**Comment by dexX7** [comment]
Thanks, please let me know, how it works! :)

**Comment by timka-zhm** [comment]
Yes, sure :)

**Comment by timka-zhm** [comment]
Hi guys!
I've installed Omnicore daemon after fixing the bug. But synchronization after 600K blocks became too slow. Approx 2 blocks per second. 
Does somebody have the same speed of the sync?

**Comment by dexX7** [comment]
> But synchronization after 600K blocks became too slow. Approx 2 blocks per second.

Usually this shouldn't happen. Maybe this was just temporary?

I synced from scratch a few days ago with the current `develop` version..

**Comment by dexX7** [comment]
Ah, just to clarify: you are syncing mainnet and not testnet?

**Comment by timka-zhm** [comment]
No, it is not temporary. The speed is still the same. Sorry, I forgot to say, I'm syncing the testnet

**Comment by timka-zhm** [comment]
Could you tell me, how can I test my work with OMNI? Do we have another testnet?

**Comment by dexX7** [comment]
> And tell me, please, where can I find a Documentation how to use and test with the regtest?

https://bitcoin.org/en/developer-examples#regtest-mode

**Comment by timka-zhm** [comment]
Sorry, but could I get OMNI coins in my private **regtest** node?
I ran it, generated an address, and sent on it some BTC coins. After confirmation of the transaction, I haven't got the coins. So I cannot send Test BTC to get Test OMNI

**Comment by dexX7** [comment]
Similar as on testnet:

- You can create coins yourself, e.g. with [omni_sendissuancefixed](https://github.com/OmniLayer/omnicore/blob/master/src/omnicore/doc/rpc-api.md#omni_sendissuancefixed).

- You you send some Test BTC to `moneyqMan7uh8FqdCA2BV5yZ8qVrc9ikLP `. After confirming the block, you should see an Test Omni balance. :)

**Comment by timka-zhm** [comment]
*You you send some Test BTC to moneyqMan7uh8FqdCA2BV5yZ8qVrc9ikLP. After confirming the block, you should see an Test Omni balance. :)*
Can I do this in the `regtest` mode?

**Comment by dexX7** [comment]
Can you please restart the client and then see, if there are tokens there?

If this doesn't work, please try the following: generate a new address, send some BTC to that address, and send then some BTC from that address to moneyqMan7uh8FqdCA2BV5yZ8qVrc9ikLP.

**Comment by skinderis** [comment]
@dexX7 I can't find information in documentation. omni_listtransactions return all transactions that are received to wallet? or it returns all transactions that have been sent from and received to wallet?

**Comment by dexX7** [comment]
Hopefully resolved via #592.
