### ISSUE TITLE
[help] Accidentally sent bitcoin to testnet MoneyMan address

### ISSUE THREAD

**Issue by Ljzn** [OmniLayer/omnicore#585]
Hi, when testing omni protocol, I accidentally sent 0.025 mainnet bitcoin to testnet MoneyMan address: moneyqMan7uh8FqdCA2BV5yZ8qVrc9ikLP (same scriptHash but encoded with mainnet prefix).
 
This is the transaction: https://blockchair.com/bitcoin/transaction/307803249#i=0

Could you help...

**Comment by dexX7** [comment]
Hi there,

this is a really interesting case. How did this happen?

Unfortunately no one of the current team has access to the private key associated with moneyqMan7uh8FqdCA2BV5yZ8qVrc9ikLP. I reached out to an old contributor, but I don't have much hope, to be honest.

**Comment by hhy464591454** [comment]
You can transfer "testnet"?API: is "omni_send"?"Omni_send "API I have some problems, hope to get your help, thank you

**Comment by dexX7** [comment]
I'm very sorry @Ljzn. We don't have the key for it!
