### ISSUE TITLE
Mac OS X Build

### ISSUE THREAD

**Issue by msgilligan** [OmniLayer/omnicore#59]
It's time to start trying to build the `omnicore-0.0.10` branch on Mac OS X.

I just made a quick try using the instructions in `README.md`, that is:

    ./autogen.sh
    ./configure
    make

And the make is failing with the following error:

    Making all in src
      CXX      omnicore/libbitcoin_server_a-version.o
    omnicore/version.cpp:9:14: fatal error: 'build.h' file not found
    #    include "build.h"
                 ^
    1 error generated.
    make[2]: *** [omnicore/libbitcoin_server_a-version.o] Error 1
    make[1]: *** [all-recursive] Error 1  
    make: *** [all-recursive] Error 1

I'm using *OS X Yosemite* 10.10.3, *Xcode* 6.3.1, and have used *Homebrew* to install the prerequisites as described in [build-osx.md](https://github.com/bitcoin/bitcoin/blob/master/doc/build-osx.md)

**Comment by dexX7** [comment]
Ahh.. I think we had this before.

Could you please try the following fix?
```diff
diff --git a/src/Makefile.omnicore.include b/src/Makefile.omnicore.include
index 0ff01d7..835dbb4 100644
--- a/src/Makefile.omnicore.include
+++ b/src/Makefile.omnicore.include
@@ -43,4 +43,4 @@ libbitcoin_server_a_SOURCES += \
   $(OMNICORE_CPP) \
   $(OMNICORE_H)
 
-libbitcoin_server_a-omnicore/version.$(OBJEXT): obj/build.h # build info
+omnicore/libbitcoin_server_a-version.$(OBJEXT): obj/build.h # build info
```

**Comment by msgilligan** [comment]
Yes, that seems to have done the trick! Running `:omnij-rpc:regTest` currently.

**Comment by zathras-crypto** [comment]
Nice :)  Does that include building the UI?

**Comment by msgilligan** [comment]
Yes, the GUI builds and seems to run OK, too. (I just did two quick launches with `-regtest` and `-testnet`)

**Comment by zathras-crypto** [comment]
Lovely :)  Could you ping me screenshots of anything that looks out of place/out of alignment/generally just funky/incorrect?  Thanks bud

**Comment by msgilligan** [comment]
So, what do we need to do to get the above patch into the development branch?

**Comment by zathras-crypto** [comment]
> So, what do we need to do to get the above patch into the development branch?

@dexX7 feel free to merge in the makefile change if it's safe cross-platform :)

**Comment by dexX7** [comment]
I'm a bit surprised it didn't cause issues until now, neither locally, nor for Travis, even with cleared cache etc.
