### ISSUE TITLE
Created an Invalid Transaction What was my mistake?

### ISSUE THREAD

**Issue by fernandoyo** [OmniLayer/omnicore#595]
I'm using omnicore-cli.

First I sent 120 USDT (from bittrex) to my local wallet.
Then, from my local I sent 2.1 USDT to another wallet "1KAsHQ2..."
https://omniexplorer.info/tx/21c3354ab4422faca43761826884bb4398871a2c404a2fff71be91c9502d3ba0

It worked without any flaw, the problem happened when I sent 2.1 USDT from this new wallet to Bittrex again. 
At first I did not pay attention and my first mistake happened, while doing the "omni_createrawtx_change" command I entered bittrex address as change address instead of mine. Ok, that's is my mistake, but I did not understood why the transaction is invalid.
https://omniexplorer.info/tx/7c9a358a100af28c6cdd50bb66899a0c2eb4299dcdd419829fef1680c0b69710
https://blockchain.info/tx/7c9a358a100af28c6cdd50bb66899a0c2eb4299dcdd419829fef1680c0b69710

I knew that the btc balance on my USDT wallet was low, so I used inputs from this address 1EdRgYUgbfjMbnQtfeFaRRVooi8fSwpCwu to pay for the transaction

I think it is invalid transaction because the omnilayer considered that "1EdRgY-address" sent the USDT without balance. It should have been sent from the "1KAsHQ2..." wallet...

My question is, did the problem happened because while doing "createrawtransaction" I first entered the txid inputs from the wallet that had no USDT?

./omnicore-cli "createrawtransaction" '[{"txid":"e57e8693be37deded83a2228374cfb1206258d57e7bca718ce0d41dad292956f","vout":0},{"txid":"21c3354ab4422faca43761826884bb4398871a2c404a2fff71be91c9502d3ba0","vout":1}]' '{}'

This inputs were used:
[
{
"txid": "e57e8693be37deded83a2228374cfb1206258d57e7bca718ce0d41dad292956f",
"vout": 0,
"address": "1EdRgYUgbfjMbnQtfeFaRRVooi8fSwpCwu",
"account": "btcteste",
"scriptPubKey": "76a914957d368eeb963742d4b53c7248b3a5f59dcd5c3488ac",
"amount": 0.00010000,
"confirmations": 320,
"spendable": true,
"solvable": true
},
{
"txid": "21c3354ab4422faca43761826884bb4398871a2c404a2fff71be91c9502d3ba0",
"vout": 1,
"address": "1KAsHQ2z9HLq6BY1CUiCuKv1CFbQakobGf",
"account": "",
"scriptPubKey": "76a914c74ffb4dcfe95fb591e0800b8709a327988a148c88ac",
"amount": 0.00000546,
"confirmations": 148,
"spendable": true,
"solvable": true
}
]

**Comment by dexX7** [comment]
Hi @fernandoyo,

thanks for asking. So just to clarify:

The "sender" of an Omni Layer transaction is determined based on the first transaction input. The other ones can be from different sources. E.g.:

```
vin[0] = 1EdRgYUgbfjMbnQtfeFaRRVooi8fSwpCwu << sender
vin[1] = 1KAsHQ2z9HLq6BY1CUiCuKv1CFbQakobGf
```

The recipient is based on the last output. If the last output then is from the sender, it's skipped once. If the next potential output is also from the sender, the recipient is also the sender. Some examples:

Normal case where the recipient simply has the last output:
```
sender = 1KAsHQ2z9HLq6BY1CUiCuKv1CFbQakobGf

vout[0] = payload
vout[1] = 1KAsHQ2z9HLq6BY1CUiCuKv1CFbQakobGf
vout[2] = 17ozxkNUuJxP9rh5AN8Zmm867LG8oYRWoH
vout[3] = 1EdRgYUgbfjMbnQtfeFaRRVooi8fSwpCwu < recipient
```

Case where the change is at the last position, but the recipient is still 1EdR:
```
sender = 1KAsHQ2z9HLq6BY1CUiCuKv1CFbQakobGf

vout[0] = payload
vout[1] = 17ozxkNUuJxP9rh5AN8Zmm867LG8oYRWoH
vout[2] = 1EdRgYUgbfjMbnQtfeFaRRVooi8fSwpCwu < recipient
vout[3] = 1KAsHQ2z9HLq6BY1CUiCuKv1CFbQakobGf < skipped once, because sender
```

Case where the recipient is also the sender:
```
sender = 1KAsHQ2z9HLq6BY1CUiCuKv1CFbQakobGf

vout[0] = payload
vout[1] = 17ozxkNUuJxP9rh5AN8Zmm867LG8oYRWoH
vout[2] = 1KAsHQ2z9HLq6BY1CUiCuKv1CFbQakobGf < recipient
vout[3] = 1KAsHQ2z9HLq6BY1CUiCuKv1CFbQakobGf < skipped once, because sender
```

**Comment by fernandoyo** [comment]
Thanks for the awnser! My other question is, since every address receives 0.00000546 btc, should I calculate the total "estimated fee" adding 0.00000546 to the estimated bitcoin blockchain fee?
I'm just setting  the bitcoin estimate fee, where does this 0.00000546 comes from?
thanks!

**Comment by dexX7** [comment]
@Amin1214: you sent tokens to an incompatible recipient, which I addressed in a different thread.

**Comment by sksk666** [comment]
Hello, guys
Does anyone have any solutions?
I happened recently.....

**Comment by dexX7** [comment]
Hi @sksk666, can you please clarify your question?
