### ISSUE TITLE
omni_listtransactions in testnet  return empty

### ISSUE THREAD

**Issue by sjgga** [OmniLayer/omnicore#598]
I have some transactions on my omni wallet(testnet) , omni_listtransactions return infos when the transaction is going. But renturn nothing where transaction has done.
 omnicore-cli -datadir=/data/omni_testnet -rpcport=7832 -port=7833 -testnet omni_listtransactions
[
]

How can i get these transactions in my wallet?
Thanks

**Comment by timka-zhm** [comment]
I had the same problem. Try to set up *optional* parameters. It works for me.
https://github.com/OmniLayer/omnicore/blob/master/src/omnicore/doc/rpc-api.md#omni_listtransactions

`"*" 10 0 0 1296426`
1296426 - max known block

**Comment by dexX7** [comment]
Hey @sjgga,

the RPC [omni_listtransactions](https://github.com/OmniLayer/omnicore/blob/master/src/omnicore/doc/rpc-api.md#omni_listtransactions) only lists wallet transactions, so just to clarify: do you have Omni Layer transactions in your wallet?

If you want to watch out for external ones, check out the [omni_listblocktransactions](https://github.com/OmniLayer/omnicore/blob/master/src/omnicore/doc/rpc-api.md#omni_listblocktransactions] RPC.

**Comment by TAiS46** [comment]
same for me, parameter doesn't help

**Comment by skinderis** [comment]
I think this is the problem with testnet, because `omni_listtransactions` on testnet returned me nothing whilst `listtransactions` was showing some info. I tried this on mainnet and `omni_listtransactions` worked fine.

So, I guess it's the bug on testnet ;)

**Comment by WuWeiWW** [comment]
I test the results of the testnet
If `omni_listtransactions` is executed immediately after transfer, it will get a history record, but after a while (10 minutes), the record will be empty again.

**Comment by burnside** [comment]
I am getting the same results as WuWeiWW.  Using testnet initially omni_listtransactions worked fine, now I get an empty response.  Anyone know why?  And are we certain this is a testnet-specific issue?

Without knowing for sure this only happens on testnet I think I am going to try using the base bitcoin listtransactions, (which I have confirmed still works) then pass each txid to omni_gettransaction.

**Comment by dexX7** [comment]
Hey guys,

can you please test the following:

```
./omnicore-cli omni_listtransactions 999999 0 0 999999
```

**Comment by phanalpha** [comment]
For the testnet, `headers` is greater than 1000000 (`getblockchaininfo`) currently. The default `endblock` paramter of `omni_listtransactions` is 999999, which is lesser. Try to use a greater `endblock` (e.g. 9999999) should help.

**Comment by phanalpha** [comment]
For testnet, the `headers` (with `getblockchaininfo`) is greater than 1000000; for mainnet, the `headers` is > 500000. The default `endblock` paramter of `omni_listtransactions` is 999999, which is lesser than `headers` of testnet, but greater than the mainnet. Try to set a greater `endblock` parameter (e.g. 9999999), it works for me.

**Comment by burnside** [comment]
@dexX7 - you bet:

```
$ ./omnicore-0.3.0/bin/omnicore-cli -conf=testnet3/bitcoin.conf omni_listtransactions 999999 0 0 999999
[
]
```

**Comment by dexX7** [comment]
Thanks a lot @phanalpha, this makes a lot of sense! I pushed a pull request to bump the default.
