### ISSUE TITLE
How to generate an address?

### ISSUE THREAD

**Issue by huturen** [OmniLayer/omnicore#599]
Hello, 

We want to receive Tether payments from different clients.
So, we need to generate different addresses for our clients to receive payments,
but i don't know how to generate an address.
Is it possible to attach a label to an address so that we can identify an address to do some special business.

Thanks.

**Comment by huturen** [comment]
use native bitcoin core rpc call:getnewaddress.

**Comment by dexX7** [comment]
Hi @huturen, correct, you can use `getnewaddress` for this.
