### ISSUE TITLE
Select no coins to spent which invalidate Omni transactions

### ISSUE THREAD

**Issue by dexX7** [OmniLayer/omnicore#6]
I noticed this quite some time ago, when writing bitcoin-spock tests, and we finally found sneaky ways to work around it, but just right now I fully realized the actual issue is part of Omni Core, and not something that should have been addressed in bitcoin-spock.

The current wallet/spending code does not check, if the coins to spent violate consensus rules.

The consensus rules are pretty simple: only pay-to-pubkey-hash and pay-to-script-hash outputs qualify as valid inputs.

The issue while testing was that the coin selection (used by `sendrawtx_MP` or `send_MP`) often selects coinbase transaction coins, which result in invalidated Omni transactions, because coinbase transaction coins are no pay-to-pubkey-hash or pay-to-script-hash coins, and thus not valid.

**Comment by zathras-crypto** [comment]
Hey bud, sorry for delayed response - was a busy weekend with family...  I just reviewed your PR for this issue and support it.

Thanks
Z

**Comment by dexX7** [comment]
Was addressed by #7.
