### ISSUE TITLE
Bitcoin Core and OmniCore run at a time

### ISSUE THREAD

**Issue by nomantariq18** [OmniLayer/omnicore#606]
is there any solution to run OMNI core and BTC core  both wallets at a time? when i install Omni core wallet it overides my bitcoin.conf file which is my BTC wallet file located in  Roaming folder/Bitcoin. or is there any settings which make them differ to each other ?

**Comment by phuongla** [comment]
You can use option "-datadir" to seperate your enviroment. (https://en.bitcoin.it/wiki/Data_directory)

**Comment by nomantariq18** [comment]
thanks issue resolved.

**Comment by dexX7** [comment]
Hi there, the related options are `-rpcport`, `-port` and `-datadir`, because you not only need to ensure they use a different datadir, but also different ports.
