### ISSUE TITLE
USDT omni_getbalance return 0

### ISSUE THREAD

**Issue by zerxon** [OmniLayer/omnicore#607]
I tried to  call `omni_getbalance` though `rpc-json` like this: 
```
{
"jsonrpc":"2.0",
"method":"omni_getbalance",
"params":["1G47mSr3oANXMafVrR8UC4pzV7FEAzo3r9", 31],
"id":1
}
```
But it doesn't work, always return the result that shows balance is zero, I'm looking forward to your help, thanks

**Comment by zerxon** [comment]
After reload the block data, it works now

**Comment by dexX7** [comment]
Great to hear it worked out!
