### ISSUE TITLE
regtest mode how to create Property 

### ISSUE THREAD

**Issue by ying23** [OmniLayer/omnicore#620]
@dexX7  help
in regtest how to get omni and how to send transaction 
can you provide examples
thanks

**Comment by timka-zhm** [comment]
#621

**Comment by dexX7** [comment]
Hi @ying23,

to create tokens, mine some blocks with `generate` and send some BTC to a new address. With that address you could use [omni_sendissuancefixed](https://github.com/OmniLayer/omnicore/blob/master/src/omnicore/doc/rpc-api.md#omni_sendissuancefixed) to create a token with fixed supply.

**Comment by kazaff** [comment]
thanks all~
