### ISSUE TITLE
where to get TestOmni from? and whose address is that? My onmi core desktop wallet generated this address on testnet mtdLJismp9qZAkyFhpMg3DAhE2W5BDE2FH

### ISSUE THREAD

**Issue by ying23** [OmniLayer/omnicore#621]

**Comment by timka-zhm** [comment]
Hi!
1. Go here https://testnet.manu.backend.hamburg/faucet and send to your address `mtdLJismp9qZAkyFhpMg3DAhE2W5BDE2FH` some test BTC. 
2. According to this link https://github.com/OmniLayer/omnicore#testnet send some BTC funds to `moneyqMan7uh8FqdCA2BV5yZ8qVrc9ikLP` address. After, you'll get 100 test OMNI instead of each 1 test BTC to the sender address.

**Comment by ying23** [comment]
ok..thanks. but step 1 tip.
"System or Wallet error, Recaptcha failed or address invalid!"

**Comment by timka-zhm** [comment]
Sometimes there are some problems with it. Try later

**Comment by timka-zhm** [comment]
358a044454b55e71bfef8d18910f9d32a1a5a572f6f0fd5a758708c6daae9d58 - this is transaction id. I sent you some coins through it.
P.S. check, do you put your address without a space in the end

**Comment by ying23** [comment]
@timka-zhm 
thank you for you help.
in my omni testnet,i got the return balance by "omni_getbalance", like
`./omnicore-cli omni_getbalance "mtdLJismp9qZAkyFhpMg3DAhE2W5BDE2FH" 1
{
  "balance": "0.00000000",
  "reserved": "0.00000000"
}
`
Is there any mistake?
and do you know how to test omni on testnet mode 
can you offer help

**Comment by vae520283995** [comment]
bitcoin.conf     set      testnet=1

**Comment by dexX7** [comment]
Hi @ying23, the RPC `omni_getbalance` only shows token balances, but not BTC balances.

You can use a "testnet faucet" to get some BTC and then check out these steps to get Test Omni:

https://github.com/OmniLayer/omnicore#testnet

**Comment by ying23** [comment]
Hi @timka-zhm ,can you give me some tbtc to mhvDB8a3mEiVvnNBJ2UGoYrvxD1RU4MZB5
thinks

**Comment by timka-zhm** [comment]
https://live.blockcypher.com/btc-testnet/tx/aac3b2e5543ad35b197c4d397078168919f75992baacacf5fc283c6c97928045/ - here is the transaction 

You can send for yourself using this https://testnet.manu.backend.hamburg/faucet service

**Comment by WuWeiWW** [comment]
HI hi can't get test coin
I send `testnet3` btc to  `moneyqMan7uh8FqdCA2BV5yZ8qVrc9ikLP`
[93f4dbffa4e914e5810c2693d66a1ee85dd99404fffc897e780e29cf4d5568f9](https://live.blockcypher.com/btc-testnet/tx/93f4dbffa4e914e5810c2693d66a1ee85dd99404fffc897e780e29cf4d5568f9/)

But I didn't get it `TestOmni`，Please help me Please /(ㄒoㄒ)/~~
![Alt text](https://github.com/WuWeiWW/libphonenumber/raw/master/resources/1.png)
![Alt text](https://github.com/WuWeiWW/libphonenumber/raw/master/resources/2.png)

**Comment by timka-zhm** [comment]
Try to use https://github.com/OmniLayer/omnicore/blob/master/src/omnicore/doc/rpc-api.md#omni_getallbalancesforid this method. And you'll see addresses, where you got test OMNI

**Comment by dexX7** [comment]
Thanks @timka-zhm!

**Comment by dexX7** [comment]
Hi @songjim, no! Test Omni and USDT are two completely different tokens, but both use the Omni Layer as platform.

**Comment by sundarammmn** [comment]
I really need OMNI test coin , can anyone can donate 10 coin to this address rDfipwDJzYdSgA8uujTFxJRercwgxi2wkf .
