### ISSUE TITLE
How to get total balance for the whole wallet ?

### ISSUE THREAD

**Issue by energy568c** [OmniLayer/omnicore#623]
bitcoin-cli getbalance [account]
 If [account] is not specified, returns the server's total available balance.
How can I get total available balance with omnicore-cli ?
Thanks a lot.

**Comment by dexX7** [comment]
Unfortunately you can only query individual addresses or tokens with the following commands:

- [omni_getbalance](https://github.com/OmniLayer/omnicore/blob/master/src/omnicore/doc/rpc-api.md#omni_getbalance)
- [omni_getallbalancesforid](https://github.com/OmniLayer/omnicore/blob/master/src/omnicore/doc/rpc-api.md#omni_getallbalancesforid)
- [omni_getallbalancesforaddress](https://github.com/OmniLayer/omnicore/blob/master/src/omnicore/doc/rpc-api.md#omni_getallbalancesforaddress)

**Comment by vetal20600** [comment]
@dexX7 So no way to get all balances that belong to wallet? Will you support this feature in future?

**Comment by dexX7** [comment]
Hi @vetal20600,

actually I'm currently working on two new RPCs:

- omni_getwalletbalances: lists the total balances for each token in the wallet
- omni_getwalletaddressbalances: lists all balances for every address in the walet

**Comment by vetal20600** [comment]
@dexX7 can you add something like omni_get_wallet_balances_for_property propertyid? it would be nice to check all tether balances in wallet

**Comment by dexX7** [comment]
Hi @vetal20600,

omni_getwalletbalances provides a list of total balances for the whole wallet for each token in the wallet, so I think it should be fine. :)

I'm going to finalize and merge the pull request (#716) tomorrow. The Omni Core v0.3.1 release is expected in roughly two weeks.

**Comment by vetal20600** [comment]
@dexX7 thanks! this is great news!

**Comment by dexX7** [comment]
Resolved via #716.
