### ISSUE TITLE
Syncing is very slow in AWS ECS

### ISSUE THREAD

**Issue by DaveWK** [OmniLayer/omnicore#627]
I am setting up some omni nodes in aws ecs, and it's taking it a very long time to sync, and routinely times out on connections, causing it to fail health checks. 

I have allocated a full m4.xlarge with 14 gigs of ram. I have set the params:
 -dbcache=10000 -omnitxcache=2000000000 -rpcworkqueue=125

and every few hours it will timeout responding to GET on / for the rpc, causing the process to reboot, and rescan from the beginning of time which causes a lot of wasted time on rescans.

I have 2 other sets of btc nodes (one v 0.13, one 0.16) and they both sync much faster than the omni node. It is not resource starved, and I can see it is not consuming nearly as much as it could in cpu and ram. how do I make this work faster and consume more resources?

**Comment by dexX7** [comment]
Hi @DaveWK,

this is an interesting case. Can you please check the result, when you do not specify a custom `-omnitxcache`?

Do you have an overview of used resources right before the reboot? My guess would be that the too high number caused the RAM to fill up.

It's really fine to use the default here. :)

**Comment by DaveWK** [comment]
I initially didn't use any omnitxcache and was hoping that would make it work faster -- it doesn't even come close to maxing out the ram with the omnitxcache and dbcache set.

**Comment by sancome** [comment]
@DaveWK i have the same problem, did you solved it?

**Comment by sancome** [comment]
@dexX7 i used the default options.

root@scan-usdt:/usdt_data# omni -datadir=/usdt_data -rpcbind=0.0.0.0 -rpcport=3001 -txindex -server -daemon -port=18333 -rpcworkqueue=128
Omni Core server starting
root@scan-usdt:/usdt_data# 2018-08-23 00:43:16 Initializing Omni Core v0.3.0 [main]
2018-08-23 00:43:16 Loading trades database: OK
2018-08-23 00:43:16 Loading send-to-owners database: OK
2018-08-23 00:43:16 Loading tx meta-info database: OK
2018-08-23 00:43:16 Loading smart property database: OK
2018-08-23 00:43:16 Loading master transactions database: OK
2018-08-23 00:43:16 Loading fee cache database: OK
2018-08-23 00:43:16 Loading fee history database: OK
2018-08-23 00:43:16 Loading persistent state: NONE (no usable previous state found)
2018-08-23 00:43:32 Scanning for transactions in block 249498 to block 537951..
2018-08-23 00:44:02 Still scanning.. at block 291053 of 537951. Progress: 4.34 %, about 10:39 minutes remaining..
2018-08-23 00:44:32 Still scanning.. at block 310866 of 537951. Progress: 6.74 %, about 13:36 minutes remaining..

**Comment by sancome** [comment]
After the omni has been running for a while, the RPC has no response, and there is no way to normally end the process by "rpc stop". If i killed the process, there will be a long scanning process.

**Comment by dexX7** [comment]
Hi @sancome,

we've made massive progress in terms of stability and parsing speed in the last weeks. Are you able to run the develop branch of this repo?

**Comment by sancome** [comment]
@dexX7 I will compile the develop version and try to run it, and then report back, thanks.

**Comment by dexX7** [comment]
Awesome! Please let me know, if you need more help. Until then, I'm going to close this issue.
