### ISSUE TITLE
How can i differentiate the currencies in my omnicore cli ??

### ISSUE THREAD

**Issue by nitsx2** [OmniLayer/omnicore#628]
I have some queries regarding omnicore and tether.
1-  How can i differentiate the currencies in my omnicore cli ??
2- Is there any limit to create addresses in omnicore-cli?
3- I read somewhere that if i send test bitcoins to moneyqMan7uh8FqdCA2BV5yZ8qVrc9ikLP address then it will return me test tethers. If it sends me then i have 2 currencies in my omnicore-cli(bitcoin, tether).Same query again how can i manage both? If i want to integrate ether only then how can i differentiate it? Is there any particular Asset Ids for every coin in omnicore??

**Comment by dexX7** [comment]
Hi @nitsx2,

1] You can query balances with the following commands:

- [omni_getbalance](https://github.com/OmniLayer/omnicore/blob/master/src/omnicore/doc/rpc-api.md#omni_getbalance)
- [omni_getallbalancesforid](https://github.com/OmniLayer/omnicore/blob/master/src/omnicore/doc/rpc-api.md#omni_getallbalancesforid)
- [omni_getallbalancesforaddress](https://github.com/OmniLayer/omnicore/blob/master/src/omnicore/doc/rpc-api.md#omni_getallbalancesforaddress)

And to list all tokens that exist, you can use:

- [omni_listproperties](https://github.com/OmniLayer/omnicore/blob/master/src/omnicore/doc/rpc-api.md#omni_listproperties)

2] You can create as many addresses as you want, but I expect some performance degradation at some point. We inherit the limitations of Bitcoin Core in this regard.

3] To handle BTC, you can use what's available in Bitcoin Core. To handle Omni Layer tokens like USDT or TestOmni, you can use:

- [omni_send](https://github.com/OmniLayer/omnicore/blob/master/src/omnicore/doc/rpc-api.md#omni_send)

**Comment by nitsx2** [comment]
Thanks i got it. The property id of tether on main net is 31. I just want to perform tether transaction on testnet, can you please assist me that how can i achieve it??

**Comment by dexX7** [comment]
There is no "official" Tether token on testnet.

**Comment by nitsx2** [comment]
ok i performed omni transaction -- 
./omnicore-cli  omni_send "munY5LZbDxUCWjQ3zho5AavymEWg3R1Ep8" "  mykJ9Mp68adZB7knteS3T9FWHjaNXAoePo" 1 90 
the transaction id - 1976f29fb337303c12f00f5889a1b48eb42f60c9dda0d22b6ebbe9b207f60547
 
When i do omni_listtransaction it shows be blank array [ ]  but when i do listtransactions it shows me  the transaction list (in BTC ) .

Can u please explain me what is happening? and what will be the fee for tether transaction??

**Comment by vae520283995** [comment]
@nitsx2 There are also parameters behind omni_listtransaction. You need to make up the parameters.
forexample:
 ./omnicore-cli omni_listtransactions "n1Cn8nKyqaLoYcN2CFUR7ApSSYxo1ZnWxX" 100 0 0 99999999

**Comment by nitsx2** [comment]
Thanks for reply @vae520283995 but really i really don't understand what are these parameters after address (100 0 0 99999999) ?

**Comment by dexX7** [comment]
Hi @nitsx2, check out the documentation for these parameters here:

https://github.com/OmniLayer/omnicore/blob/master/src/omnicore/doc/rpc-api.md#omni_listtransactions

**Comment by dexX7** [comment]
@nitsx2: does this help?

https://github.com/OmniLayer/omnicore/blob/master/src/omnicore/doc/rpc-api.md#omni_getbalance

**Comment by nitsx2** [comment]
Thank you very much for help @dexX7 but i have one thing in my mind that how can i setup a already downloaded Bitcoin block chain with omnicore? Can you please assist me?

**Comment by dexX7** [comment]
@nitsx2: which version of Bitcoin were you running?
