### ISSUE TITLE
seems a bug in encoding.cpp

### ISSUE THREAD

**Issue by lxjxiaojun** [OmniLayer/omnicore#633]
In the function OmniCore_Encode_ClassB:
`            for (int j = 0; i < 256 ; j++) { // Fix ECDSA coodinate
                vchFakeKey[32] = chRandom;
                pubKey = CPubKey(vchFakeKey);
                if (pubKey.IsFullyValid()) break;
                ++chRandom; // ... but cycle no more than 256 times to find a valid point
            }`
maybe loop forever? I'm not sure~

**Comment by dexX7** [comment]
Hi @lxjxiaojun,

thank you a lot for spotting this! The `i` should indeed be a `j`!

Fortunately in practice this isn't an issue, because a valid ECDSA point is usually around the corner, but as second safe guard we have included this check.

**Comment by dexX7** [comment]
Resolved via #634.
