### ISSUE TITLE
sendrawtransaction

### ISSUE THREAD

**Issue by ALiIsReal** [OmniLayer/omnicore#638]
![image](https://user-images.githubusercontent.com/22163736/40903294-81607f20-6809-11e8-9a03-93b79ca46623.png)
When I used this method sendrawtransaction, I made the mistake. What is the reason for this?

**Comment by dexX7** [comment]
Hi @ALiIsReal,

could it be you used very, very low output values or a too tiny transaction fee?

**Comment by jarven-zhang** [comment]
hi, I have encountered the same problem. How do you solve it?
