### ISSUE TITLE
Binance to coinbase 

### ISSUE THREAD

**Issue by Amin1214** [OmniLayer/omnicore#639]
I lost my money pls some help me ..I requested you my fund not receive 
https://omniexplorer.info/tx/1e3346ef5f0e77f71c59b55c89e04bf201a824d6c2f831b4e0d5fdc54c642ae7

**Comment by dexX7** [comment]
Hi @Amin1214, please see:

https://github.com/OmniLayer/omnicore/wiki/I-sent-tokens-to-an-incompatible-wallet-such-as-Coinbase-or-GDAX.-Can-you-reverse-the-transaction%3F
