### ISSUE TITLE
USDT wallet private chain and main chain building

### ISSUE THREAD

**Issue by xianaofei** [OmniLayer/omnicore#643]
How to build a private chain, for example, to build a BTC Wallet
WGet https://bitcoin.org/bin/bitcoin-core-0.15.1/bitcoin-0.15.1-x86_64-linux-gnu.tar.gz
Echo "export PATH=\${PATH}: /usr/local/bitcoin/bin/"
Bitcoin.conf
Seek help
How to build the private chain and main chain of USDT Purse
Thank you

**Comment by dexX7** [comment]
Hi @xianaofei, can you please rephrase your question?

**Comment by xianaofei** [comment]
wget https://bintray.com/artifact/download/omni/OmniBinaries/omnicore-0.3.0-x86_64-linux-gnu.tar.gz
Find the download address of the wallet 
The problem has been solved

Thank you
