### ISSUE TITLE
Use the same datadir for Bitcoin core and Omnicore

### ISSUE THREAD

**Issue by DonaldChiang** [OmniLayer/omnicore#646]
Hello

my Omnicore was running on a different datadir with bitcoin core, ~/.bitcoin and ./tether.

Omnicore sync block became very slow after reaching block height 350000, about 1 block per second...So can I just copy the blocks folder from .bitcoin to .tether to skip Omnicore block sync? Or Can I use the same datadir for both bitcoin core and Omnicore?

Please help thanks!

My hardware:
Google cloud platform
8-core vCpu
20 GB memory
400 GB SSD

**UPDATE1:**

I tried to use the same datadir for both Omnicore and Bitcoin core, but it always show this error

`Error: Error loading wallet.dat: Wallet requires newer version of Omni Core`

Omnicore version: v0.13.2.0-1ff8375
Bitcoin core version: v0.16.0.0-g4b4d7eb255

**After I specifying Omnicore wallet option this situation was solved**

**UPDATE2:**

When I run bitcoin core there will generate a .lock file in .bitcoin directory so I cannot run Omnicore in the same datadir, it always show:

`Error: Cannot obtain a lock on data directory /home/user/.bitcoin. Omni Core is probably already running.`

**Comment by dexX7** [comment]
Hi @DonaldChiang, while it's possible to run either one of Bitcoin Core or Omni Core at the same time, with the same datadir, it's not possible to run both side by side with the same datadir.

**Comment by DonaldChiang** [comment]
OK, I understand, thanks!
