### ISSUE TITLE
Deploy OmniLayer

### ISSUE THREAD

**Issue by khaitranvan96kt** [OmniLayer/omnicore#652]
How to deploy OmniLayer? I want to provide services to thousands of users.

**Comment by dexX7** [comment]
Hi there, can you please be more specific? There are build instructions here:

https://github.com/OmniLayer/omnicore/blob/master/doc/build-unix.md

**Comment by khaitranvan96kt** [comment]
Hi. I do not know, OmniLayer's RPC runs single-threaded or multi-threaded. I see the speed of the API is quite slow, so what should I do to make it faster. I do not understand much about OmniLayer's architecture, can you provide me with documentation?

**Comment by dexX7** [comment]
Omni Core is essentially Bitcoin Core with extended feature set.

Is your client fully synchronized?

**Comment by khaitranvan96kt** [comment]
I want to provide services to my clients. And they do not need to save any data.

**Comment by khaitranvan96kt** [comment]
If I only run omnicore client is enough or not. Please give me some advice.

**Comment by dexX7** [comment]
Running Omni Core is enough from the Omni Layer and Bitcoin side, but you'd probably still need a system to handle user accounts, the front end, etc.

**Comment by khaitranvan96kt** [comment]
thanks you ....
