### ISSUE TITLE
Accidentally sent USDT to wrong address not used by anyone yet, how rescue it?

### ISSUE THREAD

**Issue by xdemocle** [OmniLayer/omnicore#653]
Hello, I did a newbie mistake I never did before.
Made a withdrawal toward an USDT address but with last 2 letters missing, so now I sent funds to an incomplete tether address.
What is gonna happens now? Since the 2 final letters of the address are missing and address in theory is not valid, shall the transaction get rejected?

Eventually how can I create a tether address like the wrong one since hasn't been created by anyone else?

Thanks in advance.
Cheers,

**Comment by dexX7** [comment]
Hi there, where did you make the withdrawal?

A transaction with an incomplete recipient isn't valid, so you should be good.

**Comment by dexX7** [comment]
Ahh, don't be sorry! I'm very glad there was no actual loss of funds. :)
