### ISSUE TITLE
Graph interface not working (Win10)

### ISSUE THREAD

**Issue by jdloret** [OmniLayer/omnicore#654]
Hi,

I found an issue on Omni core 0.3.0.
The window does not display at all, and even block aero to work properly (super+tab does nothing ONLY when Omni core is launched, and re-works back to normal next second after Omni core is closed)

The only functions of the program still available from the notificatioin icon that work are **options**, **sign message**, and hopefully **debug window**, any other piece of interface is broken and I have just no way to access it.

The blockchain seems to sync normally, but I can't make any TX nor use the program normally through its interface, everything has to be done from the debug window.

Big note about Omni core's behavior under win7 : 
It happens often, but under w7 the function to maximize a windows to full screen from the taskbar was still there and it always fix the issue.
On win10 maximize had been removed and so it broke Omni core's interface on my win10 install.
I maintain some nodes in the public space and I never got any issues with win server 2008/2012 at all, like win 7: maximize sorts everything back to normal.

**Comment by dexX7** [comment]
Hi @jdloret,

the UI can become very unresponsive, when the client still synchronizes historical blocks.

Is this the case?

**Comment by jdloret** [comment]
I run only war machines as PCs : my win 10 on a i7-6700HQ based laptop with 16GB of RAM and 2 SSDs. Normally lanching omni on that takes like 15s/20s maximum.
Otherwise I run everything only on servers so machines running Xeon or Opteron CPUs.
The very few of the interface that is working (option/debug) works as the speed it should on any high end hardware.
The BC seems to be up to date when I tested.
The pb is really related, to me, to the fact I can't maximize a window under win10.

EDIT : found out.

**Comment by dexX7** [comment]
> EDIT : found out.

How?
