### ISSUE TITLE
Store state after initial scanning

### ISSUE THREAD

**Issue by dexX7** [OmniLayer/omnicore#66]
The state is currently only persisted, after a block was mined.

Closing the client after the initial scanning, but before a block was mined, has the effect that the scanning starts again from the very beginning.

I suggest to store the state after the initial scanning, and this raises the question: maybe we should store the state from time to time during the initial scanning as well? This could allow to stop at some point, and continue later.

**Comment by zathras-crypto** [comment]
Really?  Now that's quite surprising...

The block handler is supposed to call ```mastercore_save_state``` after each block.  This is bypassed via a check to ```writePersistence``` but should only be bypassed in the case that we're more than ```MAX_STATE_HISTORY``` before the tip.

I'd say this is a bug rather than improvement - I'll take a look mate...

Thanks

**Comment by dexX7** [comment]
`msc_initial_scan()` scans the blocks directly, without calling `mastercore_handler_block_end()` (as far as I can see at least), thus `mastercore_save_state()` isn't called either.

**Comment by zathras-crypto** [comment]
https://github.com/OmniLayer/omnicore/blob/omnicore-0.0.10/src/omnicore/omnicore.cpp#L1375

**Comment by dexX7** [comment]
Oh my, ... you're right.

**Comment by zathras-crypto** [comment]
> Closing the client after the initial scanning, but before a block was mined, has the effect that the scanning starts again from the very beginning.

Do you see this behaviour though?  Because I suggest to leave the issue open until we locate what's causing it :)

**Comment by dexX7** [comment]
> Do you see this behaviour though?

Due to the freezes, "recalling that state isn't stored during the initial scan", and after very quickly scanning over the code, I thought I do.

Right now I can say: I was wrong, it works, at least on testnet (~6 weeks behind chaintip, so the trading test is still outstanding). :)

**Comment by zathras-crypto** [comment]
Yeah the freezes during sync suck - I've been working with synced clients for a while now I forgot all about it - I do have some ideas for this though which I think can help.

Sounds like you'll get there on trading test on Windows testnet before me, I'm still about 2 years behind hehe
