### ISSUE TITLE
Omnicored hangs forever, serval times happen.

### ISSUE THREAD

**Issue by qshuai** [OmniLayer/omnicore#661]
Only kill the omnicored process and restart, it will work. The strace、 ltrace and gdb debug information as following:

![2018-06-23 10 47 23](https://user-images.githubusercontent.com/20664531/41805005-8c7d64a8-76d3-11e8-9273-23ae82d9f88c.jpg)
![2018-06-23 10 48 59](https://user-images.githubusercontent.com/20664531/41805006-8d1292b2-76d3-11e8-8728-635a933fc6eb.jpg)
![2018-06-23 10 49 06](https://user-images.githubusercontent.com/20664531/41805007-8e2e18ec-76d3-11e8-94fc-314f68bb6b1f.jpg)
![2018-06-23 10 49 18](https://user-images.githubusercontent.com/20664531/41805008-8f76341e-76d3-11e8-9e20-a6496b5769be.jpg)
![2018-06-23 10 49 22](https://user-images.githubusercontent.com/20664531/41805010-91f43b46-76d3-11e8-908e-beef45ca868d.jpg)

**Comment by dexX7** [comment]
Hi @qshuai,

in which context does the hang happen?

**Comment by qshuai** [comment]
It happens serval times when omniEngine and omnicore that was syncing the old blocks run at the same time.
