### ISSUE TITLE
omnicore rpc omni_listtransactions - no watch only options? + arguments txid filter?

### ISSUE THREAD

**Issue by essemfly** [OmniLayer/omnicore#668]
I imported watch only address to omnicore wallet and 
I want to find usdt txs by omni_listtransactions but i cannot find.

Transactions involving Watch only addresses cannot be searched by omni_listtransactions?

then is there any other option to find omni txs for watch only imported addresses?

+ omni_listtransactions argument says that txid could be the first arg for filter transactions
but how txid could be address filter in wallet transactions? 

anyone help me..

**Comment by dexX7** [comment]
Hi @essemfly, currently the RPC only works with wallet transactions, but a new command for arbitrary transaction retrieval is planed. :)
