### ISSUE TITLE
what is the type 4 transaction，send all

### ISSUE THREAD

**Issue by zhangdaoling** [OmniLayer/omnicore#670]
I find type 4 transaction in explorer but I cant find this type in https://github.com/OmniLayer/spec

https://omniexplorer.info/tx/47660514c47783a791174ef33828c0ed566e136741664851a7dd06ef5e4ede2b#collapseAmountData

**Comment by dexX7** [comment]
Hi @zhangdaoling,

the spec is incomplete and doesn't fully describe the protocol we use, because it has evolved faster than we kept up.

The sendall transaction type transfers all tokens from one ecosystem to a specified destination.
