### ISSUE TITLE
charged usdt to BitCoin-0.16.0 new address

### ISSUE THREAD

**Issue by Yucheng123** [OmniLayer/omnicore#671]
sorry , i charged usdt to BitCoin-0.16.0 generated bitcoin addresses,can i get my usdt back?

**Comment by dexX7** [comment]
Hi @Yucheng123, do you fully control the destination and have the private key for it?

**Comment by Yucheng123** [comment]
yes,i have the full control of private key

**Comment by Yucheng123** [comment]
thank you for your reply，i overcomed by signing with the btc wallet and send the raw transaction with omni-wallet
