### ISSUE TITLE
Is it possible to pay transaction fees from a different source? Please help

### ISSUE THREAD

**Issue by amarian12** [OmniLayer/omnicore#677]
let's say address 1 own 100 omni and 546 sat, address 2 own 0 omni but 1 btc.... how can we pay the fee from address 2 to send omni?

**Comment by amarian12** [comment]
ok... i manage to do it:

omnicore-cli listunspent
[
  {
    "txid": "0407c99c30dd75ea91c45e7599c8611a78ac4c27f92c2b05a8df9deace12adca",
    "vout": 2,
    "address": "ms2cyVpcYLFfGVZHR3DJrWQPicWH67rGSa",
    "account": "payment",
    "scriptPubKey": "76a9147e45bc2945d7d1d37726cea8cb2865d95763d57488ac",
    "amount": 0.00000546,
    "confirmations": 1,
    "spendable": true,
    "solvable": true
  },
  {
    "txid": "8043ffae81153a6761ceb468fb8020720973af20be215c164aee1cc5d2f20acc",
    "vout": 1,
    "address": "mifTd7G59RPTuod9MZMP26XYX6HjvZiHKo",
    "scriptPubKey": "76a91422842ff0e2468f61e1d06cd33b5829082f13b06c88ac",
    "amount": 0.99974474,
    "confirmations": 9,
    "spendable": true,
    "solvable": true
  }
]
omnicore-cli "createrawtransaction" '[{"txid":"0407c99c30dd75ea91c45e7599c8611a78ac4c27f92c2b05a8df9deace12adca","vout":2},{"txid":"8043ffae81153a6761ceb468fb8020720973af20be215c164aee1cc5d2f20acc","vout":1}]' '{}'
0100000002caad12ceea9ddfa8052b2cf9274cac781a61c899755ec491ea75dd309cc907040200000000ffffffffcc0af2d2c51cee4a165c21be20af7309722080fb68b4ce61673a1581aeff43800100000000ffffffff0000000000

omnicore-cli "omni_createpayload_simplesend" 2 "200"
000000000000000200000004a817c800

omnicore-cli "omni_createrawtx_opreturn" "0100000002caad12ceea9ddfa8052b2cf9274cac781a61c899755ec491ea75dd309cc907040200000000ffffffffcc0af2d2c51cee4a165c21be20af7309722080fb68b4ce61673a1581aeff43800100000000ffffffff0000000000" "000000000000000200000004a817c800"
0100000002caad12ceea9ddfa8052b2cf9274cac781a61c899755ec491ea75dd309cc907040200000000ffffffffcc0af2d2c51cee4a165c21be20af7309722080fb68b4ce61673a1581aeff43800100000000ffffffff010000000000000000166a146f6d6e69000000000000000200000004a817c80000000000


omnicore-cli "omni_createrawtx_reference" "0100000002caad12ceea9ddfa8052b2cf9274cac781a61c899755ec491ea75dd309cc907040200000000ffffffffcc0af2d2c51cee4a165c21be20af7309722080fb68b4ce61673a1581aeff43800100000000ffffffff010000000000000000166a146f6d6e69000000000000000200000004a817c80000000000" "mzNTtEyZtkX91oS5erkGQyhpy6aLH8N5iz"
0100000002caad12ceea9ddfa8052b2cf9274cac781a61c899755ec491ea75dd309cc907040200000000ffffffffcc0af2d2c51cee4a165c21be20af7309722080fb68b4ce61673a1581aeff43800100000000ffffffff020000000000000000166a146f6d6e69000000000000000200000004a817c80022020000000000001976a914cecf58a478037b4c0f4b2d3019e67fb619f35f4988ac00000000

omnicore-cli "omni_createrawtx_change" "0100000002caad12ceea9ddfa8052b2cf9274cac781a61c899755ec491ea75dd309cc907040200000000ffffffffcc0af2d2c51cee4a165c21be20af7309722080fb68b4ce61673a1581aeff43800100000000ffffffff020000000000000000166a146f6d6e69000000000000000200000004a817c80022020000000000001976a914cecf58a478037b4c0f4b2d3019e67fb619f35f4988ac00000000" '[{"txid":"0407c99c30dd75ea91c45e7599c8611a78ac4c27f92c2b05a8df9deace12adca","vout":2,"scriptPubKey":"76a9147e45bc2945d7d1d37726cea8cb2865d95763d57488ac","value":0.00000546},{"txid":"8043ffae81153a6761ceb468fb8020720973af20be215c164aee1cc5d2f20acc","vout":1,"scriptPubKey":"76a91422842ff0e2468f61e1d06cd33b5829082f13b06c88ac","value":0.99974474}]' "mifTd7G59RPTuod9MZMP26XYX6HjvZiHKo" 0.00001
0100000002caad12ceea9ddfa8052b2cf9274cac781a61c899755ec491ea75dd309cc907040200000000ffffffffcc0af2d2c51cee4a165c21be20af7309722080fb68b4ce61673a1581aeff43800100000000ffffffff036279f505000000001976a91422842ff0e2468f61e1d06cd33b5829082f13b06c88ac0000000000000000166a146f6d6e69000000000000000200000004a817c80022020000000000001976a914cecf58a478037b4c0f4b2d3019e67fb619f35f4988ac00000000

omnicore-cli "signrawtransaction" "0100000002caad12ceea9ddfa8052b2cf9274cac781a61c899755ec491ea75dd309cc907040200000000ffffffffcc0af2d2c51cee4a165c21be20af7309722080fb68b4ce61673a1581aeff43800100000000ffffffff036279f505000000001976a91422842ff0e2468f61e1d06cd33b5829082f13b06c88ac0000000000000000166a146f6d6e69000000000000000200000004a817c80022020000000000001976a914cecf58a478037b4c0f4b2d3019e67fb619f35f4988ac00000000"
{
  "hex": "0100000002caad12ceea9ddfa8052b2cf9274cac781a61c899755ec491ea75dd309cc90704020000006a47304402203424faaf9f1b450829424a95b6c1b7fe27ae82de48f78d111497a7ce331e8247022031993226a51a71e52e1dbea9c72ebea2b15495261b59d45a5584d15ed5714d30012102db88bd94aa0baed2ea747e84d4a26511e77dd77f54b5a70680aa82b275e38345ffffffffcc0af2d2c51cee4a165c21be20af7309722080fb68b4ce61673a1581aeff4380010000006b48304502210096f0df966789173b70f199a4efc7ba842f7f389ecf7d5090afebcd9031d1f72602205fa3540b03cf53741bddb78fb202917ebf1bc9150cd05953551fd1014fbceaa30121021708b33c2f8b95f89b9d6ec5f5199d362e8f880b546ec94fc53d5241f9cf5729ffffffff036279f505000000001976a91422842ff0e2468f61e1d06cd33b5829082f13b06c88ac0000000000000000166a146f6d6e69000000000000000200000004a817c80022020000000000001976a914cecf58a478037b4c0f4b2d3019e67fb619f35f4988ac00000000",
  "complete": true
}

omnicore-cli "sendrawtransaction" "0100000002caad12ceea9ddfa8052b2cf9274cac781a61c899755ec491ea75dd309cc90704020000006a47304402203424faaf9f1b450829424a95b6c1b7fe27ae82de48f78d111497a7ce331e8247022031993226a51a71e52e1dbea9c72ebea2b15495261b59d45a5584d15ed5714d30012102db88bd94aa0baed2ea747e84d4a26511e77dd77f54b5a70680aa82b275e38345ffffffffcc0af2d2c51cee4a165c21be20af7309722080fb68b4ce61673a1581aeff4380010000006b48304502210096f0df966789173b70f199a4efc7ba842f7f389ecf7d5090afebcd9031d1f72602205fa3540b03cf53741bddb78fb202917ebf1bc9150cd05953551fd1014fbceaa30121021708b33c2f8b95f89b9d6ec5f5199d362e8f880b546ec94fc53d5241f9cf5729ffffffff036279f505000000001976a91422842ff0e2468f61e1d06cd33b5829082f13b06c88ac0000000000000000166a146f6d6e69000000000000000200000004a817c80022020000000000001976a914cecf58a478037b4c0f4b2d3019e67fb619f35f4988ac00000000"
38af207ff3c32425de424aa2471e5e6d968f7401e9a65bdc9ac3875a849900ee

**Comment by dexX7** [comment]
Hi, it looks like you already found the tutorial for building raw transactions. As long as the first transaction input is from the token source, you can use other inputs.

There is an outstanding pull request to handle this for you, which you might check out:

https://github.com/OmniLayer/omnicore/pull/658

Otherwise it's going to be integrated in the next few days and is part of the next release, which is expected in about one month.
