### ISSUE TITLE
How to integrate Omnicore in exchange?

### ISSUE THREAD

**Issue by vimalbera92** [OmniLayer/omnicore#678]
I'm exploring omnilayer and I'm wondering about it's integration in exchange. 

Let's say I've set up node and created addresses for A, B and C users. A and B user deposited 100 Omni to their address and C wants to withdraw 150 Omni to some other wallet on exchange XYZ.

I understand there is a method `omni_send` which will use for simple send functionality but as it requires `from_address`, do we need to sweep out tokens from user A and B's address to some other central address `CW`(let's say cold wallet address) through which withdrawal will happen? If yes, then can I use BTC from my cold wallet(CW) to pay for fees while transferring omni from user's address to CW?

Can you provide me some reference for such integration for exchange? I'm already done with deposit part and researching on withdrawal options. 

Thank you,
Vimal

**Comment by JoeWallCrypt0** [comment]
I'm also interested in this. If I try `omni_getbalance` I get 100 omnis each for user A and B, and 0 omni for user C. So user is unable to withdraw.

I can try to do several `omni_send`from A and B to C but would require btc transaction fees

For bitcoin, I am able to do above with HD address generation but not sure about process for Omnicore

Thanks

**Comment by vimalbera92** [comment]
Omni will work same as ethereum. So you have to fetch coins from user's address to hot wallet and withdrawal will work from hot wallet.

Hope this answers your doubt.

Thanks,
Vimal

**Comment by dexX7** [comment]
> I can try to do several omni_sendfrom A and B to C but would require btc transaction fees

Right. Omni transactions use Bitcoin transactions, so you may have to fund destinations, before they can move tokens.

However, I recently merged #658, which should make things easier.

For a few hints regarding an integration, check out the following post:

https://github.com/OmniLayer/omnicore/wiki/Platform-Integration-of-Omni-Core
