### ISSUE TITLE
I cannot use omni_send

### ISSUE THREAD

**Issue by egonson** [OmniLayer/omnicore#679]
./omnicore-cli help omni_send
help: unknown command: omni_send

Why does my omnicore-cli not have the 'omni_send' method?

omni version is origin/master
commit 5d5afbb37e812061c45cb14b0a65650dfb078564
Merge: 1ff8375 b236998
Author: dexX7 <dexx@bitwatch.co>
Date:   Tue Jun 12 07:54:13 2018 +0200

available 'omni_' methods are...

== Omni layer (data retrieval) ==
omni_getactivations
omni_getactivecrowdsales
omni_getactivedexsells ( address )
omni_getallbalancesforaddress "address"
omni_getallbalancesforid propertyid
omni_getbalance "address" propertyid
omni_getbalanceshash propertyid
omni_getcrowdsale propertyid ( verbose )
omni_getcurrentconsensushash
omni_getfeecache ( propertyid )
omni_getfeedistribution distributionid
omni_getfeedistributions propertyid
omni_getfeetrigger ( propertyid )
omni_getgrants propertyid
omni_getinfo
omni_getmetadexhash propertyId
omni_getorderbook propertyid ( propertyid )
omni_getpayload "txid"
omni_getproperty propertyid
omni_getseedblocks startblock endblock
omni_getsto "txid" "recipientfilter"
omni_gettrade "txid"
omni_gettradehistoryforaddress "address" ( count propertyid )
omni_gettradehistoryforpair propertyid propertyid ( count )
omni_gettransaction "txid"
omni_listblocktransactions index
omni_listpendingtransactions ( "address" )
omni_listproperties

== Omni layer (payload creation) ==
omni_createpayload_cancelalltrades ecosystem
omni_createpayload_canceltradesbypair propertyidforsale propertiddesired
omni_createpayload_canceltradesbyprice propertyidforsale "amountforsale" propertiddesired "amountdesired"
omni_createpayload_changeissuer propertyid
omni_createpayload_closecrowdsale propertyid
omni_senddexaccept propertyid "amount"
omni_createpayload_dexsell propertyidforsale "amountforsale" "amountdesired" paymentwindow minacceptfee action
omni_createpayload_disablefreezing propertyid
omni_createpayload_enablefreezing propertyid
omni_createpayload_freeze "toaddress" propertyid amount 
omni_createpayload_grant propertyid "amount" ( "memo" )
omni_createpayload_issuancecrowdsale ecosystem type previousid "category" "subcategory" "name" "url" "data" propertyiddesired tokensperunit deadline earlybonus issuerpercentage
omni_createpayload_issuancefixed ecosystem type previousid "category" "subcategory" "name" "url" "data" "amount"
omni_createpayload_issuancemanaged ecosystem type previousid "category" "subcategory" "name" "url" "data"
omni_createpayload_revoke propertyid "amount" ( "memo" )
omni_createpayload_sendall ecosystem
omni_createpayload_simplesend propertyid "amount"
omni_createpayload_sto propertyid "amount" ( distributionproperty )
omni_createpayload_trade propertyidforsale "amountforsale" propertiddesired "amountdesired"
omni_createpayload_unfreeze "toaddress" propertyid amount 

== Omni layer (raw transactions) ==
omni_createrawtx_change "rawtx" "prevtxs" "destination" fee ( position )
omni_createrawtx_input "rawtx" "txid" n
omni_createrawtx_multisig "rawtx" "payload" "seed" "redeemkey"
omni_createrawtx_opreturn "rawtx" "payload"
omni_createrawtx_reference "rawtx" "destination" ( amount )
omni_decodetransaction "rawtx" ( "prevtxs" height )

**Comment by egonson** [comment]
Because of --disable-wallet option in configuration
Solved.

**Comment by dexX7** [comment]
Thanks for providing a solution also, @egonson!
