### ISSUE TITLE
omni_send error: Invalid amount

### ISSUE THREAD

**Issue by lixuegang** [OmniLayer/omnicore#680]
JSON-RPC
{"result":null,"error":{"code":-3,"message":"Invalid amount"},"id":"-7602726211412766331"}

**Comment by dexX7** [comment]
Hi there,
can you please also post which arguments you used? An invalid amount error is usually thrown, when trying to send something like 0 tokens.

**Comment by lixuegang** [comment]
OK, Thank you.
