### ISSUE TITLE
Several questions about USDT.

### ISSUE THREAD

**Issue by sunwell** [OmniLayer/omnicore#681]
When I ran `./omnicored` command, I got these below:

```
2018-07-12 01:55:09 Initializing Omni Core v0.3.0 [main]
2018-07-12 01:55:09 Loading trades database: OK
2018-07-12 01:55:09 Loading send-to-owners database: OK
2018-07-12 01:55:09 Loading tx meta-info database: OK
2018-07-12 01:55:09 Loading smart property database: OK
2018-07-12 01:55:09 Loading master transactions database: OK
2018-07-12 01:55:09 Loading fee cache database: OK
2018-07-12 01:55:09 Loading fee history database: OK
2018-07-12 01:55:09 Loading persistent state: OK [block 259388]
2018-07-12 01:55:09 Exodus balance: 2239.81478813 OMNI
2018-07-12 01:55:09 Omni Core initialization completed
```

I guess this command is running on the main net, and loading blocks to my local.

Doubt A, when I ran `./omnicore-cli omni_listproperties` command, I only got two types of currencies, like below:

```
[
  {
    "propertyid": 1,
    "name": "Omni",
    "category": "N/A",
    "subcategory": "N/A",
    "data": "Omni serve as the binding between Bitcoin, smart properties and contracts created on the Omni Layer.",
    "url": "http://www.omnilayer.org",
    "divisible": true
  },
  {
    "propertyid": 2,
    "name": "Test Omni",
    "category": "N/A",
    "subcategory": "N/A",
    "data": "Test Omni serve as the binding between Bitcoin, smart properties and contracts created on the Omni Layer.",
    "url": "http://www.omnilayer.org",
    "divisible": true
  }
]
```

Doubt B, and when I ran `./omnicore-cli omni_send` command, no matter how much I sent and what kind of currency I configured, I always got a message `Sender has insufficient balance`. 

And doubt C, I was a bit confused by `bitcoin.conf` file, and my conf content like below, does it has any problem?
```
#server=1 tells Bitcoin-Qt and bitcoind to accept JSON-RPC commands
server=1


# If no rpcpassword is set, rpc cookie auth is sought. The default `-rpccookiefile` name
# is .cookie and found in the `-datadir` being used for bitcoind. This option is typically used
# when the server and client are run as the same user.
# If not, you must set rpcuser and rpcpassword to secure the JSON-RPC api. The first
# method(DEPRECATED) is to set this pair for the server and client:
rpcuser=omnicorerpc
rpcpassword=5hMTZI9iBGFqKxsWfOUF


# By default, only RPC connections from localhost are allowed.
# Specify as many rpcallowip= settings as you like to allow connections from other hosts,
# either as a single IPv4/IPv6 or with a subnet specification.

# NOTE: opening up the RPC port to hosts outside your local trusted network is NOT RECOMMENDED,
# because the rpcpassword is transmitted over the network unencrypted.
rpcallowip=127.0.0.1


# Listen for RPC connections on this TCP port:
rpcport=8332

txindex=1

#datacarriersize=80
#logtimestamps=1
#omnidebug=tally
#omnidebug=packet
```

Appreciate for your any reply. Thx.

**Comment by dexX7** [comment]
Hi @sunwell,

based on the first lines you posted, it looks like your client is currently at block 259388. This is far away from the actual chain length. In this case no other properties were scanned and the funds you sent were also not yet seen.

Is the client still synchronizing?

**Comment by sunwell** [comment]
@dexX7 Thank u for ur reply first. U unravel my doubts.
Yeah, I saw the latest block index is 531596 and I have stopped synchronizing. 
I will continue my synchronization tonight. And by the way, how much storage the entire USDT chain will take? And where are these blocks stored in?

In addition, can u tell me ur twitter or wechat or what ever else? So that I can communicate with u conveniently.

**Comment by sunwell** [comment]
@dexX7
 Hi, I got a new question about USDT/omnicore.
I use ./omnicored command to load blocks from main net on my own Mac, but it is already about 111GB and the block number is still too small (about 432687). My disk almost explode.
Do I need load all blocks? And Are there any solution to solve this? Or build a server with a large disk capacity？
Thx~

**Comment by dexX7** [comment]
Hi @sunwell, my Twitter handle is @dexx7y and my Telegram handle is also @dexx7y.

You need all the blocks, which currently take about 220 GB, if I'm not mistaken.

**Comment by sunwell** [comment]
ok, thx~ @dexX7
