### ISSUE TITLE
Valid omni transaction has no recipient, fund is lost

### ISSUE THREAD

**Issue by nbphuoc** [OmniLayer/omnicore#682]
I accidentally built this valid omni transaction without a recipient.
https://www.omniexplorer.info/tx/bfd1d982c137beb23035838505505265e836d12ae423943c5fc07f566a94f14a
It is still considered valid on the omni network and the property amount is deducted from the sending address. However, there is no recipient so the fund is lost.
This transaction should be considered invalid and the fund should still remain in the sending address.

**Comment by dexX7** [comment]
Hi @nbphuoc,

thanks for the report. On a protocol level this is actually the case: when no receiver is specified, the funds are send to the sender! So in this case no tokens are lost and still in control of 1BUJGjEqoCK46yk5uuw1T35jAzSFbpGr4F.

However, this is certainly an issue with Omni Explorer, which doesn't show the funds. Please don't worry, @achamely will provide a fix. I created #152 to track it..

**Comment by dexX7** [comment]
The issue has been resolved:

https://www.omniexplorer.info/address/1BUJGjEqoCK46yk5uuw1T35jAzSFbpGr4F
https://www.omniexplorer.info/tx/bfd1d982c137beb23035838505505265e836d12ae423943c5fc07f566a94f14a
