### ISSUE TITLE
https://omniexplorer.info/  shows nothing?

### ISSUE THREAD

**Issue by sunwell** [OmniLayer/omnicore#683]
Through my debug, I saw these two apis failed:
https://api.omniexplorer.info/v1/system/status
https://api.omniexplorer.info/v1/transaction/general/0

Do u have the same problem? 
Please feel free to comment.

**Comment by dexX7** [comment]
Hi @sunwell, the API is up for me, might have been a temporary failure.

**Comment by sunwell** [comment]
@dexX7 yeah, it is a temporary failure. I have closed this issue.
