### ISSUE TITLE
why USDT have more than one property id?

### ISSUE THREAD

**Issue by kazaff** [OmniLayer/omnicore#685]
Many articles says that the USDT's property id is 31?
What about 192,330 and 341?
I found them on [office assets page](https://www.omniwallet.org/explorer/assets)

**Comment by vagabondan** [comment]
Any id except id=31 could be just fake ones, because anyone can create his/her own token with any additional info and token name.

**Comment by kazaff** [comment]
@vagabondan  thank you for answer

**Comment by dexX7** [comment]
I added a wiki entry for this question:

https://github.com/OmniLayer/omnicore/wiki/Why-are-there-multiple-tokens-with-similar-names,-e.g.-TetherUS%3F

**Comment by kazaff** [comment]
thanks
