### ISSUE TITLE
Error: listunspent alway returns an Empty Array

### ISSUE THREAD

**Issue by phongnguyen6691** [OmniLayer/omnicore#686]
Hi all,

This is urgent to me. I finished to set up the Omni core and it synced 100% successfully.
My version info:
![image](https://user-images.githubusercontent.com/6027307/42731792-d3639186-883e-11e8-965c-14b5ab0a9cd7.png)

Everything seems working fine now except function "listunspent".

Following the article here to create a raw transaction https://github.com/OmniLayer/omnicore/wiki/Use-the-raw-transaction-API-to-create-a-Simple-Send-transaction

I failed at the first step, the function "listunspent" always return an empty array even I tried with many addresses that I'm sure they are having some balances.

For example this address 1F2PZKpbr6ctAyHRxzeHtxLbXLFVmNSe52 https://www.omniexplorer.info/search/1F2PZKpbr6ctAyHRxzeHtxLbXLFVmNSe52

![image](https://user-images.githubusercontent.com/6027307/42731680-a8452818-883c-11e8-954b-fb2ff84c3d3b.png)

Could anyone please help to tell me what was wrong? Thank you so much!

**Comment by dexX7** [comment]
Hi @phongnguyen6691,

listunspent only shows unspent outputs that you have the private key for. Do you control the address you provided?

**Comment by phongnguyen6691** [comment]
thanks a lot @dexX7. Close the ticket
