### ISSUE TITLE
Stable mainnet production ready omni wallet

### ISSUE THREAD

**Issue by vagabondan** [OmniLayer/omnicore#688]
Hello!
Unfortunately, current omnicore is too unstable. Most annoying bugs:
Bug 1. persistent state loss
Bug 2. long RPC calls (~ 1 min or longer for simple requests like getinfo) and finally wallet freezes after several RPC calls

Bug 1 can be avoided by periodic backups of OMNI layer files, so it seems less importatnt than bug 2.
Bug 2 makes omnicore almost totally useless for automated interactions.

Can you recommend:
1. stable software for Omnilayer mainnet production environment usage?
2. stable environment (if you can't reproduce Bug 2, where do you run it?) ?
3. workaround for bug 2?

**Comment by dexX7** [comment]
Hi @vagabondan,

slow responses are usually the case, when the client is still synchronizing, because the processing of new blocks is blocking. The persistence issue is fixed in the develop branch.

**Comment by vagabondan** [comment]
Hi, 
@dexX7, no, it's not our case. I wrote about fully synced node. 
Fully synced node responses as long as ~ 1 min for simple request and freezes after several successive requests.
It's reproduced under Ubuntu 16.04, Ubuntu 18.04, latest Alpine Linux.

Didn't you reproduced it? If not, please tell me your environment configuration.

**Comment by vagabondan** [comment]
@dexX7, after some investigation with gdb I believe, that:
1. The main issue with long RPC calls is that msghand (message handler) and httpworker threads compete for cs_main mutex. msghand blocks majority of rpc calls while reading/writing/parsing transactions from new blocks (or because of neighbour nodes requests) by acquiring cs_main mutex.
2. Freezing is result of deadlock between two rpc threads. Hypothetical case:
actors: msghand, rpc1, rpc2 threads
1. rpc1 takes request for processing, tries to lock cs_main mutex, but waits until msghand releases it
2. about the same time rpc2 takes another request for processing, which requires another mutex (maybe cs_tally?) to lock along with cs_main mutex lock. rpc2 successfully acquires cs_tally mutex, but waits for cs_main because it is locked by msghand.
3. being finished request processing, msghand releases cs_main mutex
4. rpc1 acquires cs_main mutex and tries to acquire cs_tally mutex but has to be waiting for cs_tally because it is locked by rpc2
5. as a result: deadlock
rpc1 acquired cs_main mutex but waits for cs_tally mutex
rpc2 acquired cs_tally mutex, but waits for cs_main mutex
msghand waits for cs_main mutex 
and the whole wallet freezes.

**Comment by vagabondan** [comment]
@dexX7 I think this is one of the many examples of deadlocks because you lock successively at least 3 mutexes at different places: cs_main, cs_tally, cs_tx_cache...
This code should be extensively reviewed for thread safety considerations.

**Comment by vagabondan** [comment]
As workaround, I've added LOCK(cs_main) in all omni RPC calls, that use populateRPCTransactionObject function. This corresponds to bitcoin core way of call RPC procedures like getblock. Now I'm testing, but after 30k RPC calls it seems that everything is ok.
I'll come back with pull request to develop branch some time later.

**Comment by vagabondan** [comment]
It seems, that solution is even simpler:
just replace at omnicore.cpp:parseTransaction() LOCK macro with LOCK2:

    { // needed to ensure the cache isn't cleared in the meantime when doing parallel queries
    //LOCK(cs_tx_cache);
    LOCK2(cs_main,cs_tx_cache); // cs_main should be locked first to avoid deadlocks with cs_tx_cache at FillTxInputCache(...)->GetTransaction(...)->LOCK(cs_main)

**Comment by dexX7** [comment]
Thank you so much for looking into this!
