### ISSUE TITLE
Wallet creates class C transactions, even if not enabled yet

### ISSUE THREAD

**Issue by dexX7** [OmniLayer/omnicore#69]
The `ClassAgnosticWalletTXBuilder` creates class C transactions, even if this feature might not be enabled/live yet.

Suggested fix:

```diff
 static bool UseEncodingClassC(size_t nDataSize)
     size_t nTotalSize = nDataSize + 2; // Marker "om"
     bool fDataEnabled = GetBoolArg("-datacarrier", true);
 
+    int nBlockNow = GetHeight();
+    if (!isAllowedOutputType(TX_NULL_DATA, nBlockNow)) {
+        fDataEnabled = false;
+    }
     return nTotalSize <= nMaxDatacarrierBytes && fDataEnabled;
 }
```

However, I'm wondering: is there ever the case where the current height is not good enough? For example, could there be the case, where class C transactions might be created, even if not supported yet? I can't think of any case though ...

**Comment by zathras-crypto** [comment]
Yep yep, nice thanks bud - I had been intending to drop a fix in for this

**Comment by dexX7** [comment]
It's covered by #68, too.
