### ISSUE TITLE
omni_listtransaction ignore 2nd (count) and 3rd (skip) arguments

### ISSUE THREAD

**Issue by mcb345** [OmniLayer/omnicore#692]
I tried calling `omni_listtransactions` from RPC,

```
{  
  "method" : "omni_listtransactions",  
  "params" : ["",3,3]  
}
``` 

I have 3 transactions (incoming/Simple Send)

This method returned all of my transaction even if I put that 2nd and 3rd param, which supposed to show no record , as the 3rd args (which should be skipping x amount of transaction) got ignored too.

Any idea for this to make this thing work like Bitcoin listtransactions ?

**Comment by dexX7** [comment]
Hi @mcb345,

in the current release and master branch there is the issue as you described. We fixed it via #592, which is going to be part of the next release. The next version of Omni Core is going to be released within a month, but you could try to give building from the develop branch a chance.

Please note, the RPC only works for wallet transactions and can not be used to retrieve arbitrary data.
