### ISSUE TITLE
Class C encoded alerts don't pass the marker check

### ISSUE THREAD

**Issue by dexX7** [OmniLayer/omnicore#70]
Omni Core alerts use `version = 65535` and `type = 65535`.

This doesn't pass the marker check currently:

```c++
if(("6f6d0000" == temp_op_return_script_data[0].substr(0,8)) ||
   ("6f6d0001" == temp_op_return_script_data[0].substr(0,8))) { // only v0/v1 txs are live, add 6f6d0002 to parse a v2 tx when one goes live
    hasOmniBytes = true;
}
```

The way to go is probably to include the extended marker `"6f6dffff"` here.

**Comment by zathras-crypto** [comment]
Ahh good pickup there dude, though FYI I'd kind of envisaged alerts as being one of those "too big for Class C" transactions (due to the likely inclusion of a text message) which is probably why I missed this...

Nice catch will add a fix :)

**Comment by zathras-crypto** [comment]
Awesome I see you've already got a fix in another PR :)

**Comment by dexX7** [comment]
Yup, I included it in the other PR, but I could push a seperate one, and address this individually, if you prefer.

While 40 byte might be too small, 80 byte probably offer enough space for a small message and URL.
