### ISSUE TITLE
When I send USDT, receiver also get tiny BTC (0.00000540). What is this? What for?

### ISSUE THREAD

**Issue by kensama7** [OmniLayer/omnicore#701]
When I send USDT, receiver also get tiny BTC (0.00000540). What is this?
https://live.blockcypher.com/btc-testnet/tx/fc6956d5d91fdb690826ab7e9d318171b4ef8b3335c3d0d1b142d6bd3c1765ac/

And is it fixed value or not?

**Comment by dexX7** [comment]
The Omni Layer uses Bitcoin transactions to add payloads, which are interpreted by Omni aware software.

This output, with a value of a few satoshi, is needed to "tag" the recipient of an Omni Layer transaction.

**Comment by JoeWallCrypt0** [comment]
@dexX7 Would that BTC amount is enough for future USDT transactions?

I have custody of customer's USDTs and I want to know if I need additional BTC in Omnicore when they want to withdraw

**Comment by dexX7** [comment]
Hi @JoeWallCrypt0,

it's not enough to cover the whole transaction fee, but when funding from another source, it is sufficient.

I merged a patch to allow funding from a second source, which is going to be part of the next release:

https://github.com/OmniLayer/omnicore/pull/658

**Comment by JoeWallCrypt0** [comment]
Thanks @dexX7 this helps
