### ISSUE TITLE
Where is reciever address located in omni transaction data?

### ISSUE THREAD

**Issue by shahidzebpay** [OmniLayer/omnicore#703]
Hi,

After I do omni_gettransaction txId or omni_decodetransaction txraw then I get the following response.

```
{
  "txid": "f4f50e4cd2a06f62db125a96d6c945dee531f8e5756c698bc4c8f2a8dd454edd",
  "fee": "0.00005000",
  "sendingaddress": "2MyuDmv4NL7RHSMDVYraSNwmGUgR2Sp3upT",
  "referenceaddress": "mgo8TBpoS5UmMFNgmaFi8NJtzDd6ZjcQ57",
  "ismine": false,
  "version": 0,
  "type_int": 0,
  "type": "Simple Send",
  "propertyid": 1,
  "divisible": true,
  "amount": "0.01000000",
  "confirmations": 0
}
```
I am not clear about the receiver address in it. 

Any help would be appreciated.

**Comment by dexX7** [comment]
Hi there,

the receiver of this transaction is the "referenceaddress" in this output.

Does this clear your question, or where you asking about the actual on-chain transaction structure?

**Comment by shahidzebpay** [comment]
Thanks, this answers my question.
