### ISSUE TITLE
How to use omni_createrawtx_change to pay fee for sender?

### ISSUE THREAD

**Issue by zhlqee** [OmniLayer/omnicore#708]
Hi,
    I have 2 address(`mp4vDn4J5Q24FM9chHY9bfSTG9fhqUyCi9`, `moCDGyDMBWB2Va8W2McAUk3sppNGmRS9Lk`) with OMNI and 1 address(`n1FGCTNVq3oFkQ1n4G1tQ3jRXeaN39LWG5`) with BTC.
 I want to pay transaction fee from `n1FGCTNVq3oFkQ1n4G1tQ3jRXeaN39LWG5` for transaction from my omni addresses.What shall I do?

**Comment by wll2007** [comment]
@zhlqee  now I have  a scene that same to your, how can you come true it ?
