### ISSUE TITLE
OMNI node freezes after RPC requests

### ISSUE THREAD

**Issue by whateverpal** [OmniLayer/omnicore#709]
Hello,

I've been pulling Omni transactions data by sequentially scanning blocks and doing the following RPC calls for each block: getblockhash -> getblock -> omni_listblocktransactions -> (for each tx: omni_gettransaction). Somewhere around block 450000 the Omni node started freezing every now and then after RPC request is made. When frozen, it doesn't respond to any further calls (via RPC or CLI), and CPU activity falls to zero, only hard shutdown via kill -9 helps. I suspect there's a deadlock somewhere in the Omni part of RPC functionality.

**Comment by dexX7** [comment]
Hi there,

I merged a potential fix for this issue a few minutes ago. Are you able to test the develop branch?

**Comment by romever** [comment]
It's awesome!This issue has plagued me for several days.

**Comment by dexX7** [comment]
Hopefully resolved via #711.
