### ISSUE TITLE
I think block Full-sync is pain point of omnicore.

### ISSUE THREAD

**Issue by kensama7** [OmniLayer/omnicore#712]
I think block Full-sync is pain point of omnicore.
Can I avoid block Full-sync through coping block files or another way?

**Comment by dexX7** [comment]
Hi @kensama7,

there are a few similar reports of a slow download and synchronization, while we were unable to confirm it. The speed depends on your internet connection and computation power. It usually takes between half a day to a few days.

If you have 8 GB or more RAM, you can start Omni Core with `-dbcache=5000` to speed things up a bit.

Do you have an already synchronized Bitcoin Core client?

**Comment by kensama7** [comment]
Yes. I have synchronized Bitcoin Core clients. And I use Omni Core on Linux machine with 64G ram.

**Comment by kensama7** [comment]
Can I set up the `-dbcache` more than 5000. And is it worth?

**Comment by dexX7** [comment]
Awesome, please try this. You could also set `-omnidebug=none`, which may speed things up a little bit further.

**Comment by sybot99** [comment]
dexX7
-omnidebug=none
it's dont work: http://prntscr.com/kdhpkg

**Comment by dexX7** [comment]
20 days? How fast is your internet connection?

The `-dbcache=5000 -omnidebug=none` is added, when starting Omni Core, e.g.:

```
./omnicored -dbcache=5000 -omnidebug=none
```

**Comment by sybot99** [comment]
dexX7
new notebook. only win 10 there
100mb/c

**Comment by dexX7** [comment]
Hey @sybot99, sorry for the late reply.

Can you please locate the `omnicored.exe` file? If so, start a cmd (press Windows + R, then type "cmd", hit enter), and please try the following:

```
"C:\...\omnicored.exe" -dbcache=5000 -omnidebug=none
```

**Comment by sybot99** [comment]
dexX7
Thx ! Is there any possibility to decrease core size ? (I mean 200Gb+)

**Comment by dexX7** [comment]
Hi @sybot99, currently unfortunately not.

**Comment by weitaolee** [comment]
sync 30 days, and not full sync now

**Comment by gggin** [comment]
I use digitalocean and I found that no cpu or disk or RAM is in the limit.
So Maybe sth is wrong? or Just one process cannot use all CPU?

**Comment by kiel-cristian** [comment]
I'm having problems with digitalocean too, any solution?

**Comment by gggin** [comment]
@kiel-cristian  old exprience, you must use good cpu. the limit is on hash calculate.

**Comment by dexX7** [comment]
Sorry, can you clarify what you mean by "no cpu or disk or RAM is in the limit"?

**Comment by gggin** [comment]
@dexX7 any software is slow, OS is running on cpu calculations or memory swap. After a few time I found that the limit is on cpu.(cpu is usually slow on default vps machines.)

**Comment by kiel-cristian** [comment]
I was using a CPU optimized machine. And the CPU was below the 10% of It's capacity. It took around 9/10 days to be on sync. I would say that the problem was related to something else. Maybe peers networking

**Comment by dexX7** [comment]
The synchronization speed was significantly improved in the latest version:

https://github.com/OmniLayer/omnicore/releases
