### ISSUE TITLE
Omnicore node showing 'still scanning' on restart 

### ISSUE THREAD

**Issue by josepajay** [OmniLayer/omnicore#717]
![screenshot from 2018-08-06 16-54-13](https://user-images.githubusercontent.com/15032460/43717295-b3d2f63c-99a4-11e8-90b8-1adbb58b563b.png)

I have restarted node, since it was too slow. After restart I am getting error code -28 and shows still scanning. Its been more than 6 hours now after restart.

And time remaining is showing in weird way which cannot be interpreted

**Comment by dexX7** [comment]
Hi @josepajay,

did you import new addresses? This should resolve after some time.

It's hard to tell for me, which part causes this, but we've merged performance improvements into the develop branch, which should make things a bit faster.

**Comment by assionyang** [comment]
Have you solved it? I also encountered this problem.

**Comment by josepajay** [comment]
@assionyang  I got this resolved by running Omnicore in a production machine which has 100+ gbs of ram and lots of processing power. 

@dexX7 I did not  import new addresses. Also I was running the dev branch. (since I wanted the 2 omni rpc which was added in dev branch)

Initially I was running  omnicore in my personal workstation which has 16gb ram, intel i5. I was facing huge delays in rpc, more than 5 seconds most of the times. And when I restarted node to resolve these issues it got even worse and I raised this issue.

**Comment by assionyang** [comment]
@josepajay 
Thank you very much. I'm trying it on a machine with 64G memory, but the omnicore synchronization node is really slow.

**Comment by wenweih** [comment]
[OMNI CORE V0.3 RELEASED](https://blog.omni.foundation/)
> To avoid any possible database corruptions/needing to rebuild the blockchain db any running client will need to perform a clean stop using the rpc command “omnicore-cli stop”

https://github.com/OmniLayer/omnicore/issues/484#issuecomment-313322566

**Comment by laviua** [comment]
thanks for this comment )
i thought what's wrong every time...

**Comment by binlaniua** [comment]
how to solved it ? almost 7 hour... too slow

**Comment by dexX7** [comment]
Hi @binlaniua, unfortunately you need some patience.
