### ISSUE TITLE
does omni_createfunded_send work? [Error choosing inputs for the send transaction]

### ISSUE THREAD

**Issue by vetal20600** [OmniLayer/omnicore#720]
I built develop version and tried to use new features.
balance of address 1GFn8X9dtsvjLeXQ65DVjd4vttdtjqQkvx is:
```
~/dev_omnicore-cli -datadir=/home/s8273453mellybin_/omnicore -port=28333 omni_getbalance "1GFn8X9dtsvjLeXQ65DVjd4vttdtjqQkvx" 31
{
  "balance": "0.21000000",
  "reserved": "0.00000000"
}
```

then I put:
```
~/dev_omnicore-cli -datadir=/home/s8273453mellybin_/omnicore -port=28333 omni_createfunded_send "1GFn8X9dtsvjLeXQ65DVjd4vttdtjqQkvx" "1Lit2yabMhM8K9UixVr5KKVxmnJMN3U8kg" 31 "0.2" "1Lit2yabMhM8K9UixVr5KKVxmnJMN3U8kg"
the result of command was:
01000000066a0ca78b0c74554a72d39f0c32ba332b8cd18b5fd6a66c5e5f930f6c3c5d5b2a0200000000ffffffff80167407be47871a26355e87732fb2429841d4024f0e236e5e33d5f1b2571ea10200000000ffffffff839468cff6be55efbe26ae6e278334a79ae69b2f7652e81d9246340886b36a770100000000ffffffffcb16b423c448ce8830c2e0db499763ecc0d9682ca7d4e8c41b18b747fc3886430100000000fffffffffc0f938f82f4a1d15e61f700bfac0ac5d7ed6ec6d5ab5496419f9f428df5e8330200000000ffffffff80167407be47871a26355e87732fb2429841d4024f0e236e5e33d5f1b2571ea10100000000feffffff03e15b0700000000001976a914d8560ba036129944b20a81163664a56c08284d8288ac0000000000000000166a146f6d6e69000000000000001f0000000001312d0022020000000000001976a914d8560ba036129944b20a81163664a56c08284d8288ac00000000
```
My second try gave me error below: 
```
~/dev_omnicore-cli -datadir=/home/s8273453mellybin_/omnicore -port=28333 omni_createfunded_send "1GFn8X9dtsvjLeXQ65DVjd4vttdtjqQkvx" "1Lit2yabMhM8K9UixVr5KKVxmnJMN3U8kg" 31 "0.2" "1Lit2yabMhM8K9UixVr5KKVxmnJMN3U8kg"
error code: -212
error message:
Error choosing inputs for the send transaction
```

How to use this method? What went wrong?

**Comment by vetal20600** [comment]
I got to do signrawtransaction
then sendrawtransaction

**Comment by vetal20600** [comment]
Yes, this is what happened. I did not know that I have also to do signrawtransaction, then sendrawtransaction.

**Comment by dexX7** [comment]
Hm.. I see. And I can see how this could turn into a huge issue, e.g. when the user uses "omni_createfunded_send" a few times, but doesn't broadcast the transactions. He or she will then end up with locked UTXOs and may not even have an idea what's happening or how to unlock them.

Do you think it could be better to not lock the UTXO as per default? However, this bears the risk, that a second call uses the same UTXO as before.. :/

**Comment by vetal20600** [comment]
I guess you can just add description below after omni_createfunded_send command output about what to do next: 
```
1. signrawtransaction;
2. sendrawtransaction 
```

This is enough I think

**Comment by jarven-zhang** [comment]
> Hi there,
> 
> when using `omni_createfunded_send` the inputs are "locked", so they won't be selected a second time. I assume in your case this happened.

hi, do you know how to unlock the utxo ??
