### ISSUE TITLE
omni_funded_send invalid method omni core wallet 0.3.0

### ISSUE THREAD

**Issue by sgrmoharil** [OmniLayer/omnicore#737]
I want to withdraw USDT from one address of wallet to outside address and use third address which is in same wallet to pay transaction fee. As per documentations we can use omni_funded_send method for the same. But wallet is showing it as Invalid method. Please help.

**Comment by dexX7** [comment]
omni_funded_send is currently only available in the develop branch of this repository.

It's going to be released within two weeks though. :)

**Comment by sgrmoharil** [comment]
Hi dexX7,

Thanks for the reply.  :)
