### ISSUE TITLE
How to create Tether wallet in Omni Core Win ?

### ISSUE THREAD

**Issue by sybot99** [OmniLayer/omnicore#738]
I download and update full Omni core. How to create Tether address here ?
As I understand the USDT address = BTC address

One more question. How to make backup of this USDT address ?

**Comment by dexX7** [comment]
Hi,

you can go to the "receive" tab and then generate a new address. It's correct: Omni uses Bitcoin addresses and they can be backed up as regular addresses. In this case, you could backup your wallet via the file menu.

Please let me know, if you need more help. Until then, I'm going to close this issue.

**Comment by harrymaurya05** [comment]
> Hi,
> 
> you can go to the "receive" tab and then generate a new address. It's correct: Omni uses Bitcoin addresses and they can be backed up as regular addresses. In this case, you could backup your wallet via the file menu.
> 
> Please let me know, if you need more help. Until then, I'm going to close this issue.

I have setup Omni core on debian aws instance . how can i generate USDT(tether) address?

**Comment by santos177** [comment]
Hi @harrymaurya05  :  
It's just using getnewaddress RPC, like when you create any other normal bitcoin address. I hope it helps!
