### ISSUE TITLE
Sender has insufficient 

### ISSUE THREAD

**Issue by chenyunecjtu** [OmniLayer/omnicore#739]
{"txid":"2606f381f7e7a9bab42b8c58378d4875f15b94864abb1f3c67efa1b740cdc92c","fee":"0.00090000","sendingaddress":"mxJToM6XgMqeBv5CNnDZQKAs1HYqDrQVdc","referenceaddress":"mpKpT6qLSfugijMkWf3hYx5Eji8b2vbvf5","ismine":true,"version":0,"type_int":0,"type":"Simple Send","propertyid":1,"divisible":true,"amount":"100.00000000","valid":false,"invalidreason":"Sender has insufficient balance","blockhash":"000000000000016793a1ca113488d41f0a15bca5ff3ecce6ed6a169776cd713e","blocktime":1535079693,"positioninblock":663,"block":1408214,"confirmations":1} 

in wallet, one address has 100OMNI ,but no btc, other address hash btc

**Comment by alesito85** [comment]
Did you try the new method omni_funded_send or manually creating funded so that you can find token transfer from another account?

**Comment by chenyunecjtu** [comment]
@alesito85 use https://github.com/OmniLayer/omnicore/wiki/Use-the-raw-transaction-API-to-create-a-Simple-Send-transaction create raw transactions

**Comment by alesito85** [comment]
@chenyunecjtu did you try omni_funded_*?

**Comment by alesito85** [comment]
I am testing it on the develop branch. But am having issues with it... For some tokens at least on test network.

**Comment by chenyunecjtu** [comment]
@alesito85 
omni_createpayload_simplesend propertyid "amount"
omni_createrawtx_change "rawtx" "prevtxs" "destination" fee ( position )
omni_createrawtx_input "rawtx" "txid" n
omni_createrawtx_opreturn "rawtx" "payload"
omni_createrawtx_reference "rawtx" "destination" ( amount )

**Comment by chenyunecjtu** [comment]
@alesito85 omni_funded_* while file can found?

**Comment by alesito85** [comment]
What do you mean? If you compile omnicore from develop branch you will have these methods available. You will also see them in wiki on develop branch.

**Comment by chenyunecjtu** [comment]
@alesito85 
omni_createpayload_simplesend propertyid "amount"
omni_createrawtx_change "rawtx" "prevtxs" "destination" fee ( position )
omni_createrawtx_input "rawtx" "txid" n
omni_createrawtx_opreturn "rawtx" "payload"
omni_createrawtx_reference "rawtx" "destination" ( amount )
above command , can create raw transaction, which one address has btc, one address has omni?
last omni_funded_*  have a link?  i not found

**Comment by alesito85** [comment]
Here you go https://github.com/OmniLayer/omnicore/pull/728
But it appears there are quite a few issues. You can't send a master token (propertyid 1) unless you have sufficient BTC balance for fees on the withdrawing address. And you can't send any token unless you have at least some BTC balance on the withdrawing address.

**Comment by chenyunecjtu** [comment]
@alesito85 in testnet ,how get usdt coins

**Comment by alesito85** [comment]
There is no USDT on testnet (as far as I know). But you can create your own token and test with that, I did it that way.

Use https://github.com/OmniLayer/omnicore/blob/master/src/omnicore/doc/rpc-api.md#omni_sendissuancemanaged

And then grant so that you can get yourself some other tokens. You can configure it the same way as USDT is configured.

**Comment by chenyunecjtu** [comment]
@alesito85 thanks

**Comment by alesito85** [comment]
You're welcome

**Comment by chenyunecjtu** [comment]
@alesito85 compile soucre code error,error: call to '__builtin_constant_p' is ambiguous.
where can download dev bin program?

**Comment by alesito85** [comment]
I don't think that binaries are available.

**Comment by dexX7** [comment]
@chenyunecjtu: binaries are available here:

https://github.com/OmniLayer/omnicore/releases
