### ISSUE TITLE
assign other user to pay transaction fee

### ISSUE THREAD

**Issue by spursy** [OmniLayer/omnicore#740]
when i send transaction, can I assign other user to pay transaction fee?

**Comment by letreset** [comment]
#750 check this issue.

**Comment by dexX7** [comment]
Thanks @letreset. This is correct, see:

https://github.com/OmniLayer/omnicore/wiki/Is-it-possible-to-pay-transaction-fees-from-a-different-source%3F

Please let me know, if you need more help. Until then, I'm going to close this issue.
