### ISSUE TITLE
How to solve thi problem ?

### ISSUE THREAD

**Issue by alexperl123** [OmniLayer/omnicore#742]
E:\omni>omnicored -datadir=./omnidata
: Disabled transaction index detected.

Omni Core requires an enabled transaction index. To enable transaction indexing,
 please use the "-txindex" option as command line argument or add "txindex=1" to
 your client configuration file within your data directory.

Configuration file: C:\omni\omnidata\bitcoin.conf

Would you like Omni Core to attempt to update your configuration file accordingl
y?
Error: Please add txindex=1 to your configuration file manually.

Omni Core will now shutdown.
2018-08-24 10:17:43 Omni Core shutdown completed

**Comment by congnghiakhiem** [comment]
just add txindex=1 to your configuration file, then restart omnicored

**Comment by achamely** [comment]
@alexperl123 yup exactly what @congnghiakhiem said. 
You need to have `txindex=1` in the config file
