### ISSUE TITLE
Omnicore support of USDT / Tether

### ISSUE THREAD

**Issue by ric7ho** [OmniLayer/omnicore#743]
Hi there,

I am a bit confused about the current status of USDT. I would like to confirm my understanding here.

Right after the November 2017 hack, Tether released its own omnicore fork https://github.com/tetherto/omnicore/releases/tag/0.2.99.s to freeze stolen funds. However, when syncing mainnet, this version fails at block height 499200 with error "Shutting down due to unsupported feature activation (14: Unknown feature)Error: Shutting down due to unsupported feature activation (14: Unknown feature)"

At around the same time, omnicore v0.3 was released, allowing for issuers of centrally managed tokens (e.g. tether) to freeze accounts. This seems to be exactly what v0.2.99.s was trying to do.

My question is, if I want to run a full omnilayer node supporting Tether right now, is it safe to just run omnicore v0.3.0? If not, how can I resolve the issue of v.0.2.99.s dying at height 499200? Many thanks!

**Comment by sachnk** [comment]
+1

We're wondering the same thing. Any clarification would be appreciated!

**Comment by achamely** [comment]
@ric7ho @sachnk the 'fork' that Tether released was an intermediary fork that was deprecated once Omni Core v.0.3.0 was released. 
At this time you would want to use the latest version of Omni Core as it is has support for all the previous functionality
