### ISSUE TITLE
Unable to transfer USDT! ! !

### ISSUE THREAD

**Issue by gjhk9983** [OmniLayer/omnicore#748]
![omni](https://user-images.githubusercontent.com/17015025/44630691-b0d36080-a92f-11e8-883a-2f2d507d6715.PNG)
Please check my screenshot carefully, my balance is very recharge, but it is always a -211 error, I have Google all the solutions, but the problem still can not be solved, I have to collapse

**Comment by shiayoung** [comment]
The warning shows that your sending address does not have enough **BTC balance** to pay miner fee, not your USDT balance

**Comment by dexX7** [comment]
Please see:

https://github.com/OmniLayer/omnicore/wiki/Why-do-I-need-bitcoin-to-create-Omni-transactions%3F

Please let me know, if you need more help. Until then, I'm going to close this issue.
