### ISSUE TITLE
Keep track of the progress of bitcoin:0.12

### ISSUE THREAD

**Issue by dexX7** [OmniLayer/omnicore#75]
Bitcoin Core 0.11 RC1 was tagged and doesn't merge cleanly into the 0.10 branch unfortunally.

How do we proceed?

**Comment by dexX7** [comment]
Alright, I [started to port](https://github.com/dexX7/bitcoin/commits/wip-oc-0.11-merge-in-steps) the codebase to 0.11. Instead of resolving all merge conflicts manually, I basically restored all Bitcoin Core files, which were modified by Omni Core, then commited the 0.11 

The steps were as follows:

- merge 0.11 into omnicore-0.0.10 and write down all changed files
- filter those, which are not pure (unmodified) Bitcoin Core files
- checkout 0.11 (i.e. start with 0.11 clean)
- temporarily store all pure (unmodified) Bitcoin Core files
- temporarily store all files, which are somehow affected by Omni Core
- checkout new branch based on omnicore-0.0.10
- [prepare merge for 0.11 files of Bitcoin Core](https://github.com/dexX7/bitcoin/commit/773987ccb1a5e1cd79646b14b9049c97b6714000)
- [prepare merge for 0.11 files of Omni Core](https://github.com/dexX7/bitcoin/commit/c7f22c3c3af968cd78ce3ca128089dd40509c886)
- [merge 0.11](https://github.com/dexX7/bitcoin/commit/98deafa34650b44775251b98c59c37e1ee64fe86)
- [restore changed made for Omni Core](https://github.com/dexX7/bitcoin/commit/b67cccc4bb7488655f3a8dd4f16c154e756685ce)
- [update and fix some parts for the new codebase](https://github.com/bitcoin/bitcoin/compare/b67cccc4bb7488655f3a8dd4f16c154e756685ce...dexX7:24721b80376a9f40ceb91a3930da23b617d33566)
- [forward the RPC call setgenerate to generate](https://github.com/dexX7/bitcoin/commit/b139f69dbf0e07dc33e8a3aa314033291e3b54cd)
- [restore .travis.yml](https://github.com/dexX7/bitcoin/commit/edcbcfa1bb2b8d13bdd4bcb78ec9d961e0d015f3)

![overview](https://cloud.githubusercontent.com/assets/5836089/8013543/52d479fc-0bca-11e5-8ca8-18c064cf8de8.png)

![txs](https://cloud.githubusercontent.com/assets/5836089/8013548/5583afce-0bca-11e5-84c7-5f8bc231324f.png)

![debug](https://cloud.githubusercontent.com/assets/5836089/8013599/c6713026-0bca-11e5-97eb-3143f1ba895f.png)

![getinfo](https://cloud.githubusercontent.com/assets/5836089/8013602/c9d87184-0bca-11e5-82ec-dc168cb2b60a.png)

Still to-do:

- [ ] restore some icons/images used by Omni Core (easy)
- [ ] maybe adjust color scheme of Omni Core icons (medium)
- [ ] manually set locks for RPC calls (easy)
- [ ] try to cross-compile for OS X 10.9 in container based environment, or fallback to 10.7 (medium)
- [ ] maybe reject prunning mode (easy)
- [ ] clean merge (easy)

Given that it was already the first release candidate, chances are that there won't be many changes until 0.11 is released.

I think it would make sense to move to the new codebase rather sooner than later. Resolving the conflicts was the more difficult part, so I think this should not create a significant delay or stall the workflow.

What do you think?

**Comment by zathras-crypto** [comment]
@dexX7 awesome mate, what would we do without you?!?

> I think it would make sense to move to the new codebase rather sooner than later

I'm hesitant to move to Bitcoin 0.11 prior to us releasing OmniCore 0.0.10, unless there are security fixes or functionality we critically need for fear of breaking anything before release...  I would then fully support us switching to Bitcoin 0.11 for our 0.0.11 release.

**Comment by dexX7** [comment]
Haha, consider me as overly excited, when I posted the post. ;)

In general I think we should wait until a release was released (basically as before). If it integrates nicely, then we may upgrade. If not, or if we're talking about only a very few days untiil our release, then not.

At some point I'm going to take a stab at moving the QT code into `src/omnicore/qt`, but it's sort of a nasty, because some elements are shared between the code bases, such as a few icons, the overview page etc. I'm not entirely sure, how to tackle this. Ideas are welcomed, as always. :)

Regarding the Travis issues, I'm waiting for two apt whitelistings:

 - https://github.com/travis-ci/travis-ci/issues/created_by/dexX7

**Comment by zathras-crypto** [comment]
> At some point I'm going to take a stab at moving the QT code into src/omnicore/qt, but it's sort of a nasty, because some elements are shared between the code bases, such as a few icons, the overview page etc. I'm not entirely sure, how to tackle this. Ideas are welcomed, as always. :)

Interesting - I'd actually planned to redo the overview page - or at least make some changes to it - it's on my list - basically the main issue is that recent transactions only show Bitcoin transactions (not Omni) and the scroll-able property list isn't always nicely drawn in terms of scroll height etc.  I'd love to get this done for 0.0.10 and I wonder if I was to just do a completely separate overview page (instead of modifying the Bitcoin overview) whether that would make your moving the code location easier?

**Comment by dexX7** [comment]
> whether that would make your moving the code location easier?

I'm not sure, if this is the right priority. Grouping and moving files helps us, but not necessarily the user. :)

But yeah! It would help, I guess.

In this context, it's worth to take a look at the diff to `0.10`. I created a list of files to show, which files are new, or Omni Core only, and which Bitcoin Core files are modified:

- https://gist.github.com/dexX7/e3b9789316b80159cf95
- https://github.com/bitcoin/bitcoin/compare/0.10...OmniLayer:omnicore-0.0.10 (files)

All "new" files, which are not yet in `src/omnicore` can very likely be moved there. The "shared" files should probably stay where they are.

**Comment by dexX7** [comment]
Since this came up during the meeting, and we should probably discuss it rather sooner than later, I'd like to bump this thread.

To be honest, I have no good strategy for now, or for the future, to handle major Bitcoin Core upgrades.

Due to the split from master to 0.10, 0.11, 0.12, ... for each release the branches are not compatible, which is very unfortunate.

While the core of Omni Core is pretty isolated, it's going to be a mess, and basically requiring an integration by hand, for the UI.

I tend towards integrating 0.0.10-post into bitcoin:master, so we have a chance to stay in synchronization, and can avoid lagging behind further. Then again, this conflicts with the idea of more frequent minor releases, because the underlying base might be considered as unstable.

**Comment by zathras-crypto** [comment]
I think going with bitcoin:master would limit our flexibility in terms of release cycles if we wanted to stay on a stable bitcoin base (which I think is important).  

You've already done great work on isolating the core, and I think I'd like to spend some more time making the UI a bit nicer & cleaner once we get the 0.0.10 release out the way - perhaps that would be an opportunity to try and isolate more of the UI too?

**Comment by dexX7** [comment]
Sure, there is probably some room for some cleanup, but the primary challenge I see are the overlapping parts, such as the overview tab etc., where we can't really get around it.

**Comment by dexX7** [comment]
Given that 0.12 is being released, this should probably be the new target after 0.0.10.1.

**Comment by dexX7** [comment]
No longer relevant, because 0.2 was released, which is based on Bitcoin Core 0.13.2.
