### ISSUE TITLE
omni_send with redeemaddress stuck transaction

### ISSUE THREAD

**Issue by song-tan** [OmniLayer/omnicore#752]
Hi there,
I am really stuck here, I was sending a 10000 usdt to another address and trying to utilise "redeemaddress" to pay for transaction fee. However, the transaction was created with very low fee. and now it couldn't get any confirmations. i am wandering there are any way i could get the transaction cancelled or change the transaction fee.
here is my transactions. [https://omniexplorer.info/search/c5a852b2bb19900ac63f6acbd014625f3924fe972e11c15c7667177e69324b22](https://omniexplorer.info/search/c5a852b2bb19900ac63f6acbd014625f3924fe972e11c15c7667177e69324b22)
my command used:
```
curl --user accountname --data-binary '{"jsonrpc":"1.0","method":"omni_send","params":["1WBM6fN2Y6QjAPENcgNkYF2y67DJvHqnS","145DVsXKcNV5Qz7S6LtNVHnM2tKJ1D4U8U",31,"10000.0","1A4rCdWhuvx6ZL1oB6G65M6UDsbA3zEcpU"]}' -H 'content-type: text/plain;' http://47.75.149.37:8332/
{"result":"c5a852b2bb19900ac63f6acbd014625f3924fe972e11c15c7667177e69324b22","error":null,"id":null}
```
I am new to here. i really should do some test before I sent out this big amount usdt. but now i don't know any way i could get it back. so Please help!
thanks
Song

**Comment by dexX7** [comment]
Hi Song,

the redeem address is is used for bare-multisig encoding. This is usually not the case.

I see your transaction went through though. :)
