### ISSUE TITLE
omn​​i_getwalletaddressbalances is not work

### ISSUE THREAD

**Issue by initsysctrl** [OmniLayer/omnicore#757]
when i use "omni_getbalance" 、"omni_getallbalancesforaddress"、"omni_getallbalancesforid",is work normal.but when i use "omni_getwalletbalances" and "omni_getwalletaddressbalances",it return a empty list。what happen???!!
![](https://ws3.sinaimg.cn/large/006tNbRwgy1furqvp6xfoj312q06eq2x.jpg)

**Comment by achamely** [comment]
@initsysctrl  "omni_getbalance" 、"omni_getallbalancesforaddress"、"omni_getallbalancesforid" return balance information for any address in the ecosystem
"omni_getwalletbalances" and "omni_getwalletaddressbalances" ONLY return balance information for addresses in your Local Omni Core client wallet

**Comment by initsysctrl** [comment]
@achamely yes,you are right. "omni_getwalletbalances" is only return balance from local.actually,i have not any token in my wallet.thanks

**Comment by omgfin** [comment]
Hello, 
this method not found, can you check?

./omnicore-cli omni_getwalletbalances
error code: -32601
error message:
Method not found

**Comment by fvolohin** [comment]
> Hello,
> this method not found, can you check?
> 
> ./omnicore-cli omni_getwalletbalances
> error code: -32601
> error message:
> Method not found

I think it's because you use old version where this method is not implemented yet

**Comment by laviua** [comment]
v0.5.0 testnet
when i try omni_getallbalancesforaddress, it returns the balance on my machine.
when i try omni_getwalletbalances - i get empty array...
