### ISSUE TITLE
how can i get the BTC balance of an address

### ISSUE THREAD

**Issue by 437865981** [OmniLayer/omnicore#758]
**omni_getallbalancesforaddress**  this command does not contains the BTC balance

**Comment by qiao365** [comment]
omnicore-cli -conf=/Users/nevernew/var/data/omnidata/bitcoin.conf getbalance myNLUeNH7ud7hPrLrbyWc33L4nnqeTyySk

**Comment by initsysctrl** [comment]
![](https://ws2.sinaimg.cn/large/006tNbRwgy1furtkh4oy9j30yq02ywem.jpg)
this method can get balance of account ,but no address。

**Comment by achamely** [comment]
@437865981 the client can query/return the Omni Protocol balance for any address however the btc balance information is still based on the bitcoin-core code we are built on. As such you can only get btc balance information for addresses in your wallet or imported into your wallet

**Comment by dexX7** [comment]
Hi @437865981,

you could list all available coins by using `omnicore-cli listunspent`.
