### ISSUE TITLE
any full sync node that i can connect to test the RPC command?

### ISSUE THREAD

**Issue by AllenYaoya** [OmniLayer/omnicore#761]
The sync in my local is very slow, i haven't completed the sync till now. so when i test some RPC command, i get no data back. is there any full sync node that i can connect to?  if anyone can tell me, i will appreciate that so much!

**Comment by dexX7** [comment]
Hi there,

are you running the latest version?

**Comment by AllenYaoya** [comment]
Hello,

I have synced all the data. It takes nearly a week. Everything is ok now!

Thanks,
