### ISSUE TITLE
 move rpc command

### ISSUE THREAD

**Issue by chenyunecjtu** [OmniLayer/omnicore#762]
"move \"fromaccount\" \"toaccount\" amount ( minconf \"comment\" )\n"
same wallet , only move btc ? can move usdt or other coin, need support

**Comment by achamely** [comment]
@chenyunecjtu no, the move command is the native bitcoin-core command and does not work with the Omni protocol. 
The only way to move an Omni protocol asset from address a to address b is to actually send it with omni_send or a similar omni blockchain transfer command
