### ISSUE TITLE
Use omni_send sending USDT with an unexpected BTC transaction to receiver

### ISSUE THREAD

**Issue by opteacher** [OmniLayer/omnicore#765]
Hello, our wallet is confusing by this problem. Our test members found during withdrawals. According to code, I called omni_send only to send transaction(Identified recharge address and fee). But sees there's two transactions has been sent. One of them is USDT, another is BTC with a strange amount.
https://omniexplorer.info/search/ec2b94cd6b784dd2f339f49ed0823ec9ab8f2837ae5eb0b315824f12babe05b3
https://www.blockchain.com/zh-cn/btc/address/12ufYjJoz5zFf6ThVLpU73VhEK9f3tCMSR
https://www.blockchain.com/zh-cn/btc/address/1A7iffKC47SQCDftiZZgzaMT2x6UAZ85hW
As see, there's 0.0001512 BTC into receiver's address. But I didn't send any BTC, below is my code
```javascript
USD.prototype.transfer = function (from, to, amount, memo, func) {
    let pthis = this;
    Async.waterfall([function (done) {
        pthis._makeRequest('omni_send', [
            pthis.rechargeAddress,
            to,
            pthis.propertyId,
            amount.toString(),
            pthis.rechargeAddress,
            pthis.lowFee.toString()
        ], (err, res) => {
            if (err) {
                Logger.error('USD.transfer,error msg: ', err);
                return done(rpcCode.FATAL, err);
            }
            if (res.error) {
                Logger.error('USD.transfer,wallet error msg: ', getStrError(res));
                return done(rpcCode.FATAL, res.error);
            }
            return done(null, res.result);
        });
    }, function (arg, done) {
        pthis._makeRequest('omni_gettransaction', [arg], (err, res) => {
            if (err) {
                Logger.error('USD.gettransaction，err failed,error msg:%s', err);
                return done(err);
            }
            if (res.error) {
                Logger.error('USD.gettransaction，wallet failed,error msg:%s', getStrError(res));
                return done(res.error);
            }
            let data = {
                tx_hash: arg,
                fee: Math.abs(res.result.fee)
            };
            return done(null, data);
        });
    }], (err, result) => {
        if (err) {
            return func(err, result);
        }
        return func(null, result);
    });
};
```

**Comment by achamely** [comment]
@opteacher remember the Omni protocol is built on and uses the bitcoin blockchain when we encode and send an Omni Protocol transaction. 
As such all Omni Protocol transactions need to be valid bitcoin transactions at their base, this includes the outputs of the tx having some amount of BTC associated with them (this is known as the reference amount).  By default the client uses a reference amount of 0.00000546 btc (the lowest value accepted by the bitcoin network). 
If you take a look at the documentation for omni_send (https://github.com/OmniLayer/omnicore/blob/master/src/omnicore/doc/rpc-api.md#omni_send) 
you can see that the format of the call is `omni_send "fromaddress" "toaddress" propertyid "amount" ( "redeemaddress" "referenceamount" )` 
During omni_send you can override and change the reference amount as desired. Looking at your code above it appears you have confused the miner fee with the reference amount 
```pthis._makeRequest('omni_send', [
            pthis.rechargeAddress,
            to,
            pthis.propertyId,
            amount.toString(),
            pthis.rechargeAddress,
            pthis.lowFee.toString()   <------- This is the miner fee, it is the reference amount
```

So what appears to have happened is that you confused the miner fee with the reference amount which increased the respective amount in the tx. 
If you want to change the miner fee you should take a look at the `settxfee` command from the bitcoin-core rpc

We have additional info about network fee's and transaction structures in our Platform Integration guide: (https://github.com/OmniLayer/omnicore/wiki/Platform-Integration-of-Omni-Core#transaction-structure-and-network-fees)

If you have not yet read over this we highly recommend it as it helps address several of the common mistakes and hiccups integrators encounter. 

If this helps please close out the issue

**Comment by opteacher** [comment]
@achamely Thanks, I found the definition of lowFee, and removed it. I will test it and close the issue. Thanks again!

**Comment by achamely** [comment]
@opteacher can you confirm you are using the most recent version of omni core (v0.3.1) that was released just over a week ago

**Comment by opteacher** [comment]
@achamely We have updated the omni version and waiting for test result. Here an another problem. We have many users' account for accumlatting to our collection account, and use [this](https://github.com/OmniLayer/omnicore/wiki/Use-the-raw-transaction-API-to-create-a-Simple-Send-transaction) method to implement. But the node pointed out the error message "66: insufficient priority". I searched for this error is about users' BTC balances not enough, but actually they have BTC for collecting. So I was confused which step we did wrong, below is relative informations.
![output](http://owb90pdwd.bkt.clouddn.com/2018-09-10%2014-53-33%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE.png)
collection address: https://www.blockchain.com/zh-cn/btc/address/12ufYjJoz5zFf6ThVLpU73VhEK9f3tCMSR
```
user address amounts are,{'12DWtoVkvXrfvmWWk2qj2qu7CwADBckwxo': 1.0, '1A7iffKC47SQCDftiZZgzaMT2x6UAZ85hW': 0.00504, '1F2JfhZYB2FMQMJeTHhvZ4xvYqzhxWG4Sk': 0.1, '12vR75TzuM3JXJkQ157V7PyyzP3L8divjk': 1.0}
```

**Comment by opteacher** [comment]
A new withdrawal result has outputted, miner fee: 0.00001285, amount: 0.00001445. Sees already no problem, Thank you @achamely

**Comment by shahzad19** [comment]
I sand 14 usdt coin all to block chain but I receive only $0.6 transaction  fees show only 2 usdt where is my 12 usdt

**Comment by shahzad19** [comment]
Where is my 12 usdt

**Comment by shahzad19** [comment]
Where is my 12 usdt and how I can with draw
