### ISSUE TITLE
what is wrong with "omni_createrawtx_opreturn" ???

### ISSUE THREAD

**Issue by johnsneakers** [OmniLayer/omnicore#774]
i use this cmd in omni-cli:
omnicore-cli "omni_createrawtx_opreturn" "0100000001e1543b463545903dbb6c4212c3bf0e28b9632f0228922035c5350a24e18cf5450000000000ffffffff0000000000" "00000000000000020000000002625a00"

I can send transaction succ.

but i use json rpc, I pass the same parameters，it return err : payload must be hexadecimal string (not '"00000000000000020000000002625a00"'). i had read api doc, payload parameter need hex-encoded, so i change my paremeter:

{"jsonrpc":"1.0","method":"omni_createrawtx_opreturn","params":["0100000001e1543b463545903dbb6c4212c3bf0e28b9632f0228922035c5350a24e18cf5450000000000ffffffff0000000000","22303030303030303030303030303030323030303030303030303236323561303022"],"id":7}

the response look like succ.  and sendrawtransaction succ [https://live.blockcypher.com/btc-testnet/tx/45f58ce1240a35c535209228022f63b9280ebfc312426cbb3d904535463b54e1/](url) , but i never get the coin from my transaction in json-rpc api .   I can use cmd to get the coin successfully.

i I think the problem lies in the second parameter of omni_createrawtx_opreturn if i hex-encode payload it never succ.

**Comment by johnsneakers** [comment]
@dexX7  Hi bro, can you help me?

**Comment by dexX7** [comment]
Hi @johnsneakers,

the original call with omnicore-cli is the way to go and when submitting the data via JSON-PRC, it should be similar.

Were you able to resolve this issue in the meantime?
