### ISSUE TITLE
how to create my tokens  with omni??

### ISSUE THREAD

**Issue by initsysctrl** [OmniLayer/omnicore#778]
how to create tokens to represent custom currencies or assets by omni core???I did not find any documents.

**Comment by santos177** [comment]
watch the spec:  https://github.com/OmniLayer/spec and look for 'Smart Property'

**Comment by initsysctrl** [comment]
To make a token on the Omni protocol you need to login to your Omniwallet account (or create a new one if you don't have one). 
Then you need to have some BTC on your the address created by your Omniwallet (around 0.001-0.002 should be more than enough). 
You can then go to 'My Assets' and access the token creation page by clicking the drop down button to choose the type of token you wish to create. 
Simply fill in the form (take note of the ecosystem drop down in the top right) with your token details and provide an appropriate miner fee  and once the tx is completed and confirmed the token is created and will be visible in your wallet.

---this is reply from omni help desk .thank you .
