### ISSUE TITLE
create raw transaction for funded send

### ISSUE THREAD

**Issue by jackyzq** [OmniLayer/omnicore#780]
I was looking at the wiki, which documented how to create a simple send transaction. (https://github.com/OmniLayer/omnicore/wiki/Use-the-raw-transaction-API-to-create-a-Simple-Send-transaction) I'm trying to figure out how to create a raw transaction for a funded send.  The wiki shows how to sign a transaction if the signer is both the person with the omni tokens and the bitcoins. Is there a way to specify the private key to let the signer use omni tokens, from a different address?

EDIT: It seems there is a fundrawtransaction function in omnicore-cli, do I use this function between steps 4 and 5?

**Comment by dexX7** [comment]
Hi @jackyzq,

the fundrawtransaction RPC is unrelated to Omni. Do you need to handle raw transactions, or are you still fine with creating and sending transactions in one step? In this case we have two other new RPCs:

https://medium.com/omnilayer/introducing-funded-omni-layer-transactions-or-how-exchanges-can-save-money-f3f04161a6af

**Comment by jackyzq** [comment]
Thanks, that seems to be what I am looking for. However I have tried to use it, and I am running into some problems with it, that I have detailed in the other issue (https://github.com/OmniLayer/omnicore/issues/764#issuecomment-424933388).
I will close this issue.

**Comment by rdrahul** [comment]
how to create raw transaction like mentioned here for a funded transaction ? https://gist.github.com/dexX7/352670c990ebf9ea31d6346a1519eb52
