### ISSUE TITLE
I have an issue with sending Tether ( Property_id 31 )

### ISSUE THREAD

**Issue by VictorManzar** [OmniLayer/omnicore#784]
I installed omnicore on my PC (Linux mint) every thing is Ok. 
Next i sync network, every thing is Ok too. 
omnicore-cli all read methods works fine, but when i trying to send tether (property id 31) 
```
omnicore-cli omni_send 1LVV6WWENrAwk4coEh2kv5yGRvZFGNGJu6 1PUWNB7kPQwBHKu7fghiyzuCVqc1Xv51N6 31 1.0
```
The sender address have  Tether (31) and Bitcoin (for fee)
I got this error 
```
error code: -206
error message:
Error with selected inputs for the send transaction
``` 

As i can understand this is some issue with transaction fee settings (Maybe i am wrong)

Here is my config for omnicore 
```server=1
rpcuser=${RPC_USERNAME}
rpcpassword=${RPC_PASSWORD}
rpcallowip=0.0.0.0/0
rpcport=8332
txindex=1
omniseedblockfilter=1
datacarriersize=80
logtimestamps=1
datadir=${DATA_DIR}```

Could you help me to understand what i am doing wrong ?

**Comment by santos177** [comment]
Hi @VictorManzar  
Are this address 1LVV6WWENrAwk4coEh2kv5yGRvZFGNGJu6 funded with BTCs?
206 error is a problem with fundings.

**Comment by VictorManzar** [comment]
Yep, i resolved this issue after reindex database
