### ISSUE TITLE
omni_funded_send function related question

### ISSUE THREAD

**Issue by Revinand** [OmniLayer/omnicore#787]
Hello,

I tried to sweep funds with `omni_funded_send` function and for a number of tries I got `ERROR: sender has no coins` error, but my `fromaddress` had required 546 satoshis though. I noted that the transfer was accepted only after I received 6th confirmation of the transaction holding those satoshis.

Do you plan to add an ability to set the minimal amount of required output confirmations? Because in my case 1 hour is too long to wait until I can sweep funds.

BTW thanks a lot for implementing this feature

**Comment by Revinand** [comment]
Also it didn't see an available output for the `fromaddress` until I restarted the node.

**Comment by dexX7** [comment]
Hi @Revinand, actually fresh and unconfirmed coins should be usable, unless you have specified in your configuration otherwise. Maybe you could paste your bitcoin.conf (without PPC credentials!), so we can take a look?
