### ISSUE TITLE
getting omni and tomni in regtest mode

### ISSUE THREAD

**Issue by lo00l** [OmniLayer/omnicore#789]
Hi there.

I run omnicored in regtest mode.
Here is my **~/.bitcoin/bitcoin.conf** file:
```
server=1
txindex=1
regtest=1
rpcuser=user
rpcpassword=password
```

I have generated blocks by executing `omnicore-cli generate 101`.
Then I sent 1 BTC to address `moneyqMan7uh8FqdCA2BV5yZ8qVrc9ikLP` to get OMNI and TOMNI.

Then I generated 20 more blocks.

I can see result transaction:
```
{
  "amount": -1.00000000,
  "fee": -0.00003840,
  "confirmations": 20,
  "blockhash": "11973edbd2140de38fb878df939a046b3b5ae480ea176e686c6f7fd481bc93c0",
  "blockindex": 1,
  "blocktime": 1538493391,
  "txid": "710af8d294685acbe585fa0544e804076241fd157c65b22357644e59d84cb0b0",
  "walletconflicts": [
  ],
  "time": 1538493363,
  "timereceived": 1538493363,
  "bip125-replaceable": "no",
  "details": [
    {
      "account": "",
      "address": "moneyqMan7uh8FqdCA2BV5yZ8qVrc9ikLP",
      "category": "send",
      "amount": -1.00000000,
      "vout": 1,
      "fee": -0.00003840,
      "abandoned": false
    }
  ],
  "hex": "010000000126a2fedc8556be21466e91bac2e5ebf6f3bb8cf1a36e552d314a7f25e7fa701d00000000484730440220390dce7a652fb1b497423ee6dc25d37871647a0f8b403deaf6f7d076e3775c1d02207a98ad6e7486fe4f2fa6539e9a16420b2fb0584dbc59698e1558949c07ad02e301feffffff0200021024010000001976a91435c03e1a73c9338a4a34a0d3ceec0bfecce4598188ac00e1f505000000001976a9145ab93563a289b74c355a9b9258b86f12bb84affb88ac65000000"
}
```

But there's still no OMNI on address:
```
omni@281fe3c3ded2:~/omnicore$ omnicore-cli getaccountaddress ""
myrUvkXzJdeNZW9fiN2VQzyHdeavXneV8P
omni@281fe3c3ded2:~/omnicore$ omnicore-cli omni_getbalance myrUvkXzJdeNZW9fiN2VQzyHdeavXneV8P 1
{
  "balance": "0.00000000",
  "reserved": "0.00000000",
  "frozen": "0.00000000"
}
```

What am I doing wrong?

**Comment by santos177** [comment]
Hi @lo00l :   
Try to check the omni_balance of all your address of the account that send bitcoins to "moneyqMan7uh8FqdCA2BV5yZ8qVrc9ikLP" . May be you should create a separate account (not the default). Check the lines  in this test as a example:   https://github.com/OmniLayer/omnicore/blob/master/src/omnicore/test/test_metadexphase3.sh/#L7-L24

**Comment by lo00l** [comment]
Hi @santos177, thank you for reply. I checked all addresses of my account. I still haven't managed to get OMNI and TOMNI.
But I solved my problem by issuing new tokens and using them for tests.

**Comment by dexX7** [comment]
Hey guys,

it's important that the coins used to generate Test Omni are not freshly mined, but sent to an intermediate address. This is because only P2PKH and P2SH inputs are allowed on the Omni Layer, while coinbase coins are not.

**Comment by gornov** [comment]
FYI, you can't get OMNI or any other token in **regtest=1**
So you should use testnet or issue your own token (property) with the same parameters as omni has.
