### ISSUE TITLE
dFutures Contracts

### ISSUE THREAD

**Issue by patrickdugan** [OmniLayer/omnicore#80]
Let's consider implementing a smart contract type, existing as a special kind of smart property that can exist as signed integer (includes negative balances), where holding it locks up some amount of a designated collateral asset (such as OMNI, USDT) and pays/costs the address the difference between a trade price and a settlement price, either at a settlement time designed for the contract, or when the user trades an off-setting quantity. 

Standardized cost-for-difference contracts, in other words. Allows hedging and leveraged speculation on-blockchain. 

A very dated spec: 

https://docs.google.com/a/farmshares.com/document/d/1_nwkSx3zvyvMHno_zbAuM6E1ypX6LMfGyb8sGaDem_0/edit?usp=drive_web

Examples of how settlement algorithms could work:

https://docs.google.com/drawings/d/19HuBjJEYR059AnqGhWHyHIzWRHN0-69w03zt0BDmzPw/edit?usp=sharing

https://docs.google.com/drawings/d/1frsGq_EzdqqHTtjE8bN_rKN1GtPDlIfsS95vGnRKJMM/edit?usp=sharing

https://docs.google.com/drawings/d/1k60e1tkG25kBfmGqPaWyQs3Gdo5RAT_ajrRtHye34I4/edit?usp=sharing

**Comment by dexX7** [comment]
Using tokens to bind some behavior is very interesting, and this is something for the far future, I wanted to dig into in the context of the traditional DEx (where some tokens might represent "accepting an offer" - which could be traded). This proposal isn't very similar, but sort of, and it remainded me of it. :)

Just to clarify:

> 1. Alice creates future contract tokens, with a reference currency, nominal value, settlement time, margin requirements, ...

> 2. Some of Alice' balance is locked as collateral.

> 3. Alice can sell future contract tokens to Bob. (i.e. it's a tradable token)

> 4. When Bob buys those tokens, some of Bob's balance is locked as collateral.

> 5. Once the contract expires, either Alice or Bob receives a price difference, which is subtracted from the previously locked amounts.

Is this correct so far?

It's a bit unclear to me, who the counterparty is in this example, and what happens, if future tokens are transferred.

**Comment by patrickdugan** [comment]
Hey Dexx, sorry I missed this - that is correct - what you're missing is an index that provides a reference for a settlement algorithm to search through every time there is an off-set trade and chain premature settlements where the index yields a clear netting path. 

I can think of 3-4 settlement algos that would prune this index, with varying degrees of complexity and robustness, the two are somewhat correlated. 

We could have the settlement algo be a functional parameter for the parameters of creating a given contract series. I'm a big fan of callback function parameters.

**Comment by dexX7** [comment]
@patrickdugan: well yeah, I'm trying to break this down into smaller parts.

For example it could start with a new token type, which locks a certain amount of reference tokens. This doesn't make much sense on it's own, but several building blocks might be created step by step, until the full functionality is provided. I'm not implying a lock-only-and-do-nothing-else-token should become part of Omni Core without the rest, but thinking it through this way provides a clear path, with simple sub units, which is ultimately easier to integrate.

**Comment by dexX7** [comment]
To provide what you need.. you mentioned you wanted a mechanism to move tokens into reserve. Would it be accurate to assume that such a mechanism is basically "a simple send, but not credited to the available balance, and instead to the reserved balance"?

**Comment by dexX7** [comment]
I think it's better to keep track of the specification or feature proposals in the spec repository:

https://github.com/OmniLayer/spec

Please feel free to open a new issue over there.
