### ISSUE TITLE
Get notification about transactions

### ISSUE THREAD

**Issue by hainguyen291** [OmniLayer/omnicore#803]
Hi everybody,

How can I get notification about my wallet address's transactions once a new one come or exists one's status is changed?

Best regards,
Hai

**Comment by santos177** [comment]
Hi again @hainguyen291:
You can try with ./omnicore-cli  omni_gettransaction <here put the transction ID>  to watching tour transactions status. It is what you want right?

**Comment by hainguyen291** [comment]
Hi Santos,

I want to know trans's history of a wallet. In reallity, when you make a
raw transaction, it takes time to be completed. Can you tell me the flow of
transaction's status from the beginning? Are there any way to get
notification once tran's status are changed during its life cycle?

Regards,
Hai

**Comment by hainguyen291** [comment]
Can I use this command: *omni_gettradehistoryforaddress" to get history of transactions for a address?
I tried to run this command as: `omni_gettradehistoryforaddress 197Kir2psnjrTFwx8R9cUnmVCUFeUgCNxS`

This address I got from this transaction:
![image](https://user-images.githubusercontent.com/12641471/47233131-f413f200-d3fb-11e8-92a3-50353ad008e7.png)

However, I got an empty array instead of some information about this
address's transaction.

**Comment by hainguyen291** [comment]
Hi Santos,

Ok, I got your point. For sending coins in system, it mentions that we can
use either omni_send function or creating rawtransaction. How are they
different? What should I use, or should use it case by case?

Best regards,
Hai

**Comment by hungdung1326** [comment]
Chào anh @hainguyen291 
Em cũng đang làm về dịch vụ ví của usdt. Anh đang muốn hỏi về vấn đề lắng nghe 1 giao dịch khi nó pending và complete đúng không ạ? Em đã giải quyết được vấn đề này bằng các sử dụng 1 thư viện của bitcoin. Anh có thể cho em thông tin của anh, em sẽ nói rõ ràng hơn. Rất vui khi được trao đổi, trau dồi kinh nghiệm với anh!

Trân trọng,
Hung
