### ISSUE TITLE
Method not found

### ISSUE THREAD

**Issue by hainguyen291** [OmniLayer/omnicore#804]
Hi everybody,

I tried some command and almost of them are not found.

![image](https://user-images.githubusercontent.com/12641471/47162224-c789a880-d31d-11e8-9035-88bb6decca99.png)

Why did I get this error for these commands?
Regards,
Hai

**Comment by santos177** [comment]
Hi @hainguyen291 
 You are writing "omnicore-cli" two times. So you are not writing a valid command at all.

**Comment by hainguyen291** [comment]
Hi Santos,

Oh, I see. It is my bad.

Thanks for letting me know,
Hai

**Comment by hainguyen291** [comment]
Btw, I tried this command: *omni_gettradehistoryforaddress
197Kir2psnjrTFwx8R9cUnmVCUFeUgCNxS*

This address I got from this transaction:
[image: image.png]

However, I got an empty array instead of some information about this
address's transaction.

[image: image.png]

Please let me know why. Thank you
