### ISSUE TITLE
omni 0.3.1 collect to one acctount

### ISSUE THREAD

**Issue by igorbiliba** [OmniLayer/omnicore#809]
Hello guys!
In 0.3.1 was realized function for collect all amount to once main wallet address? How use this?

**Comment by dexX7** [comment]
Hi @igorbiliba,

there is the sendall transaction, which allows to send the whole balance from one source to another:

https://github.com/OmniLayer/omnicore/blob/master/src/omnicore/doc/rpc-api.md#omni_sendall
