### ISSUE TITLE
is omnilayer support p2pk tx?

### ISSUE THREAD

**Issue by gingingin** [OmniLayer/omnicore#810]
Haven't seen from the Specification?

**Comment by dexX7** [comment]
Hi @gingingin, the specification of the Omni Layer is not up-to-date and does not match the implementation entirely, but it does not support P2PK. There are allowed types:

https://github.com/OmniLayer/omnicore/blob/master/src/omnicore/rules.cpp#L362

**Comment by young001** [comment]
as I describe in issue 811,I read omni code,I just wonder the consideration why do not support p2pk as input.because some user may have some p2pk output,so it can't used as omni input
