### ISSUE TITLE
send_omni first time success, second time failed

### ISSUE THREAD

**Issue by huahuayu** [OmniLayer/omnicore#813]
when execute `omni_funded_send` or `omni_send` , I have to ensure the fromaddress have at least a litte btc, after I deposit to fromaddress I can successful send omni asset, the problem is it will fail when comes to the second time `omni_send`

the unspent btc will change to a new address, but the omni asset keeps in the old fromaddress, how to solve this problem?
```
usdt@iZj6c48apyeg9dvouqz3uxZ:~$ omnicore-cli omni_funded_send "mx7r52d2oaNTeiMDr2zrcw2VGm1BQurC9K" "n4YZv8eV8VTXW2ae2uZhnb64KdK3jS4GCx" 2 "0.2" "n1RfuCXBdVniV2afuUM67Frz5NuvWEmqxR"
0d917a54b86a2ac2f778267073d3cdaab6894a0c6d0952609abb3310630eaf6e
usdt@iZj6c48apyeg9dvouqz3uxZ:~$ omnicore-cli omni_funded_send "mx7r52d2oaNTeiMDr2zrcw2VGm1BQurC9K" "n4YZv8eV8VTXW2ae2uZhnb64KdK3jS4GCx" 2 "0.2" "n1RfuCXBdVniV2afuUM67Frz5NuvWEmqxR"
error code: -212
error message:
Error choosing inputs for the send transaction
```

**Comment by huahuayu** [comment]
@Laizhongsheng you can send usdt in a sequence how did you do that? Can you give some advice for this issue

**Comment by Laizhongsheng** [comment]
check the balance mx7r52d2oaNTeiMDr2zrcw2VGm1BQurC9K
it needs at least 0.0000546 btc

**Comment by huahuayu** [comment]
@Laizhongsheng yep, but you konw what, after I send btc to mx7r52d2oaNTeiMDr2zrcw2VGm1BQurC9K and fire the `omni_send` transaction again, the total unspend will be use, the change will send to another new created address and mx7r52d2oaNTeiMDr2zrcw2VGm1BQurC9K balance will be zero again, So I can't do another `omni_send`

**Comment by Laizhongsheng** [comment]
Correct.
You can omni_send A to B   feeD,    C to B feeD  only once, if u dont send btc to A , B.

**Comment by huahuayu** [comment]
@Laizhongsheng but when I check the bash script I didn't see you send btc to sendaddress...shall we get connect in wechat, my id: huahuayu

**Comment by dexX7** [comment]
Thanks for resolving this!
