### ISSUE TITLE
Should I ignore frozen omni transactions as a merchant listening for omni deposits?

### ISSUE THREAD

**Issue by ddengster** [OmniLayer/omnicore#819]
Reference:
https://github.com/OmniLayer/omnicore/wiki/Platform-Integration-of-Omni-Core#frozen-tokens

Also, how does the freezing mechanism work? Will an address's entire list of omni UTXOs be considered as frozen or will it be just a few of those transactions?

**Comment by dexX7** [comment]
Hello @ddengster,

when you use the regular `omni_getbalance` RPCs or simply check the validity of Omni transactions via the RPC interface, it's already ensured you don't "accept" frozen tokens.
