### ISSUE TITLE
transaction type question

### ISSUE THREAD

**Issue by hero-zhanghao** [OmniLayer/omnicore#820]
I'm here to see the API documentation: https://github.com/OmniLayer/omnicore/blob/master/src/omnicore/doc/rpc-api.md#omni_listtransactions, but not to document

> "Type_int" : n, // (number) the transaction type as number
> "Type" : "type", // (string) the transaction type as string

These two attributes explain, what values are there, and how can I tell if a transaction is a roll-in or a roll-out.
thanks

**Comment by dexX7** [comment]
Hi @hero-zhanghao,

the transaction type and transaction type description show which Omni Layer transaction you are handling. For an overview, check out the specification:

https://github.com/OmniLayer/spec/

Please note, the specification is not up-to-date, but it describes the most common type: 1 - Simple Send, which is a standard transfer of tokens.
