### ISSUE TITLE
Node shutdown with Error Message

### ISSUE THREAD

**Issue by prathab-falconxio** [OmniLayer/omnicore#821]
Was running the omnicore node with the following config 

./omnicored -server=1 -rest=1 -rpcuser=falconx -rpcpassword=falconi
ze13 -rpcport=8332 -rpcallowip=0.0.0.0/0 -daemon -txindex=1 -dbcache=16384 -omnidebug=none -rpcthreads=64 -par=8 -c
hecklevel=0 -checkblocks=1

And got the error 

2018-11-02 16:22:54 *** Shutting down due to unsupported feature activation (14: Unknown feature)
2018-11-02 16:22:54 Error: Shutting down due to unsupported feature activation (14: Unknown feature)

And the node shutdown

Any ideas?

**Comment by dexX7** [comment]
Hi @prathab-falconxio,

it looks like you are using an outdated version. Please check out the release section on GitHub or visit www.omnilayer.org to download our latest v0.3.1 release.
