### ISSUE TITLE
omni_getbalance need btc private key?

### ISSUE THREAD

**Issue by LaoBan-ywcm** [OmniLayer/omnicore#824]
I want to get balance of usdt an address.I want to confirm if the `omni_getbalance` method requires an address private key.

**Comment by santos177** [comment]
Hi @LaoBan-ywcm: 
No, you only need omnicored synchronized (or you can watch the balance also using omni webwallet). I hope it helps

**Comment by dexX7** [comment]
This is correct. Please feel free to reopen this issue, if you need any further assistance.
