### ISSUE TITLE
Can i use bitcoinjs-lib for create omni transaction?

### ISSUE THREAD

**Issue by ssssssu12** [OmniLayer/omnicore#825]
Can i use bitcoinjs-lib for create omni transaction?
(https://medium.com/@orweinberger/how-to-create-a-raw-transaction-using-bitcoinjs-lib-1347a502a3a)

If so how to set feeaddress?

**Comment by santos177** [comment]
Hi @ssssssu12 :   
I think if you want to do that, you have to consider in details how omnilayer build any of his special transactions on bitcoin . For some transactions you have to include outputs for addresses with a very small bitcoin amounts (just for signal the sender and destination ) and of course the payload (using the OP_RETURN) which contains the data (amounts, propertyId, etc).  Other alternative, is watch this repo:https://github.com/OmniLayer/OmniClientJS  and work with it or modify it. I hope it helps

**Comment by ssssssu12** [comment]
Thank you so much!
