### ISSUE TITLE
I can't get the UTXO of my address !

### ISSUE THREAD

**Issue by jarven-zhang** [OmniLayer/omnicore#826]
I could use "omnicore-cli listunspent 0 999996 '["1KBG5tKMhjAgdwa3bTr3AyjkygZPpuBSz7"]' " to get the utxo of the address. But after I use the cmd "omni_funded_send" , and the result is this:
![image](https://user-images.githubusercontent.com/44637785/48131841-6590e300-e2cc-11e8-83cf-a57bacfde3af.png)

And I can't get the utxo now!!!!!  Even the balance: 
![image](https://user-images.githubusercontent.com/44637785/48131869-7fcac100-e2cc-11e8-9d3b-1d0f7d7213ef.png)

and in [explore](https://www.omniexplorer.info/search/1KBG5tKMhjAgdwa3bTr3AyjkygZPpuBSz7) 
![image](https://user-images.githubusercontent.com/44637785/48131902-9bce6280-e2cc-11e8-9998-f275ee1dfaff.png)

**Comment by jarven-zhang** [comment]
nothing

**Comment by dexX7** [comment]
Hi @jarven-zhang, is your client fully synchronized?

**Comment by jarven-zhang** [comment]
> Hi @jarven-zhang, is your client fully synchronized?

yes ,of course!

**Comment by jarven-zhang** [comment]
I think the utxos of the address is locked and I reboot the omnicore and then  I can get the utxo .
