### ISSUE TITLE
Withdrawing USDT using OMNI LAYER

### ISSUE THREAD

**Issue by Atta68** [OmniLayer/omnicore#829]
I made withdrawal of USDT from Exmo to WEX and they use OMNI LAYER. According to https://www.omniexplorer.info/address/3FUH6dz8DYExEkaETDfozbvkm2fJyoQ4dT
the USDT is comfirmed, but am not seeing the USDT in my WEX USDT wallet.
The worse of it is that WEX support is not working, or WEX support is not Responding.
Please help out

**Comment by dexX7** [comment]
Hi there, I fear your money may be lost, if WEX doesn't support USDT and is not willing to cooperate. Please check out:

https://github.com/OmniLayer/omnicore/wiki/I-sent-tokens-to-an-incompatible-wallet-such-as-Coinbase-or-GDAX.-Can-you-reverse-the-transaction%3F
