### ISSUE TITLE
Questions about the getaddressbalance API

### ISSUE THREAD

**Issue by hero-zhanghao** [OmniLayer/omnicore#831]
I need to use the BTC core getaddressbalance API to query the balance of BTC under the address to determine whether there is enough BTC fee under the address. However, I find that this API does not seem to be available. Is there any way I can open this API, or is there any other API that can do what I need?

**Comment by santos177** [comment]
Hi @hero-zhanghao :  
Why don't you try with this command? http://chainquery.com/bitcoin-api/listunspent
With that you can check if the address has enough BTCs for fees (just watching the unspent inputs)

**Comment by qizikd** [comment]
If the private key of this address is not imported, a blank result is returned。
Bitcoin has a new function importaddress on v0.10.0, can omnicore upgrade the bitcoin kernel?

https://bitcoin.org/en/release/v0.10.0#watch-only-wallet-support

**Comment by hero-zhanghao** [comment]
Thank you for your reply. I tried to use this API, and now I can normally query the balance of BTC.
