### ISSUE TITLE
How to determine the sending address of a omni transaction?

### ISSUE THREAD

**Issue by DogRex** [OmniLayer/omnicore#836]
How can I determine the sending address and reference address of a omni transaction( like **c74b91c584be80b8ccd9e54a3e959d7de672985bc60c8c8e2d6e08da6a16d456**)?

I try to process it without omnicore. I almost check the protocal of Class A over again and again, and I can not make it.

Can anyone help? 

Thanks

**Comment by santos177** [comment]
Hi @DogRex :   
The easy way is looking into the omni explorer: https://www.omniexplorer.info/tx/c74b91c584be80b8ccd9e54a3e959d7de672985bc60c8c8e2d6e08da6a16d456 .
Other way is with omnicore using the command: omni_gettransaction  "put the txid here"

**Comment by DogRex** [comment]
Hi @santos177, thanks for you comment~ 

Yes, I think you are right, but I'm just studying on the omni protocol, and can not understand some details.

So , my actual question is ... just take this tx as an example,
**c74b91c584be80b8ccd9e54a3e959d7de672985bc60c8c8e2d6e08da6a16d456**  

how does the omni explorer determine the tx is from "1Gc3biG5hsHAoj4ZNAtnT4sCBbtF9sKEEL" to "1FLhMtcsvVFjhdE3LRBdWqR4FeXuFkTM4m"

**Comment by DogRex** [comment]
@santos177 great 👍 . Best regards at the thanks giving day~

**Comment by ngocbd** [comment]
> I understand. Well, is just watching the outputs: https://chain.so/api/v2/tx/BTC/c74b91c584be80b8ccd9e54a3e959d7de672985bc60c8c8e2d6e08da6a16d456
> 
> Here you can see 3 outputs:
> 
> output 0, to destination "1FLhMtcsvVFjhdE3LRBdWqR4FeXuFkTM4m".
> 
> output 1, to sender "1Gc3biG5hsHAoj4ZNAtnT4sCBbtF9sKEEL"
> 
> output 2, nulldata (contains the payload with omni marker 6f6d6e69, type of transaction,amounts, propertyId, etc)
> "6f6d6e6900000000000000030000000000000bb8"
> 
> Also you can study the parseTransaction function (omnicore.cpp file) and the CTransaction class : https://dev.visucore.com/bitcoin/doxygen/class_c_transaction.html
> 
> I hope it helps.

Sometimes the destination is output 0 and sender is output  3

like this https://chain.so/api/v2/tx/BTC/5bc9b6a1028dc207fcbb3ae87bf1a268f297cab6db0c96da2c6203eebbe9a60f

**Comment by santos177** [comment]
Hi @ngocbd : 
Yes, but you have yo look the amount of the outputs, in general the bigger amount is for the sender (as change). The destination contains a very small amount of BTC ( in your example is : 0.00000546).

**Comment by dexX7** [comment]
Hello,

the sender of Class A transactions is the one with the "highest contribution" of BTC, i.e. the address that contributed the most funds for the transaction. For Class B and C it's very simple: the sender is always the first input.

The reference output is the latest one, which isn't change. E.g.:

```
In[0]: A [< sender]

Out[0]: Payload
Out[1]: A
Out[2]: B
Out[3]: C [< receiver]
```

Here, it's C, because it's the latest output, which isn't the sender.

```
In[0]: A [< sender]

Out[0]: Payload
Out[1]: C
Out[2]: B [< receiver]
Out[3]: A
```

Here, it's B, because the last output is the change output.


```
In[0]: A [< sender]

Out[0]: Payload
Out[1]: B
Out[2]: A [< receiver]
Out[3]: A
```

Here, it's an edge case: it's A, because the latest output is skipped, because it's change, but the next output goes still to A, which is valid in this case.
