### ISSUE TITLE
Syncing very slow in localhost

### ISSUE THREAD

**Issue by gpoddar** [OmniLayer/omnicore#837]
Syncing is very slow, and have see that others have faced similar issues. 

Its been 4 days and we are still in Dec 2016 (block 435709). At this current rate (~16 blocks/min) it will take 5 more days to sync. 

The machine is 8GB RAM. The CPU is at 12% and RAM at 35% used so its far from resource starved. Internet is via ethernet cable. 

A few things I've noticed:
- It reached mid 2016 pretty quickly but since then its been going pretty slow. 
- Not maintaining connection with peers for long. Average is 2 hours (was maintaining connection much longer initially)
- Downloads blocks in spurts (see image):  
![whatsapp image 2018-11-27 at 4 13 32 pm](https://user-images.githubusercontent.com/16606679/49085679-8e2b4d80-f278-11e8-8b45-8ac247ff62ef.jpeg)

We also have an omni node running on AWS (4GB RAM). Similar issue; started fast but slowed down considerably when it reached 2016. And will take 30+ days to sync. 

What can we do to fix this? Thanks :)

**Comment by gpoddar** [comment]
Yeah, we are trying the same. Our BTC node crashed a few times in the middle, but excluding that it will take ~4 days to sync. How long will BTC take to sync for you? 

We've left the Omni node running, it reached block 500k (so 90% done). Has slowed to 3 blocks/min. Will take 5-10 more days.

**Comment by luongnguyenduc** [comment]
I use testnet flag and Bitcoin Core shows there are 8-10 hours left. 
I can't understand why Omni hasn't fixed the issue, is there another way to work with Omni layer without installing Omni core?

**Comment by gpoddar** [comment]
Oh really? Thats not bad. 

Yeah this is miserable, they should fix it. Only other way I know of, is if you torrent the blockchain from someone else, and then run the omni core on it to verify blocks in a few hours. If our omni node synces, will share it with you. 
Let me know once you get omni fully setup?

**Comment by luongnguyenduc** [comment]
After Bitcoin Core finished syncing, I opened Omni Core, it started syncing from the beginning. This is so frustrating.

**Comment by gpoddar** [comment]
That sucks! Still, your BTC synced a lot faster. Which region are you in and what hardware are you using? We're in India and using a 4 GB AWS machine for BTC, and a 16 GB AWS machine for Omni. Its taking forever, maybe even 2 more weeks is what its saying. I don't know if we are connecting to bad peers or have to change something in our config.

Also I read your previous comment, you said testnet flag. Thats a separate smaller blockchain from the mainnent. Just mentioning incase

**Comment by luongnguyenduc** [comment]
I am in VietNam, I'm using 2 computers 8GB and 16GB, I don't think there is any problem with our hardware or network.
What OS are you using, have you finished syncing? I used Windows and both were unbelievably slow from block 700k.
Now I am using Ubuntu (Virtualbox) and waiting for it to reach block 700k.

**Comment by gpoddar** [comment]
You're syncing the testnet blockchain (currently block 1447k). mainnet is a different blockchain (553k). Sorry, to let you know but what you have is useless (unless you wanted testnet)

**Comment by sg552** [comment]
I met the same problem , my node has been syncing for 7 days, and now reached 503745 block,  10 block/minute. In this speed, the sync will be done in 35 days. 

10 block/minute * 60 minute * 24 hour = 1440 block / day
50000 / 1440 = 35 days . 

am I doing something wrong?

**Comment by gpoddar** [comment]
I'm not sure, but am facing same issue. It starts quickly, and slows down. Ours will complete in a 4-5 days. 

What's your RAM size? 

What have you put in your config file? 

Hav you tried running a prune node (note: we haven't tried it, and I don't think you can for Omni to work, but just asking in case)

**Comment by sg552** [comment]
2G RAM , 1core CPU

in my config file the content is normal . shown as below: 

```
rpcuser=cxxxx_usdt
rpcpassword=aaxxx_$$
rpcport=8332
rpcallowip=127.0.0.1
rpcallowip=192.168.2.0/24
datadir=/opt/usdt_data/
daemon=1
server=1
txindex=1

```

and it synced from '2018-01-11' to '2018-04-23' in the past 1 day.  seems its speed up. 

nope, I haven't tried a prune node. 

now I am guessing the node is able to create wallet, send transaction without a full data synced.

**Comment by gpoddar** [comment]
Nice, how many ~blocks/min is that?

**Comment by sg552** [comment]
I am using google cloud , asia-east area, 
I haven't configured the IP that my node connected to, it's by default. 

The used hard disk is more than 252G till now. It's very quick/easy for me to enlarge it via google cloud.

**Comment by sg552** [comment]
my sync is done in about 10 days.

**Comment by dexX7** [comment]
Hello guys, please upgrade to v0.4.0 and let me know, if this is still an issue. This release includes performance improvements.

**Comment by thcrnk** [comment]
I am using v0.4.0 and syncing the testnet from 2 weeks and I am half way done, currently on block 782 000.

**Comment by hk-ng** [comment]
I am using v0.4.0.
Syncing the testnet from 3 days and currently on block 676000.
