### ISSUE TITLE
My transaction is still unconfirmed in OMNI simple send

### ISSUE THREAD

**Issue by dineshnemali** [OmniLayer/omnicore#838]
Hi ,

I see omni explorer has 78 pages of unconfirmed transactions   and others with 1 confirmations .. 

My transaction is waiting for 10 hours to get it confirmed ,can you please check it .

Simple Send
882c998a356f1bc6b3c582f853089e92ff53e2667a55a60afa9d209f3d2fff1d

**Comment by santos177** [comment]
Hi @dineshnemali :  
Your fee was very small, if you don't want to way so much time you should increase it .
You can watch this here: https://github.com/OmniLayer/omnicore/wiki/Platform-Integration-of-Omni-Core#transaction-structure-and-network-fees
