### ISSUE TITLE
Sending tokens with multiple transactions with a single input

### ISSUE THREAD

**Issue by yairas22** [OmniLayer/omnicore#844]
Let's assume that I have an address X with 100 tokens that were sent by 1 transaction.
Meaning: I have 1 OMNI/BTC input for creating a new transaction, assuming address X does not hold Bitcoins - I add another input with bitcoins.

Now I would like to do the following operations:
- Send to address Y 20 tokens from X
- Send to address Z 40 tokens from X

Problem is - I have only 1 transaction input of the `sendingaddress` to create a transaction so I can only send to address Y the 20 tokens.

How do I resolve this issue? do I need to wait until someone sends token(s) to address X for sending to address Z the 40 tokens?

**Comment by santos177** [comment]
I @yairas22 :  
You only needs enough BTC in address X to send any transaction you want (of course, if you want to send 2 OMNIS, you need balance equal or more than 2 OMNIS). 
https://github.com/OmniLayer/omnicore/wiki/Why-do-I-need-bitcoin-to-create-Omni-transactions%3F

**Comment by yairas22** [comment]
@santos177 :
But I don't need to store BTC in address X I can just add another input with bitcoins so this does not answer my question :) I have balance of 100 OMNIS in address X and I **don't want** to store bitcoins in this address so the change goes to different bitcoin address.

**Comment by dexX7** [comment]
Hello @yairas22,

currently it's not possible to send multiple tokens in one transactions and you always need some BTC to send a transaction. However, you could send some change back to the original address and then use "funded sending" to pay the missing amount in the second transaction:

https://medium.com/omnilayer/introducing-funded-omni-layer-transactions-or-how-exchanges-can-save-money-f3f04161a6af
