### ISSUE TITLE
omni_funded_send execution error

### ISSUE THREAD

**Issue by DengMins** [OmniLayer/omnicore#847]
Geth version: geth 1.8.17-stable
OS & Version: Ubuntu 5.4.0-6ubuntu1~16.04.4
OmnicoreVersion：0.3.1

Error sending USDT

![802152040310785236](https://user-images.githubusercontent.com/20965425/49636268-1958d000-fa3d-11e8-8373-d98a95b9142d.png)

@dexX7

**Comment by santos177** [comment]
Hi @DengMins  ;   
Have you ever tried using ./omnicore-cli instead of omnicore-cli ?

**Comment by DengMins** [comment]
> 嗨@DengMins ; 
> 你有没有尝试过使用./omnicore-cli而不是omnicore-cli？

Hi @santos177 ；
Thank you for answering my question. Your way is right, but I can't understand why? Other commands can be executed successfully using "omnicore-cli", but only "omni_funded_send" is not executed successfully.

**Comment by DengMins** [comment]
> Hi @DengMins ;
> Have you ever tried using ./omnicore-cli instead of omnicore-cli ?

Hi @santos177 ；
Thank you for answering my question. Your way is right, but I can't understand why? Other commands can be executed successfully using "omnicore-cli", but only "omni_funded_send" is not executed successfully.

**Comment by dexX7** [comment]
I'm glad this issue was resolved this easily. :)
