### ISSUE TITLE
Why my sync is so slow? (takes 7 days reached 50,000 blocks) and will done in 35 days

### ISSUE THREAD

**Issue by sg552** [OmniLayer/omnicore#849]
My node has been syncing for 7 days, and now reached 503793 block,  10 block/minute. 

In this speed, the sync will be done in 35 days. 

10 block/minute * 60 minute * 24 hour = 1440 block / day

Current block height is : 55300, so : 

53000 (remaining blocks) / 1440 = 36.8 days .    >_< 

am I doing something wrong?

My config:  
CPU 1 core
RAM: 2G
SSD:  250G ( used 193G )

~/.bitcoin/.bitcoin.conf

```
daemon=1
server=1
txindex=1
```

**Comment by sg552** [comment]
OK, My node has successfully synced all the blocks today.

**Comment by CyanZero** [comment]
> OK, My node has successfully synced all the blocks today.
> 
> thanks~

Hi, we encountered the same problem and we have more powerful server than yours, how did you resolve this slow sync issue? Thanks in advanced!

**Comment by sg552** [comment]
I did nothing, just waiting . and suddenly  the sync is done. ^_^

**Comment by CyanZero** [comment]
> I did nothing, just waiting . and suddenly the sync is done. ^_^

Thanks for the reply, we upgraded to SSD and restart the process with the latest v0.4, it's about 10 times faster and we finally caught up :P

**Comment by sg552** [comment]
Yeah! you got it!  for the most crypto full node ( e.g. eth, usdt ) , you have to use SSD disk. otherwise , the process will be 99.99% forever.   

so now for me I use SSD for all the node ( parity, omnicore, bitcore ) .    :-)
