### ISSUE TITLE
How to generate usdt address?

### ISSUE THREAD

**Issue by harrymaurya05** [OmniLayer/omnicore#850]
I  has done the setup of Omni layer on Debian aws instance. how can i generate USDT(Tether) address?

**Comment by ngocbd** [comment]
Usdt address is btc address

**Comment by harrymaurya05** [comment]
Thank you @ngocbd  
can you please tell me how to transfer usdt to one address to another address.

**Comment by harrymaurya05** [comment]
so basically according to you command should look like this " omnicore-cli omni_send addressSender addressReciver 31 "1" "

**Comment by harrymaurya05** [comment]
Hello, I'm new in omnicore client but as I understand 31 property identifer is assign for Usdt (tether) but
when i execute this command "omnicore-cli "omni_getproperty" 31" i'm getting this as a result
"
{
"propertyid": 31,
"name": "tokenmagic.com",
"category": "TOKENMAGIC",
"subcategory": "TOKENMAGIC",
"data": "",
"url": "Beeswax",
"divisible": false,
"issuer": "mrAVAPxdQEZxFkunh56skB6sgJa6vrfrpo",
"creationtxid": "9588ab12ef040767b1e9fe4181e294409da6cab9792f89ccc55bc621b47e2563",
"fixedissuance": true,
"managedissuance": false,
"totaltokens": "80000"
}
"
if 31 is for tether then why 31 show tokenmagic.com instead of tether.to

**Comment by gornov** [comment]
Because you're using testnet. It's just PropertyID.

**Comment by harrymaurya05** [comment]
Thank you all!!
