### ISSUE TITLE
我没有收到usdt

### ISSUE THREAD

**Issue by LiHang941** [OmniLayer/omnicore#854]
My English is not good.
我就用中文说明下我的情况，我给   moneyqMan7uh8FqdCA2BV5yZ8qVrc9ikLP 转账了0.2BTC,但是我没有收到 100 OMNI 和100 TOMNI
https://live.blockcypher.com/btc-testnet/tx/baba55f2211ce24054c1ee429db1416becb72150e82e23b0000d609efee120f8/
https://live.blockcypher.com/btc-testnet/tx/436e7e623ab8996125a1741d3d410aae788cfababc6b85187912b7a618b77693/

请帮帮我，我想测试rpc流程

**Comment by yangkun0824** [comment]
你应该已经有了，他不会再给你发一次请求，但是余额已经有了

**Comment by dexX7** [comment]
Please let me know, if this issue was resolved.
