### ISSUE TITLE
omni_funded_send  send BTC to referenceaddress?  WTF

### ISSUE THREAD

**Issue by lijianl** [OmniLayer/omnicore#856]
today, i use omni_funded_send, send usdt to an address, however, this address receive usdt and BTC?
where this happened?????
`
{
    "jsonrpc": "2.0",
    "method": "omni_funded_send",
    "params": ["1P8JznMkFbzSGnBKzvoEhvCdfm35DG6WaU","17LMo9w14Y9KdBBjNbbnVeKTgkT55MLQjw",31,"0.10000","1P8JznMkFbzSGnBKzvoEhvCdfm35DG6WaU"],
    "id": 9527
}
'

the transaction is 2397b0496cd955be23c4cd9dc23ed35bdb33aebc8736969e52850bbe9bc7e750, where BTC sended

**Comment by lijianl** [comment]
@msgilligan

**Comment by santos177** [comment]
Hi @lijianl :  
 I've been watching your transaction. Nothing is wrong, it's just the "dust" amount of BTC used by Omni to pointing the destinator address. Look at this https://chain.so/api/v2/tx/BTC/2397b0496cd955be23c4cd9dc23ed35bdb33aebc8736969e52850bbe9bc7e750   . Output 0 : who paid the fee. Output 1: the payload. Output 2: destinator. 
Cheers!
