### ISSUE TITLE
Testnet Omni and TestOmni

### ISSUE THREAD

**Issue by rockandruby** [OmniLayer/omnicore#857]
why do you send Omni to address in testnet??? So from your faucet I recieve OMNI and TOMNI and when I do omni_funded_sendall within test ecosystem only TOMNI transfers. As a result when I do omni_getwalletaddressbalances I have addresses with only OMNI and 0 btc balance(because transaction was made and no 0.00000546btc left) and finally Error: {"code"=>-212, "message"=>"Error choosing inputs for the send transaction"}

**Comment by ngocbd** [comment]
"Error choosing inputs for the send transaction" this is cancer error still remain in omnicore :D

**Comment by rockandruby** [comment]
@ngocbd the question isn't  in error, I know it's origin. The question is why do they send me OMNI in testnet mode

**Comment by dexX7** [comment]
Hello @rockandruby,

the sendall transaction has an "ecosystem" parameter, where you can specify, whether all main or test properties are transferred.

In this case: when you use 1 (= main ecosystem), Omni will be transferred and when you use 2 (= test ecosystem), Test Omni will be transferred.
