### ISSUE TITLE
how to get usdt on mainnet?

### ISSUE THREAD

**Issue by harrymaurya05** [OmniLayer/omnicore#863]

**Comment by harrymaurya05** [comment]
Hi, @santos177 I read the post in the link you provide but frankly speaking, I don't get too much form this. 
can you tell me something simple way to understand how to get real usdt in mainnet?

**Comment by harrymaurya05** [comment]
> Hi @harrymaurya05
> 
> 1. Watch the metadex's orders using the command : omni_getorderbook 31 (31 is the id of USDT) . You have to accept the offer and then pay in BTCs. See more here: https://github.com/OmniLayer/spec#purchase-mastercoins-with-bitcoins
> 2. Use other exchanges and then send to your address the tokens.
> 
> Cheers!

Hi, @santos177 I read the post in the link you provide but frankly speaking, I don't get too much form this.
can you tell me something simple way to understand how to get real usdt in mainnet?

**Comment by askucher** [comment]
How to run the mainnet of USDT?

**Comment by santos177** [comment]
@harrymaurya05:
You must buy it from someone else. You have two options. The first one is use the metadex ( decentralized exchange of omnilayer) using the command commented after, you can exchange for example omnis for usdt. Other way ( i've forgot it) is use the dex ( but i think this option is more complicated). The easy way is use a normal exchange (bitfinex or binance). I hope it helps
