### ISSUE TITLE
testnet omni_funded_send fail

### ISSUE THREAD

**Issue by isguoky** [OmniLayer/omnicore#865]
I now use both bitcoin-cli and omnicore-cli nodes.  They each have an address，When I use the omnicore address to send a token to the bitcoin address, it succeeds，but when I use the bitcoin address to send to the omnicore address, it will report an error, here are the steps

bitcoin address `mmqZKafWqR4oPovKv7uD6YGTVmLX5GY2Mu`
omincore address `mz5SxybDBszwStgyT1QwLjbHctrw8aJQBr`

```bash
$ omnicore-cli omni_funded_send "mz5SxybDBszwStgyT1QwLjbHctrw8aJQBr" "mmqZKafWqR4oPovKv7uD6YGTVmLX5GY2Mu" 2 4 "mz5SxybDBszwStgyT1QwLjbHctrw8aJQBr"
03506ce946fab4934d397bde752e8343232b60ee0ef0a67f0cab1238b0df4042
```

```bash
$ omnicore-cli omni_funded_send 'mmqZKafWqR4oPovKv7uD6YGTVmLX5GY2Mu' 'mz5SxybDBszwStgyT1QwLjbHctrw8aJQBr' 2 5 'mmqZKafWqR4oPovKv7uD6YGTVmLX5GY2Mu'
error code: -212
error message:
Error choosing inputs for the send transaction
```
Is on the testnet, and the `fromaddress` has enough balance，please help me

**Comment by isguoky** [comment]
If can't send each other, why the first step can be sent, and the second step can't be sent?

**Comment by dexX7** [comment]
Hello, I assume "mz5SxybDBszwStgyT1QwLjbHctrw8aJQBr" has all the BTC, while "mmqZKafWqR4oPovKv7uD6YGTVmLX5GY2Mu" only has some dust, right?

So you can use "mmqZKafWqR4oPovKv7uD6YGTVmLX5GY2Mu" to send tokens, but you need so specify a source to pay the transaction fees. This could be done with the other address, e.g. like this:

```
$ omnicore-cli omni_funded_send 'mmqZKafWqR4oPovKv7uD6YGTVmLX5GY2Mu' 'mz5SxybDBszwStgyT1QwLjbHctrw8aJQBr' 2 5 'mz5SxybDBszwStgyT1QwLjbHctrw8aJQBr'
```
