### ISSUE TITLE
I am getting error when i install omni core in server.

### ISSUE THREAD

**Issue by rajmantechnology** [OmniLayer/omnicore#866]
configure.ac:76: the top level
configure.ac:1132: error: possibly undefined macro: PKG_CONFIG_LIBDIR
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/local/bin/autoconf failed with exit status: 1

configure: error: *** A compiler with support for C++11 language features is required.

![screenshot_1](https://user-images.githubusercontent.com/25636468/51246428-79358580-19b0-11e9-8786-f8042f3cb677.png)

**Comment by ngocbd** [comment]
what is the version of gcc you used? It should be > 4.8

**Comment by dexX7** [comment]
Hello, did you follow the exact steps outlined in the build doc?

https://github.com/OmniLayer/omnicore/blob/master/doc/build-unix.md
