### ISSUE TITLE
how to launch the usdt node?

### ISSUE THREAD

**Issue by askucher** [OmniLayer/omnicore#867]
Do you have an example how to setup usdt node by using omnicore? 

Need clarification. I read that's it is possible but no clear documentation

**Comment by ngocbd** [comment]
So you need to run omnicore , then you have usdt node, just so.

**Comment by dexX7** [comment]
Hi there, check out the following post:

https://github.com/OmniLayer/omnicore/wiki/Platform-Integration-of-Omni-Core
