### ISSUE TITLE
[Mainnet] omni_funded_send error with available btc in feeaddress

### ISSUE THREAD

**Issue by tranchiendang** [OmniLayer/omnicore#869]
Hi,
I am facing problem when using omni_funded_send. As i know, i need deposit btc to feeaddress.
But after deposit to feeaddress, still get error _**has no coin**_ 
Go to any btc explorer, i can see my balance is  **0.7357886 BTC** 
When running this command **listunspent 0 999999** i'm getting no value returned.
Any suggestion for me to verify it.

**Comment by ngocbd** [comment]
Can you show 2 addresses ?

**Comment by oslivan** [comment]
I have same problem, my address is 12fVdGzZpVoe4E9MUtCzXa4NNjZ6rTGKLL @ngocbd

**Comment by oslivan** [comment]
Thank you for your reply, restart did not work for me, but I will try the signature transaction you said, thank you!

**Comment by tranchiendang** [comment]
After debugging more and more, i guess that issue may come from a threshold with chaining unspent transaction. 
If i create more than 25 transactions, and submit at once, omnicored wont calculate unspent transaction, thus throw error related with Address has no coin / too long mempool chain.
My workaround solution is, submit 20 transactions, and wait all of them getting at least 1 confirmation, then continuing submit 20 transactions and so on.
With this approach, i dont need to restart omnicored.
Thank you all.

**Comment by ngocbd** [comment]
@tranchiendang you can tracking unspend output by your application logic .

**Comment by dexX7** [comment]
Hey guys, indeed: when you try to spend a too long chain of unconfirmed transactions, it won't work. This is because other nodes won't further relay these transactions as per default.

**Comment by uzkicc** [comment]
code":-213,"message":"Error committing transaction"

please help me
