### ISSUE TITLE
omni_gettransaction response problem

### ISSUE THREAD

**Issue by Pz9524** [OmniLayer/omnicore#871]
hello, i use omni_gettransaction get transaction detail ,it return the response {txid=75f2a59db900d327d0aa806d939a8cbfa6aa47360c0cdcfd2391cb0c2b2ec420, type=DEx Purchase, sendingaddress=1Nmz4bdPQC4jnNB2aHGmNhHLy3tbuadW4y, purchases=[{vout=1, amountpaid=0.30000000, ismine=false, referenceaddress=1v9yVMJP1d9AhrdYicAoDJCjXdVuuTAo5, propertyid=1, amountbought=400.00000000, valid=true}], blockhash=00000000000000000010404a10adf9cbb9290f3423ae07bfeeaa49b159c816c8, blocktime=1548079918, block=559478, confirmations=81}. The propertyid is not the propertyid of usdt and the json format of the response is not same as the official format.

**Comment by lutk** [comment]
Same problem with format. Can anyone explain?

https://github.com/OmniLayer/spec#field-transaction-type
Size: 16-bit **unsigned integer**

https://api.omniexplorer.info/v1/transaction/tx/75f2a59db900d327d0aa806d939a8cbfa6aa47360c0cdcfd2391cb0c2b2ec420
"type_int": **-22**

What's happening? How to handle it? How does this affect the balance?

**Comment by dexX7** [comment]
Hello,

this is not a regular Simple Send transaction, but a trade of BTC for Omni:

https://github.com/OmniLayer/spec/#distributed-exchange
