### ISSUE TITLE
How to create transaction. Please help

### ISSUE THREAD

**Issue by hakerkiler** [OmniLayer/omnicore#873]
[root@bitcoin src]# ./omnicore-cli omni_send "mx7r52d2oaNTeiMDr2zrcw2VGm1BQurC9K" "n4YZv8eV8VTXW2ae2uZhnb64KdK3jS4GCx" 2 0.2
error code: -32601
error message:
Method not found

This method is not work. 
https://omniexplorer.info/address/1ExXugzdTNKSHfEF4RBx8by915h5VPEE4S
i have 20 TetherUS
how can transfer is to other address?
Please halp me

**Comment by achamely** [comment]
@hakerkiler  please double check your bitcoin.conf to make sure the omnicore-cli command is actually connecting to an omnicored client. 
Omnicore-cli is just like bitcoin-cli it does not do anything itself and instead sends the commands to the backend daemon (as specified in the bitcoin.conf file) . 
If it is using the normal bitcoin.conf for a bitcoind daemon running on that machine it will not have access to the omni protocol. It must connect to an running omnicored instance to enable the Omni protocol commands.
