### ISSUE TITLE
How to send a transaction which create/sign transaction is offline and send is online?

### ISSUE THREAD

**Issue by ying2025** [OmniLayer/omnicore#875]
I konw it can pack command like this https://github.com/OmniLayer/omnicore/wiki/Use-the-raw-transaction-API-to-create-a-Simple-Send-transaction, but I want to konw whether can use following rpc just including those command https://github.com/OmniLayer/omnicore/blob/master/src/omnicore/doc/rpc-api.md to send a transaction?

**Comment by dexX7** [comment]
Hi, currently this is the only way to craft raw transactions.
