### ISSUE TITLE
senddexsell accept others properties

### ISSUE THREAD

**Issue by santos177** [OmniLayer/omnicore#876]
Hi every one:

I've found that the omni_sendexsell command allows properties (like 31 tether) .According with the spec we can't trade in the DEx different properties from omni or tomy (propertyId=1 or propertyId=2). In the following line ParsePropertyId is not doing the right filtering : 

https://github.com/OmniLayer/omnicore/blob/master/src/omnicore/rpctx.cpp/#L312

Maybe this is related with #871

@dexX7  can you help us?

**Comment by achamely** [comment]
@santos177 the spec needs some updates.  
OmniDex trading of Omni property for Omni property was enabled (feature id 8) in block 438500 and is currently live/allowed.

**Comment by santos177** [comment]
@achamely :   
I'm understand, but i'm not talking about the MetaDEx. I'm talking about the ids issues when you want to purchase (using Bitcoin) tokens, please read the issue  #871. Thanks!

**Comment by achamely** [comment]
@santos177 sorry for any misunderstanding.
I've double checked the function you referenced and the PropertyID enforcement is done a few lines later. Take a look and see the calls to RequirePrimaryToken(propertyIdForSale) 
This function enforces the PropertyID restriction of 1 or 2 accordingly  https://github.com/OmniLayer/omnicore/blob/master/src/omnicore/rpcrequirements.cpp#L30-L35 and anything outside of this will cause the function to fail.
