### ISSUE TITLE
[feature request] make electrum fork to send OMNI tokens (especially USDT)

### ISSUE THREAD

**Issue by gituser** [OmniLayer/omnicore#880]
Hi.

Why not make a better light wallet for end users? 

Sending Tether (USDT) or MAIDsafe tokens or any other type of OMNI tokens is very complicated - you need to download and install omnicore wallet or use website - https://www.omniwallet.org/ also there is a 3rd way (more secure, but still very complicated through armory) - https://github.com/OmniLayer/omniwallet/wiki/Armory-Offline-Addresses

E.g. electrum based light wallet, so users would be able to operate tokens in OMNI ecosystem without downloading 200+GB of bitcoin's blockchain?

Here is some guy presented how to send USDT through electrum manually: https://jochen-hoenicke.de/crypto/omni/

You could automate this method via nice GUI so users would be able to send tokens much more easily.

Feel free to move this issue into different project if it's not related to omnicore.

**Comment by dexX7** [comment]
We would really love to have this!
