### ISSUE TITLE
Diffrerence between mainnet and testnet when run get_balance for wallet

### ISSUE THREAD

**Issue by KursLabIgor** [OmniLayer/omnicore#886]
I have run two identical omni nodes. 
One node points to testnet another to mainnet. 
This `omni_getallbalancesforaddress` function return different response depends on network.
Is it expected or it is bug or it is some config parameter?

`Testnet
./omnicore-cli omni_getallbalancesforaddress "moLWFdR3ypd15xnQPgehRdRaanEZ24FAGx"
[
  {
    "propertyid": 2147484828,
    "name": "Quantum Miner",
    "balance": "10000000000",
    "reserved": "0",
    "frozen": "0"
  }
]
`

`Miannet
./omnicore-cli omni_getallbalancesforaddress "12TrtpSGhbXhnn9wrT2eg62ibY9UULAitH" 
[
  {
    "propertyid": 31,
    "name": "TetherUS",
    "balance": "10.00000000",
    "reserved": "0.00000000",
    "frozen": "0.00000000"
  }
]
`
balance format is not equal between networks.

**Comment by santos177** [comment]
Hi @KursLabIgor :   
Yes, it's what we expected. You have to view the testnet as a blockchain only for testing, similar to mainet, but separated of it. I hope it helps!

**Comment by KursLabIgor** [comment]
@santos177 ok, but if I check balance on Omni expolorer it give me result in format as testnet, why?

**Comment by achamely** [comment]
@KursLabIgor it depends on the token. 
A token can be either divisible or not. 
Divisible tokens are represented with decimal balances and can be sent in fractional amounts just like bitcoin 1.1, 4.33,0.3333, etc...
Non Divisible tokens are represented as whole numbers and can only be sent as whole units, 1,2,3,4,5....1000 etc..
On Mainnet Tether is a divisible token and represented with decimals. On testnet the Quantum miner token is not divisible so represented with whole numbers
