### ISSUE TITLE
Not all UI views handle block reorganizations properly

### ISSUE THREAD

**Issue by dexX7** [OmniLayer/omnicore#89]
I noticed it while testing with the current 0.0.10 branch, but not yet with the UI branch, so the results may already be different there.

Not all UI views are updated after reorganizations or chain forks:

 - [ ] overview: balances are not cleared
 - [ ] balances
 - [x] send dialog
 - [x] trading interface: address selectors are not cleared (trades are)
 - [x] trade history: not cleared
 - [x] trade cancel dialog: address selectors are not cleared
 - [x] transactions: transactions are shown as unconfirmed, no details available
 
After a restart, all views are fine.

In regtest mode, it can be triggered with:
```shell
# generate transactions ...
$ ./src/bitcoin-cli getblockhash 3 # or anything
3b2d47cf687c118d7bfb3c6a2213bd6934c91ae5142e413f0358a51a9dd8e8ec
$ ./src/bitcoin-cli invalidateblock 3b2d47cf687c118d7bfb3c6a2213bd6934c91ae5142e413f0358a51a9dd8e8ec
$ ./src/bitcoin-cli setgenerate true 1 # required to trigger update
[
    "4eeb404c435f51b12acbe210c6dc057d3834835cb06941fd8d64808e6d29ff08"
]
```

![overview](https://cloud.githubusercontent.com/assets/5836089/8322721/55f6fcf8-1a3a-11e5-98fe-a37da7334a0c.png)

![trade_ui](https://cloud.githubusercontent.com/assets/5836089/8322725/59379d64-1a3a-11e5-9161-51d02170840e.png)

![trades](https://cloud.githubusercontent.com/assets/5836089/8322726/5b1cd77a-1a3a-11e5-8e4f-423dfb9d6115.png)

![trade_cancel](https://cloud.githubusercontent.com/assets/5836089/8322734/68cbcc28-1a3a-11e5-9373-64c2c2d5b57a.png)

![txhistory](https://cloud.githubusercontent.com/assets/5836089/8322729/5d77b2b0-1a3a-11e5-88a2-5b83f9ad8476.png)

In the BTC history the transaction details are still available, and transactions are flagged as "conflicting", but I don't think this is something we should necessarily mirror:

![tx_btchistory](https://cloud.githubusercontent.com/assets/5836089/8322756/a95678b0-1a3a-11e5-9409-3ec19dd3e53e.png)

**Comment by zathras-crypto** [comment]
Sounds like we need to add a kind of "full refresh" because the UI is designed for iterative updates where things are added, it's not really suited for things being removed. 

I can sort this out, leave it with me :)

**Comment by zathras-crypto** [comment]
I'm still not up to speed with the regtesting stuff (I know!!!), could you run https://github.com/zathras-crypto/omnicore/commit/f62f8f88843ee20382b06957fd7dcd2dc760973e and let me know if that resolves these issues?

**Comment by dexX7** [comment]
Code looks good! I'm currently building, and report back soon.

**Comment by dexX7** [comment]
`metadexcanceldialog` and `tradehistorydialog` use `reinitOmniBalance`, which doesn't seem to exist.

The balances on the overview page and balance tab receive the signal, but don't clear properly. The identifiers are not identifiable.

Wild guess: the global balance objects might be the reason.

**Comment by zathras-crypto** [comment]
Yikes! :) hehe that'll teach me to pump out code untested.  Alright no more excuses, regtest mode here I come!

**Comment by zathras-crypto** [comment]
Alright, https://github.com/zathras-crypto/omnicore/commit/5c34c70ed2919fed9799540039f4ba83a04b5c38

I've run it through a regtest scenario and I think this should be better :)

**Comment by dexX7** [comment]
Issue resolved with https://github.com/zathras-crypto/omnicore/commit/5c34c70ed2919fed9799540039f4ba83a04b5c38 via #82.
