### ISSUE TITLE
i hava some question

### ISSUE THREAD

**Issue by bingge1** [OmniLayer/omnicore#890]
1、if my btc transaction have multiple input (different address)to the transaction,which input address is OMNI Token sender Address
2、if my btc transaction have three output,whitch one output is Omni Token receive address,which one is change address?

我有个疑问是， 加入我的输入有多笔，而且每一笔都有对应的Omni代币，那应该优先扣除哪一笔input address对应的代币？
我的输出有三笔，那如何确定 哪一笔是找零，哪一笔是到账usdt的接收地址？？
thanks!

**Comment by achamely** [comment]
@bingge1 
1. The address that corresponds to the first input 
2. The last address in the output which is not the sending address
