### ISSUE TITLE
How to find balance of  whole node for some property or for all properties

### ISSUE THREAD

**Issue by vladyslavstartsev** [OmniLayer/omnicore#891]
I want to get info of whole node, something like `getwalletinfo` in bitcoin, where it will show balance of whole node

Is there something like that in omni?

In my case I want to get balance of TetherUSD

**Comment by achamely** [comment]
@vladyslavstartsev  yes, take a look at https://github.com/OmniLayer/omnicore/blob/master/src/omnicore/doc/rpc-api.md#omni_getwalletbalances
