### ISSUE TITLE
getaddressinfo Method not found 

### ISSUE THREAD

**Issue by yhx1014** [OmniLayer/omnicore#892]
example 
curl --user myusername --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "getaddressinfo", "params": ["1PSSGeFHDnKNxiEyFrD1wcEaHr9hrQDDWc"] }' -H 'content-type: text/plain;' http://127.0.0.1:8332/

result: Method not found
error code: -32601
error message:
Method not found

**Comment by achamely** [comment]
@yhx1014  `getaddressinfo` is not a supported rpc call. 
send the 'help' command to see all available rpc calls the client supports.
