### ISSUE TITLE
omni_send with null referenceamount

### ISSUE THREAD

**Issue by dannywillems** [OmniLayer/omnicore#894]
Hi

I try to send USDT with a null referenceamount. I created a previous raw transaction: https://www.blockchain.com/btc/tx/a10111305ebe011ecc984c1c07ef60e725f7a96f11c1d59001acebd2abd2d2a7?show_adv=false
Some BTC have been sent to `1JJGCfAPmmV79yJMbCbnXWWntZgjHBZtzn` which is something I dont't want.
When I try to create a transaction without any referenceamount, I've got this error:
```
./omnicore-cli  "omni_send" "12eXXt156hevSx14c7pgryQcGLiPBFcPMj" "1JJGCfAPmmV79yJMbCbnXWWntZ
gjHBZtzn" 31 "1" "12eXXt156hevSx14c7pgryQcGLiPBFcPMj" "0.0"
error code: -3
error message:
Invalid amount
```
Is there always the dust? No way to bypass it?

**Comment by achamely** [comment]
@dannywillems  That is correct. 
Bitcoin transactions do not allow a 0 value for an address output and since the Omni protocol is built on / uses the bitcoin blockchain it is the same constraint. 
There always has to be some amount of BTC for each address in the output list

**Comment by dannywillems** [comment]
Thanks @achamely
