### ISSUE TITLE
getbalance问题

### ISSUE THREAD

**Issue by zhlqee** [OmniLayer/omnicore#895]
为什么使用getbalance + 账户名的形式去查询余额，会返回很多的BTC
![image](https://user-images.githubusercontent.com/26194099/53950436-1ab29b00-4107-11e9-92c0-7c699f70d966.png)

这个账户下只有一个地址
![image](https://user-images.githubusercontent.com/26194099/53950456-269e5d00-4107-11e9-9c58-e23c7b62f983.png)

在BTC官网查询余额才是真实的余额
![image](https://user-images.githubusercontent.com/26194099/53950466-2d2cd480-4107-11e9-9ee9-b48884bc2945.png)

**Comment by dexX7** [comment]
Hello,
there is no convenient way to check BTC balances, but please take a look at #899.
