### ISSUE TITLE
omni_funded_send fails when tx fee is lower than dust value

### ISSUE THREAD

**Issue by bahadirbb** [OmniLayer/omnicore#896]
https://github.com/OmniLayer/omnicore/pull/769 causes this bug. This merge causes omni to prevent creating same output twice on omni_funded_send (when target == fund address). It first skips sending dust value to target account (assuming change will be sent to that address) and when tx fee is lower than dust value it also skips funding the transaction. which causes tx to be created without any outputs. This bug currently affects transactions on testnet.

Proposed Solution:
Create the tx with two similar outputs. When tx is ready - check for duplicate outputs and merge them into a single output before sending it to network

**Comment by dexX7** [comment]
Thanks for the report, this is something we should fix!

**Comment by dexX7** [comment]
Should be fixed with 0.7. :)
