### ISSUE TITLE
Can't get test OMNI coin from  moneyqMan7uh8FqdCA2BV5yZ8qVrc9ikLP 

### ISSUE THREAD

**Issue by greensea** [OmniLayer/omnicore#897]
I sent 1 BTC to  moneyqMan7uh8FqdCA2BV5yZ8qVrc9ikLP, but have not receive test OMNI coin.
According to docs, I should got 100 test OMNI coin from  moneyqMan7uh8FqdCA2BV5yZ8qVrc9ikLP.
The transaction is: https://live.blockcypher.com/btc-testnet/tx/0d33b18b9af4a62d4f743f75c60676728d3641fa9976ae75379833a959d123b1/
My address is:  miP26Hee4rJipuf5CX1YMC8ecsQKuLudnr

The transaction already have 6+ confirms, but no omni transaction sent to my address.

**Comment by greensea** [comment]
Sorry for the mistake, my BTC address is: miP26Hee4rJipuf5CX1YMC8ecsQKuLudnr

**Comment by greensea** [comment]
I have got test OMNI coin, seems there is some lack.

**Comment by sundarammmn** [comment]
i really need test OMNI coin, @greensea can transfer 10 coin to my address mfwM1udyoSoMCFHyHCvaRJjK9LaMKmW2Ff .
