### ISSUE TITLE
how can i create a raw sign  transaction  to hex then broadcast the hex 

### ISSUE THREAD

**Issue by cancerts** [OmniLayer/omnicore#898]
i want used the privatekey to sign the transaction body then get the raw hex then 

========================================

then https://api.omniexplorer.info/v1/transaction/pushtx/ broadcast

**Comment by nival999** [comment]
Try this good sir: https://bitcoin.stackexchange.com/questions/74511/how-to-create-an-omnilayer-transaction-by-myself

**Comment by dexX7** [comment]
Hi @cancerts, check out the following post:

https://github.com/OmniLayer/omnicore/wiki/Use-the-raw-transaction-API-to-create-a-Simple-Send-transaction
