### ISSUE TITLE
Api for check btc balance on omniusdt node ?

### ISSUE THREAD

**Issue by ambrish-dev** [OmniLayer/omnicore#899]
Is there any command for check btc balance of omniisudt address on omniusdt node ?. I want to check there is btc balance available to transaction fee .

Please help.

**Comment by dexX7** [comment]
Hello, you could use the ["listunspent" RPC ](http://chainquery.com/bitcoin-api/listunspent) to list unspent outputs of your wallet. There is no more convenient way currently available.

**Comment by dmitryrn** [comment]
@dexX7 but why?
