### ISSUE TITLE
omni_createpayload_simplesend doesn't handle decimals well

### ISSUE THREAD

**Issue by palimarrao** [OmniLayer/omnicore#916]
Here are some examples

```
./bin/omnicore-cli -datadir=data "omni_createpayload_simplesend" 3 "1"
00000000000000030000000000000001

./bin/omnicore-cli -datadir=data "omni_createpayload_simplesend" 3 "1.01"
00000000000000030000000000000001

./bin/omnicore-cli -datadir=data "omni_createpayload_simplesend" 3 "0.1"
error code: -3
error message:
Invalid amount
```

Notice that everything after the decimal is ignored, and amounts less than 1 result in an error. Is this expected behavior? Should amounts of divisible tokens be provided in the lowest possible denomination (i.e. multiple the amount by 100,000,000)?

**Comment by santos177** [comment]
If you look this line of the code https://github.com/OmniLayer/omnicore/blob/master/src/omnicore/rpcpayload.cpp/#L41
you can see how the amount variable is created. This variable depends of the property (if this property is divisible or indivisible). I don't know if you are in testnet or in mainnet, but i can guess that the property 3 that you are using is indivisible, so if you write 1.01 , the system just take this as 1. If you write 0.1, the code take this as 0, so you can't send 0 amount (this happened in parseamoun function: https://github.com/OmniLayer/omnicore/blob/master/src/omnicore/rpcvalues.cpp/#L60). I hope it helps you @palimarrao. Best Regards!

**Comment by palimarrao** [comment]
ahh I see, thanks for the detailed explanation @santos177! This helped a lot 👍
