### ISSUE TITLE
Method not found

### ISSUE THREAD

**Issue by iPhonePKAndroid** [OmniLayer/omnicore#919]
```
getaddressesbyaccount
```

```
newaddress
```

Method not found

**Comment by dexX7** [comment]
Hello, the RPC is called "getnewaddress".

**Comment by iPhonePKAndroid** [comment]
> Hello, the RPC is called "getnewaddress".

I know that,Sorry, it's my problem, because I started the test network.
Thank you for your participation. The Sino-US trade war has begun.
