### ISSUE TITLE
Does OmniCore support P2SH-Segwit address?

### ISSUE THREAD

**Issue by luongnguyenduc** [OmniLayer/omnicore#928]
I see some exchanges provide deposit addresses starting with 3, are they P2SH-Segwit or just P2SH (for example 36m4hEj3ee5PxEVigR6bUkUQBmP4zcCrsg (Tether USD)?

Another question: is it safe to use the same address for `toadress` and `feeaddress` in `omni_funded_send`/`omni_funded_sendall` API?
Thanks.

**Comment by dexX7** [comment]
Hey there,

Omni Core and the Omni Layer supports SegWit wrapped into P2SH. :)

And yes: it's safe.

**Comment by luongnguyenduc** [comment]
Hi @dexX7, 
How to generate P2SH segwit addresses Omni core? Is there a configuration like -addressType in bitcoin core or I have to generate the addresses externally and then import to Omni core?

Thanks.
