### ISSUE TITLE
Failed to load freeze state from levelDB. It is unsafe to continue.

### ISSUE THREAD

**Issue by weiforce** [OmniLayer/omnicore#929]
I have the same issue.
04-27 09:50:31 logicMath_EnableFreezing(): rejected: sender 3MbYQMMmSkC3AgWkj9FMo5LsPTW1zBTwXL is not  is not issuer of property 31 [issuer=32TLn1WLcu8LtfvweLzYUYU6ubc2YV9eZs]
04-27 09:50:31 ERROR: While loading freeze transaction f8d31b28c8f83d2cde19a8d78fb16f26746a4b234808b859418d62bfcfc9df0c:non-zero return from interpretPacket
04-27 09:50:31 Failed to load freeze state from levelDB.  It is unsafe to continue.
04-27 09:50:31 *** Failed to load freeze state from levelDB.  It is unsafe to continue.
04-27 09:50:31 Error: Failed to load freeze state from levelDB.  It is unsafe to continue.
04-27 09:50:31 Exodus balance after initialization: 568.28943968

**Comment by weiforce** [comment]
Omni
‏
 
@Omni_Layer
 Apr 25
More
When a client is started it will fail to validate the cached freeze status and force the client to shutdown. The workaround is to start the client with `-startclean` which will force a re-parse. Unfortunately this is a very slow process. (2/3)

**Comment by dexX7** [comment]
Hello, please check out #922.
