### ISSUE TITLE
create raw transaction and send success, but transaction is invalid

### ISSUE THREAD

**Issue by codinggg** [OmniLayer/omnicore#930]
Hi. I am trying to create raw transaction for myself. The following is my step.
> 1. I am create private key, and create bitcoin `testnet address`. I know usdt address is same with btc, the address is `miRwok2hjPnBkKRvyiCwPGtWkPeTKQyRSd` .
> 2. The address of my created has no usdt and btc. So I am use other btc, usdt account recharge 0.01 btc and 0.1 usdt.
> 3. I am use btc recharge and usdt recharge as transaction input, use `mtWe7JENdVpoVCcqEYCtaAPZJsvzjHfZ6q` as output with receiver and use sender address as change.
> 4. Next I am create raw transaction success. So I use `sendrawtransaction` send transaction to omni chain node, return `9c45c52af72590be21cc59c5e47fac3e7c7dd834ac117efe80b926392150ce47`, great, I am success.
>5. My receiver wallet has receive this transaction, but is unconfirmation state. wallet shows me like receive 0.00000*** btc. And after a while, wallet show this transaction is invalid and receive 100000000 SPT#31.

Transaction can be find in the follow blockchain explorer:
https://testnet.smartbit.com.au/tx/9c45c52af72590be21cc59c5e47fac3e7c7dd834ac117efe80b926392150ce47

I don't know what's wrong with this.  Someone can help me ?
In addition, I want to ask it's correct with my usdt transaction use btc transaction as input?

**Comment by vae520283995** [comment]
testnet only omni and tomni  property id is 1 and 2 mainnet usdt is property id 31

**Comment by santos177** [comment]
In testnet, the propertyId 31 is  named: tokenmagic, not tethers, so if you don't have tokenmagics you can't send it. The transaction is invalid for that reason (you balance of tokenmagic is zero before you sent the transaction)

**Comment by codinggg** [comment]
em... 
It's my property Id set wrong. Now I can send usdt successfully. @vae520283995  @santos177 Think you very much! ;)
