### ISSUE TITLE
Why don't you rewrite docs?

### ISSUE THREAD

**Issue by dmitryrn** [OmniLayer/omnicore#934]
For example this one: https://github.com/OmniLayer/omnicore/blob/master/doc/build-osx.md

There is bitcoin/bitcoin in entire page, no words about omnicore at all.

**Comment by dexX7** [comment]
Hi @dmitryrn,

we inherit most of it from Bitcoin Core and there are probably quite a few places with old references.

Thanks for pointing this one out!
