### ISSUE TITLE
Should I prefer segwit addresses (generated by getnewaddress and addwitnessaddress) over legacy address in Omni layer?

### ISSUE THREAD

**Issue by luongnguyenduc** [OmniLayer/omnicore#935]
In the [Omni Core Integration Guide](https://github.com/OmniLayer/omnicore/wiki/Platform-Integration-of-Omni-Core): 

> To generate a new destination to receive payments, the getnewaddress default RPC can be used.

Is this the best option? Should I generate addresses to receive payments by calling getnewaddress and then addwitnessaddress on the returned legacy address?

Thanks

**Comment by dexX7** [comment]
Hello,

while you can receive payments with SW wrapped in P2SH, there is currently no handy way to send SW Omni Layer transactions.

**Comment by Crypto2** [comment]
If you are using the omni_createrawtx_* functions they seem to work fine with 3-prefix addresses. We do recoveries time to time for people who send Omni Layer tokens to our BTC SegWit addresses and so far they've all worked as usual.

**Comment by luongnguyenduc** [comment]
@Crypto2  I generated some segwit addresses with `getnewaddress` and `addwitnessaddress`. I can send funds from those addresses by `omni_send`,  `omni_funded_send ` and `omni_funded_sendall`.
