### ISSUE TITLE
How many BTC should be sent when Omni is sent

### ISSUE THREAD

**Issue by vae520283995** [OmniLayer/omnicore#936]
https://test-insight.bitpay.com/tx/c8d8d1b2c8ba3c2bd99e9d884cf799099a7a935c9c0869fe494b6b3244e3b44b

https://test-insight.bitpay.com/tx/61861735ffb969f33eb4071d17c4e1a6e96cc67107430709e7bc69e334396da6

Why is one transaction 0.00000546btc and the other 0.00000540btc?
What should I do when I use rawtransaction

**Comment by vae520283995** [comment]
@dexX7 Excuse me, could you help me for a problem？

**Comment by pranavburnwal** [comment]
540 for P2SH addresses (multisig)
546 for P2PKH address (direct)

@vae520283995  Hope that helps.

**Comment by vae520283995** [comment]
> 540 for P2SH addresses (multisig)
> 546 for P2PKH address (direct)
> 
> @vae520283995 Hope that helps.

thank you
