### ISSUE TITLE
How to start omnicore-qt??

### ISSUE THREAD

**Issue by th-pias** [OmniLayer/omnicore#938]
in documentation you mentioned that: **"./qt/omnicore-qt if built with UI"**. But i got below error:
**./qt/omnicore-qt: No such file or directory**
I am not seeing any .qt directory in omnicore src directory. Am i missing anything when installing omnicore?

I am using ubuntu 14.04.

**Comment by dexX7** [comment]
Hello, did you follow the build instructions here?

https://github.com/OmniLayer/omnicore/blob/master/doc/build-unix.md
