### ISSUE TITLE
Too long syncronization

### ISSUE THREAD

**Issue by tanderbold** [OmniLayer/omnicore#944]
Hi, I had run new omnicored 5.0 version of daemon a 3 days ago, and 54 490 blocks leave now.
omnicored.exe -daemon -printtoconsole
Number of block             DateTime
505133				2019-05-08 10:14:46
521040				2019-05-11 11:09:01
15907 blocks 
4374 minutes = 262440 seconds
15907/262440 = 0,06 blocks/sec

What does it make all this time?
1 block in 19 seconds? 
Is it normal by your opinion?

**Comment by tanderbold** [comment]
All syncronization of bitcoin core takes only 40 hours on this machine.

**Comment by dexX7** [comment]
Hello @tanderbold,

you could try to use -omnidebug=none to speed up the process a bit, but slow synchronization is a known issue unfortunately.
