### ISSUE TITLE
Reference output must be last output?

### ISSUE THREAD

**Issue by kevindaizj** [OmniLayer/omnicore#945]
I tried to build **Simple Send** transaction without omni APIs. It seems that when i changed the position of **Referece Output**, **Reference Address** changed as well.
   
### What i expected: 

**Reference address**: mtmMxDLE2hqAqDgEorJebcHYNMGefVdCJT  
*(pub: 915335111543b24d134fab43a299cb34dfb88c12)*  

**Fee address**: mqdMjb7zy58zzx5vpiF7vcbQUXhnNfpSgn  
*(pub: 6ee7520fb5dccdfb009d45ab1e84b3e3e357bba8)*

### Unexpected Case  (Reference output was not the last output):
```
"out": [
    {
      "value": "0.00000546",
      "scriptPubKey": "OP_DUP OP_HASH160 915335111543b24d134fab43a299cb34dfb88c12 OP_EQUALVERIFY OP_CHECKSIG"
    },
    {
      "value": "0.00000000",
      "scriptPubKey": "OP_RETURN 6f6d6e6900000000800000030000000000000014"
    },
    {
      "value": "950.98930044",
      "scriptPubKey": "OP_DUP OP_HASH160 6ee7520fb5dccdfb009d45ab1e84b3e3e357bba8 OP_EQUALVERIFY OP_CHECKSIG"
    }
  ]
```
#### result: 
```
{
  "txid": "6479f25549d9c78b773a2440f716fee299d9985e144cff80e6dbb4d4423bb047",
  "fee": "0.00044550",
  "sendingaddress": "miRgAsB9CXXAQa5yLaApNjzC86W3s4JNAR",
  "referenceaddress": "mqdMjb7zy58zzx5vpiF7vcbQUXhnNfpSgn",  // wrong
  ...
}
```
  

### Expected  Case  (Reference output was the last output):
```
"out": [
    {
      "value": "1000.98884948",
      "scriptPubKey": "OP_DUP OP_HASH160 6ee7520fb5dccdfb009d45ab1e84b3e3e357bba8 OP_EQUALVERIFY OP_CHECKSIG"
    },
    {
      "value": "0.00000000",
      "scriptPubKey": "OP_RETURN 6f6d6e6900000000800000030000000000000014"
    },
    {
      "value": "0.00000546",
      "scriptPubKey": "OP_DUP OP_HASH160 915335111543b24d134fab43a299cb34dfb88c12 OP_EQUALVERIFY OP_CHECKSIG"
    }
  ]
```
#### result: 
```
{
  "txid": "4efd8233f29ac7f9334de1a59b861105e6ace34e07fe1ce4b6baaa8e347915f7",
  "fee": "0.00044550",
  "sendingaddress": "miRgAsB9CXXAQa5yLaApNjzC86W3s4JNAR",
  "referenceaddress": "mtmMxDLE2hqAqDgEorJebcHYNMGefVdCJT",   // right
  ...
}
```

My question is: Why the POSITION of reference output make difference reference address? And i can't find any rules of organizing Inputs/Outputs to build a correct transaction in spec.

Any help would be appreciated.

**Comment by santos177** [comment]
Hi @kevindaizj :  
I hope it helps #836

**Comment by kevindaizj** [comment]
So in Simple Send (Class C):

> the sender is always the first input

> the reference output is the latest one, which isn't change

Thanks, @santos177 . I am curious that why didn't omni group put this conclusion in spec. 

.

**Comment by dexX7** [comment]
Hi @kevindaizj, we're working on updating the specification to reflect these details.

**Comment by eugeniuLivandovschi** [comment]
> So in Simple Send (Class C):
> 
> > the sender is always the first input
> 
> > the reference output is the latest one, which isn't change
> 
> Thanks, @santos177 . I am curious that why didn't omni group put this conclusion in spec.
> 
> .

How do you determine what is the change address ? If it is used in inputs ? What if I wan't to send the change to another address ?
