### ISSUE TITLE
Update RPC API documentation

### ISSUE THREAD

**Issue by dexX7** [OmniLayer/omnicore#95]
The RPC API documention is outdated, and should be updated, to reflect the rebranding from Master to Omni, and to document all new commands.

**Comment by zathras-crypto** [comment]
100% agreed, in fact I think we need a whole run through of documentation - how-tos, integration guides, updated API doc etc etc.  As we get closer to sorting out the release I'm happy to take some time to tackle a documentation endeavour :)

**Comment by dexX7** [comment]
Resolved via #149 (for the most part).
