### ISSUE TITLE
How to upgrade Omnicore without taking current node down (offline)?

### ISSUE THREAD

**Issue by zinxer** [OmniLayer/omnicore#960]
Would like to upgrade to Omnicore (ver: 0.5.0) without taking it down and having to re-sync the entire node.

**Comment by dexX7** [comment]
Hello,

this is tricky. For Omni Wallet and Omni Explorer, we run two instances, upgrade one and point the interface to the other one in the meantime. Once upgraded, the frontend is pointed to the upgraded node and the other one is upgraded.

**Comment by zinxer** [comment]
> Hello,
> 
> this is tricky. For Omni Wallet and Omni Explorer, we run two instances, upgrade one and point the interface to the other one in the meantime. Once upgraded, the frontend is pointed to the upgraded node and the other one is upgraded.

Hi dexX7, however while pointing to the other instances while upgrading one. The wallet.dat which has access to the wallets would not be the same. 

How can we sync up the wallet.dat or have a solution where downtime can be mitigated so wallet access is not compromised when interfacing with another omnicore node?

Thanks,
Matt

**Comment by dexX7** [comment]
Hi @zinxer,

what if you backup the wallet, shut down node A and initiate the update, while node B still runs. When the upgrade is complete, shut down node B, and copy it's wallet back to A?

**Comment by zinxer** [comment]
> Hi @zinxer,
> 
> what if you backup the wallet, shut down node A and initiate the update, while node B still runs. When the upgrade is complete, shut down node B, and copy it's wallet back to A?

Great to hear from you @dexX7 

In this case, do you mean setup to node B with node A's wallet.dat while node A is being shutdown and updated?

The time to set up node B with node A's wallet.dat takes up say 48 hours; Within that time, more sub addresses are being added to wallet.dat thru node A. By the time node B is ready, it would have a different wallet.dat file as compared to node A (to be shutdown & updated) due to the 48 hours sync.

How can we solve this problem as syncing the wallet.dat file requires the node to restart syncing (and it take really long.) while we need to minimise downtime since new addresses are constantly being added to wallet.dat.

Thanks,
Matt
