### ISSUE TITLE
Multiple unspent input and other change address making wrong recipient transaction

### ISSUE THREAD

**Issue by mmo2112** [OmniLayer/omnicore#969]
Hi there, I have address A contains USDT and 546 Shas (sts), address B contains many sts which uses for paying fee. So I will make a transaction like that:
Making first input 546 sts (address A), second input is address B, sending USDT to address X and the changeAddress (address will receive last reamaining of this transaction) is X. The transaction is valid, sending USDT from A to X well. I will provide Blockcypher link which show you more clearly BTC inputs and Omniexplorer which is valid transaction. 
https://live.blockcypher.com/btc/tx/c9260d662a113c43faaff9661cdaddc8b19128818fd3339c46d26a1ec827d1ae/
https://omniexplorer.info/search/c9260d662a113c43faaff9661cdaddc8b19128818fd3339c46d26a1ec827d1ae
But, when I replace the changeAddress by B (for keeping all available fee in unique address), the transaction is sending USDT from A to B - not valid as my purpose A -> X.
https://live.blockcypher.com/btc/tx/fedaeb990ddb8e7858c955a42754043ff36e8b04da5e3eddccbc06d36d2e056e/
https://omniexplorer.info/search/fedaeb990ddb8e7858c955a42754043ff36e8b04da5e3eddccbc06d36d2e056e
So I want to ask which address in output array address can be received USDT? I don't think the tail address of array because if a single transaction from A (theory that address has enough sts for paying fee) to X, changeAddress is A, transaction with 1 input and 2 output is still well:
https://live.blockcypher.com/btc/tx/b801daeaf45cd0737927628ea93ed1c4fe61952c7af894ee98c941f58664ab3e/
https://omniexplorer.info/search/b801daeaf45cd0737927628ea93ed1c4fe61952c7af894ee98c941f58664ab3e
Thanks for helping so much.

**Comment by trongcauhcmus** [comment]
hi, may i ask, how can you make a transaction with address B pays transaction fee for moving USDT from address A?

**Comment by mmo2112** [comment]
> hi, may i ask, how can you make a transaction with address B pays transaction fee for moving USDT from address A?

You just simply push 1st input is 546 sts from address A, and other input (2nd, 3rd,...) is B or C or anything because Bitcoin can sign multiple unspent input.

**Comment by trongcauhcmus** [comment]
it's hard to create a raw transaction. i've found a function allow another address pay fee for transaction from version 0.3.1. the function is `omni_funded_send`
check this issue #740

**Comment by mmo2112** [comment]
> it's hard to create a raw transaction. i've found a function allow another address pay fee for transaction from version 0.3.1. the function is `omni_funded_send`
> check this issue #740

Okay I will create few transactions via RPC and check out these transactions on blockcypher, thanks for your advice.

**Comment by mmo2112** [comment]
@trongcauhcmus,
Thanks for your advice. I have tested a transaction which outputs is tail (last index of array) with 546 sts, it's okay and valid same as transaction from omni wiki "Use the raw transaction API to create a Simple Send transaction". That means if using multiple unspent inputs, the sender is head of inputs and the  - and the recipient is tail (last index in array) of outputs, simply makes 546 sts as last output after calulating fee,...
The transaction is here:
https://live.blockcypher.com/btc/tx/7f6a98835d106e2e35888628131624e0a8fd0288031acb6c7ce6d6a1cb26d834/
https://omniexplorer.info/tx/7f6a98835d106e2e35888628131624e0a8fd0288031acb6c7ce6d6a1cb26d834

//By the way, I'm working on NodeJS, and I can't send a Postman, may you give me a valid json structure? Thanks so much and have a nice day.
{
	"jsonrpc": "2.0",
	"id": "0",
	"method": "omni_createpayload_simplesend",
	"params": [{
		"propertyid": 1,
		"amount":"0.1"
	}]
}
-- Return error:
{
    "result": null,
    "error": {
        "code": -1,
        "message": "omni_createpayload_simplesend propertyid \"amount\"\n\nCreate the payload for a simple send transaction.\n\nNote: if the server is not synchronized, amounts are considered as divisible, even if the token may have indivisible units!\n\nArguments:\n1. propertyid           (number, required) the identifier of the tokens to send\n2. amount               (string, required) the amount to send\n\nResult:\n\"payload\"             (string) the hex-encoded payload\n\nExamples:\n> omnicore-cli omni_createpayload_simplesend 1 \"100.0\"\n> curl --user myusername --data-binary '{\"jsonrpc\": \"1.0\", \"id\":\"curltest\", \"method\": \"omni_createpayload_simplesend\", \"params\": [1, \"100.0\"] }' -H 'content-type: text/plain;' http://127.0.0.1:8332/\n"
    },
    "id": "0"
}

**Comment by trongcauhcmus** [comment]
i have not been worked with create raw transaction way
but, the problem of this issue is your making the wrong order of input? 
omnicore define the sender must be head and the receiver must be tail, right?

**Comment by mmo2112** [comment]
> i have not been worked with create raw transaction way
- Hm, which method are you using? Directly call from RPC? I've check Omni wiki, they launch every command which returns each part of raw transaction same as my way on NodeJS. But I can't Postman (maybe wrong JSON structure, I will check it later). So, I use their result transaction to decode and check, then I try to re-order output and luckily it's worked. ;-)
> but, the problem of this issue is your making the wrong order of input?
> omnicore define the sender must be head and the receiver must be tail, right?
- Yah, I guess they do that. If you use multiple spent inputs for paying fee (not sender address for keeping all fee in an unique address), make sure 1st input is Sender and last output is Recipient.
